import Dexie, { type Table } from 'dexie';

export interface IntervalData {
  id: string;
  name: string;
  semitones: number;
  ascAnchorDefault: string;
  descAnchorDefault: string;
  ascAnchorCustom?: string;
  descAnchorCustom?: string;
  ascCorrect: number;
  ascTotal: number;
  descCorrect: number;
  descTotal: number;
}

export interface ChordData {
  id: string;
  name: string;
  tier: 'foundational' | 'seventh' | 'dominant' | 'extensions';
  family: 'major' | 'minor' | 'dom' | 'sus' | 'dim' | 'aug';
  intervals: number[];
  formula: string;
  soundDefault: string;
  soundCustom?: string;
  correct: number;
  total: number;
}

export interface ChordShapeData {
  id: string;
  chordId: string;
  key: number;
  inversion: 0 | 1 | 2 | 3;
  mastered: boolean;
  notes?: string;
}

// One of five user-facing learning stages. Each has its own coaching
// guidance in src/modules/repertoire/stage.ts. Users control stage
// advancement; the app only suggests when criteria are met.
export type RepertoireStage =
  | 'learning'
  | 'comfortable'
  | 'internalized'
  | 'cross-key'
  | 'maintenance';

/** One reference recording, tutorial, or video tied to a song. Lives
 *  inside `Song.referenceVideos`; never persisted on its own. */
export interface ReferenceVideo {
  /** Stable id generated by `crypto.randomUUID()` at creation. Used
   *  for React keys + remove-from-array operations. */
  id: string;
  /** Free-form URL. Trimmed on save; empty entries are dropped. */
  url: string;
  /** Optional human label ("Original recording", "Jazz cover",
   *  "Lesson by X"). When omitted, the renderer falls back to the
   *  URL's hostname. */
  label?: string;
}

export interface Song {
  id: string;
  title: string;
  artist: string;
  genre?: string;
  /** Original/home key, e.g. "C", "Db", "G". */
  key?: string;
  /** Marks the key as an estimate that the user should verify against
   *  the original recording. Pre-populated songs set this for songs
   *  where the home key couldn't be determined confidently. */
  keyNeedsVerification?: boolean;
  /** Single tempo in BPM, or null/undefined if unset. */
  tempo?: number;
  /** Optional human tempo range like "60-75 BPM". Rendered verbatim. */
  tempoLabel?: string;
  /** Time signature display string like "4/4", "6/8", "5/4". Free
   *  text so uncommon meters survive — the editor surfaces a
   *  preset dropdown with an "Other" → free-text fallback.
   *  Unindexed; rides in the data JSONB blob across sync. */
  timeSignature?: string;
  /** Current user-controlled stage. Defaults to 'learning' for new
   *  songs. Advancement is user-driven; the UI suggests when criteria
   *  are met but never forces a change. */
  stage?: RepertoireStage;
  /** User-controlled learning sequence — 1-indexed, ASC = study
   *  next. Backfilled on first load to addedDate-ASC rank for
   *  existing rows (oldest = 1). The Repertoire home's
   *  learning-order sort mode is the authoring surface; the
   *  session algorithm consumes this as cold-start priority for
   *  songs with no spacingState rows (candidates.ts TODO). */
  learningOrder: number;
  /** Per-song ordering of the song detail page's main sections.
   *  When unset, the renderer uses DEFAULT_SECTION_ORDER. Stored as
   *  an array of canonical section keys
   *  ('leadSheet' | 'matrix' | 'learningStatus' | 'whyAndLinks' |
   *  'associations'). Unindexed — Dexie's `stores()` only declares
   *  indexes, so adding the field doesn't need a schema-version
   *  bump. Rides in the `data` JSONB blob across sync. */
  sectionOrder?: string[];
  /**
   * Path the user chose after reaching "comfortable in original
   * key" via the SotM congrats banner. Null/undefined while the
   * user hasn't picked yet — the session algorithm treats null as
   * an implicit "deepen" so the song stays in active rotation
   * until the banner gets a response.
   *
   *   deepen       — keep working in the original key, target solid
   *   expand-keys  — start a circle-of-4ths walk; original key
   *                  stays in maintenance
   *   maintenance  — light weekly rotation; user calls it done
   *
   * Unindexed — rides in the `data` JSONB blob across sync. */
  progressionPath?: 'deepen' | 'expand-keys' | 'maintenance' | null;
  /**
   * Circle-of-4ths walk-order populated when the user picks the
   * expand-keys path. Auto-generated from `key` via
   * `generateCircleOfFourthsSequence` so the user sees a
   * consistent next-key target. Excludes the original key itself.
   *
   * Unindexed — rides in the `data` JSONB blob across sync. */
  expandKeysOrder?: string[];
  /** Free-text "why I'm learning this" description. Starter copy is
   *  pre-populated when a song is seeded; user can edit or clear it. */
  description?: string;
  /** Full-song lyrics reference (flowing text with [Section] markers).
   *  Editable by the user. Pre-populated for the subset of seeded
   *  songs whose lyrics could be verified without fabrication; for
   *  the rest carries a short "add lyrics here" prompt. */
  fullLyrics?: string;
  /** Spotify / YouTube / Apple Music links. Free-form strings. */
  spotifyLink?: string;
  /** @deprecated — superseded by `referenceVideos`. Still read for
   *  backward compatibility (un-migrated songs display this link in
   *  the Why-this-song section); cleared on first save through the
   *  reference-videos editor, which copies the value into
   *  `referenceVideos[0]`. New code should not write to this field. */
  youtubeLink?: string;
  /** User-curated list of reference recordings / tutorials for this
   *  song. Each entry has a stable id (`crypto.randomUUID()` at
   *  creation), a url, and an optional human label. Rendered as
   *  clickable links in the Why-this-song section; the label
   *  surfaces verbatim or falls back to the URL's hostname.
   *
   *  Unindexed — rides in the `data` JSONB blob across sync, no
   *  Dexie version bump needed. */
  referenceVideos?: ReferenceVideo[];
  /** Running list of every URL the user has pasted for this song.
   *  Preserved for backward compatibility with the initial Song schema. */
  audioLinks: string[];
  addedDate: number;
  notes?: string;
  /** @deprecated — carried forward from the original schema. Not used
   *  by the Repertoire module but kept so existing backups round-trip. */
  technical?: boolean;
  /** @deprecated — see `technical`. */
  byEar?: boolean;
  /** @deprecated — see `technical`. */
  memorized?: boolean;
  /** @deprecated — see `technical`. */
  progressionAnalyzed?: boolean;
  /** @deprecated — see `technical`. */
  recorded?: boolean;
}

/** One atomic unit inside a phrase line. A word beat carries lyric
 *  text; a blank beat carries no lyric but can still hold a chord
 *  (used for instrumental hits, pickup chords, mid-word chord changes,
 *  etc.). Chords anchor to beat ids — never to character offsets — so
 *  editing lyrics can't cascade chord placements.
 *
 *  `joinToNext` marks the beat as a syllable of a larger word: when
 *  true, the renderer visually joins this beat's text to the next
 *  beat's with a hyphen, so three beats `{text:'A', joinToNext:true}`,
 *  `{text:'maz', joinToNext:true}`, `{text:'ing'}` display as
 *  "A-maz-ing" while still carrying independent chord slots above
 *  each syllable. */
export interface Beat {
  id: string;
  type: 'word' | 'blank';
  /** Word text. Undefined / empty for blank beats. */
  text?: string;
  /** Syllable-group join flag. Only meaningful on 'word' beats. */
  joinToNext?: boolean;
}

/** Named chord arrangement stored at the section level. Every phrase
 *  within a section shares this list of arrangements; each phrase
 *  decides which chord lands on which beat for each arrangement. */
export interface Arrangement {
  id: string;
  name: string;
  /** Per-arrangement notes (picked up from legacy alternateNote when
   *  the Alternates arrangement is auto-created). */
  notes?: string;
}

/**
 * Functional chord representation. The user works in functional
 * harmony, so chords store their position (scale-degree function) and
 * quality independently of any concrete key. Concrete chord names
 * ("Fmaj7", "Ab", etc.) are DERIVED at render time from the song
 * section's current key + these functional fields.
 *
 * Degree label convention matches the Chord Motion module:
 *   "1" "b2" "2" "b3" "3" "4" "#4" "5" "b6" "6" "b7" "7"
 * — so progression detection can interoperate without a translation
 * layer.
 *
 * When the user types something the parser can't resolve (a chord in
 * a key the section doesn't declare, an unrecognised quality), the
 * entry is stored with `unparsed: true` and `raw` preserved so no
 * input is silently discarded.
 */
export interface ChordFunction {
  /** Scale-degree label — "1", "b2", "2", ... "7". Empty string when
   *  parsing failed (check `unparsed`). */
  function: string;
  /** Quality suffix as the user would read it: "", "m", "7", "maj7",
   *  "m7", "m7b5", "dim", "aug", "add9", "m(add9)", etc. */
  quality: string;
  /** Bass function for slash chords, as a scale-degree label
   *  ("3", "5", "b7"). Undefined when not a slash. */
  bass?: string;
  /** Original user-entered text. Preserved verbatim so the display
   *  layer can fall back to raw when parsing produced nothing useful. */
  raw?: string;
  /** Flag set by the parser when it couldn't resolve the input to a
   *  functional position (e.g. a concrete chord name in a section
   *  whose key is unknown). Renderer shows `raw` with a small warning. */
  unparsed?: boolean;
}

/**
 * One phrase line = a sequence of beats + per-arrangement chord
 * placements over those beats.
 *
 * Legacy fields `chords` / `lyrics` remain for backward compatibility
 * with pre-beat data — the renderer derives beats from `lyrics.split`
 * when `beats` is absent. Those fields are written on seed/init but
 * the authoritative post-refactor state lives on `beats` +
 * `chordsByArrangement`.
 */
export interface Phrase {
  id: string;
  /** Ordered beat sequence. When undefined, renderer derives from
   *  `lyrics` (one word beat per whitespace-split token). */
  beats?: Beat[];
  /** arrangementId → { beatId → ChordFunction }. Functional storage
   *  means the placement survives a key change without rewriting
   *  anything — only the displayed concrete chord name (when the user
   *  has that notation mode on) re-derives. */
  chordsByArrangement?: Record<string, Record<string, ChordFunction>>;
  /** @deprecated pre-beat single chord string for the whole line.
   *  Migrated into `chordsByArrangement.basic` at render time. */
  chords?: string;
  /** @deprecated pre-beat single lyric string. Split into word beats
   *  on demand. */
  lyrics?: string;
}

export interface SongSection {
  id: string;
  songId: string;
  /** Display name — "Verse 1", "Chorus", "Bridge", "Outro", etc. */
  name: string;
  /** Ordering within the song (0-indexed). */
  order: number;
  /** Pre-populated seed lyrics or empty string. Preserved as a fallback
   *  when `phrases` is absent (legacy pre-phrase-refactor data) and as
   *  a pristine copy of the original seed text. */
  lyrics: string;
  /** When true, the section's seed lyrics came from a source the author
   *  couldn't fully verify — surface a "needs verification" hint. */
  lyricsNeedsVerification?: boolean;
  /** Authoritative lyric + chord data. Each phrase is one displayed
   *  row. Empty / missing = fall back to `lyrics` split on newlines. */
  phrases?: Phrase[];
  /** Named chord arrangements available on this section. Every
   *  section gets a seed "Basic" arrangement; users can add their own
   *  ("My arrangement", "Jazz voicings", etc.). When undefined, the
   *  renderer synthesises a single `{ id: 'basic', name: 'Basic' }`. */
  arrangements?: Arrangement[];
  /** Which arrangement is currently shown in the editor. Defaults to
   *  the first arrangement (usually 'basic'). */
  activeArrangementId?: string;
  /** @deprecated kept for backward-compat with pre-phrase-line data.
   *  Space-separated chord tokens for the whole section. */
  basicChords?: string;
  /** Optional alternate/substitution chord chart the user explores.
   *  When non-empty on first load post-refactor, auto-materialised as
   *  an "Alternates" arrangement alongside Basic. */
  alternateChords?: string;
  /** @deprecated kept for backward-compat. Per-line strike-through
   *  flags keyed by the old lyric-line index. Not used by phrase-line
   *  rendering. */
  struckLines?: number[];
  /** Section hidden from playback view (collapsed) but still in data. */
  hidden?: boolean;
  /** Per-section stage — can diverge from song-level stage. Defaults to
   *  inheriting the song's stage at render time. */
  stage?: RepertoireStage;
  /** Free text for performance cues / voicing ideas. */
  notes?: string;
  /** User note explaining when/why an alternate chord is used. */
  alternateNote?: string;
}

/** One parsed chord token inside a section. Populated by the chord
 *  parser at save time so cross-module queries ("find songs that use
 *  bVII") don't need to re-parse text on the fly. */
export interface SongChord {
  /** Composite key: `${songId}:${sectionId}:${position}`. */
  id: string;
  songId: string;
  sectionId: string;
  /** Zero-indexed position within the section's chord chart (token order). */
  position: number;
  /** Original token as typed by the user. Preserved for display so
   *  enharmonic spelling and extensions stay faithful. */
  rawText: string;
  /** Root pitch class name (e.g. "C", "F#", "Bb"). Empty string when
   *  parsing failed. */
  root: string;
  /** Coarse quality bucket. Fine extensions go in `extensions`. */
  quality: 'major' | 'minor' | 'dominant' | 'diminished' | 'augmented' | 'half-dim' | 'unknown';
  /** Extensions present on the chord (e.g. ['7', 'b9', '#11']). */
  extensions: string[];
  /** Slash-bass note name when present. */
  bass?: string;
  /** True when the parser produced usable structure. False falls back
   *  to `rawText` at render time with a small warning icon. */
  parsed: boolean;
}

export interface SongPracticeLog {
  id: string;
  songId: string;
  /** ISO-ish timestamp (epoch ms) for sort + heatmap. */
  timestamp: number;
  /** Minutes practised (whole number or decimal). */
  durationMin: number;
  /** Section ids touched in this session. Empty array = whole song. */
  sectionIds: string[];
  /** Key names practised in this session. E.g. ['C', 'G', 'Eb']. */
  keys: string[];
  /** 1-5 feel rating — 1 struggled, 5 breakthrough. */
  feelRating: 1 | 2 | 3 | 4 | 5;
  /** Optional session notes. */
  notes?: string;
  /** Marker for sessions where the user indicated they worked at
   *  target tempo. Drives the Learning → Comfortable advancement. */
  atTargetTempo?: boolean;
}

/**
 * @deprecated **Obsolete pending Phase 1.5 cleanup.** Once the
 * matrix UI ships and existing songs migrate into the new model,
 * `songCells` (one row per section × key intersection) supersedes
 * this table — `cell_state` + `consecutiveCleanCount` carry the
 * per-cell tracking, and the per-key state lives on `songKeys`.
 *
 * Kept intact in v19 to avoid forcing a data-migration step before
 * the matrix UI exists. Do NOT route new writes here. The drop
 * lands as a separate Phase 1.5 step with an accompanying
 * data-migration plan; see SONG_PROGRESSION_DESIGN_3.md "Migration
 * spec" section.
 */
export interface SongCrossKeyProgress {
  /** Composite key: `${songId}:${sectionId}:${keyName}`. */
  id: string;
  songId: string;
  sectionId: string;
  keyName: string;
  /** Count of sessions that touched this (section, key) pair. */
  sessionCount: number;
  /** Timestamp of most recent session touching this pair. */
  lastPracticed: number;
  /** User-marked mastery flag. `sessionCount` alone never promotes to
   *  mastered — the user toggles it explicitly on the grid. */
  mastered: boolean;
}

export interface WantToLearnEntry {
  id: string;
  title: string;
  artist: string;
  priority: 'high' | 'medium' | 'low';
  /** Free-text reason for wanting to learn — drives the description
   *  when the entry is promoted to the Active repertoire. */
  why?: string;
  link?: string;
  /** Loose tags for mood/style ("soul", "ballad", "up-tempo", etc.). */
  tags: string[];
  addedDate: number;
}

// --- Shapes & Patterns module (v9) ----------------------------------

/** Which activity area a drill belongs to. Four top-level categories
 *  surface in the module's UI; the first two share the heat-grid
 *  pattern while the latter two use flat lists. */
export type DrillKind =
  | 'chord-shape'
  | 'scale'
  | 'voice-leading'
  | 'mental-viz';

/**
 * Inversion-state discriminator for chord-shape drillSkills (Phase 4
 * inversion redesign). For triads and seventh chords, each
 * inversion + the fluid capstone is its own trackable skill row so
 * acquisition is scoped per inversion. Extensions / special / sixth
 * skills set this to null — they use voicings, not inversions.
 *
 *   root          — root position
 *   inv1 / inv2   — 1st / 2nd inversion
 *   inv3          — 3rd inversion (sevenths only)
 *   fluid         — capstone "all inversions fluid" drill, its own row
 *   supplementary — non-acquisition-gating drills (e.g. two-handed
 *                   LH-root + RH-triad seventh variants); excluded
 *                   from coverage denominators
 *
 * null is the legacy / extensions / special / sixth state — those
 * keep one row per (quality × key) cell with no inversion suffix
 * on the itemRef.
 */
export type InversionState =
  | 'root'
  | 'inv1'
  | 'inv2'
  | 'inv3'
  | 'fluid'
  | 'supplementary';

/**
 * A drillable "cell" — something the user can practise across
 * multiple drill types. Created lazily on first interaction: opening
 * a heat-grid cell that's never been practised materialises the
 * DrillSkill + its default DrillTypes on demand.
 *
 * The shape is deliberately polymorphic across the four drill kinds
 * because the heat-grid dimensions differ (chord×key vs scale×key vs
 * pattern×key vs single card).
 */
export interface DrillSkill {
  id: string;
  kind: DrillKind;
  /** Major-pitch-name key for the skill ("C", "Db", …, "B"). Optional
   *  because mental-viz drills aren't key-pinned. */
  keyName?: string;
  /** Chord-quality id for 'chord-shape' skills ("maj", "m7b5", etc.). */
  quality?: string;
  /** Scale id for 'scale' skills ('major' / 'natural-minor' in v1). */
  scale?: string;
  /** Voice-leading pattern id for 'voice-leading' skills. */
  patternId?: string;
  /** Mental-viz variant id ('shape-viz' / 'ghost-keyboard' / …). */
  variant?: string;
  /** Inversion state for triad / seventh chord-shape skills — one
   *  row per inversion + fluid capstone + supplementary group. Null
   *  / undefined for extension + special chord shapes (which use
   *  voicings, not inversions) and for non-chord-shape kinds.
   *  See InversionState above. Not indexed — the candidate set per
   *  (kind+keyName+quality) lookup is at most ~6 rows so a
   *  post-query filter is cheap. */
  inversionState?: InversionState | null;
  /** Denormalised display label — used when rendering without having
   *  to re-derive from catalog. Editable. */
  label?: string;
  createdAt: number;
}

/** One practice type inside a skill. E.g. for "Cmaj triad" the types
 *  are "Root position", "1st inversion", "2nd inversion", "All
 *  inversions fluid". Aggregate counts here are maintained by the
 *  session-logging flow so the heat-grid doesn't need to sum sessions
 *  at render time. */
export interface DrillType {
  id: string;
  skillId: string;
  name: string;
  /** Suggested duration in seconds — default fill for the drill
   *  session timer. Editable. */
  suggestedSeconds: number;
  /** Display ordering within the skill. */
  order: number;
  repCount: number;
  totalSeconds: number;
  lastPracticedAt: number | null;
  /** User-added drills flagged so the UI can distinguish them from
   *  defaults (only for display; no behavioural difference). */
  userCreated?: boolean;
}

export interface DrillSession {
  id: string;
  drillTypeId: string;
  skillId: string;
  /** How long this session actually ran (not the target). Minimum
   *  enforced at 30 s by the UI before a session can save. */
  durationSeconds: number;
  /** 1 = struggled, 2 = working on it, 3 = clean, 4 = in flow. */
  feelRating: 1 | 2 | 3 | 4;
  notes?: string;
  timestamp: number;
}

/**
 * Creative-time session — "Just Play" (freeform keyboard exploration)
 * or "Just Produce" (beat-making / sound design / recording). Logged
 * from the header's creative-time button, separate from the skill-
 * targeted `sessions` and `drillSessions` tables because creative
 * work isn't tied to a specific practiceable item.
 */
export interface CreativeSession {
  id: string;
  timestamp: number;
  mode: 'play' | 'produce';
  durationSeconds: number;
  /** Prompt text the user accepted (or skipped past). Undefined when
   *  the user chose to play with no prompt. */
  prompt?: string;
  /** Prompt template id — records WHICH kind of prompt was used
   *  (e.g. 'recent-drill', 'emotion-tag'). Future feedback loops. */
  promptKind?: string;
  notes?: string;
  /** Flagged when shorter than the 2-minute "genuine session"
   *  threshold. Still logged so noodling is visible. */
  quickExploration?: boolean;
}

// --- Production & Logic Pro module (v12) ----------------------------
//
// The module teaches production via six paths (Phase 1 ships the
// first three: Workflow Foundations, Language of Production, Vocal
// Production). Each path holds a list of lessons. A lesson carries
// surface + deep-dive content, a curated YouTube link, and a list
// of glossary-term ids. The user's mastery + revisit history lives
// alongside.
//
// Static content (lesson bodies, glossary definitions, starter
// reference tracks) lives in the module's content files; the tables
// here carry per-user state on top. A seed function migrates any
// new content into the user's DB on mount (idempotent).

/** Mastery state for a production lesson. */
export type ProductionLessonMastery =
  | 'not-started'
  | 'in-progress'
  | 'completed'
  | 'mastered';

export interface ProductionLesson {
  /** Stable string id — e.g. 'wf-01' for the first Workflow lesson. */
  id: string;
  /** Path id — one of the six Production paths. */
  pathId: string;
  /** Ordering within the path. */
  order: number;
  /** User mastery state. Seeds as 'not-started'. */
  mastery: ProductionLessonMastery;
  /** Number of times the user has opened this lesson. */
  revisitCount: number;
  /** Timestamp of first completion, null until Mastered/Completed. */
  completedAt: number | null;
  /** Last time the user opened the lesson. */
  lastOpenedAt: number | null;
  createdAt: number;
  updatedAt: number;
}

export interface ProductionLessonSession {
  /** Generated uid. */
  id: string;
  lessonId: string;
  timestamp: number;
  /** Duration the user spent in this revisit (seconds). Optional —
   *  the UI tracks this when the user closes the lesson. */
  durationSeconds?: number;
  /** Whether this visit opened the Deep Dive layer. */
  openedDeepDive: boolean;
}

/** Per-user understanding state for a glossary term. */
export type GlossaryMastery = 'not-yet' | 'got-it';

export interface GlossaryTermState {
  /** Term id (kebab-case). Matches the static content file. */
  id: string;
  mastery: GlossaryMastery;
  /** Number of times the user has opened this term's overlay. */
  openCount: number;
  lastEncounteredAt: number | null;
  /** Timestamp of first "Got it" click. */
  gotItAt: number | null;
}

export interface ReferenceTrack {
  id: string;
  title: string;
  artist: string;
  /** Producer credit — single free-form field so multi-producer credits
   *  ("Babyface, L.A. Reid, Daryl Simmons") read as one line. Optional
   *  because user-added tracks may not know or care. */
  producer?: string;
  genre: string;
  /** Guided-listening prompts — tells the user what to listen for in
   *  this track. Populated on add / generate, editable. Intentionally
   *  avoids fabricated gear/ratio claims. */
  whatToListenFor: string;
  /** User's own observations that grow over time as they listen in
   *  the context of the lessons they're studying. Optional. */
  myListeningNotes?: string;
  /** Optional external listening links. Treated as free-form URLs so
   *  search-style links are valid when a direct track URL is unknown. */
  spotifyLink?: string;
  youtubeLink?: string;
  /** User-editable free-form tags (lowercase). */
  tags: string[];
  /** True when the track is a starter seeded by the app; false
   *  when the user added it. Starter entries can still be edited /
   *  archived but serve as onboarding material. */
  isStarter: boolean;
  /** Provenance — 'starter' = app seed, 'user' = user-typed, 'generated'
   *  = Claude-generated from a prompt. Used in UI to badge origin and
   *  in migration logic to decide what can be safely rewritten. */
  source?: 'starter' | 'user' | 'generated';
  archived: boolean;
  addedAt: number;
  updatedAt: number;
  /** Pre-v13 field preserved for backward compatibility only. New code
   *  reads/writes `whatToListenFor` instead; migration copies the old
   *  value over. Kept optional so typecheck doesn't break on legacy
   *  rows still carrying this. */
  sonicNotes?: string;
}

/**
 * Many-to-many link between a Production lesson and a Reference Track.
 * Created when the user curates reference tracks for a specific lesson
 * (either picking from their library or adding from a suggestions pool).
 * Intentionally stored as its own table rather than an array on
 * ProductionLesson so cascade-delete from the track side is a simple
 * indexed query, and so one track can appear on multiple lessons without
 * duplicate rows.
 */
export interface LessonReferenceTrack {
  id: string;
  lessonId: string;
  trackId: string;
  addedAt: number;
}

// --- Skills registry + Harmonic Diary (v11) -------------------------
//
// These two tables power the Skills Catalogue and Harmonic Diary
// features. They are both ANNOTATION layers on top of existing module
// data — the module tables remain the source of truth for tier /
// freshness / attempt counts, while these tables carry user-set
// metadata (priorities, tags, emotional associations) that doesn't
// belong inside any single module.

/** Skill type classification — used by the Skills Catalogue to group
 *  and filter the unified view. 'theory' covers conceptual harmonic
 *  fluency cards; 'ear' covers interval / chord-recognition /
 *  progression ear-training; 'physical-*' covers the three Shapes &
 *  Patterns drill kinds (mental-viz stays its own category since it's
 *  a cognitive drill); 'song' covers repertoire entries. */
export type SkillType =
  | 'theory'
  | 'ear'
  | 'physical-chord-shape'
  | 'physical-scale'
  | 'physical-voice-leading'
  | 'physical-mental-viz'
  | 'song'
  | 'production';

/** User-settable learning intent — lets the catalogue surface what
 *  the user is actively choosing to invest in vs maintain. */
export type SkillPriority = 'comfort' | 'deep' | 'maintenance';

/**
 * User annotations for a specific skill. `skillId` is a canonical
 * string built by `canonicalSkillId` in src/modules/skills/registry.ts
 * — it stays stable across module refactors because it embeds both
 * moduleId and itemId.
 *
 * Tier / freshness / lastPracticed are INTENTIONALLY absent — those
 * are derived live from source module tables. Only user-set
 * annotations persist here.
 */
export interface SkillAnnotation {
  skillId: string;
  priority?: SkillPriority;
  /** Free-form tags the user has attached to this skill ("Modal
   *  Interchange", "gospel-blue", etc.). */
  tags: string[];
  /** User can override the catalogue's auto-derived display name. */
  customName?: string;
  /** User can write a private note about the skill, visible only
   *  inside the catalogue detail panel. */
  note?: string;
  createdAt: number;
  updatedAt: number;
}

/**
 * One harmonic-diary entry — the association a user has with a
 * specific skill. Extends the per-module association concept (the
 * existing `progressionAssociations`, `modeAssociations`, and
 * `intervalDescriptions` tables) into a single unified space that can
 * hold emotional/genre tags and link to any skill regardless of
 * source module.
 *
 * `claudeStarterText` holds the app-generated seed associated with
 * the skill. When the user edits, `userText` carries their version
 * and `isStarterEdited = true` flags that the entry is now
 * user-owned. Both are kept so we can show "Claude's starter — tap
 * to customise" in the UI when no user text exists yet.
 */
export interface HarmonicDiaryEntry {
  /** Stable id — uuid-ish. */
  entryId: string;
  /** FK into the derived skill registry. */
  skillId: string;
  /** User-written association text. Empty string when not yet
   *  personalised. */
  userText: string;
  /** App-generated starter text shown when `userText` is empty. */
  claudeStarterText?: string;
  /** True once the user has edited the starter. */
  isStarterEdited: boolean;
  /** Emotion tag vocabulary — melancholy, hopeful, tense, resolved,
   *  bright, dark, warm, dreamy, mysterious, etc. Curated in
   *  src/modules/harmonic-diary/vocab.ts. */
  emotionalTags: string[];
  /** Genre tags — gospel, soul, neo-soul, hip-hop, jazz, etc. */
  genreTags: string[];
  createdAt: number;
  lastEdited: number;
  /** When the entry was materialised from a legacy per-module
   *  association table, this records the source so subsequent syncs
   *  stay idempotent. Absent for diary-native entries. */
  legacySource?: 'progression' | 'mode' | 'interval';
}

export interface Session {
  id: string;
  date: number;
  durationMin: number;
  focus: 'ear' | 'chords' | 'songs' | 'production' | 'improv' | 'songwriting' | 'mixed';
  notes?: string;
  reflection?: string;
  feel: 'breakthrough' | 'solid' | 'maintenance' | 'rough';
}

export interface LogicSkill {
  id: string;
  order: number;
  name: string;
  complete: boolean;
  notes?: string;
  completedDate?: number;
}

export interface ProducerStat {
  id: string;
  pillar: 'storytelling' | 'arrangement' | 'beats' | 'vibe';
  count: number;
  target: number;
  notes?: string;
}

export interface QuizStat {
  id: string;
  scope: string;
  correct: number;
  wrong: number;
  streak: number;
  bestStreak: number;
}

export interface UserPref {
  key: string;
  value: unknown;
}

export type AttemptDirection = 'asc' | 'desc';

export interface AttemptRecord {
  id?: number;
  moduleId: string;
  itemId: string;
  direction?: AttemptDirection;
  correct: boolean;
  timestamp: number;
  /** Set when the attempt should still be logged (so daily goals,
      streaks, and the calendar keep working) but must NOT feed the
      rolling-window fluency calculation. Used by small-pool focus
      sessions where the user already knows what's coming and a "correct"
      answer isn't a genuine fluency signal. Older records without the
      field are treated as normal fluency-tracked attempts. */
  excludeFromFluency?: boolean;
}

export interface DailySummary {
  date: string; // YYYY-MM-DD, local day
  moduleId: string;
  correctCount: number;
  wrongCount: number;
  dailyGoal: number;
  goalMet: boolean;
}

export interface ProgressionAssociation {
  progressionId: string;
  text: string;
  updatedAt: number;
}

export interface ModeAssociation {
  modeId: string;
  text: string;
  updatedAt: number;
}

// Per-interval-quality emotional description. Keyed by a composite id
// like "minor-3rd-ascending" so ascending and descending versions of
// the same quality live on separate rows (they feel different to the
// ear and often attract different associations).
export interface IntervalDescription {
  intervalKey: string;
  text: string;
  updatedAt: number;
}

export interface FlashcardState {
  cardId: string;
  easeFactor: number;        // SM-2, starts at 2.5
  interval: number;          // days until next review
  nextReviewDate: number;    // epoch ms
  lastReviewed: number;      // epoch ms
  consecutiveCorrect: number;
  totalAttempts: number;
  totalCorrect: number;
  /** User-flagged for "study later". Optional for backwards-compat with
      records written before the field existed. */
  isFlagged?: boolean;
}

/**
 * Offline-first sync queue. Dexie write hooks push an entry here on
 * every create/update/delete of a synced table; a background drain loop
 * pops entries and sends them to Supabase. Survives page reloads, so
 * writes made offline are sent as soon as the browser comes back online.
 *
 * `tableName` is the Dexie table name (camelCase, e.g. "referenceTracks");
 * the sync engine maps it to the snake_case Postgres table.
 */
export interface SyncQueueItem {
  /** Auto-increment so FIFO ordering is preserved. */
  id?: number;
  tableName: string;
  operation: 'upsert' | 'delete';
  rowId: string;
  /** Full Dexie row for upserts; undefined for deletes. */
  rowData?: unknown;
  queuedAt: number;
  attempts: number;
  lastError?: string;
}

// ============================================================
// Practice Sessions + Goals — Phase 1 schema (v16, April 2026)
// ============================================================
//
// Eight new tables introducing the Goals layer and the foundation
// for the Practice Sessions module.
//
// Schema decisions baked in (per the April 25, 2026 design review):
//
//  - No `mode` field on practiceSessions. Modes (focus /
//    acquisition) collapsed in the design review — emergent from
//    goals + spacing state, not user-declared. `sessionIntent`
//    captures lighter per-session intent only.
//  - No `spacingPaused` on vacationPeriods. Decay continues
//    during vacation (truth-honoring); only goal target dates
//    are affected (handled by the welcome-back UI in Phase 7).
//  - No 'daily' value in goals.scope. Daily intent is generated
//    by the algorithm in Phase 3+, not stored as a goal entity.
//  - dayProfiles.expectedSessions JSONB keys are
//    morning / midday / evening (matching practiceSessions
//    .timeOfDay). UI may display "Afternoon" as user-facing copy
//    but the data key is `midday`.
//  - Multi-component goal support in schema (`isUmbrella`,
//    `parentGoalId`, `contributesNumericallyToParent`); the UI
//    for umbrella goals ships in Phase 2.
//  - spacingState.acquisitionStage replaces the user-declared
//    "acquisition mode" toggle from earlier drafts. Population
//    at scale and detection logic ship in Phase 2.
//  - proficiencyDefinitions is per-user (matching every other
//    table) rather than a global static table; the five rows
//    are identical across users.
//
// All eight tables register in SYNC_TABLES (src/lib/sync/tables.ts).
// The Dexie write hooks enqueue to syncQueue automatically — no
// `syncedWrite` wrapper exists or is needed in this codebase.

export type PracticeSessionContext = 'keys' | 'laptop' | 'phone' | 'mixed';
/**
 * Time-of-day window a session was practiced in. Auto-labeled by
 * the app from the wall clock at session start:
 *
 *   late_night : 12am – 4am  (rolls up to the previous calendar
 *                              day's metrics — Phase 3+)
 *   morning    : 4am – 12pm
 *   midday     : 12pm – 6pm
 *   evening    : 6pm – 12am
 *
 * Day profiles only have three slots (morning / midday / evening);
 * late_night is for after-the-fact session classification, not
 * something users plan around. The previous-day rollup logic is
 * a Phase 3 (algorithm) / Phase 7 (metrics) concern; Phase 1 just
 * supports the value in the schema.
 */
export type PracticeSessionTimeOfDay =
  | 'morning'
  | 'midday'
  | 'evening'
  | 'late_night';
export type PracticeSessionRole = 'opener' | 'middler' | 'closer' | 'only';
export type DayProfileName = 'standard' | 'light' | 'deep' | 'custom';
export type BlockCompletionStatus =
  | 'completed'
  | 'partial'
  | 'skipped'
  | 'extended';
export type PerformanceRating = 'flying' | 'cruising' | 'crawling';
/**
 * Whole-session rating captured at the end-of-session summary
 * (Phase 3 Step 6b). Distinct from PerformanceRating which is per-
 * block: the session rating answers "how was this session as an
 * experience?" while per-block ratings answer "how did this skill
 * feel?" Both coexist on every session.
 */
export type PracticeSessionRating = 'locked_in' | 'solid' | 'going_through_it';
/**
 * Goal scope hierarchy. No 'daily' — daily intent is generated
 * by the algorithm (Phase 3+), not stored as a goal entity.
 *
 * The two-to-three-year layer (was three-to-five-year in earlier
 * drafts) reflects a more honest planning horizon; the lifetime
 * vision layer absorbs longer-range aspiration.
 */
export type GoalScope =
  | 'lifetime'
  | 'two_to_three_year'
  | 'yearly'
  | 'quarterly'
  | 'monthly'
  | 'weekly';
export type GoalStatus = 'active' | 'paused' | 'completed' | 'abandoned';
export type MemoryType =
  | 'declarative'
  | 'procedural'
  | 'integration'
  | 'expression';
export type AcquisitionStage =
  | 'new'
  | 'acquiring'
  | 'acquired'
  | 'consolidated'
  | 'mastered';
/**
 * Canonical proficiency levels across four scopes. Twelve unique
 * levels span:
 *
 *   skill scope (6)        — accuracy-band states for measured-
 *                            accuracy modules (ear training, shapes
 *                            & patterns, harmonic fluency):
 *                            planting → sprouting → branching →
 *                            rooted → seasoned → maintenance
 *
 *   song scope (5)         — whole-song progression as surfaced in
 *                            goal targeting:
 *                            learning → comfortable → solid →
 *                            cross_key → internalized
 *                            (Phase 1 song-goal addendum, April 26,
 *                            2026: Maintenance removed — it's a
 *                            user-declared intent, not a level;
 *                            Solid inserted at order 3; cross-key
 *                            renamed cross_key and pushed to order
 *                            4.) NOTE: the legacy `RepertoireStage`
 *                            type still uses kebab `cross-key` for
 *                            song-stage tracking in the repertoire
 *                            module — that vocabulary is reworked
 *                            wholesale in Phase 1.5 (Song Progression
 *                            Redesign).
 *
 *   song_key scope (3)     — per-key progression for a single song
 *                            (introduced by the Phase 1 song-goal
 *                            addendum):
 *                            learning → comfortable → solid
 *                            No Maintenance row.
 *
 *   production scope (5)   — Production lessons:
 *                            learning → comfortable →
 *                            cross-context → internalized →
 *                            maintenance
 *
 * Some level identifiers are shared across scopes. The `(scope,
 * level)` pair is the canonical key in the proficiencyDefinitions
 * table — the same level identifier in different scopes points to a
 * different definition row.
 *
 * Identifier conventions: skill levels are single words; song and
 * song_key levels use snake_case for multi-word values (`cross_key`)
 * per the addendum; production keeps kebab `cross-context` until a
 * future redesign harmonizes it.
 */
export type ProficiencyLevel =
  // Skill scope
  | 'planting'
  | 'sprouting'
  | 'branching'
  | 'rooted'
  | 'seasoned'
  // Song + song_key scopes
  | 'learning'
  | 'comfortable'
  | 'solid'
  | 'cross_key'
  | 'internalized'
  // Production scope (adds cross-context; learning / comfortable /
  // internalized are shared with song scope)
  | 'cross-context'
  // Shared post-mastery state — skill and production scopes only;
  // song and song_key scopes do not use Maintenance as a level
  | 'maintenance';
/**
 * Proficiency vocabulary scope. The `(scope, level)` pair is the
 * canonical key — the same level string in different scopes points
 * to different definitions.
 *
 *   song        — whole-song progression (goal targeting)
 *   song_key    — per-key progression for one song (Phase 1
 *                 song-goal addendum, April 26, 2026)
 *   skill       — measured-accuracy module skills
 *   production  — Production lessons
 *   concept     — reserved for future glossary / concept tracking
 *                 (kept in the union now so adding a row later
 *                 doesn't churn types)
 */
export type ProficiencyScope =
  | 'song'
  | 'song_key'
  | 'skill'
  | 'production'
  | 'concept';
export type PromptTier = 'high' | 'medium' | 'low';
export type PromptStatus =
  | 'queued'
  | 'shown'
  | 'dismissed'
  | 'engaged'
  | 'expired';
export type PromptSurface = 'banner' | 'session_end' | 'home_screen' | 'modal';

/**
 * One slot in a day profile. `skip = true` means the user has
 * declared "no practice in this slot" (not "not yet filled in");
 * minutes/context carry no meaning when skip is true.
 */
export interface DayProfileSlot {
  minutes: number;
  context: PracticeSessionContext;
  skip: boolean;
}

/**
 * Day profile expected-sessions shape. Keys are canonical
 * timeOfDay values: morning / midday / evening. UI can label the
 * midday slot as "Afternoon" if that reads better.
 */
export interface DayProfileExpectedSessions {
  morning: DayProfileSlot;
  midday: DayProfileSlot;
  evening: DayProfileSlot;
}

/**
 * One Practice Sessions session. Phase 1 only writes manually-
 * logged sessions; richer fields (sessionRole, energy*,
 * dayProfileUsed, reasoningSnapshot) are populated by the input
 * questionnaire + generator algorithm in Phase 3+.
 */
export interface PracticeSession {
  id: string;
  startedAt: number;            // epoch ms
  endedAt: number | null;
  plannedDurationMin: number;
  actualDurationMin: number | null;
  context: PracticeSessionContext;
  timeOfDay: PracticeSessionTimeOfDay;
  sessionRole: PracticeSessionRole;
  /** Per-session intent (e.g. 'balanced', 'lean_to_goals',
   *  'recover', 'push_on_X'). Replaces the multi-week mode
   *  declarations from earlier drafts. */
  sessionIntent: string | null;
  hardBlocks: boolean;
  energyFocus: number | null;       // 1-5
  energyMotivation: number | null;  // 1-5
  energyInspiration: number | null; // 1-5
  dayProfileUsed: DayProfileName | null;
  /** "Why this plan?" data captured at generation time. Phase 3+. */
  reasoningSnapshot: Record<string, unknown> | null;
  notes: string | null;
  /** Application-managed; updated when user revisits / edits the
   *  session. Phase 1 sets this on manual-log create. */
  lastEngagedAt: number | null;
  /**
   * Whole-session rating from the end-of-session summary's top
   * zone (Phase 3 Step 6b). One-tap pick: Locked in / Solid /
   * Going through it. Optional — null when the user closes the
   * summary without rating. Distinct from per-block performanceRating.
   */
  sessionRating: PracticeSessionRating | null;
  /**
   * "Optional — a note to your future self" affirmation captured
   * from the end-of-session summary's bottom zone (Phase 3 Step 6d).
   * Free text, optional, "I am..." or "I can..." prompted. Empty
   * string and null are equivalent — caller normalizes to null on
   * save. Surfaced back on future proposal screens via
   * pickRandomAffirmation (Step 4h).
   */
  affirmation: string | null;
}

/**
 * One block within a session. Phase 1 ships the table; the
 * timer-execution UI that creates blocks ships in Phase 4.
 */
export interface PracticeBlock {
  id: string;
  sessionId: string;
  orderIndex: number;
  moduleRef: string;
  subModuleRef: string | null;
  itemRefs: string[];
  plannedMinutes: number;
  actualMinutes: number | null;
  completionStatus: BlockCompletionStatus | null;
  /** Flying / Cruising / Crawling — Phase 4 UI. */
  performanceRating: PerformanceRating | null;
  blockColor: string | null;
  notes: string | null;
}

/**
 * One goal at any scope. `parentGoalId` links to a higher-scope
 * goal as a relationship; `contributesNumericallyToParent` is a
 * separate toggle for whether progress rolls up. Multi-component
 * (umbrella) goals have `isUmbrella = true` and may have null
 * targetMetric/targetValue (their progress comes from children).
 */
export interface Goal {
  id: string;
  scope: GoalScope;
  description: string;
  /** Metric identifier — e.g. 'songs_at_comfortable_plus',
   *  'hours_on_module', 'custom'. Null when umbrella. */
  targetMetric: string | null;
  targetValue: number | null;
  targetUnit: string | null;
  currentValue: number;
  contextTag: PracticeSessionContext | null;
  relatedModules: string[];
  relatedItems: string[];
  startDate: number;   // epoch ms
  targetDate: number;  // epoch ms
  status: GoalStatus;
  /** Relationship link — does NOT imply numerical rollup. */
  parentGoalId: string | null;
  /** Rollup toggle — only meaningful when parentGoalId is set
   *  AND metrics are compatible. Phase 1 surfaces the toggle in
   *  the form; smart auto-suggestion fires in Phase 7. */
  contributesNumericallyToParent: boolean;
  /** Umbrella goals have child sub-goals. Their own
   *  targetMetric/targetValue may be null — progress is computed
   *  across children. Schema in Phase 1; UI in Phase 2. */
  isUmbrella: boolean;
  lastEngagedAt: number | null;
}

/**
 * One of the user's day profiles — Standard, Light, Deep, or a
 * Custom variant. Three profiles seeded during Goals onboarding;
 * any slot is editable post-onboarding.
 */
export interface DayProfile {
  id: string;
  name: DayProfileName;
  expectedSessions: DayProfileExpectedSessions;
  isDefault: boolean;
}

/**
 * A user-declared period off. Spacing decay continues during
 * vacation (truth-honoring) — the only thing vacation affects is
 * goal target dates, handled by the welcome-back UI in Phase 7.
 * No `spacingPaused` field by design.
 */
export interface VacationPeriod {
  id: string;
  startDate: number;  // epoch ms
  endDate: number;    // epoch ms
  reason: string | null;
}

/**
 * Read-only canonical proficiency vocabulary, seeded once per
 * user. Goals, Song Repertoire, Skills Catalogue, and Practice
 * Sessions all reference these definitions. Per-user (matching
 * every other table in this codebase) rather than global; the
 * five rows are identical across users.
 */
export interface ProficiencyDefinition {
  id: string;
  level: ProficiencyLevel;
  scope: ProficiencyScope;
  shortLabel: string;
  description: string;
  example: string;
  displayOrder: number;
}

/**
 * Per-item spacing + acquisition state. Phase 1 creates the
 * table with acquisitionStage defaulting to 'new'; population
 * at scale and signal-driven stage-advancement logic ship in
 * Phase 2.
 */
export interface SpacingState {
  id: string;
  itemRef: string;
  moduleRef: string;
  memoryType: MemoryType;
  acquisitionStage: AcquisitionStage;
  currentIntervalDays: number;
  lastEngagedAt: number | null;
  nextDueAt: number | null;
  performanceHistory: Array<Record<string, unknown>>;
}

/**
 * Centralized prompt orchestration row. All proactive prompts
 * route through this table — Phase 1 only fires the "set goals"
 * nudge user-visibly, plus simple banners for vacation_return
 * and end_of_month events. The orchestration layer enforces a
 * 3/day soft cap, tier prioritization, and suppression during
 * active sessions.
 *
 * The user-facing Settings UI for queue inspection and category
 * mute toggles is deferred to Phase 7 when more prompt types
 * are firing. Phase 1 verifies orchestration via dev console /
 * programmatic checks.
 */
export interface PromptRecord {
  id: string;
  promptType: string;
  tier: PromptTier;
  payload: Record<string, unknown>;
  surface: PromptSurface;
  status: PromptStatus;
  /** Application-managed; set at row creation. Drives FIFO
   *  ordering within tier in the orchestrator. */
  createdAt: number;
  shownAt: number | null;
  dismissedAt: number | null;
  expiresAt: number | null;
  engagedAt: number | null;
  /** Bumped on every dismissal — drives per-prompt-type cadence
   *  rules (e.g., 3-day re-prompt for set_goals_nudge). */
  userDismissalCount: number;
}

// =================================================================
// Song Progression Redesign (Phase 1.5 step 1)
// =================================================================
//
// Six new tables backing the section × key matrix model. Full spec:
// docs/SONG_PROGRESSION_DESIGN_3.md.
//
// Naming note (read this if you're confused about `SongMatrixSection`
// vs `SongSection`): the design doc names its first table
// `songSections`, but that name is already taken in this codebase by
// the Repertoire module's lead-sheet layout (lyrics, phrases, chord
// arrangements — see SongSection above). To ship Phase 1.5 step 1
// without forcing a rename of the lead-sheet system, the matrix
// metadata table goes by `songMatrixSections` here. The two are
// deliberately separate concepts at separate abstraction levels;
// a future unification pass may merge them.
// =================================================================

export interface SongMatrixSection {
  id: string;
  songId: string;
  /** User-defined section name (Verse 1, Chorus, Bridge, Outro,
   *  etc.). No canonical set — suggested chips are offered at
   *  section setup time, custom names allowed alongside. */
  name: string;
  /** Display order in the matrix UI; updated on drag-to-reorder. */
  displayOrder: number;
  /** Soft delete flag. Archived sections are hidden from the matrix
   *  but their cell history is preserved. State rollup excludes
   *  archived sections; restoring re-includes them and key states
   *  recalculate honestly. */
  isArchived: boolean;
  /** When this section was created via a "split" mutation, the
   *  parent section's id. Preserves lineage. Null when the section
   *  was created fresh by the user. */
  splitFromSectionId: string | null;
  /** FK → songSections.id. When set, this matrix row mirrors a
   *  lead-sheet section and the reconciler keeps the two in
   *  lockstep (rename, reorder, archive). Null for legacy matrix
   *  rows created before the one-way sync landed — the reconciler
   *  matches those by name on first run and stamps this field. */
  songSectionId?: string | null;
  createdAt: number;
  updatedAt: number;
}

export type SongKeyState = 'not_started' | 'learning' | 'comfortable' | 'solid';
export type SongKeySolidDecayState = 'solid' | 'fading' | 'lapsed';

export interface SongKey {
  id: string;
  songId: string;
  /** "C", "G", "F#", "Bb", etc. — one of the 12 major keys. */
  keyName: string;
  /** Exactly one row per song has isOriginalKey=true at any time.
   *  Reassignable; matrix data stays intact, only the designation
   *  changes. */
  isOriginalKey: boolean;
  keyState: SongKeyState;
  /** Set when keyState first transitions to 'solid'. Null otherwise. */
  solidAt: number | null;
  /** 'solid' (recently touched) → 'fading' (past 14-day warning) →
   *  'lapsed' (past 30-day threshold, retest recommended). Null
   *  while keyState !== 'solid'. */
  solidDecayState: SongKeySolidDecayState | null;
  lastDecayCheckAt: number | null;
  /** Total sessions that have ever touched this key. */
  livedWithSessionCount: number;
  livedWithFirstSessionAt: number | null;
  /** Rolling-window anchor; re-anchored on each new engagement. */
  livedWithWindowStartAt: number | null;
  /** Sessions touching this key inside the current rolling window. */
  livedWithSessionsInWindow: number;
  /** Most recent timestamp at which the whole-song test was passed
   *  (3 consecutive clean run-throughs at tempo). */
  wholeSongTestPassedAt: number | null;
  /** Set true by the decay algorithm when retest is due. */
  isRetestRecommended: boolean;
  lastEngagedAt: number | null;
  createdAt: number;
  updatedAt: number;
}

export type SongCellState = 'empty' | 'learning' | 'comfortable';

export interface SongCell {
  id: string;
  songId: string;
  /** FK → songMatrixSections.id */
  sectionId: string;
  /** FK → songKeys.id */
  songKeyId: string;
  cellState: SongCellState;
  /** Set when cellState first transitions to 'comfortable'. */
  comfortableAt: number | null;
  /** Current streak toward the 3-run test (0–3). Resets to 0 on any
   *  failed run-through; advances cellState to 'comfortable' when it
   *  reaches 3. */
  consecutiveCleanCount: number;
  lastRunAt: number | null;
  /** True if the most recent run-through was clean; null when no
   *  run-through has been logged yet. */
  lastRunWasClean: boolean | null;
  notes: string | null;
  lastEngagedAt: number | null;
  createdAt: number;
  updatedAt: number;
}

/**
 * Append-only log of cell run-throughs. Inserts drive cell-state
 * advancement via the rollup logic in
 * SONG_PROGRESSION_DESIGN_3.md "Rollup logic". Never updated after
 * insert.
 */
export interface SongCellRunThrough {
  id: string;
  cellId: string;
  songId: string;
  sectionId: string;
  songKeyId: string;
  wasClean: boolean;
  /** Tempo at which the run-through was attempted, or null when the
   *  user logged without a tempo (e.g., from a free-form session). */
  tempoBpm: number | null;
  notes: string | null;
  createdAt: number;
}

/**
 * Append-only log of whole-song test run-throughs. Gates the
 * comfortable → solid transition at the key level: 3 consecutive
 * clean run-throughs IN A SINGLE SESSION required. Test sessions are
 * discrete (each modal-open starts at 0/3) — the user has to put
 * three in a row in one sitting to pass.
 */
export interface SongKeyRunThrough {
  id: string;
  songKeyId: string;
  songId: string;
  wasClean: boolean;
  /** Streak value AFTER this run-through is applied, within the
   *  session that produced it (0 on a failed run, prior+1 on a clean
   *  run, capped at 3). Discrete-session semantics: a row from one
   *  session never sees a row from the previous one — the count
   *  resets at every modal open. Stored for audit-ability so the
   *  log can reconstruct how a session played out. */
  consecutiveCleanCount: number;
  tempoBpm: number | null;
  notes: string | null;
  /** True when this run-through is part of a prompted retest after
   *  a decay lapse, false when it's part of initial Solid testing.
   *  Important for Practice Sessions prioritization and the
   *  meta-dashboard. */
  isRetest: boolean;
  createdAt: number;
}

/**
 * One row per session per key. Any activity touching the song in
 * a given key logs an engagement here; lived-with window logic
 * runs on insert and writes back to songKeys.livedWithSessionsInWindow.
 */
export interface SongKeyEngagement {
  id: string;
  songKeyId: string;
  songId: string;
  /** Optional link to the practice session this engagement belongs
   *  to. Null when logged directly from Song Repertoire without a
   *  session context. */
  practiceSessionId: string | null;
  engagedAt: number;
  createdAt: number;
}

export class AppDB extends Dexie {
  intervals!: Table<IntervalData, string>;
  chordQualities!: Table<ChordData, string>;
  chordShapes!: Table<ChordShapeData, string>;
  songs!: Table<Song, string>;
  sessions!: Table<Session, string>;
  logicSkills!: Table<LogicSkill, string>;
  producerStats!: Table<ProducerStat, string>;
  quizStats!: Table<QuizStat, string>;
  userPrefs!: Table<UserPref, string>;
  attempts!: Table<AttemptRecord, number>;
  dailySummaries!: Table<DailySummary, [string, string]>;
  progressionAssociations!: Table<ProgressionAssociation, string>;
  flashcardStates!: Table<FlashcardState, string>;
  modeAssociations!: Table<ModeAssociation, string>;
  intervalDescriptions!: Table<IntervalDescription, string>;
  songSections!: Table<SongSection, string>;
  songChords!: Table<SongChord, string>;
  songPracticeLog!: Table<SongPracticeLog, string>;
  songCrossKeyProgress!: Table<SongCrossKeyProgress, string>;
  wantToLearn!: Table<WantToLearnEntry, string>;
  drillSkills!: Table<DrillSkill, string>;
  drillTypes!: Table<DrillType, string>;
  drillSessions!: Table<DrillSession, string>;
  creativeSessions!: Table<CreativeSession, string>;
  skillAnnotations!: Table<SkillAnnotation, string>;
  harmonicDiaryEntries!: Table<HarmonicDiaryEntry, string>;
  productionLessons!: Table<ProductionLesson, string>;
  productionLessonSessions!: Table<ProductionLessonSession, string>;
  glossaryTermStates!: Table<GlossaryTermState, string>;
  referenceTracks!: Table<ReferenceTrack, string>;
  lessonReferenceTracks!: Table<LessonReferenceTrack, string>;
  syncQueue!: Table<SyncQueueItem, number>;
  // Practice Sessions + Goals — v16
  practiceSessions!: Table<PracticeSession, string>;
  practiceBlocks!: Table<PracticeBlock, string>;
  goals!: Table<Goal, string>;
  dayProfiles!: Table<DayProfile, string>;
  vacationPeriods!: Table<VacationPeriod, string>;
  proficiencyDefinitions!: Table<ProficiencyDefinition, string>;
  spacingState!: Table<SpacingState, string>;
  prompts!: Table<PromptRecord, string>;
  // Song Progression Redesign — v19 (Phase 1.5 step 1)
  songMatrixSections!: Table<SongMatrixSection, string>;
  songKeys!: Table<SongKey, string>;
  songCells!: Table<SongCell, string>;
  songCellRunThroughs!: Table<SongCellRunThrough, string>;
  songKeyRunThroughs!: Table<SongKeyRunThrough, string>;
  songKeyEngagements!: Table<SongKeyEngagement, string>;

  constructor() {
    super('musical-journey');
    this.version(1).stores({
      intervals: 'id, name, semitones',
      chordQualities: 'id, name, tier, family',
      chordShapes: 'id, chordId, key, inversion',
      songs: 'id, title, artist, addedDate',
      sessions: 'id, date, focus',
      logicSkills: 'id, order',
      producerStats: 'id, pillar',
      quizStats: 'id, scope',
      userPrefs: 'key',
    });
    this.version(2).stores({
      intervals: 'id, name, semitones',
      chordQualities: 'id, name, tier, family',
      chordShapes: 'id, chordId, key, inversion',
      songs: 'id, title, artist, addedDate',
      sessions: 'id, date, focus',
      logicSkills: 'id, order',
      producerStats: 'id, pillar',
      quizStats: 'id, scope',
      userPrefs: 'key',
      attempts: '++id, timestamp, moduleId, [moduleId+itemId+direction]',
    });
    this.version(3).stores({
      intervals: 'id, name, semitones',
      chordQualities: 'id, name, tier, family',
      chordShapes: 'id, chordId, key, inversion',
      songs: 'id, title, artist, addedDate',
      sessions: 'id, date, focus',
      logicSkills: 'id, order',
      producerStats: 'id, pillar',
      quizStats: 'id, scope',
      userPrefs: 'key',
      attempts: '++id, timestamp, moduleId, [moduleId+itemId+direction]',
      dailySummaries: '[date+moduleId], date, moduleId',
    });
    this.version(4).stores({
      intervals: 'id, name, semitones',
      chordQualities: 'id, name, tier, family',
      chordShapes: 'id, chordId, key, inversion',
      songs: 'id, title, artist, addedDate',
      sessions: 'id, date, focus',
      logicSkills: 'id, order',
      producerStats: 'id, pillar',
      quizStats: 'id, scope',
      userPrefs: 'key',
      attempts: '++id, timestamp, moduleId, [moduleId+itemId+direction]',
      dailySummaries: '[date+moduleId], date, moduleId',
      progressionAssociations: 'progressionId',
    });
    this.version(5).stores({
      intervals: 'id, name, semitones',
      chordQualities: 'id, name, tier, family',
      chordShapes: 'id, chordId, key, inversion',
      songs: 'id, title, artist, addedDate',
      sessions: 'id, date, focus',
      logicSkills: 'id, order',
      producerStats: 'id, pillar',
      quizStats: 'id, scope',
      userPrefs: 'key',
      attempts: '++id, timestamp, moduleId, [moduleId+itemId+direction]',
      dailySummaries: '[date+moduleId], date, moduleId',
      progressionAssociations: 'progressionId',
      flashcardStates: 'cardId, nextReviewDate',
    });
    this.version(6).stores({
      intervals: 'id, name, semitones',
      chordQualities: 'id, name, tier, family',
      chordShapes: 'id, chordId, key, inversion',
      songs: 'id, title, artist, addedDate',
      sessions: 'id, date, focus',
      logicSkills: 'id, order',
      producerStats: 'id, pillar',
      quizStats: 'id, scope',
      userPrefs: 'key',
      attempts: '++id, timestamp, moduleId, [moduleId+itemId+direction]',
      dailySummaries: '[date+moduleId], date, moduleId',
      progressionAssociations: 'progressionId',
      flashcardStates: 'cardId, nextReviewDate',
      modeAssociations: 'modeId',
    });
    this.version(7).stores({
      intervals: 'id, name, semitones',
      chordQualities: 'id, name, tier, family',
      chordShapes: 'id, chordId, key, inversion',
      songs: 'id, title, artist, addedDate',
      sessions: 'id, date, focus',
      logicSkills: 'id, order',
      producerStats: 'id, pillar',
      quizStats: 'id, scope',
      userPrefs: 'key',
      attempts: '++id, timestamp, moduleId, [moduleId+itemId+direction]',
      dailySummaries: '[date+moduleId], date, moduleId',
      progressionAssociations: 'progressionId',
      flashcardStates: 'cardId, nextReviewDate',
      modeAssociations: 'modeId',
      intervalDescriptions: 'intervalKey',
    });
    this.version(8).stores({
      intervals: 'id, name, semitones',
      chordQualities: 'id, name, tier, family',
      chordShapes: 'id, chordId, key, inversion',
      songs: 'id, title, artist, addedDate, stage',
      sessions: 'id, date, focus',
      logicSkills: 'id, order',
      producerStats: 'id, pillar',
      quizStats: 'id, scope',
      userPrefs: 'key',
      attempts: '++id, timestamp, moduleId, [moduleId+itemId+direction]',
      dailySummaries: '[date+moduleId], date, moduleId',
      progressionAssociations: 'progressionId',
      flashcardStates: 'cardId, nextReviewDate',
      modeAssociations: 'modeId',
      intervalDescriptions: 'intervalKey',
      // Repertoire module v8 tables. songSections indexes songId so
      // SongDetail can pull all sections at once. songPracticeLog
      // indexes songId + timestamp so the history list is cheap to
      // sort. crossKeyProgress indexes songId and [songId+sectionId]
      // for the per-section grid.
      songSections: 'id, songId, order, [songId+order]',
      songChords: 'id, songId, sectionId, [songId+sectionId+position]',
      songPracticeLog: 'id, songId, timestamp, [songId+timestamp]',
      songCrossKeyProgress: 'id, songId, sectionId, [songId+sectionId]',
      wantToLearn: 'id, addedDate, priority',
    });
    this.version(9).stores({
      intervals: 'id, name, semitones',
      chordQualities: 'id, name, tier, family',
      chordShapes: 'id, chordId, key, inversion',
      songs: 'id, title, artist, addedDate, stage',
      sessions: 'id, date, focus',
      logicSkills: 'id, order',
      producerStats: 'id, pillar',
      quizStats: 'id, scope',
      userPrefs: 'key',
      attempts: '++id, timestamp, moduleId, [moduleId+itemId+direction]',
      dailySummaries: '[date+moduleId], date, moduleId',
      progressionAssociations: 'progressionId',
      flashcardStates: 'cardId, nextReviewDate',
      modeAssociations: 'modeId',
      intervalDescriptions: 'intervalKey',
      songSections: 'id, songId, order, [songId+order]',
      songChords: 'id, songId, sectionId, [songId+sectionId+position]',
      songPracticeLog: 'id, songId, timestamp, [songId+timestamp]',
      songCrossKeyProgress: 'id, songId, sectionId, [songId+sectionId]',
      wantToLearn: 'id, addedDate, priority',
      // Shapes & Patterns module. drillSkills indexes kind + the
      // triplet (kind, keyName, quality) so heat-grid lookups are
      // one round-trip per tab. drillTypes + drillSessions pivot on
      // skillId / drillTypeId for the obvious aggregations.
      drillSkills: 'id, kind, [kind+keyName+quality], [kind+keyName+scale], [kind+patternId+keyName], [kind+variant]',
      drillTypes: 'id, skillId, [skillId+order]',
      drillSessions: 'id, drillTypeId, skillId, timestamp, [skillId+timestamp], [drillTypeId+timestamp]',
    });
    this.version(10).stores({
      intervals: 'id, name, semitones',
      chordQualities: 'id, name, tier, family',
      chordShapes: 'id, chordId, key, inversion',
      songs: 'id, title, artist, addedDate, stage',
      sessions: 'id, date, focus',
      logicSkills: 'id, order',
      producerStats: 'id, pillar',
      quizStats: 'id, scope',
      userPrefs: 'key',
      attempts: '++id, timestamp, moduleId, [moduleId+itemId+direction]',
      dailySummaries: '[date+moduleId], date, moduleId',
      progressionAssociations: 'progressionId',
      flashcardStates: 'cardId, nextReviewDate',
      modeAssociations: 'modeId',
      intervalDescriptions: 'intervalKey',
      songSections: 'id, songId, order, [songId+order]',
      songChords: 'id, songId, sectionId, [songId+sectionId+position]',
      songPracticeLog: 'id, songId, timestamp, [songId+timestamp]',
      songCrossKeyProgress: 'id, songId, sectionId, [songId+sectionId]',
      wantToLearn: 'id, addedDate, priority',
      drillSkills: 'id, kind, [kind+keyName+quality], [kind+keyName+scale], [kind+patternId+keyName], [kind+variant]',
      drillTypes: 'id, skillId, [skillId+order]',
      drillSessions: 'id, drillTypeId, skillId, timestamp, [skillId+timestamp], [drillTypeId+timestamp]',
      // Creative-time sessions (Just Play / Just Produce). Indexed by
      // timestamp for "this week / this month" aggregation and by
      // [mode+timestamp] so the dashboard can split play vs produce
      // time without scanning everything.
      creativeSessions: 'id, timestamp, mode, [mode+timestamp]',
    });
    // v11 — Skills Catalogue user annotations + Harmonic Diary.
    this.version(11).stores({
      intervals: 'id, name, semitones',
      chordQualities: 'id, name, tier, family',
      chordShapes: 'id, chordId, key, inversion',
      songs: 'id, title, artist, addedDate, stage',
      sessions: 'id, date, focus',
      logicSkills: 'id, order',
      producerStats: 'id, pillar',
      quizStats: 'id, scope',
      userPrefs: 'key',
      attempts: '++id, timestamp, moduleId, [moduleId+itemId+direction]',
      dailySummaries: '[date+moduleId], date, moduleId',
      progressionAssociations: 'progressionId',
      flashcardStates: 'cardId, nextReviewDate',
      modeAssociations: 'modeId',
      intervalDescriptions: 'intervalKey',
      songSections: 'id, songId, order, [songId+order]',
      songChords: 'id, songId, sectionId, [songId+sectionId+position]',
      songPracticeLog: 'id, songId, timestamp, [songId+timestamp]',
      songCrossKeyProgress: 'id, songId, sectionId, [songId+sectionId]',
      wantToLearn: 'id, addedDate, priority',
      drillSkills: 'id, kind, [kind+keyName+quality], [kind+keyName+scale], [kind+patternId+keyName], [kind+variant]',
      drillTypes: 'id, skillId, [skillId+order]',
      drillSessions: 'id, drillTypeId, skillId, timestamp, [skillId+timestamp], [drillTypeId+timestamp]',
      creativeSessions: 'id, timestamp, mode, [mode+timestamp]',
      // Skills Catalogue user annotations — keyed by canonical
      // skillId so joins with derived module data are O(1).
      skillAnnotations: 'skillId, priority, updatedAt',
      // Harmonic Diary entries. Indexed on skillId for per-skill
      // lookup and legacySource so we can deduplicate across the
      // old per-module association tables on first migration.
      harmonicDiaryEntries: 'entryId, skillId, lastEdited, legacySource',
    });
    // v12 — Production & Logic Pro module. Per-user lesson + glossary
    // state on top of static content files. Lesson session log
    // tracks revisits for freshness heuristics.
    this.version(12).stores({
      intervals: 'id, name, semitones',
      chordQualities: 'id, name, tier, family',
      chordShapes: 'id, chordId, key, inversion',
      songs: 'id, title, artist, addedDate, stage',
      sessions: 'id, date, focus',
      logicSkills: 'id, order',
      producerStats: 'id, pillar',
      quizStats: 'id, scope',
      userPrefs: 'key',
      attempts: '++id, timestamp, moduleId, [moduleId+itemId+direction]',
      dailySummaries: '[date+moduleId], date, moduleId',
      progressionAssociations: 'progressionId',
      flashcardStates: 'cardId, nextReviewDate',
      modeAssociations: 'modeId',
      intervalDescriptions: 'intervalKey',
      songSections: 'id, songId, order, [songId+order]',
      songChords: 'id, songId, sectionId, [songId+sectionId+position]',
      songPracticeLog: 'id, songId, timestamp, [songId+timestamp]',
      songCrossKeyProgress: 'id, songId, sectionId, [songId+sectionId]',
      wantToLearn: 'id, addedDate, priority',
      drillSkills: 'id, kind, [kind+keyName+quality], [kind+keyName+scale], [kind+patternId+keyName], [kind+variant]',
      drillTypes: 'id, skillId, [skillId+order]',
      drillSessions: 'id, drillTypeId, skillId, timestamp, [skillId+timestamp], [drillTypeId+timestamp]',
      creativeSessions: 'id, timestamp, mode, [mode+timestamp]',
      skillAnnotations: 'skillId, priority, updatedAt',
      harmonicDiaryEntries: 'entryId, skillId, lastEdited, legacySource',
      productionLessons: 'id, pathId, [pathId+order], mastery, lastOpenedAt',
      productionLessonSessions: 'id, lessonId, timestamp',
      glossaryTermStates: 'id, mastery, lastEncounteredAt',
      referenceTracks: 'id, artist, genre, archived, addedAt',
    });
    // v13 — Reference Track schema update: rename sonicNotes →
    // whatToListenFor, add myListeningNotes, spotify/youtube links,
    // and a `source` provenance flag. Indexes unchanged (new fields
    // aren't indexed). The upgrade hook copies legacy sonicNotes to
    // whatToListenFor and backfills `source` from the existing
    // `isStarter` flag so existing rows don't look blank.
    this.version(13).stores({
      intervals: 'id, name, semitones',
      chordQualities: 'id, name, tier, family',
      chordShapes: 'id, chordId, key, inversion',
      songs: 'id, title, artist, addedDate, stage',
      sessions: 'id, date, focus',
      logicSkills: 'id, order',
      producerStats: 'id, pillar',
      quizStats: 'id, scope',
      userPrefs: 'key',
      attempts: '++id, timestamp, moduleId, [moduleId+itemId+direction]',
      dailySummaries: '[date+moduleId], date, moduleId',
      progressionAssociations: 'progressionId',
      flashcardStates: 'cardId, nextReviewDate',
      modeAssociations: 'modeId',
      intervalDescriptions: 'intervalKey',
      songSections: 'id, songId, order, [songId+order]',
      songChords: 'id, songId, sectionId, [songId+sectionId+position]',
      songPracticeLog: 'id, songId, timestamp, [songId+timestamp]',
      songCrossKeyProgress: 'id, songId, sectionId, [songId+sectionId]',
      wantToLearn: 'id, addedDate, priority',
      drillSkills: 'id, kind, [kind+keyName+quality], [kind+keyName+scale], [kind+patternId+keyName], [kind+variant]',
      drillTypes: 'id, skillId, [skillId+order]',
      drillSessions: 'id, drillTypeId, skillId, timestamp, [skillId+timestamp], [drillTypeId+timestamp]',
      creativeSessions: 'id, timestamp, mode, [mode+timestamp]',
      skillAnnotations: 'skillId, priority, updatedAt',
      harmonicDiaryEntries: 'entryId, skillId, lastEdited, legacySource',
      productionLessons: 'id, pathId, [pathId+order], mastery, lastOpenedAt',
      productionLessonSessions: 'id, lessonId, timestamp',
      glossaryTermStates: 'id, mastery, lastEncounteredAt',
      referenceTracks: 'id, artist, genre, archived, addedAt',
    }).upgrade(async tx => {
      const table = tx.table('referenceTracks');
      await table.toCollection().modify(row => {
        if (typeof row.whatToListenFor !== 'string') {
          row.whatToListenFor = typeof row.sonicNotes === 'string' ? row.sonicNotes : '';
        }
        if (typeof row.myListeningNotes !== 'string') {
          row.myListeningNotes = '';
        }
        if (!row.source) {
          row.source = row.isStarter ? 'starter' : 'user';
        }
      });
    });
    // v15 adds the offline sync queue; see below. No schema changes
    // to existing tables — v14 remains the authoritative shape.
    // v14 — User-curated per-lesson reference track associations.
    // Replaces the content-authored `referenceTracks: [...]` arrays on
    // lessons. Indexed by lessonId and trackId separately (both sides
    // of the many-to-many are queried independently) plus the composite
    // so "is this exact pair already linked?" lookups are one hit.
    this.version(14).stores({
      intervals: 'id, name, semitones',
      chordQualities: 'id, name, tier, family',
      chordShapes: 'id, chordId, key, inversion',
      songs: 'id, title, artist, addedDate, stage',
      sessions: 'id, date, focus',
      logicSkills: 'id, order',
      producerStats: 'id, pillar',
      quizStats: 'id, scope',
      userPrefs: 'key',
      attempts: '++id, timestamp, moduleId, [moduleId+itemId+direction]',
      dailySummaries: '[date+moduleId], date, moduleId',
      progressionAssociations: 'progressionId',
      flashcardStates: 'cardId, nextReviewDate',
      modeAssociations: 'modeId',
      intervalDescriptions: 'intervalKey',
      songSections: 'id, songId, order, [songId+order]',
      songChords: 'id, songId, sectionId, [songId+sectionId+position]',
      songPracticeLog: 'id, songId, timestamp, [songId+timestamp]',
      songCrossKeyProgress: 'id, songId, sectionId, [songId+sectionId]',
      wantToLearn: 'id, addedDate, priority',
      drillSkills: 'id, kind, [kind+keyName+quality], [kind+keyName+scale], [kind+patternId+keyName], [kind+variant]',
      drillTypes: 'id, skillId, [skillId+order]',
      drillSessions: 'id, drillTypeId, skillId, timestamp, [skillId+timestamp], [drillTypeId+timestamp]',
      creativeSessions: 'id, timestamp, mode, [mode+timestamp]',
      skillAnnotations: 'skillId, priority, updatedAt',
      harmonicDiaryEntries: 'entryId, skillId, lastEdited, legacySource',
      productionLessons: 'id, pathId, [pathId+order], mastery, lastOpenedAt',
      productionLessonSessions: 'id, lessonId, timestamp',
      glossaryTermStates: 'id, mastery, lastEncounteredAt',
      referenceTracks: 'id, artist, genre, archived, addedAt',
      lessonReferenceTracks: 'id, lessonId, trackId, [lessonId+trackId]',
    });
    // v15 — Offline sync queue. Dexie write hooks push jobs here;
    // the sync engine drains them to Supabase when online. Auto-
    // incrementing id for FIFO ordering; indexed by tableName +
    // queuedAt so the drain loop can batch by table.
    this.version(15).stores({
      intervals: 'id, name, semitones',
      chordQualities: 'id, name, tier, family',
      chordShapes: 'id, chordId, key, inversion',
      songs: 'id, title, artist, addedDate, stage',
      sessions: 'id, date, focus',
      logicSkills: 'id, order',
      producerStats: 'id, pillar',
      quizStats: 'id, scope',
      userPrefs: 'key',
      attempts: '++id, timestamp, moduleId, [moduleId+itemId+direction]',
      dailySummaries: '[date+moduleId], date, moduleId',
      progressionAssociations: 'progressionId',
      flashcardStates: 'cardId, nextReviewDate',
      modeAssociations: 'modeId',
      intervalDescriptions: 'intervalKey',
      songSections: 'id, songId, order, [songId+order]',
      songChords: 'id, songId, sectionId, [songId+sectionId+position]',
      songPracticeLog: 'id, songId, timestamp, [songId+timestamp]',
      songCrossKeyProgress: 'id, songId, sectionId, [songId+sectionId]',
      wantToLearn: 'id, addedDate, priority',
      drillSkills: 'id, kind, [kind+keyName+quality], [kind+keyName+scale], [kind+patternId+keyName], [kind+variant]',
      drillTypes: 'id, skillId, [skillId+order]',
      drillSessions: 'id, drillTypeId, skillId, timestamp, [skillId+timestamp], [drillTypeId+timestamp]',
      creativeSessions: 'id, timestamp, mode, [mode+timestamp]',
      skillAnnotations: 'skillId, priority, updatedAt',
      harmonicDiaryEntries: 'entryId, skillId, lastEdited, legacySource',
      productionLessons: 'id, pathId, [pathId+order], mastery, lastOpenedAt',
      productionLessonSessions: 'id, lessonId, timestamp',
      glossaryTermStates: 'id, mastery, lastEncounteredAt',
      referenceTracks: 'id, artist, genre, archived, addedAt',
      lessonReferenceTracks: 'id, lessonId, trackId, [lessonId+trackId]',
      syncQueue: '++id, tableName, queuedAt, [tableName+queuedAt]',
    });
    // v16 — Practice Sessions + Goals foundation. Eight new tables
    // introducing the Goals layer and the foundation for the
    // Practice Sessions module. Indexes chosen for the queries we
    // know we'll run in Phase 1 (recent sessions by startedAt,
    // active goals by scope+status, due items by nextDueAt, queued
    // prompts by status+tier). Composite indexes match the
    // orchestrator queries described in PRACTICE_SESSIONS_DESIGN_3.md.
    this.version(16).stores({
      intervals: 'id, name, semitones',
      chordQualities: 'id, name, tier, family',
      chordShapes: 'id, chordId, key, inversion',
      songs: 'id, title, artist, addedDate, stage',
      sessions: 'id, date, focus',
      logicSkills: 'id, order',
      producerStats: 'id, pillar',
      quizStats: 'id, scope',
      userPrefs: 'key',
      attempts: '++id, timestamp, moduleId, [moduleId+itemId+direction]',
      dailySummaries: '[date+moduleId], date, moduleId',
      progressionAssociations: 'progressionId',
      flashcardStates: 'cardId, nextReviewDate',
      modeAssociations: 'modeId',
      intervalDescriptions: 'intervalKey',
      songSections: 'id, songId, order, [songId+order]',
      songChords: 'id, songId, sectionId, [songId+sectionId+position]',
      songPracticeLog: 'id, songId, timestamp, [songId+timestamp]',
      songCrossKeyProgress: 'id, songId, sectionId, [songId+sectionId]',
      wantToLearn: 'id, addedDate, priority',
      drillSkills: 'id, kind, [kind+keyName+quality], [kind+keyName+scale], [kind+patternId+keyName], [kind+variant]',
      drillTypes: 'id, skillId, [skillId+order]',
      drillSessions: 'id, drillTypeId, skillId, timestamp, [skillId+timestamp], [drillTypeId+timestamp]',
      creativeSessions: 'id, timestamp, mode, [mode+timestamp]',
      skillAnnotations: 'skillId, priority, updatedAt',
      harmonicDiaryEntries: 'entryId, skillId, lastEdited, legacySource',
      productionLessons: 'id, pathId, [pathId+order], mastery, lastOpenedAt',
      productionLessonSessions: 'id, lessonId, timestamp',
      glossaryTermStates: 'id, mastery, lastEncounteredAt',
      referenceTracks: 'id, artist, genre, archived, addedAt',
      lessonReferenceTracks: 'id, lessonId, trackId, [lessonId+trackId]',
      syncQueue: '++id, tableName, queuedAt, [tableName+queuedAt]',
      // Practice Sessions + Goals (Phase 1)
      practiceSessions: 'id, startedAt, sessionRole, dayProfileUsed',
      practiceBlocks: 'id, sessionId, [sessionId+orderIndex]',
      goals: 'id, scope, status, parentGoalId, targetDate, [scope+status]',
      dayProfiles: 'id, name',
      vacationPeriods: 'id, startDate, endDate',
      proficiencyDefinitions: 'id, level, displayOrder',
      spacingState: 'id, itemRef, moduleRef, nextDueAt, acquisitionStage, [moduleRef+itemRef]',
      prompts: 'id, status, tier, promptType, surface, expiresAt, createdAt, [status+tier]',
    });
    // v17 — checkpoint for two TS-level enum widenings landing
    // alongside Goals module sub-phase 3 (April 25, 2026 kick-off):
    //
    //   - PracticeSessionTimeOfDay gains 'late_night' (4-window
    //     classification with previous-day rollup for after-midnight
    //     sessions; rollup logic itself is Phase 3+).
    //   - GoalScope replaces 'three_to_five_year' with
    //     'two_to_three_year' (more honest planning horizon).
    //
    // Both values live in the JSONB `data` payload of their rows
    // (time_of_day on practiceSessions, scope is indexed in Dexie
    // but the index is over string content, not enum constraints),
    // so the .stores() declaration is identical to v16. The version
    // bump is a checkpoint so future readers can correlate the
    // schema version with the type widening, not a structural
    // change Dexie needs to migrate.
    //
    // No Postgres migration: 003_practice_sessions_phase1.sql
    // declared both columns as TEXT / JSONB-only with no CHECK
    // constraints, so Postgres already accepts the new values.
    this.version(17).stores({
      intervals: 'id, name, semitones',
      chordQualities: 'id, name, tier, family',
      chordShapes: 'id, chordId, key, inversion',
      songs: 'id, title, artist, addedDate, stage',
      sessions: 'id, date, focus',
      logicSkills: 'id, order',
      producerStats: 'id, pillar',
      quizStats: 'id, scope',
      userPrefs: 'key',
      attempts: '++id, timestamp, moduleId, [moduleId+itemId+direction]',
      dailySummaries: '[date+moduleId], date, moduleId',
      progressionAssociations: 'progressionId',
      flashcardStates: 'cardId, nextReviewDate',
      modeAssociations: 'modeId',
      intervalDescriptions: 'intervalKey',
      songSections: 'id, songId, order, [songId+order]',
      songChords: 'id, songId, sectionId, [songId+sectionId+position]',
      songPracticeLog: 'id, songId, timestamp, [songId+timestamp]',
      songCrossKeyProgress: 'id, songId, sectionId, [songId+sectionId]',
      wantToLearn: 'id, addedDate, priority',
      drillSkills: 'id, kind, [kind+keyName+quality], [kind+keyName+scale], [kind+patternId+keyName], [kind+variant]',
      drillTypes: 'id, skillId, [skillId+order]',
      drillSessions: 'id, drillTypeId, skillId, timestamp, [skillId+timestamp], [drillTypeId+timestamp]',
      creativeSessions: 'id, timestamp, mode, [mode+timestamp]',
      skillAnnotations: 'skillId, priority, updatedAt',
      harmonicDiaryEntries: 'entryId, skillId, lastEdited, legacySource',
      productionLessons: 'id, pathId, [pathId+order], mastery, lastOpenedAt',
      productionLessonSessions: 'id, lessonId, timestamp',
      glossaryTermStates: 'id, mastery, lastEncounteredAt',
      referenceTracks: 'id, artist, genre, archived, addedAt',
      lessonReferenceTracks: 'id, lessonId, trackId, [lessonId+trackId]',
      syncQueue: '++id, tableName, queuedAt, [tableName+queuedAt]',
      practiceSessions: 'id, startedAt, sessionRole, dayProfileUsed',
      practiceBlocks: 'id, sessionId, [sessionId+orderIndex]',
      goals: 'id, scope, status, parentGoalId, targetDate, [scope+status]',
      dayProfiles: 'id, name',
      vacationPeriods: 'id, startDate, endDate',
      proficiencyDefinitions: 'id, level, displayOrder',
      spacingState: 'id, itemRef, moduleRef, nextDueAt, acquisitionStage, [moduleRef+itemRef]',
      prompts: 'id, status, tier, promptType, surface, expiresAt, createdAt, [status+tier]',
    });
    // v18 — checkpoint for the proficiency framework expansion in
    // sub-phase 3 step 4: ProficiencyLevel widens to eleven unique
    // levels across three vocabularies (skill / song / production)
    // and ProficiencyScope adds 'production'. Both fields live in
    // JSONB on the proficiency_definitions row, so the .stores()
    // declaration is identical to v17 — the bump is a traceability
    // marker for the type widening.
    //
    // Also: the song stage display_order in the
    // proficiencyDefinitions seed reorders cross-key (was 4) → 3
    // and internalized (was 3) → 4. No data migration on the
    // songs.stage column itself: stage strings on existing rows
    // are unchanged; only their meaning shifts under the new
    // framework (a song labeled 'internalized' now means "memorized
    // and felt in any key" instead of "memorized in original key").
    // The user is the only consumer; existing 'internalized' songs
    // may not meet the new definition and will be re-evaluated
    // outside the system.
    //
    // No Postgres migration: proficiency_definitions.scope and
    // .level are TEXT columns with no CHECK constraints in the
    // 003 migration, so Postgres already accepts the new values.
    this.version(18).stores({
      intervals: 'id, name, semitones',
      chordQualities: 'id, name, tier, family',
      chordShapes: 'id, chordId, key, inversion',
      songs: 'id, title, artist, addedDate, stage',
      sessions: 'id, date, focus',
      logicSkills: 'id, order',
      producerStats: 'id, pillar',
      quizStats: 'id, scope',
      userPrefs: 'key',
      attempts: '++id, timestamp, moduleId, [moduleId+itemId+direction]',
      dailySummaries: '[date+moduleId], date, moduleId',
      progressionAssociations: 'progressionId',
      flashcardStates: 'cardId, nextReviewDate',
      modeAssociations: 'modeId',
      intervalDescriptions: 'intervalKey',
      songSections: 'id, songId, order, [songId+order]',
      songChords: 'id, songId, sectionId, [songId+sectionId+position]',
      songPracticeLog: 'id, songId, timestamp, [songId+timestamp]',
      songCrossKeyProgress: 'id, songId, sectionId, [songId+sectionId]',
      wantToLearn: 'id, addedDate, priority',
      drillSkills: 'id, kind, [kind+keyName+quality], [kind+keyName+scale], [kind+patternId+keyName], [kind+variant]',
      drillTypes: 'id, skillId, [skillId+order]',
      drillSessions: 'id, drillTypeId, skillId, timestamp, [skillId+timestamp], [drillTypeId+timestamp]',
      creativeSessions: 'id, timestamp, mode, [mode+timestamp]',
      skillAnnotations: 'skillId, priority, updatedAt',
      harmonicDiaryEntries: 'entryId, skillId, lastEdited, legacySource',
      productionLessons: 'id, pathId, [pathId+order], mastery, lastOpenedAt',
      productionLessonSessions: 'id, lessonId, timestamp',
      glossaryTermStates: 'id, mastery, lastEncounteredAt',
      referenceTracks: 'id, artist, genre, archived, addedAt',
      lessonReferenceTracks: 'id, lessonId, trackId, [lessonId+trackId]',
      syncQueue: '++id, tableName, queuedAt, [tableName+queuedAt]',
      practiceSessions: 'id, startedAt, sessionRole, dayProfileUsed',
      practiceBlocks: 'id, sessionId, [sessionId+orderIndex]',
      goals: 'id, scope, status, parentGoalId, targetDate, [scope+status]',
      dayProfiles: 'id, name',
      vacationPeriods: 'id, startDate, endDate',
      proficiencyDefinitions: 'id, level, displayOrder',
      spacingState: 'id, itemRef, moduleRef, nextDueAt, acquisitionStage, [moduleRef+itemRef]',
      prompts: 'id, status, tier, promptType, surface, expiresAt, createdAt, [status+tier]',
    });

    // v19 — Phase 1.5 step 1: Song Progression Redesign schema.
    // Six new tables backing the section × key matrix model.
    // See docs/SONG_PROGRESSION_DESIGN_3.md and the Postgres
    // mirror at supabase/migrations/004_song_progression_phase_1_5.sql.
    //
    // The v18 `songSections` (lead-sheet layout) stays in place
    // unchanged; the matrix metadata table ships as
    // `songMatrixSections` to dodge the name collision. The v18
    // `songCrossKeyProgress` is also kept intact — see the
    // @deprecated note on the SongCrossKeyProgress interface above.
    this.version(19).stores({
      intervals: 'id, name, semitones',
      chordQualities: 'id, name, tier, family',
      chordShapes: 'id, chordId, key, inversion',
      songs: 'id, title, artist, addedDate, stage',
      sessions: 'id, date, focus',
      logicSkills: 'id, order',
      producerStats: 'id, pillar',
      quizStats: 'id, scope',
      userPrefs: 'key',
      attempts: '++id, timestamp, moduleId, [moduleId+itemId+direction]',
      dailySummaries: '[date+moduleId], date, moduleId',
      progressionAssociations: 'progressionId',
      flashcardStates: 'cardId, nextReviewDate',
      modeAssociations: 'modeId',
      intervalDescriptions: 'intervalKey',
      songSections: 'id, songId, order, [songId+order]',
      songChords: 'id, songId, sectionId, [songId+sectionId+position]',
      songPracticeLog: 'id, songId, timestamp, [songId+timestamp]',
      songCrossKeyProgress: 'id, songId, sectionId, [songId+sectionId]',
      wantToLearn: 'id, addedDate, priority',
      drillSkills: 'id, kind, [kind+keyName+quality], [kind+keyName+scale], [kind+patternId+keyName], [kind+variant]',
      drillTypes: 'id, skillId, [skillId+order]',
      drillSessions: 'id, drillTypeId, skillId, timestamp, [skillId+timestamp], [drillTypeId+timestamp]',
      creativeSessions: 'id, timestamp, mode, [mode+timestamp]',
      skillAnnotations: 'skillId, priority, updatedAt',
      harmonicDiaryEntries: 'entryId, skillId, lastEdited, legacySource',
      productionLessons: 'id, pathId, [pathId+order], mastery, lastOpenedAt',
      productionLessonSessions: 'id, lessonId, timestamp',
      glossaryTermStates: 'id, mastery, lastEncounteredAt',
      referenceTracks: 'id, artist, genre, archived, addedAt',
      lessonReferenceTracks: 'id, lessonId, trackId, [lessonId+trackId]',
      syncQueue: '++id, tableName, queuedAt, [tableName+queuedAt]',
      practiceSessions: 'id, startedAt, sessionRole, dayProfileUsed',
      practiceBlocks: 'id, sessionId, [sessionId+orderIndex]',
      goals: 'id, scope, status, parentGoalId, targetDate, [scope+status]',
      dayProfiles: 'id, name',
      vacationPeriods: 'id, startDate, endDate',
      proficiencyDefinitions: 'id, level, displayOrder',
      spacingState: 'id, itemRef, moduleRef, nextDueAt, acquisitionStage, [moduleRef+itemRef]',
      prompts: 'id, status, tier, promptType, surface, expiresAt, createdAt, [status+tier]',
      songMatrixSections: 'id, songId, displayOrder, [songId+displayOrder], isArchived',
      songKeys: 'id, songId, keyName, isOriginalKey, keyState, solidDecayState, lastEngagedAt, [songId+keyName]',
      songCells: 'id, songId, sectionId, songKeyId, cellState, [sectionId+songKeyId]',
      songCellRunThroughs: 'id, cellId, songId, sectionId, songKeyId, createdAt, [cellId+createdAt]',
      songKeyRunThroughs: 'id, songKeyId, songId, createdAt, isRetest, [songKeyId+createdAt]',
      songKeyEngagements: 'id, songKeyId, songId, engagedAt, practiceSessionId, [songKeyId+engagedAt]',
    });

    // v20 — checkpoint for Phase 3 Step 6a TS-level additions on
    // PracticeSession: sessionRating + affirmation columns. Both
    // live in the JSONB `data` payload of practice_sessions (per
    // 003_practice_sessions_phase1.sql — the row's non-indexed
    // fields are JSONB, not columns), so .stores() is unchanged
    // and no Postgres migration is required. The version bump is
    // a checkpoint so future readers can correlate the schema
    // version with the type widening.
    this.version(20).stores({
      intervals: 'id, name, semitones',
      chordQualities: 'id, name, tier, family',
      chordShapes: 'id, chordId, key, inversion',
      songs: 'id, title, artist, addedDate, stage',
      sessions: 'id, date, focus',
      logicSkills: 'id, order',
      producerStats: 'id, pillar',
      quizStats: 'id, scope',
      userPrefs: 'key',
      attempts: '++id, timestamp, moduleId, [moduleId+itemId+direction]',
      dailySummaries: '[date+moduleId], date, moduleId',
      progressionAssociations: 'progressionId',
      flashcardStates: 'cardId, nextReviewDate',
      modeAssociations: 'modeId',
      intervalDescriptions: 'intervalKey',
      songSections: 'id, songId, order, [songId+order]',
      songChords: 'id, songId, sectionId, [songId+sectionId+position]',
      songPracticeLog: 'id, songId, timestamp, [songId+timestamp]',
      songCrossKeyProgress: 'id, songId, sectionId, [songId+sectionId]',
      wantToLearn: 'id, addedDate, priority',
      drillSkills: 'id, kind, [kind+keyName+quality], [kind+keyName+scale], [kind+patternId+keyName], [kind+variant]',
      drillTypes: 'id, skillId, [skillId+order]',
      drillSessions: 'id, drillTypeId, skillId, timestamp, [skillId+timestamp], [drillTypeId+timestamp]',
      creativeSessions: 'id, timestamp, mode, [mode+timestamp]',
      skillAnnotations: 'skillId, priority, updatedAt',
      harmonicDiaryEntries: 'entryId, skillId, lastEdited, legacySource',
      productionLessons: 'id, pathId, [pathId+order], mastery, lastOpenedAt',
      productionLessonSessions: 'id, lessonId, timestamp',
      glossaryTermStates: 'id, mastery, lastEncounteredAt',
      referenceTracks: 'id, artist, genre, archived, addedAt',
      lessonReferenceTracks: 'id, lessonId, trackId, [lessonId+trackId]',
      syncQueue: '++id, tableName, queuedAt, [tableName+queuedAt]',
      practiceSessions: 'id, startedAt, sessionRole, dayProfileUsed',
      practiceBlocks: 'id, sessionId, [sessionId+orderIndex]',
      goals: 'id, scope, status, parentGoalId, targetDate, [scope+status]',
      dayProfiles: 'id, name',
      vacationPeriods: 'id, startDate, endDate',
      proficiencyDefinitions: 'id, level, displayOrder',
      spacingState: 'id, itemRef, moduleRef, nextDueAt, acquisitionStage, [moduleRef+itemRef]',
      prompts: 'id, status, tier, promptType, surface, expiresAt, createdAt, [status+tier]',
      songMatrixSections: 'id, songId, displayOrder, [songId+displayOrder], isArchived',
      songKeys: 'id, songId, keyName, isOriginalKey, keyState, solidDecayState, lastEngagedAt, [songId+keyName]',
      songCells: 'id, songId, sectionId, songKeyId, cellState, [sectionId+songKeyId]',
      songCellRunThroughs: 'id, cellId, songId, sectionId, songKeyId, createdAt, [cellId+createdAt]',
      songKeyRunThroughs: 'id, songKeyId, songId, createdAt, isRetest, [songKeyId+createdAt]',
      songKeyEngagements: 'id, songKeyId, songId, engagedAt, practiceSessionId, [songKeyId+engagedAt]',
    });

    // v21 — Song.learningOrder field for the user-authored study
    // sequence. Backfills existing rows to addedDate-ASC rank so
    // oldest = 1 (matches the user's expectation of "the songs I
    // added first are earliest in my learning queue"). New rows
    // assign MAX(learningOrder) + 1 at insert time — see
    // assignNextLearningOrder() in modules/repertoire/seedSongs.ts.
    //
    // TODO (Supabase): Postgres migration to add the matching column
    // before this schema reaches production sync:
    //   ALTER TABLE songs ADD COLUMN learning_order INTEGER NOT NULL DEFAULT 0;
    // Then backfill via SQL using row_number() OVER (ORDER BY added_date),
    // matching the Dexie upgrade callback below. Until the column
    // exists, learningOrder still round-trips because the full Dexie
    // row lives in the `data` JSONB blob — only the indexed top-level
    // column is missing. Once the migration ships, add the mapping
    // `{ dexie: 'learningOrder', pg: 'learning_order' }` to the songs
    // entry in src/lib/sync/tables.ts (a TODO is parked there).
    this.version(21).stores({
      intervals: 'id, name, semitones',
      chordQualities: 'id, name, tier, family',
      chordShapes: 'id, chordId, key, inversion',
      songs: 'id, title, artist, addedDate, stage, learningOrder',
      sessions: 'id, date, focus',
      logicSkills: 'id, order',
      producerStats: 'id, pillar',
      quizStats: 'id, scope',
      userPrefs: 'key',
      attempts: '++id, timestamp, moduleId, [moduleId+itemId+direction]',
      dailySummaries: '[date+moduleId], date, moduleId',
      progressionAssociations: 'progressionId',
      flashcardStates: 'cardId, nextReviewDate',
      modeAssociations: 'modeId',
      intervalDescriptions: 'intervalKey',
      songSections: 'id, songId, order, [songId+order]',
      songChords: 'id, songId, sectionId, [songId+sectionId+position]',
      songPracticeLog: 'id, songId, timestamp, [songId+timestamp]',
      songCrossKeyProgress: 'id, songId, sectionId, [songId+sectionId]',
      wantToLearn: 'id, addedDate, priority',
      drillSkills: 'id, kind, [kind+keyName+quality], [kind+keyName+scale], [kind+patternId+keyName], [kind+variant]',
      drillTypes: 'id, skillId, [skillId+order]',
      drillSessions: 'id, drillTypeId, skillId, timestamp, [skillId+timestamp], [drillTypeId+timestamp]',
      creativeSessions: 'id, timestamp, mode, [mode+timestamp]',
      skillAnnotations: 'skillId, priority, updatedAt',
      harmonicDiaryEntries: 'entryId, skillId, lastEdited, legacySource',
      productionLessons: 'id, pathId, [pathId+order], mastery, lastOpenedAt',
      productionLessonSessions: 'id, lessonId, timestamp',
      glossaryTermStates: 'id, mastery, lastEncounteredAt',
      referenceTracks: 'id, artist, genre, archived, addedAt',
      lessonReferenceTracks: 'id, lessonId, trackId, [lessonId+trackId]',
      syncQueue: '++id, tableName, queuedAt, [tableName+queuedAt]',
      practiceSessions: 'id, startedAt, sessionRole, dayProfileUsed',
      practiceBlocks: 'id, sessionId, [sessionId+orderIndex]',
      goals: 'id, scope, status, parentGoalId, targetDate, [scope+status]',
      dayProfiles: 'id, name',
      vacationPeriods: 'id, startDate, endDate',
      proficiencyDefinitions: 'id, level, displayOrder',
      spacingState: 'id, itemRef, moduleRef, nextDueAt, acquisitionStage, [moduleRef+itemRef]',
      prompts: 'id, status, tier, promptType, surface, expiresAt, createdAt, [status+tier]',
      songMatrixSections: 'id, songId, displayOrder, [songId+displayOrder], isArchived',
      songKeys: 'id, songId, keyName, isOriginalKey, keyState, solidDecayState, lastEngagedAt, [songId+keyName]',
      songCells: 'id, songId, sectionId, songKeyId, cellState, [sectionId+songKeyId]',
      songCellRunThroughs: 'id, cellId, songId, sectionId, songKeyId, createdAt, [cellId+createdAt]',
      songKeyRunThroughs: 'id, songKeyId, songId, createdAt, isRetest, [songKeyId+createdAt]',
      songKeyEngagements: 'id, songKeyId, songId, engagedAt, practiceSessionId, [songKeyId+engagedAt]',
    }).upgrade(async tx => {
      // Backfill: existing songs get sequential learningOrder values
      // based on addedDate ASC (oldest first). Rows without an
      // addedDate (defensive against partial data) sort to the end.
      const rows = await tx.table('songs').toArray();
      rows.sort((a, b) => (a.addedDate ?? Infinity) - (b.addedDate ?? Infinity));
      for (let i = 0; i < rows.length; i++) {
        await tx.table('songs').update(rows[i].id, { learningOrder: i + 1 });
      }
    });
  }
}

export const db = new AppDB();

// Dev-only: expose db on window for console debugging. Vite strips
// the entire block from production builds via the import.meta.env.DEV
// guard (it folds to `if (false)` and tree-shakes).
if (import.meta.env.DEV) {
  (window as unknown as { db: AppDB }).db = db;
}
