/**
 * Phase 3 Step 2e — Time allocation + block sequencing.
 *
 * Two pure transformations on the candidate-block list the algorithm
 * builds upstream:
 *
 *   allocateBlockTime(blocks, availableSeconds)
 *     Distributes the session's total time across blocks honoring per-
 *     memory-type minimums and typicals (algorithm Step 7). Strategy:
 *     start each block at its typical-low duration; scale all blocks
 *     proportionally up or down to match available time; if scaling
 *     would push any block below its minimum, drop the lowest-weight
 *     blocks and retry. Never returns a block below its minimum.
 *
 *   sequenceBlocks(blocks)
 *     Orders blocks per algorithm Step 8: acquisition / hard cognitive
 *     work first (fresh attention), review / maintenance in the middle,
 *     creative / expression last. Within phase, higher-weight blocks
 *     come first. The result's first block carries the warm-up badge
 *     in the UI; this layer doesn't tag it explicitly.
 *
 * Within-day spacing (algorithm Step 6) is intentionally out of scope
 * for Phase 3 — blocks here are independent of any other-time-of-day
 * touches.
 */

import type { MemoryType } from '../db';

const SECONDS_PER_MINUTE = 60;

// ---------------------------------------------------------------------
// Per-memory-type duration table
// ---------------------------------------------------------------------

export interface DurationTier {
  /** Minimum block duration in seconds — never go below this. */
  minSeconds: number;
  /** Typical low end (default block size). */
  typicalLowSeconds: number;
  /** Typical high end. */
  typicalHighSeconds: number;
}

export const MEMORY_TYPE_DURATIONS: Record<MemoryType, DurationTier> = {
  declarative: {
    minSeconds:         3 * SECONDS_PER_MINUTE,
    typicalLowSeconds:  5 * SECONDS_PER_MINUTE,
    typicalHighSeconds: 10 * SECONDS_PER_MINUTE,
  },
  procedural: {
    minSeconds:         5 * SECONDS_PER_MINUTE,
    typicalLowSeconds:  10 * SECONDS_PER_MINUTE,
    typicalHighSeconds: 15 * SECONDS_PER_MINUTE,
  },
  integration: {
    minSeconds:         10 * SECONDS_PER_MINUTE,
    typicalLowSeconds:  15 * SECONDS_PER_MINUTE,
    typicalHighSeconds: 20 * SECONDS_PER_MINUTE,
  },
  expression: {
    minSeconds:         5 * SECONDS_PER_MINUTE,
    typicalLowSeconds:  10 * SECONDS_PER_MINUTE,
    typicalHighSeconds: 20 * SECONDS_PER_MINUTE,
  },
};

export function durationTierFor(memoryType: MemoryType): DurationTier {
  return MEMORY_TYPE_DURATIONS[memoryType];
}

// ---------------------------------------------------------------------
// Block phase (sequencing)
// ---------------------------------------------------------------------

export type BlockPhase = 'acquisition' | 'review' | 'expression';

export const PHASE_ORDER: Record<BlockPhase, number> = {
  acquisition: 0,
  review:      1,
  expression:  2,
};

// ---------------------------------------------------------------------
// Algorithm block shape
// ---------------------------------------------------------------------

export interface AlgorithmBlock {
  /** Stable id for ordering / mapping. Generated by the caller. */
  id: string;
  moduleRef: string;
  memoryType: MemoryType;
  itemRefs: readonly string[];
  /** Composite weight from Step 2d. Drives proportional scaling and
   *  drop priority. */
  weight: number;
  /** True when at least one of the block's items is in the acquiring
   *  stage. Drives phase classification. */
  hasAcquiringItems: boolean;
}

export interface AllocatedBlock extends AlgorithmBlock {
  /** Allocated duration in seconds. Always ≥ min for the memory type. */
  plannedSeconds: number;
  /** Phase classification used by sequenceBlocks. */
  phase: BlockPhase;
}

// ---------------------------------------------------------------------
// Phase classification
// ---------------------------------------------------------------------

export function phaseForBlock(block: AlgorithmBlock): BlockPhase {
  if (block.memoryType === 'expression') return 'expression';
  if (block.hasAcquiringItems)            return 'acquisition';
  return 'review';
}

// ---------------------------------------------------------------------
// Time allocation
// ---------------------------------------------------------------------

/**
 * Distribute `availableSeconds` across blocks. Returns null when no
 * blocks can fit — the caller should fall back to the abundance
 * surface or cold-start path. Otherwise returns the full block list
 * with per-block plannedSeconds, possibly with the lowest-weight
 * blocks dropped to make space.
 *
 * Algorithm:
 *   1. Compute each block's typical-low duration (default ask).
 *   2. If sum ≤ available: scale up proportionally toward typical-high,
 *      capping at typical-high.
 *   3. If sum > available: scale down proportionally; if any block
 *      would fall below its min, drop the lowest-weight block and
 *      retry from step 1 with the remaining set.
 *
 * Returned blocks preserve input order — sequencing happens separately.
 */
export function allocateBlockTime(
  blocks: ReadonlyArray<AlgorithmBlock>,
  availableSeconds: number,
): AllocatedBlock[] | null {
  if (availableSeconds <= 0) return null;

  let working = blocks.slice();

  while (working.length > 0) {
    const tiers = working.map(b => durationTierFor(b.memoryType));
    const minTotal = tiers.reduce((s, t) => s + t.minSeconds, 0);
    const typicalLowTotal = tiers.reduce((s, t) => s + t.typicalLowSeconds, 0);
    const typicalHighTotal = tiers.reduce((s, t) => s + t.typicalHighSeconds, 0);

    if (minTotal > availableSeconds) {
      // Even at minimums, can't fit. Drop lowest-weight block.
      const dropIdx = lowestWeightIndex(working);
      working = working.filter((_, i) => i !== dropIdx);
      continue;
    }

    // We can fit. Pick a target distribution.
    const allocated = distribute(working, tiers, availableSeconds, typicalLowTotal, typicalHighTotal);
    return allocated.map(({ block, seconds }) => ({
      ...block,
      plannedSeconds: seconds,
      phase: phaseForBlock(block),
    }));
  }

  return null;
}

function distribute(
  blocks: ReadonlyArray<AlgorithmBlock>,
  tiers: ReadonlyArray<DurationTier>,
  available: number,
  typicalLowTotal: number,
  typicalHighTotal: number,
): Array<{ block: AlgorithmBlock; seconds: number }> {
  const out: Array<{ block: AlgorithmBlock; seconds: number }> = [];

  if (available >= typicalHighTotal) {
    // Plenty of time — give each block its typical-high.
    blocks.forEach((b, i) => {
      out.push({ block: b, seconds: tiers[i].typicalHighSeconds });
    });
    return out;
  }

  if (available >= typicalLowTotal) {
    // Between typical-low and typical-high — interpolate proportionally.
    const span = typicalHighTotal - typicalLowTotal;
    const t = span === 0 ? 0 : (available - typicalLowTotal) / span;
    blocks.forEach((b, i) => {
      const tier = tiers[i];
      const seconds = Math.round(
        tier.typicalLowSeconds + t * (tier.typicalHighSeconds - tier.typicalLowSeconds),
      );
      out.push({ block: b, seconds });
    });
    return out;
  }

  // Less than the typical-low total — scale down from typical-low,
  // clamping at min. (We already verified minTotal ≤ available
  // upstream, so the clamp won't push us over.)
  const scaleSpan = typicalLowTotal - blocks.reduce((s, _b, i) => s + tiers[i].minSeconds, 0);
  const targetSpan = available - blocks.reduce((s, _b, i) => s + tiers[i].minSeconds, 0);
  const t = scaleSpan === 0 ? 0 : Math.max(0, Math.min(1, targetSpan / scaleSpan));
  blocks.forEach((b, i) => {
    const tier = tiers[i];
    const seconds = Math.round(
      tier.minSeconds + t * (tier.typicalLowSeconds - tier.minSeconds),
    );
    out.push({ block: b, seconds });
  });
  return out;
}

function lowestWeightIndex(blocks: ReadonlyArray<AlgorithmBlock>): number {
  let idx = 0;
  let minW = blocks[0].weight;
  for (let i = 1; i < blocks.length; i++) {
    if (blocks[i].weight < minW) {
      minW = blocks[i].weight;
      idx = i;
    }
  }
  return idx;
}

// ---------------------------------------------------------------------
// Sequencing
// ---------------------------------------------------------------------

/**
 * Order allocated blocks per algorithm Step 8:
 *   acquisition (fresh attention) → review → expression (consolidation)
 *
 * Within a phase, higher-weight blocks come first so the most
 * important work lands when attention is at its best for that phase.
 *
 * Sort is stable: blocks with the same phase + weight retain their
 * input order. Pure; doesn't mutate input.
 */
export function sequenceBlocks(blocks: ReadonlyArray<AllocatedBlock>): AllocatedBlock[] {
  const indexed = blocks.map((b, i) => ({ b, i }));
  indexed.sort((a, b) => {
    const phaseDiff = PHASE_ORDER[a.b.phase] - PHASE_ORDER[b.b.phase];
    if (phaseDiff !== 0) return phaseDiff;
    if (a.b.weight !== b.b.weight) return b.b.weight - a.b.weight;
    return a.i - b.i;
  });
  return indexed.map(x => x.b);
}
