/**
 * Every generated card id, paired with the question it addresses.
 *
 * =====================================================================
 * THIS PINS THE PAIRING, NOT THE SET — AND THAT IS THE WHOLE POINT.
 *
 * A test that ids are unique, or that a category holds N cards, PASSES
 * under renumbering. Renumbering does not change the set of ids; it
 * repoints them at different content. `nn-7` still exists, still
 * unique, still one of twenty-four — it is simply a different question
 * now.
 *
 * That is why the failure is silent, and it is the same shape as the
 * phantom key rows: the row is not renamed, a DIFFERENT row is
 * addressed, and the history detaches with nothing on screen to say so.
 * Here the history is `flashcardStates.cardId` (SM-2 ease factor,
 * interval, streak), every `attempts.itemId`, and the `spacingState`
 * row at `itemRef` — all three keyed on this string.
 *
 * TWO NUMBERING SCHEMES LIVE HERE NOW, and they have different risks.
 *
 * POSITIONAL — `nn-1`, `iv-1`, `rkp-1`, `tt-1`, `enh-n-1`. These number
 * by index into a generator's input array, so INSERTING into the middle
 * of one of those lists silently renumbers everything after it. That is
 * exactly the edit someone makes when adding a missing key.
 *
 * ROOT-SUFFIXED — `pent-major-Ab`, `fh-ii-v-i-Db`, `sc-6-b7-Gb`. These
 * carry the root in the id, so reordering their root list cannot
 * repoint anything. Every id added on or after 24 August 2026 uses this
 * shape, and new ones should too.
 *
 * `scale-degree-math` is a third case — its ids compose the degree and
 * the interval (`sdm-1-up-2nd`) and are stable under reordering. It is
 * pinned anyway: what protects it is a naming scheme, and a naming
 * scheme can be changed.
 *
 * WHEN THIS TEST FAILS, THE FIX IS ALMOST NEVER TO UPDATE THE FIXTURE.
 * It is to give the new cards new ids and leave the existing pairings
 * where they are.
 * =====================================================================
 *
 * Captured 24 August 2026, extended the same day to cover the
 * twelve-key expansions. Format is `id|question`.
 *
 * ---------------------------------------------------------------
 * 29 AUGUST 2026 — EIGHTEEN IDS UPDATED, AND THIS IS THE "ALMOST
 * NEVER" THE RULE ABOVE ALLOWS FOR.
 *
 * The header says a rename is possible even where a renumber is not,
 * and that is what happened: `MAJOR_ROOTS` spelled the sixth key G♭
 * and `MINOR_ROOTS` spelled the ninth G♯, both display choices, and
 * both were reaching card ids. Ids mint from the identity vocabulary
 * now — the rule `lib/spelling.ts` states.
 *
 * WHAT MAKES THIS SAFE TO RE-PIN, checked rather than assumed: all
 * eighteen changes are one id swapped for another with the QUESTION
 * BYTE-IDENTICAL. Nothing was repointed, nothing added, nothing lost —
 * 18 removals, 18 additions, every one matched by its question. The
 * whole 649-card corpus was hashed over question, answer, decoys and
 * explanation before and after: unchanged.
 *
 * Four of the eighteen had history behind them —
 * `pent-major-Gb`, `pent-relative-Gb`, `pr-1564-Gb`, `pent-minor-G#` —
 * and `identityIdMigration.ts` carries their rows across. The other
 * fourteen had none.
 * ---------------------------------------------------------------
 */
export const GENERATED_CARD_PAIRING: ReadonlyArray<string> = [
  // --- scale-degree-math ---
  // The 84 positional ids (`sdm-2-down-6th`) were retired here when
  // the quality-carrying set replaced them; `sdmQualityMigration.ts`
  // moved their history onto the content-suffixed ids below.
  // --- scale-degree-math, quality-carrying (the 168) ---
  // Content-suffixed: `sdm-2-down-m6` names its own card, so inserting
  // a quality cannot repoint any of them. Pinned all the same, because
  // the pairing is what history hangs on and a RENAME is still
  // possible even when a renumber is not.
  'sdm-1-up-m2|In any major key, 1 up a minor 2nd = ?',
  'sdm-1-down-m2|In any major key, 1 down a minor 2nd = ?',
  'sdm-1-up-M2|In any major key, 1 up a major 2nd = ?',
  'sdm-1-down-M2|In any major key, 1 down a major 2nd = ?',
  'sdm-1-up-m3|In any major key, 1 up a minor 3rd = ?',
  'sdm-1-down-m3|In any major key, 1 down a minor 3rd = ?',
  'sdm-1-up-M3|In any major key, 1 up a major 3rd = ?',
  'sdm-1-down-M3|In any major key, 1 down a major 3rd = ?',
  'sdm-1-up-P4|In any major key, 1 up a perfect 4th = ?',
  'sdm-1-down-P4|In any major key, 1 down a perfect 4th = ?',
  'sdm-1-up-A4|In any major key, 1 up an augmented 4th = ?',
  'sdm-1-down-A4|In any major key, 1 down an augmented 4th = ?',
  'sdm-1-up-d5|In any major key, 1 up a diminished 5th = ?',
  'sdm-1-down-d5|In any major key, 1 down a diminished 5th = ?',
  'sdm-1-up-P5|In any major key, 1 up a perfect 5th = ?',
  'sdm-1-down-P5|In any major key, 1 down a perfect 5th = ?',
  'sdm-1-up-m6|In any major key, 1 up a minor 6th = ?',
  'sdm-1-down-m6|In any major key, 1 down a minor 6th = ?',
  'sdm-1-up-M6|In any major key, 1 up a major 6th = ?',
  'sdm-1-down-M6|In any major key, 1 down a major 6th = ?',
  'sdm-1-up-m7|In any major key, 1 up a minor 7th = ?',
  'sdm-1-down-m7|In any major key, 1 down a minor 7th = ?',
  'sdm-1-up-M7|In any major key, 1 up a major 7th = ?',
  'sdm-1-down-M7|In any major key, 1 down a major 7th = ?',
  'sdm-2-up-m2|In any major key, 2 up a minor 2nd = ?',
  'sdm-2-down-m2|In any major key, 2 down a minor 2nd = ?',
  'sdm-2-up-M2|In any major key, 2 up a major 2nd = ?',
  'sdm-2-down-M2|In any major key, 2 down a major 2nd = ?',
  'sdm-2-up-m3|In any major key, 2 up a minor 3rd = ?',
  'sdm-2-down-m3|In any major key, 2 down a minor 3rd = ?',
  'sdm-2-up-M3|In any major key, 2 up a major 3rd = ?',
  'sdm-2-down-M3|In any major key, 2 down a major 3rd = ?',
  'sdm-2-up-P4|In any major key, 2 up a perfect 4th = ?',
  'sdm-2-down-P4|In any major key, 2 down a perfect 4th = ?',
  'sdm-2-up-A4|In any major key, 2 up an augmented 4th = ?',
  'sdm-2-down-A4|In any major key, 2 down an augmented 4th = ?',
  'sdm-2-up-d5|In any major key, 2 up a diminished 5th = ?',
  'sdm-2-down-d5|In any major key, 2 down a diminished 5th = ?',
  'sdm-2-up-P5|In any major key, 2 up a perfect 5th = ?',
  'sdm-2-down-P5|In any major key, 2 down a perfect 5th = ?',
  'sdm-2-up-m6|In any major key, 2 up a minor 6th = ?',
  'sdm-2-down-m6|In any major key, 2 down a minor 6th = ?',
  'sdm-2-up-M6|In any major key, 2 up a major 6th = ?',
  'sdm-2-down-M6|In any major key, 2 down a major 6th = ?',
  'sdm-2-up-m7|In any major key, 2 up a minor 7th = ?',
  'sdm-2-down-m7|In any major key, 2 down a minor 7th = ?',
  'sdm-2-up-M7|In any major key, 2 up a major 7th = ?',
  'sdm-2-down-M7|In any major key, 2 down a major 7th = ?',
  'sdm-3-up-m2|In any major key, 3 up a minor 2nd = ?',
  'sdm-3-down-m2|In any major key, 3 down a minor 2nd = ?',
  'sdm-3-up-M2|In any major key, 3 up a major 2nd = ?',
  'sdm-3-down-M2|In any major key, 3 down a major 2nd = ?',
  'sdm-3-up-m3|In any major key, 3 up a minor 3rd = ?',
  'sdm-3-down-m3|In any major key, 3 down a minor 3rd = ?',
  'sdm-3-up-M3|In any major key, 3 up a major 3rd = ?',
  'sdm-3-down-M3|In any major key, 3 down a major 3rd = ?',
  'sdm-3-up-P4|In any major key, 3 up a perfect 4th = ?',
  'sdm-3-down-P4|In any major key, 3 down a perfect 4th = ?',
  'sdm-3-up-A4|In any major key, 3 up an augmented 4th = ?',
  'sdm-3-down-A4|In any major key, 3 down an augmented 4th = ?',
  'sdm-3-up-d5|In any major key, 3 up a diminished 5th = ?',
  'sdm-3-down-d5|In any major key, 3 down a diminished 5th = ?',
  'sdm-3-up-P5|In any major key, 3 up a perfect 5th = ?',
  'sdm-3-down-P5|In any major key, 3 down a perfect 5th = ?',
  'sdm-3-up-m6|In any major key, 3 up a minor 6th = ?',
  'sdm-3-down-m6|In any major key, 3 down a minor 6th = ?',
  'sdm-3-up-M6|In any major key, 3 up a major 6th = ?',
  'sdm-3-down-M6|In any major key, 3 down a major 6th = ?',
  'sdm-3-up-m7|In any major key, 3 up a minor 7th = ?',
  'sdm-3-down-m7|In any major key, 3 down a minor 7th = ?',
  'sdm-3-up-M7|In any major key, 3 up a major 7th = ?',
  'sdm-3-down-M7|In any major key, 3 down a major 7th = ?',
  'sdm-4-up-m2|In any major key, 4 up a minor 2nd = ?',
  'sdm-4-down-m2|In any major key, 4 down a minor 2nd = ?',
  'sdm-4-up-M2|In any major key, 4 up a major 2nd = ?',
  'sdm-4-down-M2|In any major key, 4 down a major 2nd = ?',
  'sdm-4-up-m3|In any major key, 4 up a minor 3rd = ?',
  'sdm-4-down-m3|In any major key, 4 down a minor 3rd = ?',
  'sdm-4-up-M3|In any major key, 4 up a major 3rd = ?',
  'sdm-4-down-M3|In any major key, 4 down a major 3rd = ?',
  'sdm-4-up-P4|In any major key, 4 up a perfect 4th = ?',
  'sdm-4-down-P4|In any major key, 4 down a perfect 4th = ?',
  'sdm-4-up-A4|In any major key, 4 up an augmented 4th = ?',
  'sdm-4-down-A4|In any major key, 4 down an augmented 4th = ?',
  'sdm-4-up-d5|In any major key, 4 up a diminished 5th = ?',
  'sdm-4-down-d5|In any major key, 4 down a diminished 5th = ?',
  'sdm-4-up-P5|In any major key, 4 up a perfect 5th = ?',
  'sdm-4-down-P5|In any major key, 4 down a perfect 5th = ?',
  'sdm-4-up-m6|In any major key, 4 up a minor 6th = ?',
  'sdm-4-down-m6|In any major key, 4 down a minor 6th = ?',
  'sdm-4-up-M6|In any major key, 4 up a major 6th = ?',
  'sdm-4-down-M6|In any major key, 4 down a major 6th = ?',
  'sdm-4-up-m7|In any major key, 4 up a minor 7th = ?',
  'sdm-4-down-m7|In any major key, 4 down a minor 7th = ?',
  'sdm-4-up-M7|In any major key, 4 up a major 7th = ?',
  'sdm-4-down-M7|In any major key, 4 down a major 7th = ?',
  'sdm-5-up-m2|In any major key, 5 up a minor 2nd = ?',
  'sdm-5-down-m2|In any major key, 5 down a minor 2nd = ?',
  'sdm-5-up-M2|In any major key, 5 up a major 2nd = ?',
  'sdm-5-down-M2|In any major key, 5 down a major 2nd = ?',
  'sdm-5-up-m3|In any major key, 5 up a minor 3rd = ?',
  'sdm-5-down-m3|In any major key, 5 down a minor 3rd = ?',
  'sdm-5-up-M3|In any major key, 5 up a major 3rd = ?',
  'sdm-5-down-M3|In any major key, 5 down a major 3rd = ?',
  'sdm-5-up-P4|In any major key, 5 up a perfect 4th = ?',
  'sdm-5-down-P4|In any major key, 5 down a perfect 4th = ?',
  'sdm-5-up-A4|In any major key, 5 up an augmented 4th = ?',
  'sdm-5-down-A4|In any major key, 5 down an augmented 4th = ?',
  'sdm-5-up-d5|In any major key, 5 up a diminished 5th = ?',
  'sdm-5-down-d5|In any major key, 5 down a diminished 5th = ?',
  'sdm-5-up-P5|In any major key, 5 up a perfect 5th = ?',
  'sdm-5-down-P5|In any major key, 5 down a perfect 5th = ?',
  'sdm-5-up-m6|In any major key, 5 up a minor 6th = ?',
  'sdm-5-down-m6|In any major key, 5 down a minor 6th = ?',
  'sdm-5-up-M6|In any major key, 5 up a major 6th = ?',
  'sdm-5-down-M6|In any major key, 5 down a major 6th = ?',
  'sdm-5-up-m7|In any major key, 5 up a minor 7th = ?',
  'sdm-5-down-m7|In any major key, 5 down a minor 7th = ?',
  'sdm-5-up-M7|In any major key, 5 up a major 7th = ?',
  'sdm-5-down-M7|In any major key, 5 down a major 7th = ?',
  'sdm-6-up-m2|In any major key, 6 up a minor 2nd = ?',
  'sdm-6-down-m2|In any major key, 6 down a minor 2nd = ?',
  'sdm-6-up-M2|In any major key, 6 up a major 2nd = ?',
  'sdm-6-down-M2|In any major key, 6 down a major 2nd = ?',
  'sdm-6-up-m3|In any major key, 6 up a minor 3rd = ?',
  'sdm-6-down-m3|In any major key, 6 down a minor 3rd = ?',
  'sdm-6-up-M3|In any major key, 6 up a major 3rd = ?',
  'sdm-6-down-M3|In any major key, 6 down a major 3rd = ?',
  'sdm-6-up-P4|In any major key, 6 up a perfect 4th = ?',
  'sdm-6-down-P4|In any major key, 6 down a perfect 4th = ?',
  'sdm-6-up-A4|In any major key, 6 up an augmented 4th = ?',
  'sdm-6-down-A4|In any major key, 6 down an augmented 4th = ?',
  'sdm-6-up-d5|In any major key, 6 up a diminished 5th = ?',
  'sdm-6-down-d5|In any major key, 6 down a diminished 5th = ?',
  'sdm-6-up-P5|In any major key, 6 up a perfect 5th = ?',
  'sdm-6-down-P5|In any major key, 6 down a perfect 5th = ?',
  'sdm-6-up-m6|In any major key, 6 up a minor 6th = ?',
  'sdm-6-down-m6|In any major key, 6 down a minor 6th = ?',
  'sdm-6-up-M6|In any major key, 6 up a major 6th = ?',
  'sdm-6-down-M6|In any major key, 6 down a major 6th = ?',
  'sdm-6-up-m7|In any major key, 6 up a minor 7th = ?',
  'sdm-6-down-m7|In any major key, 6 down a minor 7th = ?',
  'sdm-6-up-M7|In any major key, 6 up a major 7th = ?',
  'sdm-6-down-M7|In any major key, 6 down a major 7th = ?',
  'sdm-7-up-m2|In any major key, 7 up a minor 2nd = ?',
  'sdm-7-down-m2|In any major key, 7 down a minor 2nd = ?',
  'sdm-7-up-M2|In any major key, 7 up a major 2nd = ?',
  'sdm-7-down-M2|In any major key, 7 down a major 2nd = ?',
  'sdm-7-up-m3|In any major key, 7 up a minor 3rd = ?',
  'sdm-7-down-m3|In any major key, 7 down a minor 3rd = ?',
  'sdm-7-up-M3|In any major key, 7 up a major 3rd = ?',
  'sdm-7-down-M3|In any major key, 7 down a major 3rd = ?',
  'sdm-7-up-P4|In any major key, 7 up a perfect 4th = ?',
  'sdm-7-down-P4|In any major key, 7 down a perfect 4th = ?',
  'sdm-7-up-A4|In any major key, 7 up an augmented 4th = ?',
  'sdm-7-down-A4|In any major key, 7 down an augmented 4th = ?',
  'sdm-7-up-d5|In any major key, 7 up a diminished 5th = ?',
  'sdm-7-down-d5|In any major key, 7 down a diminished 5th = ?',
  'sdm-7-up-P5|In any major key, 7 up a perfect 5th = ?',
  'sdm-7-down-P5|In any major key, 7 down a perfect 5th = ?',
  'sdm-7-up-m6|In any major key, 7 up a minor 6th = ?',
  'sdm-7-down-m6|In any major key, 7 down a minor 6th = ?',
  'sdm-7-up-M6|In any major key, 7 up a major 6th = ?',
  'sdm-7-down-M6|In any major key, 7 down a major 6th = ?',
  'sdm-7-up-m7|In any major key, 7 up a minor 7th = ?',
  'sdm-7-down-m7|In any major key, 7 down a minor 7th = ?',
  'sdm-7-up-M7|In any major key, 7 up a major 7th = ?',
  'sdm-7-down-M7|In any major key, 7 down a major 7th = ?',

  // --- degree-notes ---
  // `named-notes` WAS HERE, and its 24 positional ids are gone with the
  // category — folded into this family on 3 Sep 2026, with
  // `retiredCategoryMigration.ts` carrying every row across. The one
  // exception is the LAST line of this block: `nn-12` asks the 4 of F♯
  // and this family asks it in G♭, so it kept its own id and its own
  // rows and simply changed which category it is filed under.
  //
  // The 624 are CONTENT-SUFFIXED — `dgn-Ab-b6` names its own card — so
  // no reordering can repoint one. Pinned anyway, for the same reason
  // scale-degree-math is: a naming scheme is what protects them, and a
  // naming scheme can be changed. The QUESTION half of each pair is
  // load-bearing here for a second reason — the degree a card asks
  // about is written into it.
  //
  // FOUR PREFIXES, ONE PER QUESTION: `dgn` names the note, `dgd` the
  // degree, `dgp` the key under a finger, `dgk` the key itself.
  'dgn-C-1|In the key of C, what is the 1?',
  'dgn-C-b2|In the key of C, what is the ♭2?',
  'dgn-C-2|In the key of C, what is the 2?',
  'dgn-C-b3|In the key of C, what is the ♭3?',
  'dgn-C-3|In the key of C, what is the 3?',
  'dgn-C-4|In the key of C, what is the 4?',
  'dgn-C-s4|In the key of C, what is the ♯4?',
  'dgn-C-b5|In the key of C, what is the ♭5?',
  'dgn-C-5|In the key of C, what is the 5?',
  'dgn-C-b6|In the key of C, what is the ♭6?',
  'dgn-C-6|In the key of C, what is the 6?',
  'dgn-C-b7|In the key of C, what is the ♭7?',
  'dgn-C-7|In the key of C, what is the 7?',
  'dgn-Db-1|In the key of Db, what is the 1?',
  'dgn-Db-b2|In the key of Db, what is the ♭2?',
  'dgn-Db-2|In the key of Db, what is the 2?',
  'dgn-Db-b3|In the key of Db, what is the ♭3?',
  'dgn-Db-3|In the key of Db, what is the 3?',
  'dgn-Db-4|In the key of Db, what is the 4?',
  'dgn-Db-s4|In the key of Db, what is the ♯4?',
  'dgn-Db-b5|In the key of Db, what is the ♭5?',
  'dgn-Db-5|In the key of Db, what is the 5?',
  'dgn-Db-b6|In the key of Db, what is the ♭6?',
  'dgn-Db-6|In the key of Db, what is the 6?',
  'dgn-Db-b7|In the key of Db, what is the ♭7?',
  'dgn-Db-7|In the key of Db, what is the 7?',
  'dgn-D-1|In the key of D, what is the 1?',
  'dgn-D-b2|In the key of D, what is the ♭2?',
  'dgn-D-2|In the key of D, what is the 2?',
  'dgn-D-b3|In the key of D, what is the ♭3?',
  'dgn-D-3|In the key of D, what is the 3?',
  'dgn-D-4|In the key of D, what is the 4?',
  'dgn-D-s4|In the key of D, what is the ♯4?',
  'dgn-D-b5|In the key of D, what is the ♭5?',
  'dgn-D-5|In the key of D, what is the 5?',
  'dgn-D-b6|In the key of D, what is the ♭6?',
  'dgn-D-6|In the key of D, what is the 6?',
  'dgn-D-b7|In the key of D, what is the ♭7?',
  'dgn-D-7|In the key of D, what is the 7?',
  'dgn-Eb-1|In the key of Eb, what is the 1?',
  'dgn-Eb-b2|In the key of Eb, what is the ♭2?',
  'dgn-Eb-2|In the key of Eb, what is the 2?',
  'dgn-Eb-b3|In the key of Eb, what is the ♭3?',
  'dgn-Eb-3|In the key of Eb, what is the 3?',
  'dgn-Eb-4|In the key of Eb, what is the 4?',
  'dgn-Eb-s4|In the key of Eb, what is the ♯4?',
  'dgn-Eb-b5|In the key of Eb, what is the ♭5?',
  'dgn-Eb-5|In the key of Eb, what is the 5?',
  'dgn-Eb-b6|In the key of Eb, what is the ♭6?',
  'dgn-Eb-6|In the key of Eb, what is the 6?',
  'dgn-Eb-b7|In the key of Eb, what is the ♭7?',
  'dgn-Eb-7|In the key of Eb, what is the 7?',
  'dgn-E-1|In the key of E, what is the 1?',
  'dgn-E-b2|In the key of E, what is the ♭2?',
  'dgn-E-2|In the key of E, what is the 2?',
  'dgn-E-b3|In the key of E, what is the ♭3?',
  'dgn-E-3|In the key of E, what is the 3?',
  'dgn-E-4|In the key of E, what is the 4?',
  'dgn-E-s4|In the key of E, what is the ♯4?',
  'dgn-E-b5|In the key of E, what is the ♭5?',
  'dgn-E-5|In the key of E, what is the 5?',
  'dgn-E-b6|In the key of E, what is the ♭6?',
  'dgn-E-6|In the key of E, what is the 6?',
  'dgn-E-b7|In the key of E, what is the ♭7?',
  'dgn-E-7|In the key of E, what is the 7?',
  'dgn-F-1|In the key of F, what is the 1?',
  'dgn-F-b2|In the key of F, what is the ♭2?',
  'dgn-F-2|In the key of F, what is the 2?',
  'dgn-F-b3|In the key of F, what is the ♭3?',
  'dgn-F-3|In the key of F, what is the 3?',
  'dgn-F-4|In the key of F, what is the 4?',
  'dgn-F-s4|In the key of F, what is the ♯4?',
  'dgn-F-b5|In the key of F, what is the ♭5?',
  'dgn-F-5|In the key of F, what is the 5?',
  'dgn-F-b6|In the key of F, what is the ♭6?',
  'dgn-F-6|In the key of F, what is the 6?',
  'dgn-F-b7|In the key of F, what is the ♭7?',
  'dgn-F-7|In the key of F, what is the 7?',
  'dgn-Fs-1|In the key of Gb, what is the 1?',
  'dgn-Fs-b2|In the key of Gb, what is the ♭2?',
  'dgn-Fs-2|In the key of Gb, what is the 2?',
  'dgn-Fs-b3|In the key of Gb, what is the ♭3?',
  'dgn-Fs-3|In the key of Gb, what is the 3?',
  'dgn-Fs-4|In the key of Gb, what is the 4?',
  'dgn-Fs-s4|In the key of Gb, what is the ♯4?',
  'dgn-Fs-b5|In the key of Gb, what is the ♭5?',
  'dgn-Fs-5|In the key of Gb, what is the 5?',
  'dgn-Fs-b6|In the key of Gb, what is the ♭6?',
  'dgn-Fs-6|In the key of Gb, what is the 6?',
  'dgn-Fs-b7|In the key of Gb, what is the ♭7?',
  'dgn-Fs-7|In the key of Gb, what is the 7?',
  'dgn-G-1|In the key of G, what is the 1?',
  'dgn-G-b2|In the key of G, what is the ♭2?',
  'dgn-G-2|In the key of G, what is the 2?',
  'dgn-G-b3|In the key of G, what is the ♭3?',
  'dgn-G-3|In the key of G, what is the 3?',
  'dgn-G-4|In the key of G, what is the 4?',
  'dgn-G-s4|In the key of G, what is the ♯4?',
  'dgn-G-b5|In the key of G, what is the ♭5?',
  'dgn-G-5|In the key of G, what is the 5?',
  'dgn-G-b6|In the key of G, what is the ♭6?',
  'dgn-G-6|In the key of G, what is the 6?',
  'dgn-G-b7|In the key of G, what is the ♭7?',
  'dgn-G-7|In the key of G, what is the 7?',
  'dgn-Ab-1|In the key of Ab, what is the 1?',
  'dgn-Ab-b2|In the key of Ab, what is the ♭2?',
  'dgn-Ab-2|In the key of Ab, what is the 2?',
  'dgn-Ab-b3|In the key of Ab, what is the ♭3?',
  'dgn-Ab-3|In the key of Ab, what is the 3?',
  'dgn-Ab-4|In the key of Ab, what is the 4?',
  'dgn-Ab-s4|In the key of Ab, what is the ♯4?',
  'dgn-Ab-b5|In the key of Ab, what is the ♭5?',
  'dgn-Ab-5|In the key of Ab, what is the 5?',
  'dgn-Ab-b6|In the key of Ab, what is the ♭6?',
  'dgn-Ab-6|In the key of Ab, what is the 6?',
  'dgn-Ab-b7|In the key of Ab, what is the ♭7?',
  'dgn-Ab-7|In the key of Ab, what is the 7?',
  'dgn-A-1|In the key of A, what is the 1?',
  'dgn-A-b2|In the key of A, what is the ♭2?',
  'dgn-A-2|In the key of A, what is the 2?',
  'dgn-A-b3|In the key of A, what is the ♭3?',
  'dgn-A-3|In the key of A, what is the 3?',
  'dgn-A-4|In the key of A, what is the 4?',
  'dgn-A-s4|In the key of A, what is the ♯4?',
  'dgn-A-b5|In the key of A, what is the ♭5?',
  'dgn-A-5|In the key of A, what is the 5?',
  'dgn-A-b6|In the key of A, what is the ♭6?',
  'dgn-A-6|In the key of A, what is the 6?',
  'dgn-A-b7|In the key of A, what is the ♭7?',
  'dgn-A-7|In the key of A, what is the 7?',
  'dgn-Bb-1|In the key of Bb, what is the 1?',
  'dgn-Bb-b2|In the key of Bb, what is the ♭2?',
  'dgn-Bb-2|In the key of Bb, what is the 2?',
  'dgn-Bb-b3|In the key of Bb, what is the ♭3?',
  'dgn-Bb-3|In the key of Bb, what is the 3?',
  'dgn-Bb-4|In the key of Bb, what is the 4?',
  'dgn-Bb-s4|In the key of Bb, what is the ♯4?',
  'dgn-Bb-b5|In the key of Bb, what is the ♭5?',
  'dgn-Bb-5|In the key of Bb, what is the 5?',
  'dgn-Bb-b6|In the key of Bb, what is the ♭6?',
  'dgn-Bb-6|In the key of Bb, what is the 6?',
  'dgn-Bb-b7|In the key of Bb, what is the ♭7?',
  'dgn-Bb-7|In the key of Bb, what is the 7?',
  'dgn-B-1|In the key of B, what is the 1?',
  'dgn-B-b2|In the key of B, what is the ♭2?',
  'dgn-B-2|In the key of B, what is the 2?',
  'dgn-B-b3|In the key of B, what is the ♭3?',
  'dgn-B-3|In the key of B, what is the 3?',
  'dgn-B-4|In the key of B, what is the 4?',
  'dgn-B-s4|In the key of B, what is the ♯4?',
  'dgn-B-b5|In the key of B, what is the ♭5?',
  'dgn-B-5|In the key of B, what is the 5?',
  'dgn-B-b6|In the key of B, what is the ♭6?',
  'dgn-B-6|In the key of B, what is the 6?',
  'dgn-B-b7|In the key of B, what is the ♭7?',
  'dgn-B-7|In the key of B, what is the 7?',
  'dgd-C-1|In the key of C, C is which degree?',
  'dgd-C-b2|In the key of C, D♭ is which degree?',
  'dgd-C-2|In the key of C, D is which degree?',
  'dgd-C-b3|In the key of C, E♭ is which degree?',
  'dgd-C-3|In the key of C, E is which degree?',
  'dgd-C-4|In the key of C, F is which degree?',
  'dgd-C-s4|In the key of C, F♯ is which degree?',
  'dgd-C-b5|In the key of C, G♭ is which degree?',
  'dgd-C-5|In the key of C, G is which degree?',
  'dgd-C-b6|In the key of C, A♭ is which degree?',
  'dgd-C-6|In the key of C, A is which degree?',
  'dgd-C-b7|In the key of C, B♭ is which degree?',
  'dgd-C-7|In the key of C, B is which degree?',
  'dgd-Db-1|In the key of Db, D♭ is which degree?',
  'dgd-Db-b2|In the key of Db, E𝄫 (D) is which degree?',
  'dgd-Db-2|In the key of Db, E♭ is which degree?',
  'dgd-Db-b3|In the key of Db, F♭ (E) is which degree?',
  'dgd-Db-3|In the key of Db, F is which degree?',
  'dgd-Db-4|In the key of Db, G♭ is which degree?',
  'dgd-Db-s4|In the key of Db, G is which degree?',
  'dgd-Db-b5|In the key of Db, A𝄫 (G) is which degree?',
  'dgd-Db-5|In the key of Db, A♭ is which degree?',
  'dgd-Db-b6|In the key of Db, B𝄫 (A) is which degree?',
  'dgd-Db-6|In the key of Db, B♭ is which degree?',
  'dgd-Db-b7|In the key of Db, C♭ (B) is which degree?',
  'dgd-Db-7|In the key of Db, C is which degree?',
  'dgd-D-1|In the key of D, D is which degree?',
  'dgd-D-b2|In the key of D, E♭ is which degree?',
  'dgd-D-2|In the key of D, E is which degree?',
  'dgd-D-b3|In the key of D, F is which degree?',
  'dgd-D-3|In the key of D, F♯ is which degree?',
  'dgd-D-4|In the key of D, G is which degree?',
  'dgd-D-s4|In the key of D, G♯ is which degree?',
  'dgd-D-b5|In the key of D, A♭ is which degree?',
  'dgd-D-5|In the key of D, A is which degree?',
  'dgd-D-b6|In the key of D, B♭ is which degree?',
  'dgd-D-6|In the key of D, B is which degree?',
  'dgd-D-b7|In the key of D, C is which degree?',
  'dgd-D-7|In the key of D, C♯ is which degree?',
  'dgd-Eb-1|In the key of Eb, E♭ is which degree?',
  'dgd-Eb-b2|In the key of Eb, F♭ (E) is which degree?',
  'dgd-Eb-2|In the key of Eb, F is which degree?',
  'dgd-Eb-b3|In the key of Eb, G♭ is which degree?',
  'dgd-Eb-3|In the key of Eb, G is which degree?',
  'dgd-Eb-4|In the key of Eb, A♭ is which degree?',
  'dgd-Eb-s4|In the key of Eb, A is which degree?',
  'dgd-Eb-b5|In the key of Eb, B𝄫 (A) is which degree?',
  'dgd-Eb-5|In the key of Eb, B♭ is which degree?',
  'dgd-Eb-b6|In the key of Eb, C♭ (B) is which degree?',
  'dgd-Eb-6|In the key of Eb, C is which degree?',
  'dgd-Eb-b7|In the key of Eb, D♭ is which degree?',
  'dgd-Eb-7|In the key of Eb, D is which degree?',
  'dgd-E-1|In the key of E, E is which degree?',
  'dgd-E-b2|In the key of E, F is which degree?',
  'dgd-E-2|In the key of E, F♯ is which degree?',
  'dgd-E-b3|In the key of E, G is which degree?',
  'dgd-E-3|In the key of E, G♯ is which degree?',
  'dgd-E-4|In the key of E, A is which degree?',
  'dgd-E-s4|In the key of E, A♯ is which degree?',
  'dgd-E-b5|In the key of E, B♭ is which degree?',
  'dgd-E-5|In the key of E, B is which degree?',
  'dgd-E-b6|In the key of E, C is which degree?',
  'dgd-E-6|In the key of E, C♯ is which degree?',
  'dgd-E-b7|In the key of E, D is which degree?',
  'dgd-E-7|In the key of E, D♯ is which degree?',
  'dgd-F-1|In the key of F, F is which degree?',
  'dgd-F-b2|In the key of F, G♭ is which degree?',
  'dgd-F-2|In the key of F, G is which degree?',
  'dgd-F-b3|In the key of F, A♭ is which degree?',
  'dgd-F-3|In the key of F, A is which degree?',
  'dgd-F-4|In the key of F, B♭ is which degree?',
  'dgd-F-s4|In the key of F, B is which degree?',
  'dgd-F-b5|In the key of F, C♭ (B) is which degree?',
  'dgd-F-5|In the key of F, C is which degree?',
  'dgd-F-b6|In the key of F, D♭ is which degree?',
  'dgd-F-6|In the key of F, D is which degree?',
  'dgd-F-b7|In the key of F, E♭ is which degree?',
  'dgd-F-7|In the key of F, E is which degree?',
  'dgd-Fs-1|In the key of Gb, G♭ is which degree?',
  'dgd-Fs-b2|In the key of Gb, A𝄫 (G) is which degree?',
  'dgd-Fs-2|In the key of Gb, A♭ is which degree?',
  'dgd-Fs-b3|In the key of Gb, B𝄫 (A) is which degree?',
  'dgd-Fs-3|In the key of Gb, B♭ is which degree?',
  'dgd-Fs-4|In the key of Gb, C♭ (B) is which degree?',
  'dgd-Fs-s4|In the key of Gb, C is which degree?',
  'dgd-Fs-b5|In the key of Gb, D𝄫 (C) is which degree?',
  'dgd-Fs-5|In the key of Gb, D♭ is which degree?',
  'dgd-Fs-b6|In the key of Gb, E𝄫 (D) is which degree?',
  'dgd-Fs-6|In the key of Gb, E♭ is which degree?',
  'dgd-Fs-b7|In the key of Gb, F♭ (E) is which degree?',
  'dgd-Fs-7|In the key of Gb, F is which degree?',
  'dgd-G-1|In the key of G, G is which degree?',
  'dgd-G-b2|In the key of G, A♭ is which degree?',
  'dgd-G-2|In the key of G, A is which degree?',
  'dgd-G-b3|In the key of G, B♭ is which degree?',
  'dgd-G-3|In the key of G, B is which degree?',
  'dgd-G-4|In the key of G, C is which degree?',
  'dgd-G-s4|In the key of G, C♯ is which degree?',
  'dgd-G-b5|In the key of G, D♭ is which degree?',
  'dgd-G-5|In the key of G, D is which degree?',
  'dgd-G-b6|In the key of G, E♭ is which degree?',
  'dgd-G-6|In the key of G, E is which degree?',
  'dgd-G-b7|In the key of G, F is which degree?',
  'dgd-G-7|In the key of G, F♯ is which degree?',
  'dgd-Ab-1|In the key of Ab, A♭ is which degree?',
  'dgd-Ab-b2|In the key of Ab, B𝄫 (A) is which degree?',
  'dgd-Ab-2|In the key of Ab, B♭ is which degree?',
  'dgd-Ab-b3|In the key of Ab, C♭ (B) is which degree?',
  'dgd-Ab-3|In the key of Ab, C is which degree?',
  'dgd-Ab-4|In the key of Ab, D♭ is which degree?',
  'dgd-Ab-s4|In the key of Ab, D is which degree?',
  'dgd-Ab-b5|In the key of Ab, E𝄫 (D) is which degree?',
  'dgd-Ab-5|In the key of Ab, E♭ is which degree?',
  'dgd-Ab-b6|In the key of Ab, F♭ (E) is which degree?',
  'dgd-Ab-6|In the key of Ab, F is which degree?',
  'dgd-Ab-b7|In the key of Ab, G♭ is which degree?',
  'dgd-Ab-7|In the key of Ab, G is which degree?',
  'dgd-A-1|In the key of A, A is which degree?',
  'dgd-A-b2|In the key of A, B♭ is which degree?',
  'dgd-A-2|In the key of A, B is which degree?',
  'dgd-A-b3|In the key of A, C is which degree?',
  'dgd-A-3|In the key of A, C♯ is which degree?',
  'dgd-A-4|In the key of A, D is which degree?',
  'dgd-A-s4|In the key of A, D♯ is which degree?',
  'dgd-A-b5|In the key of A, E♭ is which degree?',
  'dgd-A-5|In the key of A, E is which degree?',
  'dgd-A-b6|In the key of A, F is which degree?',
  'dgd-A-6|In the key of A, F♯ is which degree?',
  'dgd-A-b7|In the key of A, G is which degree?',
  'dgd-A-7|In the key of A, G♯ is which degree?',
  'dgd-Bb-1|In the key of Bb, B♭ is which degree?',
  'dgd-Bb-b2|In the key of Bb, C♭ (B) is which degree?',
  'dgd-Bb-2|In the key of Bb, C is which degree?',
  'dgd-Bb-b3|In the key of Bb, D♭ is which degree?',
  'dgd-Bb-3|In the key of Bb, D is which degree?',
  'dgd-Bb-4|In the key of Bb, E♭ is which degree?',
  'dgd-Bb-s4|In the key of Bb, E is which degree?',
  'dgd-Bb-b5|In the key of Bb, F♭ (E) is which degree?',
  'dgd-Bb-5|In the key of Bb, F is which degree?',
  'dgd-Bb-b6|In the key of Bb, G♭ is which degree?',
  'dgd-Bb-6|In the key of Bb, G is which degree?',
  'dgd-Bb-b7|In the key of Bb, A♭ is which degree?',
  'dgd-Bb-7|In the key of Bb, A is which degree?',
  'dgd-B-1|In the key of B, B is which degree?',
  'dgd-B-b2|In the key of B, C is which degree?',
  'dgd-B-2|In the key of B, C♯ is which degree?',
  'dgd-B-b3|In the key of B, D is which degree?',
  'dgd-B-3|In the key of B, D♯ is which degree?',
  'dgd-B-4|In the key of B, E is which degree?',
  'dgd-B-s4|In the key of B, E♯ (F) is which degree?',
  'dgd-B-b5|In the key of B, F is which degree?',
  'dgd-B-5|In the key of B, F♯ is which degree?',
  'dgd-B-b6|In the key of B, G is which degree?',
  'dgd-B-6|In the key of B, G♯ is which degree?',
  'dgd-B-b7|In the key of B, A is which degree?',
  'dgd-B-7|In the key of B, A♯ is which degree?',
  'dgp-C-1|In the key of C, press the 1.',
  'dgp-C-b2|In the key of C, press the ♭2.',
  'dgp-C-2|In the key of C, press the 2.',
  'dgp-C-b3|In the key of C, press the ♭3.',
  'dgp-C-3|In the key of C, press the 3.',
  'dgp-C-4|In the key of C, press the 4.',
  'dgp-C-s4|In the key of C, press the ♯4.',
  'dgp-C-b5|In the key of C, press the ♭5.',
  'dgp-C-5|In the key of C, press the 5.',
  'dgp-C-b6|In the key of C, press the ♭6.',
  'dgp-C-6|In the key of C, press the 6.',
  'dgp-C-b7|In the key of C, press the ♭7.',
  'dgp-C-7|In the key of C, press the 7.',
  'dgp-Db-1|In the key of Db, press the 1.',
  'dgp-Db-b2|In the key of Db, press the ♭2.',
  'dgp-Db-2|In the key of Db, press the 2.',
  'dgp-Db-b3|In the key of Db, press the ♭3.',
  'dgp-Db-3|In the key of Db, press the 3.',
  'dgp-Db-4|In the key of Db, press the 4.',
  'dgp-Db-s4|In the key of Db, press the ♯4.',
  'dgp-Db-b5|In the key of Db, press the ♭5.',
  'dgp-Db-5|In the key of Db, press the 5.',
  'dgp-Db-b6|In the key of Db, press the ♭6.',
  'dgp-Db-6|In the key of Db, press the 6.',
  'dgp-Db-b7|In the key of Db, press the ♭7.',
  'dgp-Db-7|In the key of Db, press the 7.',
  'dgp-D-1|In the key of D, press the 1.',
  'dgp-D-b2|In the key of D, press the ♭2.',
  'dgp-D-2|In the key of D, press the 2.',
  'dgp-D-b3|In the key of D, press the ♭3.',
  'dgp-D-3|In the key of D, press the 3.',
  'dgp-D-4|In the key of D, press the 4.',
  'dgp-D-s4|In the key of D, press the ♯4.',
  'dgp-D-b5|In the key of D, press the ♭5.',
  'dgp-D-5|In the key of D, press the 5.',
  'dgp-D-b6|In the key of D, press the ♭6.',
  'dgp-D-6|In the key of D, press the 6.',
  'dgp-D-b7|In the key of D, press the ♭7.',
  'dgp-D-7|In the key of D, press the 7.',
  'dgp-Eb-1|In the key of Eb, press the 1.',
  'dgp-Eb-b2|In the key of Eb, press the ♭2.',
  'dgp-Eb-2|In the key of Eb, press the 2.',
  'dgp-Eb-b3|In the key of Eb, press the ♭3.',
  'dgp-Eb-3|In the key of Eb, press the 3.',
  'dgp-Eb-4|In the key of Eb, press the 4.',
  'dgp-Eb-s4|In the key of Eb, press the ♯4.',
  'dgp-Eb-b5|In the key of Eb, press the ♭5.',
  'dgp-Eb-5|In the key of Eb, press the 5.',
  'dgp-Eb-b6|In the key of Eb, press the ♭6.',
  'dgp-Eb-6|In the key of Eb, press the 6.',
  'dgp-Eb-b7|In the key of Eb, press the ♭7.',
  'dgp-Eb-7|In the key of Eb, press the 7.',
  'dgp-E-1|In the key of E, press the 1.',
  'dgp-E-b2|In the key of E, press the ♭2.',
  'dgp-E-2|In the key of E, press the 2.',
  'dgp-E-b3|In the key of E, press the ♭3.',
  'dgp-E-3|In the key of E, press the 3.',
  'dgp-E-4|In the key of E, press the 4.',
  'dgp-E-s4|In the key of E, press the ♯4.',
  'dgp-E-b5|In the key of E, press the ♭5.',
  'dgp-E-5|In the key of E, press the 5.',
  'dgp-E-b6|In the key of E, press the ♭6.',
  'dgp-E-6|In the key of E, press the 6.',
  'dgp-E-b7|In the key of E, press the ♭7.',
  'dgp-E-7|In the key of E, press the 7.',
  'dgp-F-1|In the key of F, press the 1.',
  'dgp-F-b2|In the key of F, press the ♭2.',
  'dgp-F-2|In the key of F, press the 2.',
  'dgp-F-b3|In the key of F, press the ♭3.',
  'dgp-F-3|In the key of F, press the 3.',
  'dgp-F-4|In the key of F, press the 4.',
  'dgp-F-s4|In the key of F, press the ♯4.',
  'dgp-F-b5|In the key of F, press the ♭5.',
  'dgp-F-5|In the key of F, press the 5.',
  'dgp-F-b6|In the key of F, press the ♭6.',
  'dgp-F-6|In the key of F, press the 6.',
  'dgp-F-b7|In the key of F, press the ♭7.',
  'dgp-F-7|In the key of F, press the 7.',
  'dgp-Fs-1|In the key of Gb, press the 1.',
  'dgp-Fs-b2|In the key of Gb, press the ♭2.',
  'dgp-Fs-2|In the key of Gb, press the 2.',
  'dgp-Fs-b3|In the key of Gb, press the ♭3.',
  'dgp-Fs-3|In the key of Gb, press the 3.',
  'dgp-Fs-4|In the key of Gb, press the 4.',
  'dgp-Fs-s4|In the key of Gb, press the ♯4.',
  'dgp-Fs-b5|In the key of Gb, press the ♭5.',
  'dgp-Fs-5|In the key of Gb, press the 5.',
  'dgp-Fs-b6|In the key of Gb, press the ♭6.',
  'dgp-Fs-6|In the key of Gb, press the 6.',
  'dgp-Fs-b7|In the key of Gb, press the ♭7.',
  'dgp-Fs-7|In the key of Gb, press the 7.',
  'dgp-G-1|In the key of G, press the 1.',
  'dgp-G-b2|In the key of G, press the ♭2.',
  'dgp-G-2|In the key of G, press the 2.',
  'dgp-G-b3|In the key of G, press the ♭3.',
  'dgp-G-3|In the key of G, press the 3.',
  'dgp-G-4|In the key of G, press the 4.',
  'dgp-G-s4|In the key of G, press the ♯4.',
  'dgp-G-b5|In the key of G, press the ♭5.',
  'dgp-G-5|In the key of G, press the 5.',
  'dgp-G-b6|In the key of G, press the ♭6.',
  'dgp-G-6|In the key of G, press the 6.',
  'dgp-G-b7|In the key of G, press the ♭7.',
  'dgp-G-7|In the key of G, press the 7.',
  'dgp-Ab-1|In the key of Ab, press the 1.',
  'dgp-Ab-b2|In the key of Ab, press the ♭2.',
  'dgp-Ab-2|In the key of Ab, press the 2.',
  'dgp-Ab-b3|In the key of Ab, press the ♭3.',
  'dgp-Ab-3|In the key of Ab, press the 3.',
  'dgp-Ab-4|In the key of Ab, press the 4.',
  'dgp-Ab-s4|In the key of Ab, press the ♯4.',
  'dgp-Ab-b5|In the key of Ab, press the ♭5.',
  'dgp-Ab-5|In the key of Ab, press the 5.',
  'dgp-Ab-b6|In the key of Ab, press the ♭6.',
  'dgp-Ab-6|In the key of Ab, press the 6.',
  'dgp-Ab-b7|In the key of Ab, press the ♭7.',
  'dgp-Ab-7|In the key of Ab, press the 7.',
  'dgp-A-1|In the key of A, press the 1.',
  'dgp-A-b2|In the key of A, press the ♭2.',
  'dgp-A-2|In the key of A, press the 2.',
  'dgp-A-b3|In the key of A, press the ♭3.',
  'dgp-A-3|In the key of A, press the 3.',
  'dgp-A-4|In the key of A, press the 4.',
  'dgp-A-s4|In the key of A, press the ♯4.',
  'dgp-A-b5|In the key of A, press the ♭5.',
  'dgp-A-5|In the key of A, press the 5.',
  'dgp-A-b6|In the key of A, press the ♭6.',
  'dgp-A-6|In the key of A, press the 6.',
  'dgp-A-b7|In the key of A, press the ♭7.',
  'dgp-A-7|In the key of A, press the 7.',
  'dgp-Bb-1|In the key of Bb, press the 1.',
  'dgp-Bb-b2|In the key of Bb, press the ♭2.',
  'dgp-Bb-2|In the key of Bb, press the 2.',
  'dgp-Bb-b3|In the key of Bb, press the ♭3.',
  'dgp-Bb-3|In the key of Bb, press the 3.',
  'dgp-Bb-4|In the key of Bb, press the 4.',
  'dgp-Bb-s4|In the key of Bb, press the ♯4.',
  'dgp-Bb-b5|In the key of Bb, press the ♭5.',
  'dgp-Bb-5|In the key of Bb, press the 5.',
  'dgp-Bb-b6|In the key of Bb, press the ♭6.',
  'dgp-Bb-6|In the key of Bb, press the 6.',
  'dgp-Bb-b7|In the key of Bb, press the ♭7.',
  'dgp-Bb-7|In the key of Bb, press the 7.',
  'dgp-B-1|In the key of B, press the 1.',
  'dgp-B-b2|In the key of B, press the ♭2.',
  'dgp-B-2|In the key of B, press the 2.',
  'dgp-B-b3|In the key of B, press the ♭3.',
  'dgp-B-3|In the key of B, press the 3.',
  'dgp-B-4|In the key of B, press the 4.',
  'dgp-B-s4|In the key of B, press the ♯4.',
  'dgp-B-b5|In the key of B, press the ♭5.',
  'dgp-B-5|In the key of B, press the 5.',
  'dgp-B-b6|In the key of B, press the ♭6.',
  'dgp-B-6|In the key of B, press the 6.',
  'dgp-B-b7|In the key of B, press the ♭7.',
  'dgp-B-7|In the key of B, press the 7.',
  'dgk-C-1|C is the 1 of which major key?',
  'dgk-C-b2|D♭ is the ♭2 of which major key?',
  'dgk-C-2|D is the 2 of which major key?',
  'dgk-C-b3|E♭ is the ♭3 of which major key?',
  'dgk-C-3|E is the 3 of which major key?',
  'dgk-C-4|F is the 4 of which major key?',
  'dgk-C-s4|F♯ is the ♯4 of which major key?',
  'dgk-C-b5|G♭ is the ♭5 of which major key?',
  'dgk-C-5|G is the 5 of which major key?',
  'dgk-C-b6|A♭ is the ♭6 of which major key?',
  'dgk-C-6|A is the 6 of which major key?',
  'dgk-C-b7|B♭ is the ♭7 of which major key?',
  'dgk-C-7|B is the 7 of which major key?',
  'dgk-Db-1|D♭ is the 1 of which major key?',
  'dgk-Db-b2|E𝄫 (D) is the ♭2 of which major key?',
  'dgk-Db-2|E♭ is the 2 of which major key?',
  'dgk-Db-b3|F♭ (E) is the ♭3 of which major key?',
  'dgk-Db-3|F is the 3 of which major key?',
  'dgk-Db-4|G♭ is the 4 of which major key?',
  'dgk-Db-s4|G is the ♯4 of which major key?',
  'dgk-Db-b5|A𝄫 (G) is the ♭5 of which major key?',
  'dgk-Db-5|A♭ is the 5 of which major key?',
  'dgk-Db-b6|B𝄫 (A) is the ♭6 of which major key?',
  'dgk-Db-6|B♭ is the 6 of which major key?',
  'dgk-Db-b7|C♭ (B) is the ♭7 of which major key?',
  'dgk-Db-7|C is the 7 of which major key?',
  'dgk-D-1|D is the 1 of which major key?',
  'dgk-D-b2|E♭ is the ♭2 of which major key?',
  'dgk-D-2|E is the 2 of which major key?',
  'dgk-D-b3|F is the ♭3 of which major key?',
  'dgk-D-3|F♯ is the 3 of which major key?',
  'dgk-D-4|G is the 4 of which major key?',
  'dgk-D-s4|G♯ is the ♯4 of which major key?',
  'dgk-D-b5|A♭ is the ♭5 of which major key?',
  'dgk-D-5|A is the 5 of which major key?',
  'dgk-D-b6|B♭ is the ♭6 of which major key?',
  'dgk-D-6|B is the 6 of which major key?',
  'dgk-D-b7|C is the ♭7 of which major key?',
  'dgk-D-7|C♯ is the 7 of which major key?',
  'dgk-Eb-1|E♭ is the 1 of which major key?',
  'dgk-Eb-b2|F♭ (E) is the ♭2 of which major key?',
  'dgk-Eb-2|F is the 2 of which major key?',
  'dgk-Eb-b3|G♭ is the ♭3 of which major key?',
  'dgk-Eb-3|G is the 3 of which major key?',
  'dgk-Eb-4|A♭ is the 4 of which major key?',
  'dgk-Eb-s4|A is the ♯4 of which major key?',
  'dgk-Eb-b5|B𝄫 (A) is the ♭5 of which major key?',
  'dgk-Eb-5|B♭ is the 5 of which major key?',
  'dgk-Eb-b6|C♭ (B) is the ♭6 of which major key?',
  'dgk-Eb-6|C is the 6 of which major key?',
  'dgk-Eb-b7|D♭ is the ♭7 of which major key?',
  'dgk-Eb-7|D is the 7 of which major key?',
  'dgk-E-1|E is the 1 of which major key?',
  'dgk-E-b2|F is the ♭2 of which major key?',
  'dgk-E-2|F♯ is the 2 of which major key?',
  'dgk-E-b3|G is the ♭3 of which major key?',
  'dgk-E-3|G♯ is the 3 of which major key?',
  'dgk-E-4|A is the 4 of which major key?',
  'dgk-E-s4|A♯ is the ♯4 of which major key?',
  'dgk-E-b5|B♭ is the ♭5 of which major key?',
  'dgk-E-5|B is the 5 of which major key?',
  'dgk-E-b6|C is the ♭6 of which major key?',
  'dgk-E-6|C♯ is the 6 of which major key?',
  'dgk-E-b7|D is the ♭7 of which major key?',
  'dgk-E-7|D♯ is the 7 of which major key?',
  'dgk-F-1|F is the 1 of which major key?',
  'dgk-F-b2|G♭ is the ♭2 of which major key?',
  'dgk-F-2|G is the 2 of which major key?',
  'dgk-F-b3|A♭ is the ♭3 of which major key?',
  'dgk-F-3|A is the 3 of which major key?',
  'dgk-F-4|B♭ is the 4 of which major key?',
  'dgk-F-s4|B is the ♯4 of which major key?',
  'dgk-F-b5|C♭ (B) is the ♭5 of which major key?',
  'dgk-F-5|C is the 5 of which major key?',
  'dgk-F-b6|D♭ is the ♭6 of which major key?',
  'dgk-F-6|D is the 6 of which major key?',
  'dgk-F-b7|E♭ is the ♭7 of which major key?',
  'dgk-F-7|E is the 7 of which major key?',
  'dgk-Fs-1|G♭ is the 1 of which major key?',
  'dgk-Fs-b2|A𝄫 (G) is the ♭2 of which major key?',
  'dgk-Fs-2|A♭ is the 2 of which major key?',
  'dgk-Fs-b3|B𝄫 (A) is the ♭3 of which major key?',
  'dgk-Fs-3|B♭ is the 3 of which major key?',
  'dgk-Fs-4|C♭ (B) is the 4 of which major key?',
  'dgk-Fs-s4|C is the ♯4 of which major key?',
  'dgk-Fs-b5|D𝄫 (C) is the ♭5 of which major key?',
  'dgk-Fs-5|D♭ is the 5 of which major key?',
  'dgk-Fs-b6|E𝄫 (D) is the ♭6 of which major key?',
  'dgk-Fs-6|E♭ is the 6 of which major key?',
  'dgk-Fs-b7|F♭ (E) is the ♭7 of which major key?',
  'dgk-Fs-7|F is the 7 of which major key?',
  'dgk-G-1|G is the 1 of which major key?',
  'dgk-G-b2|A♭ is the ♭2 of which major key?',
  'dgk-G-2|A is the 2 of which major key?',
  'dgk-G-b3|B♭ is the ♭3 of which major key?',
  'dgk-G-3|B is the 3 of which major key?',
  'dgk-G-4|C is the 4 of which major key?',
  'dgk-G-s4|C♯ is the ♯4 of which major key?',
  'dgk-G-b5|D♭ is the ♭5 of which major key?',
  'dgk-G-5|D is the 5 of which major key?',
  'dgk-G-b6|E♭ is the ♭6 of which major key?',
  'dgk-G-6|E is the 6 of which major key?',
  'dgk-G-b7|F is the ♭7 of which major key?',
  'dgk-G-7|F♯ is the 7 of which major key?',
  'dgk-Ab-1|A♭ is the 1 of which major key?',
  'dgk-Ab-b2|B𝄫 (A) is the ♭2 of which major key?',
  'dgk-Ab-2|B♭ is the 2 of which major key?',
  'dgk-Ab-b3|C♭ (B) is the ♭3 of which major key?',
  'dgk-Ab-3|C is the 3 of which major key?',
  'dgk-Ab-4|D♭ is the 4 of which major key?',
  'dgk-Ab-s4|D is the ♯4 of which major key?',
  'dgk-Ab-b5|E𝄫 (D) is the ♭5 of which major key?',
  'dgk-Ab-5|E♭ is the 5 of which major key?',
  'dgk-Ab-b6|F♭ (E) is the ♭6 of which major key?',
  'dgk-Ab-6|F is the 6 of which major key?',
  'dgk-Ab-b7|G♭ is the ♭7 of which major key?',
  'dgk-Ab-7|G is the 7 of which major key?',
  'dgk-A-1|A is the 1 of which major key?',
  'dgk-A-b2|B♭ is the ♭2 of which major key?',
  'dgk-A-2|B is the 2 of which major key?',
  'dgk-A-b3|C is the ♭3 of which major key?',
  'dgk-A-3|C♯ is the 3 of which major key?',
  'dgk-A-4|D is the 4 of which major key?',
  'dgk-A-s4|D♯ is the ♯4 of which major key?',
  'dgk-A-b5|E♭ is the ♭5 of which major key?',
  'dgk-A-5|E is the 5 of which major key?',
  'dgk-A-b6|F is the ♭6 of which major key?',
  'dgk-A-6|F♯ is the 6 of which major key?',
  'dgk-A-b7|G is the ♭7 of which major key?',
  'dgk-A-7|G♯ is the 7 of which major key?',
  'dgk-Bb-1|B♭ is the 1 of which major key?',
  'dgk-Bb-b2|C♭ (B) is the ♭2 of which major key?',
  'dgk-Bb-2|C is the 2 of which major key?',
  'dgk-Bb-b3|D♭ is the ♭3 of which major key?',
  'dgk-Bb-3|D is the 3 of which major key?',
  'dgk-Bb-4|E♭ is the 4 of which major key?',
  'dgk-Bb-s4|E is the ♯4 of which major key?',
  'dgk-Bb-b5|F♭ (E) is the ♭5 of which major key?',
  'dgk-Bb-5|F is the 5 of which major key?',
  'dgk-Bb-b6|G♭ is the ♭6 of which major key?',
  'dgk-Bb-6|G is the 6 of which major key?',
  'dgk-Bb-b7|A♭ is the ♭7 of which major key?',
  'dgk-Bb-7|A is the 7 of which major key?',
  'dgk-B-1|B is the 1 of which major key?',
  'dgk-B-b2|C is the ♭2 of which major key?',
  'dgk-B-2|C♯ is the 2 of which major key?',
  'dgk-B-b3|D is the ♭3 of which major key?',
  'dgk-B-3|D♯ is the 3 of which major key?',
  'dgk-B-4|E is the 4 of which major key?',
  'dgk-B-s4|E♯ (F) is the ♯4 of which major key?',
  'dgk-B-b5|F is the ♭5 of which major key?',
  'dgk-B-5|F♯ is the 5 of which major key?',
  'dgk-B-b6|G is the ♭6 of which major key?',
  'dgk-B-6|G♯ is the 6 of which major key?',
  'dgk-B-b7|A is the ♭7 of which major key?',
  'dgk-B-7|A♯ is the 7 of which major key?',
  'nn-12|In F# major, 4 of the scale = ?',
  // `reverse-key-pivots` WAS HERE. All twenty-four positional cards
  // and the three root-suffixed top-ups folded into `degree-notes` on
  // 3 Sep 2026 as its fourth question type — the one whose answer is a
  // KEY. Every one of them moved its history onto its counterpart.
  // --- intervals ---
  'iv-1|The interval from C to G ascending = ?',
  'iv-2|The interval from C to E ascending = ?',
  'iv-3|The interval from C to F ascending = ?',
  'iv-4|The interval from C to A ascending = ?',
  'iv-5|The interval from C to B ascending = ?',
  'iv-6|The interval from D to F ascending = ?',
  'iv-7|The interval from D to A ascending = ?',
  'iv-8|The interval from E to G ascending = ?',
  'iv-9|The interval from E to B ascending = ?',
  'iv-10|The interval from F to Bb ascending = ?',
  'iv-11|The interval from G to D ascending = ?',
  'iv-12|The interval from G to B ascending = ?',
  'iv-13|The interval from A to C ascending = ?',
  'iv-14|The interval from A to E ascending = ?',
  'iv-15|The interval from Bb to D ascending = ?',
  'iv-16|The interval from Bb to F ascending = ?',
  'iv-17|The interval from F to B ascending = ?',
  'iv-18|The interval from E to A ascending = ?',
  'iv-19|The interval from D to G ascending = ?',
  'iv-20|The interval from G to F ascending = ?',
  'iv-Db-5|The interval from D♭ to A♭ ascending = ?',
  'iv-Eb-3|The interval from E♭ to G ascending = ?',
  'iv-Gb-4|The interval from G♭ to C♭ (B) ascending = ?',
  'iv-Ab-6|The interval from A♭ to F ascending = ?',
  'iv-B-7|The interval from B to A♯ ascending = ?',
  'iv-inv-of-unison|A Unison inverted is a _____',
  'iv-inv-of-octave|An Octave inverted is a _____',
  'iv-inv-of-minor-2nd|A minor 2nd inverted is a _____',
  'iv-inv-of-major-7th|A Major 7th inverted is a _____',
  'iv-inv-of-major-2nd|A Major 2nd inverted is a _____',
  'iv-inv-of-minor-7th|A minor 7th inverted is a _____',
  'iv-inv-of-minor-3rd|A minor 3rd inverted is a _____',
  'iv-inv-of-major-6th|A Major 6th inverted is a _____',
  'iv-inv-of-major-3rd|A Major 3rd inverted is a _____',
  'iv-inv-of-minor-6th|A minor 6th inverted is a _____',
  'iv-inv-of-perfect-4th|A Perfect 4th inverted is a _____',
  'iv-inv-of-perfect-5th|A Perfect 5th inverted is a _____',
  'iv-inv-of-tritone|A Tritone inverted is a _____',
  'iv-inv-sum|An interval and its inversion always add up to _____',
  'iv-inv-quality-rule|When an interval inverts, its quality _____',
  // `tritone-pairs` WAS HERE. All twelve folded into `degree-notes`
  // on 3 Sep 2026 — eleven onto a ♯4 card and `tt-12` onto the ♭5 of
  // B, each asserted to be the identical answer before its rows moved.
  // --- enharmonic-equivalents ---
  'enh-n-1|Enharmonic equivalent of Ab?',
  'enh-n-2|Enharmonic equivalent of G#?',
  'enh-n-3|Enharmonic equivalent of Bb?',
  'enh-n-4|Enharmonic equivalent of A#?',
  'enh-n-5|Enharmonic equivalent of Db?',
  'enh-n-6|Enharmonic equivalent of C#?',
  'enh-n-7|Enharmonic equivalent of Eb?',
  'enh-n-8|Enharmonic equivalent of D#?',
  'enh-n-9|Enharmonic equivalent of Gb?',
  'enh-n-10|Enharmonic equivalent of F#?',
  'enh-n-11|Enharmonic equivalent of B#?',
  'enh-n-12|Enharmonic equivalent of C?',
  'enh-n-13|Enharmonic equivalent of Cb?',
  'enh-n-14|Enharmonic equivalent of B?',
  'enh-n-15|Enharmonic equivalent of E#?',
  'enh-n-16|Enharmonic equivalent of F?',
  'enh-n-17|Enharmonic equivalent of Fb?',
  'enh-n-18|Enharmonic equivalent of E?',
  'enh-i-19|Enharmonic equivalent of 2?',
  'enh-i-20|Enharmonic equivalent of 9?',
  'enh-i-21|Enharmonic equivalent of b2?',
  'enh-i-22|Enharmonic equivalent of b9?',
  'enh-i-23|Enharmonic equivalent of #2?',
  'enh-i-24|Enharmonic equivalent of b3?',
  'enh-i-25|Enharmonic equivalent of #9?',
  'enh-i-26|Enharmonic equivalent of 4?',
  'enh-i-27|Enharmonic equivalent of 11?',
  'enh-i-28|Enharmonic equivalent of #4?',
  'enh-i-29|Enharmonic equivalent of b5?',
  'enh-i-30|Enharmonic equivalent of #11?',
  'enh-i-31|Enharmonic equivalent of 6?',
  'enh-i-32|Enharmonic equivalent of 13?',
  'enh-i-33|Enharmonic equivalent of b6?',
  'enh-i-34|Enharmonic equivalent of #5?',
  'enh-i-35|Enharmonic equivalent of b13?',
  // --- pentatonic-scales ---
  'pent-1|What 5 notes make up the major pentatonic scale?',
  'pent-2|The major pentatonic scale is the major scale with which two notes removed?',
  'pent-5|What 5 notes make up the minor pentatonic scale?',
  'pent-6|The minor pentatonic scale is the natural minor scale with which two notes removed?',
  'pent-9|The minor pentatonic scale starting on the ___ of the major pentatonic gives you the relative minor pentatonic',
  'pent-8|In C minor pentatonic, the notes are _____',
  'pent-minor-Db|In C♯ (D♭) minor pentatonic, the notes are _____',
  'pent-minor-D|In D minor pentatonic, the notes are _____',
  'pent-minor-Eb|In E♭ minor pentatonic, the notes are _____',
  'pent-minor-E|In E minor pentatonic, the notes are _____',
  'pent-minor-F|In F minor pentatonic, the notes are _____',
  'pent-minor-F#|In F♯ (G♭) minor pentatonic, the notes are _____',
  'pent-minor-G|In G minor pentatonic, the notes are _____',
  'pent-minor-Ab|In G♯ (A♭) minor pentatonic, the notes are _____',
  'pent-minor-A|In A minor pentatonic, the notes are _____',
  'pent-minor-Bb|In B♭ minor pentatonic, the notes are _____',
  'pent-minor-B|In B minor pentatonic, the notes are _____',
  'pent-major-C|In C major pentatonic, the notes are _____',
  'pent-major-Db|In D♭ major pentatonic, the notes are _____',
  'pent-major-D|In D major pentatonic, the notes are _____',
  'pent-major-Eb|In E♭ major pentatonic, the notes are _____',
  'pent-major-E|In E major pentatonic, the notes are _____',
  'pent-major-F|In F major pentatonic, the notes are _____',
  'pent-major-F#|In G♭ major pentatonic, the notes are _____',
  'pent-major-G|In G major pentatonic, the notes are _____',
  'pent-major-Ab|In A♭ major pentatonic, the notes are _____',
  'pent-major-A|In A major pentatonic, the notes are _____',
  'pent-major-Bb|In B♭ major pentatonic, the notes are _____',
  'pent-major-B|In B major pentatonic, the notes are _____',
  'pent-10|C major pentatonic and A minor pentatonic share the same _____',
  'pent-relative-Db|D♭ major pentatonic and B♭ minor pentatonic share the same _____',
  'pent-relative-D|D major pentatonic and B minor pentatonic share the same _____',
  'pent-relative-Eb|E♭ major pentatonic and C minor pentatonic share the same _____',
  'pent-relative-E|E major pentatonic and C♯ (D♭) minor pentatonic share the same _____',
  'pent-relative-F|F major pentatonic and D minor pentatonic share the same _____',
  'pent-relative-F#|G♭ major pentatonic and E♭ minor pentatonic share the same _____',
  'pent-relative-G|G major pentatonic and E minor pentatonic share the same _____',
  'pent-relative-Ab|A♭ major pentatonic and F minor pentatonic share the same _____',
  'pent-relative-A|A major pentatonic and F♯ (G♭) minor pentatonic share the same _____',
  'pent-relative-Bb|B♭ major pentatonic and G minor pentatonic share the same _____',
  'pent-relative-B|B major pentatonic and G♯ (A♭) minor pentatonic share the same _____',
  // --- functional-harmony ---
  'fh-1|The V chord most strongly resolves to _____',
  'fh-2|The leading tone (7th scale degree) resolves to _____',
  'fh-3|The ii-V-I cadence in C major is _____',
  'fh-4|The IV → I move (the "Amen" cadence) is also called the _____',
  'fh-5|The strongest "going home" cadence — V → I — is also called the _____',
  'fh-6|When V goes to vi instead of I (the "fake-out" resolution), the cadence is called _____',
  'fh-7|A phrase that ends "hanging" on the V chord (waiting for resolution) uses a _____',
  'fh-8|The tonic function is served by which chord(s)?',
  'fh-9|The "lead-up" function (chords that set up the V) is served by _____',
  'fh-10|The dominant function (chords that pull back to I) is served by _____',
  'fh-11|A secondary dominant V/V in C major is which chord?',
  'fh-12|V/vi in C major resolves to _____',
  'fh-13|In jazz, the "tritone substitution" of G7 is _____',
  'fh-14|bVII in a major key is borrowed from _____',
  'fh-15|iv minor in a major key is borrowed from _____',
  'fh-16|Ending a minor-key song on a major I chord (instead of minor i) creates _____',
  'fh-17|The circle of fifths describes motion by _____',
  'fh-18|In a 1-5-6-4 progression, swapping the plain V for a fuller version typically means using _____',
  'fh-19|A chord that has both tonic and dominant function qualities is _____',
  'fh-ii-v-i-Db|The ii-V-I cadence in D♭ major is _____',
  'fh-ii-v-i-D|The ii-V-I cadence in D major is _____',
  'fh-ii-v-i-Eb|The ii-V-I cadence in E♭ major is _____',
  'fh-ii-v-i-E|The ii-V-I cadence in E major is _____',
  'fh-ii-v-i-F|The ii-V-I cadence in F major is _____',
  'fh-ii-v-i-F#|The ii-V-I cadence in G♭ major is _____',
  'fh-ii-v-i-G|The ii-V-I cadence in G major is _____',
  'fh-ii-v-i-Ab|The ii-V-I cadence in A♭ major is _____',
  'fh-ii-v-i-A|The ii-V-I cadence in A major is _____',
  'fh-ii-v-i-Bb|The ii-V-I cadence in B♭ major is _____',
  'fh-ii-v-i-B|The ii-V-I cadence in B major is _____',
  'fh-v-of-v-Db|A secondary dominant V/V in D♭ major is which chord?',
  'fh-v-of-v-D|A secondary dominant V/V in D major is which chord?',
  'fh-v-of-v-Eb|A secondary dominant V/V in E♭ major is which chord?',
  'fh-v-of-v-E|A secondary dominant V/V in E major is which chord?',
  'fh-v-of-v-F|A secondary dominant V/V in F major is which chord?',
  'fh-v-of-v-F#|A secondary dominant V/V in G♭ major is which chord?',
  'fh-v-of-v-G|A secondary dominant V/V in G major is which chord?',
  'fh-v-of-v-Ab|A secondary dominant V/V in A♭ major is which chord?',
  'fh-v-of-v-A|A secondary dominant V/V in A major is which chord?',
  'fh-v-of-v-Bb|A secondary dominant V/V in B♭ major is which chord?',
  'fh-v-of-v-B|A secondary dominant V/V in B major is which chord?',
  'fh-v-of-vi-Db|V/vi in D♭ major resolves to _____',
  'fh-v-of-vi-D|V/vi in D major resolves to _____',
  'fh-v-of-vi-Eb|V/vi in E♭ major resolves to _____',
  'fh-v-of-vi-E|V/vi in E major resolves to _____',
  'fh-v-of-vi-F|V/vi in F major resolves to _____',
  'fh-v-of-vi-F#|V/vi in G♭ major resolves to _____',
  'fh-v-of-vi-G|V/vi in G major resolves to _____',
  'fh-v-of-vi-Ab|V/vi in A♭ major resolves to _____',
  'fh-v-of-vi-A|V/vi in A major resolves to _____',
  'fh-v-of-vi-Bb|V/vi in B♭ major resolves to _____',
  'fh-v-of-vi-B|V/vi in B major resolves to _____',
  // --- modes ---
  'mo-1|Dorian mode starts on which scale degree of the major scale?',
  'mo-2|Phrygian mode starts on which scale degree?',
  'mo-3|Lydian mode starts on which scale degree?',
  'mo-4|Mixolydian mode starts on which scale degree?',
  'mo-5|Aeolian mode (natural minor) starts on which scale degree?',
  'mo-6|Locrian mode starts on which scale degree?',
  'mo-7|Mixolydian mode\'s signature altered note is _____',
  'mo-8|Lydian mode\'s signature altered note is _____',
  'mo-9|Dorian mode\'s signature altered note is _____',
  'mo-10|Phrygian mode\'s signature altered note is _____',
  'mo-11|The mode of C major starting on A is _____',
  'mo-12|The mode of C major starting on D is _____',
  'mo-13|The mode of C major starting on G is _____',
  'mo-14|The signature chord that says \'Dorian\' is _____',
  'mo-15|The signature chord that says \'Lydian\' is _____',
  'mo-16|The signature chord that says \'Mixolydian\' is _____',
  'mo-17|Harmonic minor differs from natural minor by _____',
  'mo-18|Melodic minor (ascending) differs from natural minor by _____',
  'mo-20|Ionian mode is the same as _____',
  'mo-mode-of-Db-2|The mode of D♭ major starting on E♭ is _____',
  'mo-mode-of-Db-5|The mode of D♭ major starting on A♭ is _____',
  'mo-mode-of-Db-6|The mode of D♭ major starting on B♭ is _____',
  'mo-mode-of-D-2|The mode of D major starting on E is _____',
  'mo-mode-of-D-5|The mode of D major starting on A is _____',
  'mo-mode-of-D-6|The mode of D major starting on B is _____',
  'mo-mode-of-Eb-2|The mode of E♭ major starting on F is _____',
  'mo-mode-of-Eb-5|The mode of E♭ major starting on B♭ is _____',
  'mo-mode-of-Eb-6|The mode of E♭ major starting on C is _____',
  'mo-mode-of-E-2|The mode of E major starting on F♯ is _____',
  'mo-mode-of-E-5|The mode of E major starting on B is _____',
  'mo-mode-of-E-6|The mode of E major starting on C♯ is _____',
  'mo-mode-of-F-2|The mode of F major starting on G is _____',
  'mo-mode-of-F-5|The mode of F major starting on C is _____',
  'mo-mode-of-F-6|The mode of F major starting on D is _____',
  'mo-mode-of-F#-2|The mode of G♭ major starting on A♭ is _____',
  'mo-mode-of-F#-5|The mode of G♭ major starting on D♭ is _____',
  'mo-mode-of-F#-6|The mode of G♭ major starting on E♭ is _____',
  'mo-mode-of-G-2|The mode of G major starting on A is _____',
  'mo-mode-of-G-5|The mode of G major starting on D is _____',
  'mo-mode-of-G-6|The mode of G major starting on E is _____',
  'mo-mode-of-Ab-2|The mode of A♭ major starting on B♭ is _____',
  'mo-mode-of-Ab-5|The mode of A♭ major starting on E♭ is _____',
  'mo-mode-of-Ab-6|The mode of A♭ major starting on F is _____',
  'mo-mode-of-A-2|The mode of A major starting on B is _____',
  'mo-mode-of-A-5|The mode of A major starting on E is _____',
  'mo-mode-of-A-6|The mode of A major starting on F♯ is _____',
  'mo-mode-of-Bb-2|The mode of B♭ major starting on C is _____',
  'mo-mode-of-Bb-5|The mode of B♭ major starting on F is _____',
  'mo-mode-of-Bb-6|The mode of B♭ major starting on G is _____',
  'mo-mode-of-B-2|The mode of B major starting on C♯ is _____',
  'mo-mode-of-B-5|The mode of B major starting on F♯ is _____',
  'mo-mode-of-B-6|The mode of B major starting on G♯ is _____',
  // --- slash-chords ---
  'sc-1|C/E is in which inversion?',
  'sc-2|C/G is in which inversion?',
  'sc-3|Cmaj7/B is in which inversion?',
  'sc-4|G/B in the key of C major functions as _____',
  'sc-5|A 2nd inversion triad has which note in the bass?',
  'sc-6|A 1st inversion triad has which note in the bass?',
  'sc-7|F/G in the key of C major is most often used as _____',
  'sc-8|What is 1/3 in C major?',
  'sc-9|What is 5/7 in C major?',
  'sc-10|What is 4/5 in C major?',
  'sc-11|What is 6/b7 in C major?',
  'sc-12|The descending bass line 1 - 5/7 - 6 - 1/3 moves the bass by _____',
  'sc-13|A pedal-tone progression using slash chords over a single bass note is called a _____',
  'sc-14|A slash chord X/Y where Y is NOT a chord tone is sometimes called _____',
  'sc-15|The main purpose of using slash chords is to _____',
  'sc-16|The V chord in first inversion has which chord tone in the bass?',
  'sc-1-3-Db|What is 1/3 in D♭ major?',
  'sc-5-7-Db|What is 5/7 in D♭ major?',
  'sc-4-5-Db|What is 4/5 in D♭ major?',
  'sc-6-b7-Db|What is 6/b7 in D♭ major?',
  'sc-1-3-D|What is 1/3 in D major?',
  'sc-5-7-D|What is 5/7 in D major?',
  'sc-4-5-D|What is 4/5 in D major?',
  'sc-6-b7-D|What is 6/b7 in D major?',
  'sc-1-3-Eb|What is 1/3 in E♭ major?',
  'sc-5-7-Eb|What is 5/7 in E♭ major?',
  'sc-4-5-Eb|What is 4/5 in E♭ major?',
  'sc-6-b7-Eb|What is 6/b7 in E♭ major?',
  'sc-1-3-E|What is 1/3 in E major?',
  'sc-5-7-E|What is 5/7 in E major?',
  'sc-4-5-E|What is 4/5 in E major?',
  'sc-6-b7-E|What is 6/b7 in E major?',
  'sc-1-3-F|What is 1/3 in F major?',
  'sc-5-7-F|What is 5/7 in F major?',
  'sc-4-5-F|What is 4/5 in F major?',
  'sc-6-b7-F|What is 6/b7 in F major?',
  'sc-1-3-F#|What is 1/3 in G♭ major?',
  'sc-5-7-F#|What is 5/7 in G♭ major?',
  'sc-4-5-F#|What is 4/5 in G♭ major?',
  'sc-6-b7-F#|What is 6/b7 in G♭ major?',
  'sc-1-3-G|What is 1/3 in G major?',
  'sc-5-7-G|What is 5/7 in G major?',
  'sc-4-5-G|What is 4/5 in G major?',
  'sc-6-b7-G|What is 6/b7 in G major?',
  'sc-1-3-Ab|What is 1/3 in A♭ major?',
  'sc-5-7-Ab|What is 5/7 in A♭ major?',
  'sc-4-5-Ab|What is 4/5 in A♭ major?',
  'sc-6-b7-Ab|What is 6/b7 in A♭ major?',
  'sc-1-3-A|What is 1/3 in A major?',
  'sc-5-7-A|What is 5/7 in A major?',
  'sc-4-5-A|What is 4/5 in A major?',
  'sc-6-b7-A|What is 6/b7 in A major?',
  'sc-1-3-Bb|What is 1/3 in B♭ major?',
  'sc-5-7-Bb|What is 5/7 in B♭ major?',
  'sc-4-5-Bb|What is 4/5 in B♭ major?',
  'sc-6-b7-Bb|What is 6/b7 in B♭ major?',
  'sc-1-3-B|What is 1/3 in B major?',
  'sc-5-7-B|What is 5/7 in B major?',
  'sc-4-5-B|What is 4/5 in B major?',
  'sc-6-b7-B|What is 6/b7 in B major?',
  // --- progressions ---
  'pr-1|The 1-5-6-4 progression in C major is _____',
  'pr-2|The 2-5-1 in Bb major is _____',
  'pr-3|The 1-6-4-5 in G major is _____',
  'pr-4|The 6-4-1-5 in D major is _____',
  'pr-5|The gospel walk-up I-II-iii-IV in C major is _____',
  'pr-6|Rhythm changes A section in Bb major starts with _____',
  'pr-7|The backdoor progression I-IV-bVII-I in F major is _____',
  'pr-8|A plagal vamp is which two chords alternating?',
  'pr-9|The 1-5-6-4 and 6-4-1-5 progressions use the same chords; what changes?',
  'pr-10|The neo-soul cycle Imaj7-iii7-vi7-IVmaj7 in C is _____',
  'pr-11|The descending minor progression i-bVII-bVI-V in A minor is _____',
  'pr-12|In the 12-bar blues, bars 5-6 typically go to which chord?',
  'pr-13|The bossa nova standard I-VI-ii-V in F is _____',
  'pr-14|A Dorian vamp i-IV in D is _____',
  'pr-15|The 4-1-5-6 in D major is _____',
  'pr-16|A tonic-pedal progression keeps which note in the bass?',
  'pr-17|A dominant pedal progression keeps which note in the bass?',
  'pr-18|The 1-4-5 in A major is _____',
  'pr-19|The Coltrane changes cycle through how many key centers?',
  'pr-20|The 1-b7-4 progression in C major is _____',
  'pr-1564-Db|The 1-5-6-4 progression in D♭ major is _____',
  'pr-1564-Eb|The 1-5-6-4 progression in E♭ major is _____',
  'pr-1564-E|The 1-5-6-4 progression in E major is _____',
  'pr-1564-F#|The 1-5-6-4 progression in G♭ major is _____',
  'pr-1564-Ab|The 1-5-6-4 progression in A♭ major is _____',
  'pr-1564-B|The 1-5-6-4 progression in B major is _____',
  // --- key-signatures ---
  'ks-1|C major has _____ sharps/flats',
  'ks-2|G major has _____ sharps',
  'ks-3|D major has _____ sharps',
  'ks-4|A major has _____ sharps',
  'ks-5|E major has _____ sharps',
  'ks-6|B major has _____ sharps',
  'ks-7|F# major has _____ sharps',
  'ks-8|F major has _____ flats',
  'ks-9|Bb major has _____ flats',
  'ks-10|Eb major has _____ flats',
  'ks-11|Ab major has _____ flats',
  'ks-12|Db major has _____ flats',
  'ks-13|The relative minor of C major is _____',
  'ks-14|The relative minor of G major is _____',
  'ks-15|The relative minor of Ab major is _____',
  'ks-16|The relative major of A minor is _____',
  'ks-17|The parallel minor of D major is _____',
  'ks-18|The parallel minor of F major is _____',
  'ks-19|A key with 3 flats is most likely _____',
  'ks-20|A key with 4 sharps is most likely _____',
  'ks-21|The order of sharps in a key signature is _____',
  'ks-22|The order of flats in a key signature is _____',
  'ksc-1|What are the intervals of the natural minor scale?',
  'ksc-2|Natural minor differs from major by which altered notes?',
  'ksc-4|The relative major of E minor is _____',
  'ksc-5|The relative major of B minor is _____',
  'ksc-6|The relative major of F# minor is _____',
  'ksc-7|The relative major of C# minor is _____',
  'ksc-8|The relative major of G# minor is _____',
  'ksc-9|The relative major of D# minor is _____',
  'ksc-10|The relative major of Bb minor is _____',
  'ksc-11|The relative major of F minor is _____',
  'ksc-12|The relative major of C minor is _____',
  'ksc-13|The relative major of G minor is _____',
  'ksc-14|The relative major of D minor is _____',
  'ksc-15|To find the relative major of any minor key, go ___ half steps up from the minor root',
  'ksc-16|Parallel minor vs relative minor — what is the difference?',
  'ksc-17|The parallel minor of G major is _____',
  'ksc-18|The parallel minor of Bb major is _____',
  'ks-relative-Db|The relative minor of D♭ major is _____',
  'ks-relative-D|The relative minor of D major is _____',
  'ks-relative-Eb|The relative minor of E♭ major is _____',
  'ks-relative-E|The relative minor of E major is _____',
  'ks-relative-F|The relative minor of F major is _____',
  'ks-relative-F#|The relative minor of G♭ major is _____',
  'ks-relative-A|The relative minor of A major is _____',
  'ks-relative-Bb|The relative minor of B♭ major is _____',
  'ks-relative-B|The relative minor of B major is _____',
  'ks-parallel-C|The parallel minor of C major is _____',
  'ks-parallel-Db|The parallel minor of D♭ major is _____',
  'ks-parallel-Eb|The parallel minor of E♭ major is _____',
  'ks-parallel-E|The parallel minor of E major is _____',
  'ks-parallel-F#|The parallel minor of G♭ major is _____',
  'ks-parallel-Ab|The parallel minor of A♭ major is _____',
  'ks-parallel-A|The parallel minor of A major is _____',
  'ks-parallel-B|The parallel minor of B major is _____',
];
