import type { GlossaryContent } from './types';

// Phase 1 glossary — 90+ terms covering Logic Pro interface,
// audio fundamentals, recording, microphones, signal processing,
// mixing, vocal work, and file formats. Definitions are written
// for working musicians (not engineers), tuned to gospel / R&B /
// soul / jazz / neo-soul / hip-hop production aesthetics.

export const GLOSSARY: GlossaryContent[] = [
  // --- Logic Pro interface ----------------------------------------
  {
    id: 'main-window',
    name: 'Main Window',
    definition: 'The primary Logic Pro workspace — the single window that holds your tracks, the playhead, and most of your daily tools.',
    example: 'When you launch Logic and open a project, the giant grid you see is the Main Window.',
    whyItMatters: 'Every other surface in Logic orbits this view. Getting fluent here is the single biggest speed-up in your workflow.',
    relatedLessons: ['wf-01'],
  },
  {
    id: 'control-bar',
    name: 'Control Bar',
    definition: 'The strip across the top of the Main Window with transport controls, the LCD time display, and buttons for features like Cycle and Count-in.',
    example: 'The Play, Record, and Stop buttons you press a thousand times a session all live in the Control Bar.',
    whyItMatters: 'You customise what lives up here — pin the controls you actually use and hide the ones you don’t.',
    relatedLessons: ['wf-01'],
  },
  {
    id: 'tracks-area',
    name: 'Tracks Area',
    definition: 'The central timeline where audio and MIDI regions live on their tracks. Left-to-right is time, stacked rows are tracks.',
    example: 'When you drag a loop into Logic, it becomes a region in the Tracks Area.',
    whyItMatters: 'This is where arrangement happens. Most of your thinking in a session is "how do these regions fit together" — the Tracks Area is the canvas.',
    relatedLessons: ['wf-01'],
  },
  {
    id: 'inspector',
    name: 'Inspector',
    definition: 'The left-side panel that shows detailed parameters for the currently selected track and region — channel strip, routing, groove settings.',
    example: 'Click a vocal track, open the Inspector, and you see its input, output, plugins, and send amounts in one place.',
    whyItMatters: 'The Inspector is your "look under the hood" view — most deep tweaks happen here without opening the full Mixer.',
    relatedLessons: ['wf-01'],
  },
  {
    id: 'library',
    name: 'Library',
    definition: 'The browser that lets you audition and apply track presets, patches, and plugin settings without leaving the Main Window.',
    example: 'Create a new Software Instrument track, open the Library, and scroll through Rhodes patches to pick the one with the right character.',
    whyItMatters: 'Logic ships with great presets. The Library keeps them one click away — starting from a pro-tuned sound is often faster than building one from scratch.',
    relatedLessons: ['wf-01'],
  },
  {
    id: 'smart-controls',
    name: 'Smart Controls',
    definition: 'Eight to twenty-four simplified knobs mapped to the most important parameters of the current patch — the "top-layer" controls built for performance.',
    example: 'On a Rhodes patch, Smart Controls might expose Tine Level, Drive, and Tremolo Rate — the knobs you’d actually twist while tracking.',
    whyItMatters: 'Great for tracking. You shape the sound with three knobs instead of diving into menus mid-take.',
    relatedLessons: ['wf-01'],
  },
  {
    id: 'mixer',
    name: 'Mixer',
    definition: 'The window (shortcut X) showing every track as a vertical channel strip with faders, pans, sends, inserts, and output routing.',
    example: 'Hit X and Logic opens a mixing console laid out like the hardware boards that inspired it.',
    whyItMatters: 'When you’re mixing — not arranging — the Mixer is the room you live in.',
    relatedLessons: ['wf-01'],
  },
  {
    id: 'transport',
    name: 'Transport',
    definition: 'The cluster of playback controls — Play, Stop, Record, Rewind, Fast Forward, Cycle.',
    example: 'When people say "hit the transport," they mean press Play (Spacebar) or Record (R).',
    whyItMatters: 'Every session move starts with a transport action. Learn the shortcuts before anything else.',
    relatedLessons: ['wf-01', 'wf-03'],
  },
  {
    id: 'region',
    name: 'Region',
    definition: 'A single block of audio or MIDI on a track — a take, a loop, a bounce, a piano part.',
    example: 'When you record eight bars of Rhodes, Logic creates a MIDI region. When you import an 808 loop, it becomes an audio region.',
    whyItMatters: 'Everything you arrange in Logic is a region. Splits, merges, loops, trims — all region operations.',
    relatedLessons: ['wf-01', 'wf-07'],
  },
  {
    id: 'track',
    name: 'Track',
    definition: 'A horizontal lane in the Tracks Area that holds regions of one type (audio / software instrument / drum machine / external MIDI).',
    example: 'Your lead vocal, your kick, your bass — each typically lives on its own track.',
    whyItMatters: 'One track per element is the clean baseline. Mixing becomes impossible when everything is stacked on one track.',
    relatedLessons: ['wf-01'],
  },
  {
    id: 'screenset',
    name: 'Screenset',
    definition: 'A saved window layout — the specific combination of Main Window, Mixer, Piano Roll, plugin windows, and their sizes and positions.',
    example: 'Cmd+1 might be your tracking screenset; Cmd+2 your mixing screenset with the Mixer full-screen.',
    whyItMatters: 'Switching between tracking and mixing without re-arranging windows is a massive time-saver.',
    relatedLessons: ['wf-01', 'wf-02'],
  },

  // --- Basic audio --------------------------------------------------
  {
    id: 'decibel',
    name: 'Decibel (dB)',
    definition: 'The standard unit for measuring sound level. It is a ratio, not an absolute — "loud" relative to a reference.',
    example: 'A whisper is ~30 dB SPL; a conversation ~60 dB SPL; a loud club ~110 dB SPL.',
    whyItMatters: 'Every mix decision is "how many dB louder / softer." Training your ear to notice 1–2 dB changes is a core skill.',
    relatedLessons: ['lang-01'],
  },
  {
    id: 'dbfs',
    name: 'dBFS',
    definition: 'Decibels Full Scale — digital audio’s decibel scale where 0 dBFS is the loudest a signal can be before it clips. All values are negative.',
    example: 'Your master bus might peak at -6 dBFS for headroom; a kick hitting -3 dBFS; a quiet verse around -18 dBFS RMS.',
    whyItMatters: 'Stay well under 0 dBFS. Digital clipping is harsh and unforgiving — unlike tape, which compresses pleasantly.',
    relatedLessons: ['lang-01', 'lang-06'],
  },
  {
    id: 'hz',
    name: 'Hertz (Hz)',
    definition: 'A unit of frequency — cycles per second. In audio, it describes pitch.',
    example: 'A4 (the A above middle C) vibrates at 440 Hz. A kick drum’s thump lives around 60–80 Hz.',
    whyItMatters: 'EQ decisions are frequency decisions. Knowing "that 200 Hz mud" or "that 3 kHz harshness" by ear is foundational.',
    relatedLessons: ['lang-01', 'lang-02'],
  },
  {
    id: 'kilohertz',
    name: 'Kilohertz (kHz)',
    definition: '1,000 Hz. Higher frequencies get named in kHz once they pass 1,000.',
    example: 'Vocal sibilance lives around 6–10 kHz. A "bright" hi-hat sparkles around 12 kHz and up.',
    whyItMatters: 'Everything above roughly 2 kHz is "air" or "presence." Those bands shape how modern and polished a mix feels.',
    relatedLessons: ['lang-01', 'lang-02'],
  },
  {
    id: 'frequency',
    name: 'Frequency',
    definition: 'How many times per second a sound wave cycles. Measured in Hz. Higher frequency = higher pitch.',
    example: 'The bass on a Donny Hathaway record is a low-frequency instrument; the hi-hat is high-frequency.',
    whyItMatters: 'Mixing = managing frequencies so every element has its own space.',
    relatedLessons: ['lang-01', 'lang-02'],
  },
  {
    id: 'pitch',
    name: 'Pitch',
    definition: 'The musical note a sound represents — how high or low it sounds. Directly tied to frequency.',
    example: 'A vocal singing A4 has a fundamental pitch of 440 Hz plus harmonics above.',
    whyItMatters: 'Pitch and frequency are two names for the same thing; producers talk about pitch, engineers reach for Hz — learn both.',
    relatedLessons: ['lang-01', 'vocal-03'],
  },
  {
    id: 'amplitude',
    name: 'Amplitude',
    definition: 'The size of a sound wave — how loud it is. Usually measured in dB.',
    example: 'A fader boost raises amplitude; a compressor reduces the peaks of amplitude.',
    whyItMatters: 'Dynamics (loud vs. soft) are an amplitude story. Emotional arc in a mix = amplitude changes over time.',
    relatedLessons: ['lang-01'],
  },
  {
    id: 'harmonic',
    name: 'Harmonic',
    definition: 'A frequency that’s a whole-number multiple of the fundamental pitch of a sound. Harmonics are what make a Rhodes sound different from a piano even at the same pitch.',
    example: 'A 220 Hz note has harmonics at 440, 660, 880 Hz and so on.',
    whyItMatters: 'Tape, tube, and transformer saturation add harmonics — that’s the "warmth" you’re chasing.',
    relatedLessons: ['lang-07'],
  },
  {
    id: 'peak',
    name: 'Peak',
    definition: 'The single loudest instant in a sound’s amplitude.',
    example: 'A kick drum’s transient is a peak; the sustained body that follows is the RMS level.',
    whyItMatters: 'Limiters catch peaks. Peak-watching prevents clipping; managing peaks vs RMS is the whole game of mastering.',
    relatedLessons: ['lang-06'],
  },
  {
    id: 'phase',
    name: 'Phase',
    definition: 'The relative timing of two audio signals. When two signals are "out of phase," their waveforms cancel each other.',
    example: 'Two mics on the same guitar cabinet — move one a half-inch and the tone changes completely because phase shifts.',
    whyItMatters: 'Phase issues are subtle. The most common sign: bass feels weak on a layered track — flip the phase and it jumps forward.',
    relatedLessons: ['lang-01'],
  },

  // --- Recording ----------------------------------------------------
  {
    id: 'record',
    name: 'Record',
    definition: 'The act of capturing audio or MIDI into a track. In Logic, engaged by pressing R.',
    example: 'Arm the track, hit R, play; Logic creates a new region with your performance.',
    whyItMatters: 'Recording is the step where intention becomes data. Everything downstream depends on the take.',
    relatedLessons: ['wf-04'],
  },
  {
    id: 'take',
    name: 'Take',
    definition: 'A single recorded pass over a section of a song.',
    example: 'You record three verses back-to-back in Cycle mode — each loop is a separate take.',
    whyItMatters: 'Great performances are almost never one perfect take. Comp multiple takes for the best of each.',
    relatedLessons: ['wf-04', 'wf-07', 'vocal-02'],
  },
  {
    id: 'take-folder',
    name: 'Take Folder',
    definition: 'A Logic region that holds multiple takes stacked on the same track — the artefact created by Cycle recording.',
    example: 'After looped recording, you get one region labelled "Verse 1" containing all the takes as lanes.',
    whyItMatters: 'Take Folders + Quick Swipe Comping are Logic’s killer vocal workflow. Nearly every modern R&B vocal is built this way.',
    relatedLessons: ['wf-07', 'vocal-02'],
  },
  {
    id: 'comping',
    name: 'Comping',
    definition: 'Short for "compositing" — choosing the best sections from multiple takes and assembling them into one continuous performance.',
    example: 'Take 1 has the best first line; Take 3 has the best chorus note; Take 4 nails the bridge. Comp them together.',
    whyItMatters: 'Modern vocal production is inseparable from comping. Learn it before you learn anything else vocal-related.',
    relatedLessons: ['wf-07', 'vocal-02'],
  },
  {
    id: 'quick-swipe-comping',
    name: 'Quick Swipe Comping',
    definition: 'Logic’s interaction for comping: drag across take lanes to pick which take plays at which moment.',
    example: 'Inside a Take Folder, swipe your mouse across the verse — Logic highlights the chosen take for that span.',
    whyItMatters: 'Dramatically faster than cutting + moving regions manually. The difference between "I can comp" and "I dread comping."',
    relatedLessons: ['wf-07', 'vocal-02'],
  },
  {
    id: 'flatten',
    name: 'Flatten',
    definition: 'The action of committing a Take Folder’s comp into a single audio region — no more swiping, just the chosen performance.',
    example: 'Right-click a Take Folder → Flatten. The folder collapses into one region containing only the selected takes.',
    whyItMatters: 'Flatten after comping so downstream edits (tuning, timing) operate on one clean region.',
    relatedLessons: ['wf-07', 'vocal-02'],
  },
  {
    id: 'composite',
    name: 'Composite',
    definition: 'The finished comp — the single assembled performance that resulted from swiping across takes.',
    example: 'After flattening, the composite is your official Verse 1 vocal.',
    whyItMatters: 'When producers ask "send me the comp," they mean the composite — not the Take Folder with all the alternates.',
    relatedLessons: ['wf-07', 'vocal-02'],
  },
  {
    id: 'midi',
    name: 'MIDI',
    definition: 'A data format that records what notes you played and how, but not the sound. MIDI drives a synth or sampler to make the actual audio.',
    example: 'Play a Rhodes patch on a keyboard controller — Logic stores the notes as MIDI, and the patch turns them into audible Rhodes.',
    whyItMatters: 'Endlessly editable. You can change the patch, transpose, quantise, swap notes — long after recording.',
    relatedLessons: ['wf-04'],
  },
  {
    id: 'arm',
    name: 'Arm',
    definition: 'Enabling a track so it will record when you hit R. Shows as a red "R" button glowing on the track.',
    example: 'Click the R button on your vocal track to arm it, then press Record.',
    whyItMatters: 'Forgetting to arm the right track is the most common reason "Logic didn’t record anything."',
    relatedLessons: ['wf-04'],
  },
  {
    id: 'input-monitoring',
    name: 'Input Monitoring',
    definition: 'Hearing the input signal through Logic’s processing even when you’re not recording. Toggled with the "I" button next to the arm button.',
    example: 'Turn on Input Monitoring to hear your vocal with reverb and compression while you warm up, without rolling tape.',
    whyItMatters: 'Singers perform differently when they hear themselves processed. Give them the full mix — it pulls a better take.',
    relatedLessons: ['wf-04', 'vocal-01'],
  },
  {
    id: 'cycle',
    name: 'Cycle',
    definition: 'A playback / recording mode that loops a section between two locators repeatedly.',
    example: 'Set a cycle over the chorus, hit record, and sing four passes back-to-back — Logic stacks them as takes.',
    whyItMatters: 'The core move of modern vocal production. Cycle + comp = the way nearly every vocal is built.',
    relatedLessons: ['wf-07', 'vocal-02'],
  },
  {
    id: 'punch',
    name: 'Punch',
    definition: 'Recording only over a specific range inside an existing region — "punching in" replaces just that section.',
    example: 'The vocalist flubbed one line. Set the punch points around that line, hit record, and they sing only the fix.',
    whyItMatters: 'Surgical. Saves re-tracking a whole verse when only one line is the problem.',
    relatedLessons: ['wf-04'],
  },
  {
    id: 'playhead',
    name: 'Playhead',
    definition: 'The vertical line in the Tracks Area showing your current playback position.',
    example: 'Click anywhere in the timeline to move the playhead; press Return to send it to the beginning.',
    whyItMatters: 'Your constant companion — knowing the playhead’s state is half of navigation.',
    relatedLessons: ['wf-01', 'wf-06'],
  },
  {
    id: 'marker',
    name: 'Marker',
    definition: 'A named point on the timeline. Used to label sections of a song so you can jump instantly.',
    example: 'Add markers for Intro, Verse 1, Pre-Chorus, Chorus, Bridge, Outro. Press the marker shortcut to jump between.',
    whyItMatters: 'Navigating a song by "drag the playhead until it looks right" is brutal. Markers are the answer.',
    relatedLessons: ['wf-06'],
  },
  {
    id: 'arrangement-track',
    name: 'Arrangement Track',
    definition: 'A specialised track where you define song sections as coloured blocks — drag them around to re-order entire verses or choruses.',
    example: 'Decide the bridge should come before the second chorus? Drag the Bridge block in the Arrangement Track — every track moves with it.',
    whyItMatters: 'The single fastest way to try a different song form. Experiments you’d avoid with regions are one-drag trivial here.',
    relatedLessons: ['wf-06'],
  },

  // --- Microphones --------------------------------------------------
  {
    id: 'microphone',
    name: 'Microphone',
    definition: 'A transducer that converts sound pressure into an electrical signal so it can be recorded.',
    example: 'A Shure SM7B on a vocal, an SM57 on a snare, a large-diaphragm condenser on a piano — each converts air into voltage differently.',
    whyItMatters: 'The mic is step one. No amount of plugin magic can fix a bad mic choice or placement.',
    relatedLessons: ['vocal-01'],
  },
  {
    id: 'pop-filter',
    name: 'Pop Filter',
    definition: 'A mesh screen placed between the singer and the microphone to catch plosives.',
    example: 'The thin black disc you see on every vocal booth photo — that’s the pop filter.',
    whyItMatters: 'Cheap, effective, essential. Fixing a popped "P" in post is tedious; a pop filter makes it a non-issue.',
    relatedLessons: ['vocal-01'],
  },
  {
    id: 'plosive',
    name: 'Plosive',
    definition: 'A low-frequency thump caused by a burst of air hitting the mic on consonants like P and B.',
    example: '"Pop" sung too close to the mic creates a loud thud that takes over the waveform.',
    whyItMatters: 'Plosives ruin otherwise great takes. Pop filter + mic placement off-axis solves 95% of them.',
    relatedLessons: ['vocal-01'],
  },
  {
    id: 'sibilance',
    name: 'Sibilance',
    definition: 'The harsh high-frequency energy in "S" and "Sh" sounds — typically 5–10 kHz.',
    example: 'A singer who hisses noticeably on "sail" or "stay" — that’s sibilance.',
    whyItMatters: 'Modern pop mixes process sibilance heavily with de-essers. Every vocal chain needs to address it.',
    relatedLessons: ['vocal-05'],
  },
  {
    id: 'phantom-power',
    name: 'Phantom Power',
    definition: '+48 volts sent through an XLR cable to power a condenser microphone. Toggled with a switch on your audio interface labelled 48V.',
    example: 'Plug in a condenser mic, flip the 48V switch on your interface, and the mic comes to life.',
    whyItMatters: 'Dynamic mics don’t need it; condensers don’t work without it. Forget to turn it on and you’ll think your mic is dead.',
    relatedLessons: ['vocal-01'],
  },
  {
    id: 'condenser-microphone',
    name: 'Condenser Microphone',
    definition: 'A sensitive mic style favoured for vocals and quiet acoustic sources. Needs phantom power.',
    example: 'A Neumann U87, a Warm WA-47, a Rode NT1 — all condensers.',
    whyItMatters: 'The go-to for lead vocals in modern R&B and gospel because of their detail and air.',
    relatedLessons: ['vocal-01'],
  },
  {
    id: 'dynamic-microphone',
    name: 'Dynamic Microphone',
    definition: 'A rugged mic style that doesn’t need phantom power. Less sensitive than condensers, great for loud or untreated rooms.',
    example: 'A Shure SM7B is a dynamic — famously used on Michael Jackson’s Thriller vocals.',
    whyItMatters: 'If your room isn’t acoustically treated, a dynamic rejects more of the bad room sound than a condenser picks up.',
    relatedLessons: ['vocal-01'],
  },

  // --- Processing: EQ -----------------------------------------------
  {
    id: 'eq',
    name: 'EQ',
    definition: 'Equalisation — turning specific frequency bands up or down to shape the tone of a sound.',
    example: 'Boost 5 kHz on a vocal for presence; cut 250 Hz on an acoustic guitar to remove boxiness.',
    whyItMatters: 'EQ is the most-used tool in any mix. Every track has EQ decisions — intentional or not.',
    relatedLessons: ['lang-02'],
  },
  {
    id: 'parametric-eq',
    name: 'Parametric EQ',
    definition: 'An EQ where you choose the frequency, amount, and width (Q) of each band precisely. The standard modern EQ.',
    example: 'Logic’s Channel EQ is parametric — you can boost 3 kHz by 2 dB with a Q of 1.2 and see the exact curve.',
    whyItMatters: 'Surgical and corrective work needs parametric precision. "That vocal is muddy" requires a specific cut at a specific frequency.',
    relatedLessons: ['lang-02'],
  },
  {
    id: 'shelving-eq',
    name: 'Shelving EQ',
    definition: 'An EQ band that boosts or cuts everything above (high shelf) or below (low shelf) a chosen frequency.',
    example: 'Pull a high shelf at 10 kHz down 2 dB to soften a too-bright vocal.',
    whyItMatters: 'Great for broad tonal moves — warmer, brighter, fatter — in a way bell-shaped parametric cuts can’t match.',
    relatedLessons: ['lang-02'],
  },
  {
    id: 'high-pass-filter',
    name: 'High-pass Filter',
    definition: 'An EQ move that removes everything below a chosen frequency, letting only higher frequencies through.',
    example: 'Put a high-pass at 80 Hz on a vocal to kill rumble and plosive energy without affecting the voice itself.',
    whyItMatters: 'Almost every mix track gets a high-pass. Cleans out bass-region mud that doesn’t belong.',
    relatedLessons: ['lang-02'],
  },
  {
    id: 'low-pass-filter',
    name: 'Low-pass Filter',
    definition: 'An EQ move that removes everything above a chosen frequency, letting only lower frequencies through.',
    example: 'Low-pass a synth pad at 8 kHz to tuck it behind the lead vocal.',
    whyItMatters: 'Classic for making a part feel "darker" or "further back" — a common move in modern R&B pads.',
    relatedLessons: ['lang-02'],
  },
  {
    id: 'q-factor',
    name: 'Q Factor',
    definition: 'The width of an EQ band. High Q = narrow, surgical. Low Q = wide, musical.',
    example: 'Boost 300 Hz with Q=1 (wide, warms the whole track) versus Q=8 (narrow, only hits a specific resonance).',
    whyItMatters: 'Corrective cuts want high Q; musical boosts want low Q. Mixing the two up sounds harsh.',
    relatedLessons: ['lang-02'],
  },

  // --- Processing: Compression --------------------------------------
  {
    id: 'compression',
    name: 'Compression',
    definition: 'A process that turns down loud parts of a signal and leaves quiet parts alone, reducing the range between them.',
    example: 'A vocal that sings from whisper to scream gets compressed so every word sits at roughly the same level.',
    whyItMatters: 'Modern records are heavily compressed. Without it, vocals disappear in quiet sections and distort in loud ones.',
    relatedLessons: ['lang-03', 'vocal-04'],
  },
  {
    id: 'threshold',
    name: 'Threshold',
    definition: 'The level a signal must cross before a compressor starts acting on it.',
    example: 'Set the threshold to -18 dB on a vocal — everything above -18 dB gets compressed, below stays untouched.',
    whyItMatters: 'Threshold decides how often the compressor does anything. Too high = no compression; too low = everything compressed, squashed.',
    relatedLessons: ['lang-03', 'vocal-04'],
  },
  {
    id: 'ratio',
    name: 'Ratio',
    definition: 'How aggressively a compressor reduces signal that crosses the threshold. 4:1 means 4 dB over becomes 1 dB over.',
    example: 'A gentle vocal compressor at 2:1; a drum-bus compressor at 4:1; a limiter at 20:1+.',
    whyItMatters: 'Ratio is the compressor’s personality — subtle evening-out versus aggressive shaping.',
    relatedLessons: ['lang-03', 'vocal-04'],
  },
  {
    id: 'attack',
    name: 'Attack',
    definition: 'How quickly a compressor reacts once the signal crosses the threshold. Measured in milliseconds.',
    example: 'Fast attack (1 ms) grabs transients; slow attack (30 ms) lets the punch through and compresses the sustain.',
    whyItMatters: 'Attack shapes punch. Fast attacks flatten dynamics; slow attacks preserve them. Both are right tools — for different jobs.',
    relatedLessons: ['lang-03'],
  },
  {
    id: 'release',
    name: 'Release',
    definition: 'How quickly a compressor stops compressing once the signal drops back below the threshold.',
    example: 'Fast release can pump; slow release leaves the signal compressed until things settle.',
    whyItMatters: 'Release tuning is half of what makes a compressor "feel musical." Match it to the song’s tempo and you get groove.',
    relatedLessons: ['lang-03'],
  },
  {
    id: 'knee',
    name: 'Knee',
    definition: 'How abrupt the compression onset is as the signal crosses the threshold. Soft knee = gradual; hard knee = sudden.',
    example: 'A vocal compressor with a soft knee feels invisible; a drum-bus compressor with a hard knee hits like a punch.',
    whyItMatters: 'Soft knee for vocals and anything "gentle"; hard knee for attitude and grit.',
    relatedLessons: ['lang-03'],
  },
  {
    id: 'makeup-gain',
    name: 'Makeup Gain',
    definition: 'Volume added after compression to restore the loudness you lost when the compressor pushed peaks down.',
    example: 'Compression reduces a vocal by 4 dB at the peaks; add 4 dB of makeup gain to bring the average level back up.',
    whyItMatters: 'Without makeup gain, compressed tracks sound quieter rather than more-controlled — the move feels like a downgrade.',
    relatedLessons: ['lang-03'],
  },
  {
    id: 'gain-reduction',
    name: 'Gain Reduction',
    definition: 'How many dB the compressor is currently cutting. Read off the GR meter on the plugin.',
    example: 'A vocal compressor showing 3–6 dB GR on the loudest words is doing a healthy amount.',
    whyItMatters: 'The GR meter tells you what the compressor is actually doing — more useful than any knob in diagnosing problems.',
    relatedLessons: ['lang-03'],
  },
  {
    id: 'parallel-compression',
    name: 'Parallel Compression',
    definition: 'Blending a heavily-compressed copy of a track underneath the uncompressed original.',
    example: 'Send drums to a bus, crush them with a compressor, blend 30% of the crushed copy back in — drums feel huge without losing their transients.',
    whyItMatters: 'The secret behind "New York" drum tones and weightier lead vocals. You get the body without flattening the performance.',
    relatedLessons: ['vocal-08'],
  },
  {
    id: 'side-chain',
    name: 'Side-chain',
    definition: 'Telling a compressor to react to a different signal than the one it’s processing. Most famously, ducking the bass every time the kick hits.',
    example: 'Set the compressor on your bass track to side-chain from the kick — every kick hit pulls the bass down briefly, then it rebounds.',
    whyItMatters: 'The defining sound of modern pop, house, and a lot of R&B — the "pump" that gives a mix forward motion.',
    relatedLessons: ['lang-08'],
  },

  // --- Processing: Reverb -------------------------------------------
  {
    id: 'reverb',
    name: 'Reverb',
    definition: 'Simulated room sound — the tail of reflections that tells your ear "this happened in a space."',
    example: 'A dry vocal sounds like it’s in your face; add a plate reverb and it sounds like it’s in a studio booth.',
    whyItMatters: 'Reverb glues sounds together and places them in emotional space. Too much = distant and muddy; none = sterile.',
    relatedLessons: ['lang-04', 'vocal-06'],
  },
  {
    id: 'decay',
    name: 'Decay',
    definition: 'How long a reverb tail lasts before it fades out. Measured in seconds.',
    example: 'A 0.8 s decay is a small room; 2.5 s is a hall; 6 s is a cathedral.',
    whyItMatters: 'Decay decides scale. A ballad loves 2+ second plates; a tight funk groove wants 0.6 s rooms.',
    relatedLessons: ['lang-04', 'vocal-06'],
  },
  {
    id: 'pre-delay',
    name: 'Pre-delay',
    definition: 'The gap between a sound and the start of its reverb tail. Measured in milliseconds.',
    example: 'Pre-delay of 30 ms on a vocal reverb keeps the dry word clear; the reverb blooms after the consonant.',
    whyItMatters: 'The single most underrated reverb control. Adds depth without mud.',
    relatedLessons: ['lang-04', 'vocal-06'],
  },
  {
    id: 'wet-dry',
    name: 'Wet/Dry',
    definition: 'The balance between the processed reverb signal (wet) and the original untreated signal (dry).',
    example: 'A Wet/Dry knob at 20% means 20% reverb, 80% direct sound.',
    whyItMatters: 'On sends you go 100% wet (the dry comes from the original track). On inserts you mix wet + dry in one place.',
    relatedLessons: ['lang-04', 'vocal-06'],
  },
  {
    id: 'chromaverb',
    name: 'ChromaVerb',
    definition: 'Logic Pro’s flagship reverb plugin. Offers room, chamber, plate, and creative algorithms in one interface.',
    example: 'Load ChromaVerb on a vocal send, pick Chamber, tune decay to 1.8 s, pre-delay 25 ms — a classic lead-vocal space.',
    whyItMatters: 'High-quality, low-CPU, always installed. No need to spend money to get a pro vocal reverb in Logic.',
    relatedLessons: ['lang-04', 'vocal-06'],
  },
  {
    id: 'space-designer',
    name: 'Space Designer',
    definition: 'Logic Pro’s convolution reverb — plays your signal through impulse responses captured from real rooms, halls, and hardware.',
    example: 'Load a Sinatra-era studio impulse response into Space Designer for a vintage chamber sound.',
    whyItMatters: 'Convolution gives you character no algorithmic reverb can — real spaces have irregularities that algorithms smooth over.',
    relatedLessons: ['lang-04'],
  },
  {
    id: 'plate-reverb',
    name: 'Plate Reverb',
    definition: 'A reverb style originally made by vibrating a large steel plate with the signal and miking its response. Known for its dense, smooth, bright tail.',
    example: 'Every classic soul and Motown vocal sits in a plate — the shimmering wash behind Aretha and Marvin.',
    whyItMatters: 'The go-to vocal reverb for anything vintage or polished. Modern plate plugins emulate the EMT 140 hardware.',
    relatedLessons: ['lang-04', 'vocal-06'],
  },
  {
    id: 'hall-reverb',
    name: 'Hall Reverb',
    definition: 'A reverb style emulating large concert halls — long decay, pronounced early reflections, a sense of grand space.',
    example: 'Gospel choir stacks and orchestral productions live in halls.',
    whyItMatters: 'For ballads and epic moments, a hall makes things feel important. Overused on close-mic’d R&B it just sounds "far away."',
    relatedLessons: ['lang-04', 'vocal-06'],
  },
  {
    id: 'convolution',
    name: 'Convolution',
    definition: 'A technique that applies the acoustic signature of a real space (an impulse response) to your audio.',
    example: 'Convolution reverbs turn your track into "how it would sound inside Abbey Road Studio 2."',
    whyItMatters: 'Where algorithmic reverb approximates, convolution copies. The difference is audible on lead vocals and acoustic sources.',
    relatedLessons: ['lang-04'],
  },
  {
    id: 'send',
    name: 'Send',
    definition: 'Routing a copy of a track’s signal to a separate auxiliary destination, typically for a shared reverb or delay.',
    example: 'Send your lead vocal, BGVs, and snare to one "Verb A" bus — they share the same reverb and feel like the same space.',
    whyItMatters: 'Sends are how you glue a mix. One reverb on five sources uses less CPU and sounds more cohesive than five separate reverbs.',
    relatedLessons: ['lang-04', 'vocal-06'],
  },

  // --- Processing: Delay + Saturation -------------------------------
  {
    id: 'delay',
    name: 'Delay',
    definition: 'An effect that plays back a copy of the signal after a chosen time, creating echoes.',
    example: 'A dotted-eighth delay on a vocal "ooh" creates a rhythmic ping that plays against the main groove.',
    whyItMatters: 'Delay carves space differently from reverb — rhythmic, intentional. Every modern R&B hook has delay on something.',
    relatedLessons: ['lang-05'],
  },
  {
    id: 'feedback',
    name: 'Feedback',
    definition: 'The number of echoes a delay repeats before fading out. Higher feedback = more repeats.',
    example: 'Feedback at 25% = three clear echoes; at 70% = the echo stacks into a washy cloud.',
    whyItMatters: 'Feedback is where delay goes from a subtle nudge to a psychedelic signature.',
    relatedLessons: ['lang-05'],
  },
  {
    id: 'slapback',
    name: 'Slapback',
    definition: 'A short, single delay (typically 80–150 ms) with no feedback — one quick echo that thickens the source.',
    example: 'Elvis’ vocals, rockabilly guitars, some Kirk Franklin adlibs — all lean on slapback.',
    whyItMatters: 'A classic vintage sound. Doubles a vocal without the phase issues of actual doubling.',
    relatedLessons: ['lang-05'],
  },
  {
    id: 'tape-delay',
    name: 'Tape Delay',
    definition: 'A delay emulation of old tape-based units. Characterised by warm saturation, pitch wobble, and high-frequency roll-off on each repeat.',
    example: 'Use a tape delay on a lead vocal hook — the repeats get darker and more analogue as they fade.',
    whyItMatters: 'The sound of decades of soul, dub, and hip-hop. Digital delays can sound sterile; tape delay is instant character.',
    relatedLessons: ['lang-05'],
  },
  {
    id: 'stereo-delay',
    name: 'Stereo Delay',
    definition: 'A delay that outputs different echoes to the left and right speakers.',
    example: 'Left delayed 3/8 note, right delayed 1/4 note — a vocal ad-lib bounces around the room.',
    whyItMatters: 'Creates motion and width without making the mix feel cluttered in the centre.',
    relatedLessons: ['lang-05'],
  },
  {
    id: 'saturation',
    name: 'Saturation',
    definition: 'Gentle distortion that adds harmonic complexity to a signal — the "warmth" engineers chase.',
    example: 'Run a clean bass DI through a tape saturation plugin — the tone thickens and the level feels more solid.',
    whyItMatters: 'Digital recordings can feel sterile. Saturation is the difference between "recorded" and "sounds like a record."',
    relatedLessons: ['lang-07'],
  },
  {
    id: 'distortion',
    name: 'Distortion',
    definition: 'A stronger cousin of saturation — clipping that creates obvious harmonic colour and texture.',
    example: 'A subtly distorted drum bus on a hip-hop record; obvious guitar distortion on a rock track.',
    whyItMatters: 'Distortion used in small amounts on drums and bass is one of the defining sounds of modern rap and R&B.',
    relatedLessons: ['lang-07'],
  },
  {
    id: 'tape-saturation',
    name: 'Tape Saturation',
    definition: 'Saturation that emulates the soft compression and harmonic character of analogue tape.',
    example: 'J Dilla’s drums sit in a halo of tape saturation — softer transients, warmer tone.',
    whyItMatters: 'Every track on a Motown record was on tape. Emulating that softens modern plugins’ edges.',
    relatedLessons: ['lang-07'],
  },
  {
    id: 'tube-saturation',
    name: 'Tube Saturation',
    definition: 'Saturation emulating vacuum-tube amplifiers. Adds even-order harmonics — musical, smooth, pleasing.',
    example: 'Tube saturation on a lead vocal adds "presence" without EQ — the vocal sits forward, feels rounder.',
    whyItMatters: 'Tube character is why vintage gear is prized. Software emulations are now excellent.',
    relatedLessons: ['lang-07'],
  },

  // --- Mixing -------------------------------------------------------
  {
    id: 'gain-staging',
    name: 'Gain Staging',
    definition: 'Managing the volume level of a signal at every stage of the chain so nothing clips, distorts, or falls too quiet.',
    example: 'Recording at -18 dBFS average, keeping inserts from clipping, leaving -6 dB headroom on the master.',
    whyItMatters: 'Boring but fundamental. Bad gain staging is why "my mix sounds muddy" — everything’s overloaded.',
    relatedLessons: ['lang-06'],
  },
  {
    id: 'headroom',
    name: 'Headroom',
    definition: 'The space between the loudest peak in your mix and 0 dBFS (where digital clipping happens).',
    example: 'If your loudest moment peaks at -6 dBFS, you have 6 dB of headroom.',
    whyItMatters: 'Mastering engineers want headroom to work with. A mix clipping into the master is already cooked.',
    relatedLessons: ['lang-06'],
  },
  {
    id: 'clipping',
    name: 'Clipping',
    definition: 'When a signal exceeds the maximum digital level. The waveform gets cut off at the ceiling, producing harsh distortion.',
    example: 'Red lights on your meters mean clipping. Back off.',
    whyItMatters: 'Digital clipping sounds bad — nothing like the pleasant tape saturation you get when analogue gear overloads.',
    relatedLessons: ['lang-06'],
  },
  {
    id: 'clip-gain',
    name: 'Clip Gain',
    definition: 'Volume automation applied directly to a region — the gain handle at the top of an audio clip that you can drag.',
    example: 'One word of a vocal take is too loud; pull its clip gain down 3 dB instead of automating the whole fader.',
    whyItMatters: 'Surgical. Fixes dynamic inconsistencies before the compressor has to, giving the compressor less work to do.',
    relatedLessons: ['lang-06'],
  },
  {
    id: 'master-fader',
    name: 'Master Fader',
    definition: 'The single fader controlling the overall output level of your mix.',
    example: 'The rightmost fader in the Mixer window — when you pull it down, the whole song gets quieter.',
    whyItMatters: 'Never push the master fader hard to compensate for a quiet mix. Fix the mix; leave the master near 0.',
    relatedLessons: ['lang-06'],
  },
  {
    id: 'mix-bus',
    name: 'Mix Bus',
    definition: 'The signal path where all your tracks are summed together — typically the Stereo Out in Logic.',
    example: 'A 2-bus compressor glues the whole mix together; EQ on the mix bus shapes the final tone.',
    whyItMatters: 'Mix-bus processing is the final 5% that makes a mix feel cohesive and commercial.',
    relatedLessons: ['lang-06'],
  },
  {
    id: 'auxiliary-track',
    name: 'Auxiliary Track',
    definition: 'A track that doesn’t record audio itself — it sums signals sent to it for processing (reverb, delay, parallel compression, etc.).',
    example: 'Create an Aux, insert ChromaVerb on it, send your lead vocal there — that Aux is your vocal-reverb bus.',
    whyItMatters: 'The foundation of send-based effects and grouped processing. Indispensable once you have more than five tracks.',
    relatedLessons: ['lang-04', 'vocal-06'],
  },
  {
    id: 'pan',
    name: 'Pan',
    definition: 'The left/right position of a track in the stereo field.',
    example: 'Center the kick and lead vocal. Hard-left the rhythm guitar. Hard-right the shaker. Everything else spread across.',
    whyItMatters: 'Pan is free real estate. Two instruments fighting in mono stop fighting when you pan them apart.',
    relatedLessons: ['lang-06', 'vocal-07'],
  },
  {
    id: 'stereo-field',
    name: 'Stereo Field',
    definition: 'The panoramic space between your left and right speakers.',
    example: 'A mix with a wide stereo field feels big and immersive; a narrow one feels small and intimate.',
    whyItMatters: 'How you place elements in the stereo field shapes perceived scale — ballads want less width, dance tracks want more.',
    relatedLessons: ['lang-06'],
  },
  {
    id: 'automation',
    name: 'Automation',
    definition: 'Recorded movements of any mix parameter over time — faders, pan, plugin knobs.',
    example: 'Ride the vocal fader up 1 dB for the chorus, automating the move so it happens every pass.',
    whyItMatters: 'Static mixes feel lifeless. Automation is the craft of modern mixing — small moves in the right places.',
    relatedLessons: ['lang-06'],
  },

  // --- Vocal-specific -----------------------------------------------
  {
    id: 'de-esser',
    name: 'De-esser',
    definition: 'A specialised compressor that only reduces high-frequency sibilance — the "S" and "Sh" energy that sticks out.',
    example: 'A de-esser triggered at 7 kHz reduces sibilance by 3 dB on the offending consonants only.',
    whyItMatters: 'Without de-essing, modern vocal processing (especially bright EQ + compression) makes every S into an ice-pick.',
    relatedLessons: ['vocal-05'],
  },
  {
    id: 'flex-pitch',
    name: 'Flex Pitch',
    definition: 'Logic Pro’s built-in pitch correction editor. Analyses an audio vocal, lets you nudge individual notes up or down, adjust vibrato, and reshape the performance.',
    example: 'A singer’s third line lands 40 cents flat; Flex Pitch lets you drag that note up to exactly in-tune.',
    whyItMatters: 'Tuning is standard modern practice. Done well, it’s invisible; done heavy-handed, it sounds robotic. Flex Pitch supports both.',
    relatedLessons: ['vocal-03'],
  },
  {
    id: 'pitch-correction',
    name: 'Pitch Correction',
    definition: 'The general category of tools (Flex Pitch, Melodyne, Auto-Tune) that nudge off-pitch performances closer to correct notes.',
    example: 'Tuning a soul ballad subtly for polish; tuning a trap hook heavy-handed for the Auto-Tune effect.',
    whyItMatters: 'Almost every pop / R&B / gospel vocal on a release is pitch-corrected. The question is always "how much."',
    relatedLessons: ['vocal-03'],
  },
  {
    id: 'cents',
    name: 'Cents',
    definition: 'A unit of pitch — 1 semitone = 100 cents. Used for fine pitch adjustments below the note level.',
    example: 'A singer’s "Yeah" lands 20 cents sharp; Flex Pitch pulls it down 20 cents to sit exactly on the note.',
    whyItMatters: 'Modern tuning lives in cents, not semitones. Small cent moves preserve a singer’s character.',
    relatedLessons: ['vocal-03'],
  },
  {
    id: 'semitone',
    name: 'Semitone',
    definition: 'A half-step — the distance from one key on the piano to the next, including black keys.',
    example: 'C to C# is a semitone; E to F is also a semitone.',
    whyItMatters: 'Transposing by one semitone up often makes a performance feel brighter; down often darker and warmer.',
    relatedLessons: ['vocal-03'],
  },
  {
    id: 'formant',
    name: 'Formant',
    definition: 'The harmonic resonances of the vocal tract that make a voice sound like a specific person.',
    example: 'Shift formants up and a deep voice becomes a chipmunk; shift down and a bright voice becomes dark — even at the same pitch.',
    whyItMatters: 'Pitch-correction plugins can shift formants independently. Keep them natural and heavy tuning stays invisible.',
    relatedLessons: ['vocal-03'],
  },
  {
    id: 'new-york-compression',
    name: 'New York Compression',
    definition: 'A slang term for parallel compression applied to vocals or drums — blending a heavily-compressed duplicate under the dry original.',
    example: 'Lead vocal on its own fader; a buried, crushed parallel copy adds weight without flattening dynamics.',
    whyItMatters: 'The trick behind tracks that feel dense and controlled without sounding obviously compressed.',
    relatedLessons: ['vocal-08'],
  },
  {
    id: 'background-vocals',
    name: 'Background Vocals (BGVs)',
    definition: 'The harmony and texture vocals that support the lead — typically stacked, panned wide, and mixed softer than the lead.',
    example: 'Classic Boyz II Men choruses are dense BGV stacks; gospel choir productions are layered BGVs on steroids.',
    whyItMatters: 'BGVs are how a mix feels big. The lead is the soloist; the BGVs are the building.',
    relatedLessons: ['vocal-07'],
  },
  {
    id: 'bgv',
    name: 'BGV',
    definition: 'Abbreviation for Background Vocal — used interchangeably with "BGV stack" or "background vocal track."',
    example: 'Engineer to producer: "Send me the lead, the BGV stack, and the ad-libs stems."',
    whyItMatters: 'Studio shorthand. Learn the abbreviations and your sessions move faster.',
    relatedLessons: ['vocal-07'],
  },
  {
    id: 'stacking',
    name: 'Stacking',
    definition: 'Recording the same vocal line (or harmony) multiple times on separate tracks and layering them.',
    example: 'Stack three unison takes of a chorus vocal, pan them at 10-o’clock, center, and 2-o’clock for a solid "wall."',
    whyItMatters: 'The fundamental BGV technique. Two is sparse, three is solid, five+ is a choir.',
    relatedLessons: ['vocal-07'],
  },
  {
    id: 'double',
    name: 'Double',
    definition: 'A second performance of a part recorded to thicken it — typically panned against the original or layered in unison.',
    example: 'Lead vocal + one unison "double" makes the lead feel fuller without being as dense as full BGV stacks.',
    whyItMatters: 'A lightweight thickening trick. Double the chorus vocal, not the verse, and you get a natural "lift" at the hook.',
    relatedLessons: ['vocal-07'],
  },

  // --- Files / formats / bouncing -----------------------------------
  {
    id: 'wav',
    name: 'WAV',
    definition: 'An uncompressed audio file format — preserves every bit of the original recording.',
    example: 'Bounce your mix as a 24-bit, 44.1 kHz WAV to send to mastering.',
    whyItMatters: 'Mastering, collaboration, archive — always WAV. MP3 is for listening, not working.',
    relatedLessons: ['wf-08'],
  },
  {
    id: 'mp3',
    name: 'MP3',
    definition: 'A compressed audio file format — smaller file size at the cost of some high-frequency detail.',
    example: 'Export a 320 kbps MP3 of a rough mix to share with a collaborator over text.',
    whyItMatters: 'Great for sharing rough mixes, wrong for final delivery. Never master from an MP3.',
    relatedLessons: ['wf-08'],
  },
  {
    id: 'sample-rate',
    name: 'Sample Rate',
    definition: 'How many times per second digital audio samples the analogue signal. Measured in kHz.',
    example: '44.1 kHz is CD-quality; 48 kHz is video-standard; 96 kHz is high-resolution.',
    whyItMatters: 'Match your project to your final format. Mismatches cause subtle quality loss in conversion.',
    relatedLessons: ['wf-08'],
  },
  {
    id: 'bit-depth',
    name: 'Bit Depth',
    definition: 'How many bits represent each audio sample. Higher bit depth = more dynamic range.',
    example: '16-bit is CD-quality; 24-bit is modern studio standard; 32-bit float is "no clipping possible" territory.',
    whyItMatters: 'Record and mix at 24-bit. Export final masters at whatever the platform requires — usually 16-bit for streaming.',
    relatedLessons: ['wf-08'],
  },
  {
    id: 'bounce',
    name: 'Bounce',
    definition: 'Exporting a mix or part of a mix from Logic as a new audio file.',
    example: 'File → Bounce → Project or Section creates a WAV of your song.',
    whyItMatters: 'Bouncing is the step that turns a Logic session into a shareable, listenable file.',
    relatedLessons: ['wf-08'],
  },
  {
    id: 'bounce-in-place',
    name: 'Bounce in Place',
    definition: 'Bouncing a single track (including its plugins) to a new audio file inside the same project.',
    example: 'Bounce a synth patch with its effects to free up CPU — the audio file now replaces the live plugin chain.',
    whyItMatters: 'Performance and permanence. Once a synth sound is locked in, bounce in place and stop worrying about it.',
    relatedLessons: ['wf-08'],
  },
  {
    id: 'stem',
    name: 'Stem',
    definition: 'A bounce of a grouped element (all drums, all BGVs, etc.) that contains processing but is separate from the rest of the mix.',
    example: 'Deliver a drum stem, a bass stem, a vocal stem, and a music-bed stem for remix collaboration.',
    whyItMatters: 'Stems are the standard handoff format for remixing, mastering alternates, and collaboration.',
    relatedLessons: ['wf-08'],
  },

  // --- Phase 2: Arrangement / song structure --------------------------
  {
    id: 'intro',
    name: 'Intro',
    definition: 'The opening section of a song before the first verse. Sets the mood, establishes the key, and invites the listener in.',
    example: 'The gentle acoustic guitar that opens "End of the Road" before the vocals arrive is the intro.',
    whyItMatters: 'The intro is your first impression. In a streaming era where listeners skip in seconds, a good intro buys attention.',
    relatedLessons: ['arr-01', 'arr-02'],
  },
  {
    id: 'verse',
    name: 'Verse',
    definition: 'The storytelling section of a song — lyrics advance, melody usually repeats across different verses. Builds context for the chorus.',
    example: 'The verses of "Superstition" each carry different lyrics but sit on the same groove and melodic shape.',
    whyItMatters: 'Verses carry the narrative; weak verses mean listeners never reach the chorus. Verse and chorus must sound different enough that the arrival of the chorus feels like a release.',
    relatedLessons: ['arr-01', 'arr-02'],
  },
  {
    id: 'pre-chorus',
    name: 'Pre-chorus',
    definition: 'A short transitional section between verse and chorus that builds tension and makes the chorus feel earned.',
    example: 'The "and I know, and I know" build in countless 80s and 90s ballads is a pre-chorus.',
    whyItMatters: "Without a pre-chorus, many songs arrive at the chorus too suddenly. The pre-chorus is where dynamics climb — often the producer's secret tool for emotional lift.",
    relatedLessons: ['arr-01', 'arr-02'],
  },
  {
    id: 'chorus',
    name: 'Chorus',
    definition: 'The repeating hook section — usually the most memorable, most emotional, most singable part of the song. The lyric often contains the title.',
    example: 'The "I will always love you" line and its surrounding section is the chorus of Whitney\'s song.',
    whyItMatters: "The chorus is where most listeners decide whether they love a song. Every arrangement decision in verse and pre-chorus exists to make this moment land.",
    relatedLessons: ['arr-01', 'arr-02'],
  },
  {
    id: 'bridge',
    name: 'Bridge',
    definition: 'A contrasting section that appears once, usually late in the song, offering harmonic or emotional departure before returning to the final chorus.',
    example: 'The "I love you, I honestly love you" section of Olivia Newton-John\'s classic is a textbook bridge.',
    whyItMatters: 'The bridge prevents the song from feeling repetitive by the third chorus. Good bridges reframe the song — the final chorus hits differently because of them.',
    relatedLessons: ['arr-01'],
  },
  {
    id: 'outro',
    name: 'Outro',
    definition: 'The closing section. Can be an instrumental fade, a final vamp, or a brief musical coda.',
    example: 'The repeated "we\'ll be together" vamp at the end of many R&B songs is an outro.',
    whyItMatters: 'The outro controls how the song leaves the listener. Long ad-lib vamps build emotional residue; quick outros create cleaner transitions between tracks.',
    relatedLessons: ['arr-01'],
  },
  {
    id: 'aaba',
    name: 'AABA',
    definition: 'A classic 32-bar song form where three similar sections (A) bracket a contrasting middle (B). Common in jazz standards and early pop.',
    example: '"Somewhere Over the Rainbow" is AABA — two verses, a bridge, a final verse.',
    whyItMatters: "Understanding AABA is understanding where modern song forms came from. Many R&B ballads are descendants of this structure.",
    relatedLessons: ['arr-01'],
  },
  {
    id: 'song-form',
    name: 'Song Form',
    definition: 'The overall architecture of a song — which sections appear, in what order, and how many times. E.g., verse-chorus-verse-chorus-bridge-chorus.',
    example: 'Most pop songs today follow verse-chorus-verse-chorus-bridge-chorus (V-C-V-C-B-C).',
    whyItMatters: 'Form is the skeleton underneath the notes. Learning the common forms gives you a toolkit for shaping any rough idea into a finished song.',
    relatedLessons: ['arr-01', 'arr-02'],
  },
  {
    id: 'hook',
    name: 'Hook',
    definition: 'The catchiest, most memorable piece of the song — typically a vocal melody, instrumental riff, or rhythmic figure the listener carries away.',
    example: 'The "can you feel the love tonight" phrase is the hook of that song.',
    whyItMatters: 'The hook is why a song sticks. Strong hooks are simple enough to hum after one listen but varied enough to withstand dozens.',
    relatedLessons: ['arr-04'],
  },
  {
    id: 'earworm',
    name: 'Earworm',
    definition: 'A short piece of melody or lyric that repeats in your head after you stop listening. The strongest form of a hook.',
    example: 'The whistle line in "Pumped Up Kicks" is an earworm — it plays in your head whether you want it to or not.',
    whyItMatters: "Earworms are what separate forgettable songs from hits. A producer's job includes making sure something in the track becomes one.",
    relatedLessons: ['arr-04'],
  },
  {
    id: 'call-and-response',
    name: 'Call and Response',
    definition: 'A musical conversation where one voice or instrument poses a phrase and another answers it. Rooted in gospel, blues, and African tradition.',
    example: 'Gospel choirs trading lines with a lead vocalist — or Destiny\'s Child trading "say my name, say my name" between members.',
    whyItMatters: "Call and response keeps arrangements dynamic. It's also the single most effective way to make a one-singer song feel like a community.",
    relatedLessons: ['gen-02a', 'gen-10a'],
  },
  {
    id: 'syncopation',
    name: 'Syncopation',
    definition: 'Emphasis placed on the "off" beats (the ands, the weak parts of the bar) rather than the expected downbeats. Creates rhythmic interest and groove.',
    example: "A snare on the '2-and' instead of the '2' is syncopated. Most gospel, funk, and R&B lives on syncopation.",
    whyItMatters: "Syncopation is what makes a beat groove instead of march. Understanding it unlocks how gospel, neo-soul, and hip-hop drums feel human.",
    relatedLessons: ['arr-03'],
  },
  {
    id: 'arrangement',
    name: 'Arrangement',
    definition: 'The set of decisions about which instruments play what, when, at what volume — the sonic architecture of a song.',
    example: 'A song with just piano and voice in the first verse that adds drums at the chorus has an arrangement that builds.',
    whyItMatters: "Arrangement is where emotional storytelling happens before any effect is applied. Even a perfect mix can't save a bad arrangement.",
    relatedLessons: ['arr-01', 'arr-05'],
  },
  {
    id: 'section',
    name: 'Section',
    definition: 'A distinct portion of a song (verse, chorus, etc.) with consistent arrangement and feel. Sections transition into each other to shape the overall arc.',
    example: 'A 16-bar verse, an 8-bar pre-chorus, and a 16-bar chorus are three sections.',
    whyItMatters: 'Thinking in sections rather than bars helps you plan arrangements; each section is a design choice about what should change and what should stay.',
    relatedLessons: ['arr-01'],
  },
  {
    id: 'transition',
    name: 'Transition',
    definition: "The bar or two where the song moves from one section to another. Often contains a drum fill, a vocal riff, a reverse cymbal, or a harmonic move.",
    example: 'The drop before the first chorus of most pop songs — where the beat cuts or a reverse swell rises — is a transition.',
    whyItMatters: 'Transitions signal to the listener that something is about to change. Done well, they create anticipation; done poorly, they jar.',
    relatedLessons: ['arr-01'],
  },
  {
    id: 'emotional-arc',
    name: 'Emotional Arc',
    definition: 'The rise and fall of feeling across a song — from quiet beginning through peaks and valleys to the end. Arrangement choices shape the arc.',
    example: 'Whitney\'s "I Will Always Love You" builds from a nearly a cappella intro to a full orchestral chorus, then returns to quiet — a classic emotional arc.',
    whyItMatters: "A song without emotional arc feels static. Every great production decision — arrangement, dynamics, instrumentation — serves the arc.",
    relatedLessons: ['arr-01', 'arr-05'],
  },
  {
    id: 'drum-fill',
    name: 'Drum Fill',
    definition: 'A short rhythmic flourish played on the drums — usually on toms or snare — that marks the transition between sections.',
    example: 'The classic "ba-da-ba-dum" snare roll into a chorus is a drum fill.',
    whyItMatters: 'Fills are the drummer\'s punctuation marks. Programmed or played, they tell the listener "new section coming." Without them, transitions feel flat.',
    relatedLessons: ['arr-03'],
  },
  {
    id: 'vamp',
    name: 'Vamp',
    definition: 'A short repeating section — usually one or two chords — that loops at the end of a song or between sections while a lead improvises.',
    example: 'The "I just wanna praise you" outro of many gospel songs is a vamp.',
    whyItMatters: 'Vamps are gospel and soul\'s climax mechanism. They let the lead and choir go places no written chorus can, because the bed just keeps going.',
    relatedLessons: ['gen-02a'],
  },
  {
    id: 'half-time',
    name: 'Half-time',
    definition: 'A rhythmic feel where the snare lands on beat 3 instead of beats 2 and 4, making the track feel twice as slow even though the tempo is unchanged.',
    example: 'Many trap and modern R&B choruses drop into half-time — the tempo stays, but the groove expands.',
    whyItMatters: 'Half-time flips the emotional weight of a section without changing tempo. It\'s a favorite trick in modern hip-hop and trap-R&B.',
    relatedLessons: ['arr-03', 'gen-08a'],
  },
  {
    id: 'time-signature',
    name: 'Time Signature',
    definition: 'The pair of numbers (e.g., 4/4, 6/8, 3/4) that tells you how many beats are in each bar and what note value gets the beat.',
    example: '4/4 means four quarter notes per bar; 6/8 means six eighth notes per bar with a triplet feel.',
    whyItMatters: 'Time signature is the grid every musical decision sits on. Feeling the difference between 4/4 and 6/8 unlocks whole genres.',
    relatedLessons: ['arr-03', 'gen-01a'],
  },
  {
    id: 'six-eight',
    name: '6/8',
    definition: "A time signature of six eighth notes per bar, felt as two groups of three. Creates the 'rolling' or 'swaying' feel of most church ballads and gospel worship songs.",
    example: '"Amazing Grace," "House of the Rising Sun," and most gospel ballads live in 6/8.',
    whyItMatters: 'The 6/8 feel is the heart of church-beat gospel and pop ballads. It swings, lilts, and lifts in a way that straight 4/4 can\'t.',
    relatedLessons: ['gen-01a', 'gen-01b'],
  },
  {
    id: 'triplet',
    name: 'Triplet',
    definition: 'Three notes played in the space normally occupied by two. Gives the rhythm a rolling, swung feel.',
    example: 'The hi-hat pattern in most modern trap is built on triplet subdivisions.',
    whyItMatters: 'Triplets are the rhythmic DNA of 6/8, swing jazz, and modern trap. Programming them naturally is key to genres outside straight 4/4.',
    relatedLessons: ['gen-01a', 'gen-08a'],
  },

  // --- Phase 2: Drum terms -------------------------------------------
  {
    id: 'kick',
    name: 'Kick',
    definition: 'The low drum that provides the "thump" — usually on beats 1 and 3 in pop and R&B, more complex in modern hip-hop.',
    example: 'The low thud at the start of most bars in almost any modern song is the kick.',
    whyItMatters: 'The kick anchors the low end of the mix and defines the groove\'s pulse. A weak kick makes a track feel weightless; a sloppy kick makes it feel drunk.',
    relatedLessons: ['arr-03'],
  },
  {
    id: 'snare',
    name: 'Snare',
    definition: 'The sharp, cracking drum usually on beats 2 and 4 that carries the backbeat. The emotional center of a rock, pop, or R&B groove.',
    example: 'The "clap" you feel on 2 and 4 in almost any pop song is the snare (or a clap layered on top of one).',
    whyItMatters: "The snare is what makes people nod their heads. Its tone (crack, thump, fat, thin) changes the entire character of the track.",
    relatedLessons: ['arr-03'],
  },
  {
    id: 'hi-hat',
    name: 'Hi-hat',
    definition: 'The pair of cymbals that play the quick "ts-ts-ts" pattern between kick and snare, dictating the song\'s rhythmic subdivision.',
    example: 'The rapid-fire 16th or 32nd note hi-hats in trap drive the song\'s urgency.',
    whyItMatters: 'Hi-hats tell the ear what tempo the groove is operating at. Their pattern — straight, swung, stuttering — defines the subgenre.',
    relatedLessons: ['arr-03'],
  },
  {
    id: 'ghost-note',
    name: 'Ghost Note',
    definition: "A very quiet drum hit — usually on the snare — that you don't consciously hear but makes the groove feel human.",
    example: "Listen carefully between the main snare hits in D'Angelo's grooves; the snare is constantly whispering ghost notes.",
    whyItMatters: 'Ghost notes separate programmed drums from feel-real drums. They\'re the difference between a beat that sounds "right" and a groove that breathes.',
    relatedLessons: ['arr-03', 'gen-11a'],
  },
  {
    id: 'swing',
    name: 'Swing',
    definition: 'A rhythmic feel where every pair of notes is uneven — first note longer, second shorter — creating a skipping or lilting motion.',
    example: 'Jazz drumming is swung; J Dilla\'s beats are subtly swung; 4-on-the-floor disco is straight.',
    whyItMatters: 'Amount of swing is one of the most powerful knobs in modern DAW drum programming. Even 8-16% swing transforms a rigid beat into a groove.',
    relatedLessons: ['arr-03', 'gen-11a'],
  },
  {
    id: 'pocket',
    name: 'Pocket',
    definition: 'The precise, feel-based place where the drummer sits relative to the beat. Behind, on top, or ahead — each creates a different emotional feel.',
    example: "D'Angelo's drummers famously sit behind the beat, creating his lazy, sensual groove. Motown drummers sit right on top.",
    whyItMatters: 'Pocket is the soul of a groove. Tempo is the what; pocket is the how. Locking into someone else\'s pocket is the highest band skill.',
    relatedLessons: ['arr-03', 'gen-11a'],
  },

  // --- Phase 2: Genre-specific instrumentation -----------------------
  {
    id: 'rhodes',
    name: 'Rhodes',
    definition: "A classic electric piano with a warm, bell-like tone. The Fender Rhodes is the dominant keyboard sound of 70s soul, neo-soul, and modern R&B.",
    example: "D'Angelo's Voodoo is built around the Rhodes; Jordan Evans uses it all over Daniel Caesar records.",
    whyItMatters: "The Rhodes instantly signals warmth, jazz-influence, and intimacy. It's a shortcut to a whole family of genres' emotional palette.",
    relatedLessons: ['gen-06a', 'gen-11a'],
  },
  {
    id: 'electric-piano',
    name: 'Electric Piano',
    definition: 'Any keyboard designed to emulate an acoustic piano through electronic means — Rhodes, Wurlitzer, CP-70, and digital emulations.',
    example: 'The opening of Daniel Caesar\'s "Get You" is a Wurlitzer-style electric piano.',
    whyItMatters: "Electric pianos sit in a softer, warmer frequency range than acoustic pianos — easier to mix under vocals. Every R&B producer has a go-to.",
    relatedLessons: ['gen-06a'],
  },
  {
    id: 'dx7',
    name: 'DX7',
    definition: 'The Yamaha DX7 — a 1983 FM synthesizer whose bell-like "E.Piano 1" patch dominated 80s pop ballads.',
    example: 'The keyboard on Whitney Houston\'s "Saving All My Love" is the DX7\'s signature electric piano sound.',
    whyItMatters: 'The DX7 is the single most recognizable 80s keyboard. Any era-authentic pop ballad production uses it (or emulates it).',
    relatedLessons: ['gen-07a'],
  },
  {
    id: 'fm-synthesis',
    name: 'FM Synthesis',
    definition: 'A synthesis method (frequency modulation) that creates complex, often metallic or bell-like tones by modulating one oscillator with another.',
    example: 'The DX7 uses FM. Modern software like Operator (Ableton) and FM8 (Native Instruments) continue the tradition.',
    whyItMatters: 'FM creates tones subtractive synths can\'t: bells, brass, electric pianos, percussive attacks. Understanding FM opens up whole sonic palettes.',
    relatedLessons: ['gen-07a'],
  },
  {
    id: 'chorus-effect',
    name: 'Chorus Effect',
    definition: 'A modulation effect that creates a shimmering, wider sound by duplicating the signal and slightly detuning the copy.',
    example: 'The guitars on almost every 80s pop ballad are drenched in chorus — it\'s why they sound "wide" and "shimmery."',
    whyItMatters: 'Chorus is an instant stereo-widener and era signifier. On a mono guitar it adds width; on synths it adds shimmer.',
    relatedLessons: ['gen-07a'],
  },
  {
    id: 'string-pad',
    name: 'String Pad',
    definition: 'A sustained synthetic or sampled strings sound used to fill harmonic space behind a vocal or groove.',
    example: 'The lush backing in most 80s power ballads and modern gospel songs is a string pad.',
    whyItMatters: 'String pads are the easiest way to add emotional weight without cluttering the mix. They sit behind everything, quietly adding glue.',
    relatedLessons: ['gen-07a', 'gen-02a'],
  },
  {
    id: 'walking-bass',
    name: 'Walking Bass',
    definition: 'A bass line that plays a steady quarter-note or eighth-note pattern moving through scale tones — walking from chord to chord.',
    example: 'Classic jazz trio bass lines, but also Motown hits like "I Want You Back" — all walking.',
    whyItMatters: 'Walking bass connects chords melodically instead of just harmonically. It\'s the backbone of jazz, soul, and many Motown grooves.',
    relatedLessons: ['gen-10a'],
  },
  {
    id: 'gated-reverb',
    name: 'Gated Reverb',
    definition: 'A reverb effect that cuts off abruptly instead of fading naturally. The signature 80s "huge" snare sound.',
    example: 'The snare on Phil Collins\' "In the Air Tonight" — huge, then suddenly silent — is gated reverb.',
    whyItMatters: 'Gated reverb is the most era-specific drum effect in pop history. Use it to make a drum sound instantly 80s.',
    relatedLessons: ['gen-07a'],
  },
  {
    id: 'vinyl-effect',
    name: 'Vinyl Effect',
    definition: "A processing chain that adds warmth, slight wow-and-flutter, crackle, and a limited frequency range to give audio a 'played off a record' feel.",
    example: 'Most lo-fi hip-hop tracks run the whole beat through a vinyl emulator.',
    whyItMatters: 'Vinyl effect is a signifier — it says "analog," "vintage," "imperfect." Used right, it adds character; overused, it becomes a crutch.',
    relatedLessons: ['gen-05a'],
  },
  {
    id: 'sampling',
    name: 'Sampling',
    definition: 'Taking a piece of a pre-existing recording and using it as an element in a new production — a loop, a chop, a texture.',
    example: "J Dilla's beats are built from sample chops; Kanye's early Roc-A-Fella work was dominated by soul samples.",
    whyItMatters: 'Sampling is the foundation of hip-hop, much of R&B, and most lo-fi. Understanding it — both creatively and legally — is essential.',
    relatedLessons: ['gen-05a', 'gen-11a', 'biz-03'],
  },
  {
    id: 'sample-chop',
    name: 'Sample Chop',
    definition: 'A technique where a sampled phrase is cut into small pieces and rearranged to create a new melody or groove.',
    example: "The chopped-up soul vocal flips on Kanye's early work are sample chops.",
    whyItMatters: 'Sample chopping turns existing recordings into raw material for something new. It\'s a production craft in itself.',
    relatedLessons: ['gen-05a'],
  },
  {
    id: 'vocal-chop',
    name: 'Vocal Chop',
    definition: 'A short, pitched vocal phrase — often a syllable or two — looped or rearranged as a melodic hook.',
    example: 'The high-pitched "oh oh oh" hook on many modern pop/EDM tracks is a vocal chop.',
    whyItMatters: 'Vocal chops give tracks a hook that feels human without requiring a full vocal performance. A modern production essential.',
    relatedLessons: ['gen-05a'],
  },
  {
    id: 'dusty',
    name: 'Dusty',
    definition: 'An aesthetic term for an intentionally imperfect, crackly, vintage-sounding production — like it was found on an old 45.',
    example: 'The Alchemist\'s beats are often described as dusty — they sound like they were recorded through a dusty old mic in a basement.',
    whyItMatters: "Dusty is the opposite of pristine. In lo-fi hip-hop and neo-soul, dust is beautiful because it signals humanity and history.",
    relatedLessons: ['gen-05a'],
  },
  {
    id: 'lofi-aesthetic',
    name: 'Lo-fi Aesthetic',
    definition: 'A production approach that embraces low-fidelity imperfection — tape hiss, vinyl crackle, compressed bandwidth — as a stylistic choice.',
    example: 'ChilledCow\'s Lo-fi Beats to Study/Relax livestream is the canonical lo-fi aesthetic.',
    whyItMatters: 'Lo-fi is now a genre, not just a recording quality. It prizes mood over clarity — the opposite of pop mixing.',
    relatedLessons: ['gen-05a'],
  },
  {
    id: 'sparse-arrangement',
    name: 'Sparse Arrangement',
    definition: "An arrangement with few instruments at any given moment. Relies on space and restraint rather than density.",
    example: 'Frank Ocean\'s "Thinkin Bout You" has maybe three things happening at any moment — sparse.',
    whyItMatters: 'Sparse arrangements give each element weight. A single drum hit in a sparse mix carries more emotional weight than a wall of sound.',
    relatedLessons: ['gen-06a', 'arr-05'],
  },
  {
    id: 'synth-pad',
    name: 'Synth Pad',
    definition: 'A sustained synthesizer tone that fills space in the mix — think slow, warm, atmospheric.',
    example: 'The lush background textures in The Weeknd\'s tracks are synth pads.',
    whyItMatters: 'Synth pads replace string pads in modern productions — cheaper, more flexible, more customizable. A go-to space-filler.',
    relatedLessons: ['gen-06a'],
  },
  {
    id: '808',
    name: '808',
    definition: 'The Roland TR-808 drum machine (1980) and by extension its iconic sub-bass kick drum sound, now central to hip-hop, trap, and modern pop.',
    example: "Every trap song you've heard has the 808's sub-bass kick carrying the low end.",
    whyItMatters: 'The 808 is the most influential drum sound in hip-hop history. Understanding how to use 808s is basic hip-hop/trap production literacy.',
    relatedLessons: ['gen-08a'],
  },
  {
    id: 'glide',
    name: 'Glide (Portamento)',
    definition: 'The smooth slide between two notes on a synth or bass, instead of jumping instantly from one pitch to the next.',
    example: 'The sliding bass on trap records — notes swoop between pitches rather than stepping cleanly — is glide.',
    whyItMatters: 'Glide gives synths and 808s a vocal, expressive quality. Used sparingly, it adds motion; overused, it turns notes into mush.',
    relatedLessons: ['gen-08a'],
  },

  // --- Phase 2: Mixing / mastering remainders -------------------------
  {
    id: 'multi-band-compression',
    name: 'Multi-band Compression',
    definition: "A compressor that splits the signal into frequency bands (e.g., lows, mids, highs) and compresses each independently.",
    example: 'Use it to tame only the boomy low-mids of a bass track without compressing the highs.',
    whyItMatters: 'Multi-band compression is the mastering engineer\'s scalpel. It lets you fix problems in specific frequency ranges without collateral damage.',
    relatedLessons: ['arr-05'],
  },
  {
    id: 'limiter',
    name: 'Limiter',
    definition: 'An extreme compressor — infinite ratio, fast attack — that prevents any signal from crossing a specified threshold.',
    example: 'The brick-wall limiter on a mastered track stops the signal from clipping at 0 dBFS.',
    whyItMatters: "Limiters are the last stop before a track gets loud. Too heavy, and the song loses dynamics; done right, it adds presence.",
    relatedLessons: ['arr-05'],
  },
  {
    id: 'gate',
    name: 'Gate (Noise Gate)',
    definition: 'A processor that silences signal below a threshold — commonly used to clean up drum bleed or microphone hum.',
    example: "Gate a tom mic so you only hear it when the tom is hit — not when the snare bleeds into it.",
    whyItMatters: 'Gates clean up mixes by removing bleed and noise. Essential for drum mixing and any multi-mic setup.',
    relatedLessons: ['arr-05'],
  },
  {
    id: 'expander',
    name: 'Expander',
    definition: 'A processor that increases dynamic range below a threshold — the opposite of a compressor. Makes quiet parts quieter.',
    example: 'Use an expander on a vocal to push down the noise between words without fully gating it.',
    whyItMatters: 'Expanders are gentler than gates. Great for adding dynamic range back to over-compressed material or cleaning vocals.',
    relatedLessons: [],
  },
  {
    id: 'upward-compression',
    name: 'Upward Compression',
    definition: 'A compression technique that raises the level of quiet parts rather than lowering the loud parts. The opposite of traditional compression.',
    example: "Use upward compression on a soft vocal passage to bring intimate details forward without changing the loud parts.",
    whyItMatters: "Traditional compression squashes dynamics; upward compression preserves them while increasing perceived loudness.",
    relatedLessons: [],
  },
  {
    id: 'dynamic-range',
    name: 'Dynamic Range',
    definition: 'The difference between the quietest and loudest parts of a recording, measured in dB.',
    example: 'A whispered intro and a full-throated climax might span 40 dB of dynamic range — that\'s significant.',
    whyItMatters: 'Dynamic range is emotional range. The Loudness Wars crushed it out of music; modern streaming normalization is slowly bringing it back.',
    relatedLessons: ['arr-05'],
  },
  {
    id: 'mid-side-processing',
    name: 'Mid-Side Processing',
    definition: 'A mixing technique that separates the mono center (mid) from the stereo sides (side) and processes them independently.',
    example: 'Boost the mids of the center channel to emphasize the vocal without widening the stereo image.',
    whyItMatters: 'Mid-side processing gives surgical control over stereo balance. A mastering technique; advanced mixers use it too.',
    relatedLessons: [],
  },
  {
    id: 'mono-compatibility',
    name: 'Mono Compatibility',
    definition: "How well a stereo mix holds up when summed to mono — important for phone speakers, club systems, and old radios.",
    example: 'Check your mix in mono regularly. If the vocal disappears, you have a phase problem.',
    whyItMatters: 'Much of the world still hears music in mono. A gorgeous stereo mix that collapses in mono is a failed mix.',
    relatedLessons: [],
  },
  {
    id: 'dither',
    name: 'Dither',
    definition: 'A small amount of noise added when reducing bit depth (e.g., 24-bit to 16-bit) to prevent digital artifacts.',
    example: "When exporting a final master from 24-bit to 16-bit for CD, always apply dither on the final bounce only.",
    whyItMatters: 'Dither is a specialized step in the mastering chain. Done wrong or twice, it adds unnecessary noise; skipped, you get digital quantization errors.',
    relatedLessons: [],
  },
  {
    id: 'true-peak',
    name: 'True Peak',
    definition: 'The actual peak level of a signal after digital-to-analog conversion — which can exceed the sample peaks on a meter.',
    example: "A track showing -0.1 dBFS sample peak might have +0.3 dB true peak after D/A conversion, causing clipping on some playback devices.",
    whyItMatters: "Streaming services reject masters with true-peak overs. Understanding true peak is mandatory for modern delivery.",
    relatedLessons: ['arr-05'],
  },
  {
    id: 'lufs',
    name: 'LUFS',
    definition: "Loudness Units relative to Full Scale — the modern unit for measuring perceived loudness of an entire track.",
    example: "Spotify targets -14 LUFS integrated loudness; TV broadcast is -24 LUFS.",
    whyItMatters: "LUFS is the standard for streaming and broadcast delivery. Aim for platform-appropriate LUFS or your track will sound too loud or too soft.",
    relatedLessons: ['arr-05'],
  },
  {
    id: 'loudness-normalization',
    name: 'Loudness Normalization',
    definition: "Streaming platforms' practice of turning tracks up or down to a consistent loudness target, regardless of how loud they were mastered.",
    example: "Spotify normalizes to -14 LUFS by default. A hyper-compressed -8 LUFS master gets turned DOWN by Spotify, negating the hype master.",
    whyItMatters: "Loudness normalization ended the Loudness Wars. Today, dynamic range wins over raw loudness on streaming.",
    relatedLessons: ['arr-05'],
  },
  {
    id: 'stereo-imaging',
    name: 'Stereo Imaging',
    definition: "The perceived width and spatial placement of sounds in a stereo field — where each element sits between the left and right speakers.",
    example: "Pan the rhythm guitar hard left, its double hard right, and keep the lead vocal dead center — that's a stereo image decision.",
    whyItMatters: "Stereo imaging creates depth and space. Flat images feel small; good imaging makes tracks feel three-dimensional.",
    relatedLessons: ['arr-05'],
  },

  // --- Phase 2: Business terms ---------------------------------------
  {
    id: 'record-label',
    name: 'Record Label',
    definition: "A company that signs, records, markets, and distributes recordings by artists. Majors (Universal, Sony, Warner) and independents (every other).",
    example: "When Lauryn Hill released The Miseducation, she was signed to Ruffhouse/Columbia — a major label imprint.",
    whyItMatters: "Labels still control most major-artist releases and publishing deals. Understanding how they make money is essential before signing anything.",
    relatedLessons: ['biz-01', 'biz-02'],
  },
  {
    id: 'advance',
    name: 'Advance',
    definition: "Money a label pays an artist upfront against future royalties. It's a loan you pay back from your royalty earnings, not a gift.",
    example: "A new artist might sign for a $100,000 advance — they don't see another royalty check until they've 'recouped' that amount.",
    whyItMatters: "Most artists never recoup. Understanding advances keeps you from taking deals that trade future income for short-term cash.",
    relatedLessons: ['biz-02'],
  },
  {
    id: 'royalty',
    name: 'Royalty',
    definition: "A payment owed to a rights holder each time a song is played, sold, or licensed.",
    example: "Every time 'Happy Birthday' is played on TV, a royalty is paid to whoever holds the rights (until it entered public domain).",
    whyItMatters: "Royalties are how artists and producers earn recurring income. Learning which types exist is fundamental business literacy.",
    relatedLessons: ['biz-02'],
  },
  {
    id: 'album-era',
    name: 'Album Era',
    definition: "The period (roughly 1960s-2000) when albums were the primary commercial unit of music — not singles.",
    example: "Thriller sold as an album, not a pile of singles. The Album Era built careers around cohesive multi-track statements.",
    whyItMatters: "The Album Era's logic still shapes how we talk about artists, even as streaming makes singles dominant again.",
    relatedLessons: ['biz-01'],
  },
  {
    id: 'napster',
    name: 'Napster',
    definition: "The 1999-2001 peer-to-peer file-sharing service that first made music freely downloadable — and began the collapse of the album-sales business model.",
    example: "By 2001, you could download any song for free on Napster. The CD industry never fully recovered.",
    whyItMatters: "Napster is the pivot point between the CD era and the streaming era. Understanding it explains why the music industry looks the way it does today.",
    relatedLessons: ['biz-01'],
  },
  {
    id: 'streaming',
    name: 'Streaming',
    definition: "Playing music through a paid or ad-supported service (Spotify, Apple Music, YouTube Music) rather than owning a copy.",
    example: "Today, over 80% of music industry revenue comes from streaming.",
    whyItMatters: "Streaming is the dominant music economy. Every income, marketing, and release decision today is shaped by streaming platform logic.",
    relatedLessons: ['biz-01', 'biz-02'],
  },
  {
    id: 'sync-licensing',
    name: 'Sync Licensing',
    definition: "Licensing a piece of music to be used in visual media — film, TV, advertising, video games, YouTube.",
    example: "'Wait for It' from Hamilton being licensed for a Verizon commercial is a sync license.",
    whyItMatters: "Sync is often the single biggest income stream for working producers and songwriters. One placement can pay more than a million streams.",
    relatedLessons: ['biz-02'],
  },
  {
    id: 'streaming-royalty',
    name: 'Streaming Royalty',
    definition: "Micropayments earned each time a track is played on a streaming service — typically $0.003-$0.005 per play for the recording royalty.",
    example: "1,000,000 Spotify streams pays the rights holders around $3,000-$5,000 total, split across label, artist, publisher, writer.",
    whyItMatters: "Understanding streaming pay rates is sobering. It also clarifies why sync, touring, and merch matter more than ever for artists.",
    relatedLessons: ['biz-02'],
  },
  {
    id: 'publishing-royalty',
    name: 'Publishing Royalty',
    definition: "The portion of royalties paid to the songwriter and publisher for the composition itself (as opposed to the recording).",
    example: "When your song plays on Spotify, both the master owner AND the publisher earn — the publisher's share is the publishing royalty.",
    whyItMatters: "Publishing royalties are often the most durable income for a songwriter. They keep paying long after a label's interest has ended.",
    relatedLessons: ['biz-02', 'biz-03'],
  },
  {
    id: 'ascap',
    name: 'ASCAP',
    definition: "A Performing Rights Organization (PRO) in the US that collects and distributes public performance royalties to songwriters and publishers.",
    example: "When your song plays on the radio, ASCAP collects from the station and distributes to its member writers.",
    whyItMatters: "Every working songwriter should be registered with ASCAP, BMI, or SESAC — otherwise public performance royalties go uncollected.",
    relatedLessons: ['biz-02', 'biz-05'],
  },
  {
    id: 'bmi',
    name: 'BMI',
    definition: "A Performing Rights Organization (PRO) in the US — same function as ASCAP, with different member rosters.",
    example: "Artists like Mariah Carey, Taylor Swift, and Kendrick Lamar are BMI affiliates.",
    whyItMatters: "Pick one of ASCAP/BMI/SESAC as a writer — can't belong to two. Understanding the difference helps you pick the right home.",
    relatedLessons: ['biz-02', 'biz-05'],
  },
  {
    id: 'sesac',
    name: 'SESAC',
    definition: "The smallest and most selective of the US PROs. Invitation-only rather than open registration.",
    example: "Rihanna and Lady Gaga are SESAC affiliates; their songs collect performance royalties through SESAC.",
    whyItMatters: "SESAC has stricter standards but often pays out more per play for its smaller, curated roster.",
    relatedLessons: ['biz-02', 'biz-05'],
  },
  {
    id: 'beat-leasing',
    name: 'Beat Leasing',
    definition: "A licensing model where a producer rents a beat to a rapper or singer for a limited-use contract, often for a fee under $100.",
    example: "Buying a non-exclusive lease for $49 on BeatStars gives you rights to use that beat within specified stream/sale caps.",
    whyItMatters: "Beat leasing is how most independent producers monetize. It's also how most independent rappers source beats.",
    relatedLessons: ['biz-02'],
  },
  {
    id: 'non-exclusive-lease',
    name: 'Non-Exclusive Lease',
    definition: "A beat lease that allows the producer to sell the same beat to multiple artists. Usually has lower fees and stream caps.",
    example: "A $30 non-exclusive lease from BeatStars might cap the buyer at 10,000 streams or 2,000 downloads.",
    whyItMatters: "Non-exclusives are great for beginning artists and income-stream-diversifying producers. Understand the caps before committing.",
    relatedLessons: ['biz-02'],
  },
  {
    id: 'exclusive-lease',
    name: 'Exclusive Lease',
    definition: "A beat lease where the artist gets sole usage rights — the producer removes the beat from sale to others.",
    example: "Buying an exclusive lease on a beat for $1,500 typically removes it from the producer's catalog forever.",
    whyItMatters: "Exclusives protect your song from collision with another artist's version. Expensive but essential for serious releases.",
    relatedLessons: ['biz-02'],
  },
  {
    id: 'producer-points',
    name: 'Producer Points',
    definition: "A percentage of the recording revenue owed to a producer on a major-label release — typically 3-5%.",
    example: "A producer credited with three percentage 'points' earns 3% of the sound recording royalty share.",
    whyItMatters: "Producer points are the standard major-label producer payment structure. Understanding them is essential before signing any producer agreement.",
    relatedLessons: ['biz-02', 'biz-03'],
  },
  {
    id: 'copyright',
    name: 'Copyright',
    definition: "Legal ownership of a creative work, granted automatically the moment the work is fixed in a tangible medium.",
    example: "The moment you record a demo and save it, you own the copyright in both the composition and the recording.",
    whyItMatters: "Copyright is the foundation of all music business. If you don't understand what you own, you can't protect or monetize it.",
    relatedLessons: ['biz-03'],
  },
  {
    id: 'registration',
    name: 'Copyright Registration',
    definition: "Filing your copyright with the US Copyright Office — not required for ownership, but required to sue for statutory damages.",
    example: "Register your song within 3 months of release with copyright.gov to preserve your full legal remedies.",
    whyItMatters: "You own your song either way, but without registration, your enforcement options are much weaker. It costs $65 and takes 20 minutes.",
    relatedLessons: ['biz-03'],
  },
  {
    id: 'split-sheet',
    name: 'Split Sheet',
    definition: "A document signed at the end of a writing session listing all contributors and their percentage ownership of the composition.",
    example: "After a session, writers agree: Writer A = 40%, Writer B = 40%, Producer C = 20%. That goes on a split sheet, signed by all.",
    whyItMatters: "Without a split sheet, royalties get disputed forever. Every session should end with one. This is the most-neglected, most-important music business habit.",
    relatedLessons: ['biz-03'],
  },
  {
    id: 'master-rights',
    name: 'Master Rights',
    definition: "Ownership of a specific recording of a song — the 'master tape'. Separate from the song itself (which is covered by publishing rights).",
    example: "Beyoncé fought to own her masters — her specific recordings of her own songs.",
    whyItMatters: "Master ownership is where sampling and licensing money comes from. Losing your masters means losing control over how your recordings are used.",
    relatedLessons: ['biz-03'],
  },
  {
    id: 'publishing-rights',
    name: 'Publishing Rights',
    definition: "Ownership of the song itself — the composition (melody + lyrics) independent of any specific recording.",
    example: "Whether Adele, Taylor Swift, or a kid on YouTube records 'Happy Birthday', the song's publishing owner collects.",
    whyItMatters: "Publishing is often the most durable asset in music. Many artists sell recordings but keep publishing — the long-term income stream.",
    relatedLessons: ['biz-03'],
  },
  {
    id: 'work-for-hire',
    name: 'Work-for-Hire',
    definition: "A contract structure in which the person paying owns the copyright from the start — you don't retain ownership of what you create.",
    example: "Composing a jingle for an ad agency on work-for-hire means the agency owns your music forever; you get paid once.",
    whyItMatters: "Work-for-hire is often hidden in producer and session agreements. If you sign without reading, you can give up your copyright without realizing it.",
    relatedLessons: ['biz-03'],
  },
  {
    id: 'public-domain',
    name: 'Public Domain',
    definition: "Works no longer protected by copyright — free for anyone to use, record, or adapt.",
    example: "Beethoven's symphonies are public domain — you can record and sell them without paying anyone.",
    whyItMatters: "Public domain compositions (classical music, old hymns, folk songs) are free source material. Understanding when works enter PD is a creative opportunity.",
    relatedLessons: ['biz-03'],
  },
  {
    id: 'soundexchange',
    name: 'SoundExchange',
    definition: "A nonprofit that collects royalties for digital performance of sound recordings — satellite radio, internet radio, non-interactive streaming.",
    example: "When your song plays on Pandora or SiriusXM, SoundExchange collects and distributes the performance royalties.",
    whyItMatters: "Most artists don't realize they have unclaimed SoundExchange royalties. Registering (free) takes one form and unlocks ongoing income.",
    relatedLessons: ['biz-02', 'biz-05'],
  },
  {
    id: 'epk',
    name: 'EPK',
    definition: "An Electronic Press Kit — a webpage or PDF containing an artist's bio, photos, videos, press coverage, and contact info.",
    example: "Before pitching a venue, blog, or sync agent, you send your EPK.",
    whyItMatters: "An EPK is your professional first impression. Without one, many pro opportunities are impossible.",
    relatedLessons: ['biz-05'],
  },
  {
    id: 'distribution',
    name: 'Distribution',
    definition: "The business of getting music to listeners — today primarily through services like DistroKid, TuneCore, CD Baby, or Amuse that push your tracks to all streaming platforms.",
    example: "DistroKid charges ~$23/year for unlimited uploads to Spotify, Apple Music, and every other major service.",
    whyItMatters: "Independent artists need distribution to earn streaming revenue. It's the minimum required setup to have a music business.",
    relatedLessons: ['biz-02', 'biz-05'],
  },
  {
    id: 'catalog',
    name: 'Catalog',
    definition: "The body of recordings and compositions an artist, label, or producer owns over their career.",
    example: "Bruce Springsteen sold his catalog to Sony in 2021 for around $500 million.",
    whyItMatters: "Your catalog is your long-term asset. Even a modest catalog generating steady streaming income accumulates value.",
    relatedLessons: ['biz-02', 'biz-03', 'biz-05'],
  },

  // --- Phase 2: AI era -----------------------------------------------
  {
    id: 'ai-music',
    name: 'AI Music',
    definition: "Music generated by or significantly produced using artificial intelligence models — either partly (as a tool) or entirely (from text prompt).",
    example: "Udio and Suno can generate full songs from a text prompt in seconds.",
    whyItMatters: "AI music is now cheap, fast, and increasingly convincing. The industry's response is still forming; every working musician needs to understand what's happening.",
    relatedLessons: ['biz-04'],
  },
  {
    id: 'stem-separation',
    name: 'Stem Separation',
    definition: "AI tools that split a finished recording back into its original components — drums, bass, vocals, other — from just the final mix.",
    example: "Tools like Spleeter, Moises, and Logic's Stem Splitter can pull a vocal out of a commercial record in seconds.",
    whyItMatters: "Stem separation is revolutionizing sampling, karaoke, and remixing. The legal implications for sample clearance are still being argued.",
    relatedLessons: ['biz-04'],
  },
  {
    id: 'vocal-cloning',
    name: 'Vocal Cloning',
    definition: "AI tools that learn the sound of a specific voice from training data and can then generate new vocals in that voice.",
    example: "The 'fake Drake' AI vocal song that went viral in 2023 used vocal cloning trained on Drake's catalog.",
    whyItMatters: "Vocal cloning raises urgent questions about identity rights and consent. This area of law is evolving rapidly.",
    relatedLessons: ['biz-04'],
  },
  {
    id: 'training-data',
    name: 'Training Data',
    definition: "The collection of songs an AI music model learned from. Often collected without explicit permission from the rights holders.",
    example: "Suno was sued in 2024 by major labels claiming its training data included copyrighted recordings without license.",
    whyItMatters: "Whether AI companies can legally train on copyrighted music without paying is a multi-billion-dollar legal question currently being litigated.",
    relatedLessons: ['biz-04'],
  },
  {
    id: 'ai-generated-content',
    name: 'AI-generated Content',
    definition: "Any creative output produced largely or entirely by an AI system rather than a human.",
    example: "An album released in 2023 entirely composed of AI-generated music.",
    whyItMatters: "Streaming platforms are starting to flag or de-prioritize AI-generated content. Disclosure rules are forming.",
    relatedLessons: ['biz-04'],
  },
  {
    id: 'udio',
    name: 'Udio',
    definition: "A generative AI service (launched 2024) that creates full songs from text prompts.",
    example: "Type 'sad indie folk song about losing a father' into Udio and get a two-minute track back within a minute.",
    whyItMatters: "Udio and its peers represent a shift in the floor of what 'good' music costs to make. Understanding their capability is now part of being a working producer.",
    relatedLessons: ['biz-04'],
  },
  {
    id: 'suno',
    name: 'Suno',
    definition: "A generative AI music service (2023-) for creating complete tracks from text descriptions, including lyrics.",
    example: "Suno v3 can generate a chorus with recognizable structure and emotional arc from a single paragraph of description.",
    whyItMatters: "Suno is one of the first AI music services to make generated output commercially persuasive. Its rise is reshaping music industry economics.",
    relatedLessons: ['biz-04'],
  },
];

export function glossaryById(id: string): GlossaryContent | undefined {
  return GLOSSARY.find(t => t.id === id);
}

/** Alphabetical index for the standalone glossary view. */
export function glossaryAlphabetical(): GlossaryContent[] {
  return [...GLOSSARY].sort((a, b) => a.name.localeCompare(b.name));
}
