import type { GlossaryContent } from './types';

// Phase 1 glossary — 90+ terms covering Logic Pro interface,
// audio fundamentals, recording, microphones, signal processing,
// mixing, vocal work, and file formats. Definitions are written
// for working musicians (not engineers), tuned to gospel / R&B /
// soul / jazz / neo-soul / hip-hop production aesthetics.

export const GLOSSARY: GlossaryContent[] = [
  // --- Logic Pro interface ----------------------------------------
  {
    id: 'main-window',
    name: 'Main Window',
    definition: 'The primary Logic Pro workspace — the single window that holds your tracks, the playhead, and most of your daily tools.',
    example: 'When you launch Logic and open a project, the giant grid you see is the Main Window.',
    whyItMatters: 'Every other surface in Logic orbits this view. Getting fluent here is the single biggest speed-up in your workflow.',
    relatedLessons: ['wf-01'],
  },
  {
    id: 'control-bar',
    name: 'Control Bar',
    definition: 'The strip across the top of the Main Window with transport controls, the LCD time display, and buttons for features like Cycle and Count-in.',
    example: 'The Play, Record, and Stop buttons you press a thousand times a session all live in the Control Bar.',
    whyItMatters: 'You customise what lives up here — pin the controls you actually use and hide the ones you don’t.',
    relatedLessons: ['wf-01'],
  },
  {
    id: 'tracks-area',
    name: 'Tracks Area',
    definition: 'The central timeline where audio and MIDI regions live on their tracks. Left-to-right is time, stacked rows are tracks.',
    example: 'When you drag a loop into Logic, it becomes a region in the Tracks Area.',
    whyItMatters: 'This is where arrangement happens. Most of your thinking in a session is "how do these regions fit together" — the Tracks Area is the canvas.',
    relatedLessons: ['wf-01'],
  },
  {
    id: 'inspector',
    name: 'Inspector',
    definition: 'The left-side panel that shows detailed parameters for the currently selected track and region — channel strip, routing, groove settings.',
    example: 'Click a vocal track, open the Inspector, and you see its input, output, plugins, and send amounts in one place.',
    whyItMatters: 'The Inspector is your "look under the hood" view — most deep tweaks happen here without opening the full Mixer.',
    relatedLessons: ['wf-01'],
  },
  {
    id: 'library',
    name: 'Library',
    definition: 'The browser that lets you audition and apply track presets, patches, and plugin settings without leaving the Main Window.',
    example: 'Create a new Software Instrument track, open the Library, and scroll through Rhodes patches to pick the one with the right character.',
    whyItMatters: 'Logic ships with great presets. The Library keeps them one click away — starting from a pro-tuned sound is often faster than building one from scratch.',
    relatedLessons: ['wf-01'],
  },
  {
    id: 'smart-controls',
    name: 'Smart Controls',
    definition: 'Eight to twenty-four simplified knobs mapped to the most important parameters of the current patch — the "top-layer" controls built for performance.',
    example: 'On a Rhodes patch, Smart Controls might expose Tine Level, Drive, and Tremolo Rate — the knobs you’d actually twist while tracking.',
    whyItMatters: 'Great for tracking. You shape the sound with three knobs instead of diving into menus mid-take.',
    relatedLessons: ['wf-01'],
  },
  {
    id: 'mixer',
    name: 'Mixer',
    definition: 'The window (shortcut X) showing every track as a vertical channel strip with faders, pans, sends, inserts, and output routing.',
    example: 'Hit X and Logic opens a mixing console laid out like the hardware boards that inspired it.',
    whyItMatters: 'When you’re mixing — not arranging — the Mixer is the room you live in.',
    relatedLessons: ['wf-01'],
  },
  {
    id: 'transport',
    name: 'Transport',
    definition: 'The cluster of playback controls — Play, Stop, Record, Rewind, Fast Forward, Cycle.',
    example: 'When people say "hit the transport," they mean press Play (Spacebar) or Record (R).',
    whyItMatters: 'Every session move starts with a transport action. Learn the shortcuts before anything else.',
    relatedLessons: ['wf-01', 'wf-03'],
  },
  {
    id: 'region',
    name: 'Region',
    definition: 'A single block of audio or MIDI on a track — a take, a loop, a bounce, a piano part.',
    example: 'When you record eight bars of Rhodes, Logic creates a MIDI region. When you import an 808 loop, it becomes an audio region.',
    whyItMatters: 'Everything you arrange in Logic is a region. Splits, merges, loops, trims — all region operations.',
    relatedLessons: ['wf-01', 'wf-07'],
  },
  {
    id: 'track',
    name: 'Track',
    definition: 'A horizontal lane in the Tracks Area that holds regions of one type (audio / software instrument / drum machine / external MIDI).',
    example: 'Your lead vocal, your kick, your bass — each typically lives on its own track.',
    whyItMatters: 'One track per element is the clean baseline. Mixing becomes impossible when everything is stacked on one track.',
    relatedLessons: ['wf-01'],
  },
  {
    id: 'screenset',
    name: 'Screenset',
    definition: 'A saved window layout — the specific combination of Main Window, Mixer, Piano Roll, plugin windows, and their sizes and positions.',
    example: 'Cmd+1 might be your tracking screenset; Cmd+2 your mixing screenset with the Mixer full-screen.',
    whyItMatters: 'Switching between tracking and mixing without re-arranging windows is a massive time-saver.',
    relatedLessons: ['wf-01', 'wf-02'],
  },

  // --- Basic audio --------------------------------------------------
  {
    id: 'decibel',
    name: 'Decibel (dB)',
    definition: 'The standard unit for measuring sound level. It is a ratio, not an absolute — "loud" relative to a reference.',
    example: 'A whisper is ~30 dB SPL; a conversation ~60 dB SPL; a loud club ~110 dB SPL.',
    whyItMatters: 'Every mix decision is "how many dB louder / softer." Training your ear to notice 1–2 dB changes is a core skill.',
    relatedLessons: ['lang-01'],
  },
  {
    id: 'dbfs',
    name: 'dBFS',
    definition: 'Decibels Full Scale — digital audio’s decibel scale where 0 dBFS is the loudest a signal can be before it clips. All values are negative.',
    example: 'Your master bus might peak at -6 dBFS for headroom; a kick hitting -3 dBFS; a quiet verse around -18 dBFS RMS.',
    whyItMatters: 'Stay well under 0 dBFS. Digital clipping is harsh and unforgiving — unlike tape, which compresses pleasantly.',
    relatedLessons: ['lang-01', 'lang-06'],
  },
  {
    id: 'hz',
    name: 'Hertz (Hz)',
    definition: 'A unit of frequency — cycles per second. In audio, it describes pitch.',
    example: 'A4 (the A above middle C) vibrates at 440 Hz. A kick drum’s thump lives around 60–80 Hz.',
    whyItMatters: 'EQ decisions are frequency decisions. Knowing "that 200 Hz mud" or "that 3 kHz harshness" by ear is foundational.',
    relatedLessons: ['lang-01', 'lang-02'],
  },
  {
    id: 'kilohertz',
    name: 'Kilohertz (kHz)',
    definition: '1,000 Hz. Higher frequencies get named in kHz once they pass 1,000.',
    example: 'Vocal sibilance lives around 6–10 kHz. A "bright" hi-hat sparkles around 12 kHz and up.',
    whyItMatters: 'Everything above roughly 2 kHz is "air" or "presence." Those bands shape how modern and polished a mix feels.',
    relatedLessons: ['lang-01', 'lang-02'],
  },
  {
    id: 'frequency',
    name: 'Frequency',
    definition: 'How many times per second a sound wave cycles. Measured in Hz. Higher frequency = higher pitch.',
    example: 'The bass on a Donny Hathaway record is a low-frequency instrument; the hi-hat is high-frequency.',
    whyItMatters: 'Mixing = managing frequencies so every element has its own space.',
    relatedLessons: ['lang-01', 'lang-02'],
  },
  {
    id: 'pitch',
    name: 'Pitch',
    definition: 'The musical note a sound represents — how high or low it sounds. Directly tied to frequency.',
    example: 'A vocal singing A4 has a fundamental pitch of 440 Hz plus harmonics above.',
    whyItMatters: 'Pitch and frequency are two names for the same thing; producers talk about pitch, engineers reach for Hz — learn both.',
    relatedLessons: ['lang-01', 'vocal-03'],
  },
  {
    id: 'amplitude',
    name: 'Amplitude',
    definition: 'The size of a sound wave — how loud it is. Usually measured in dB.',
    example: 'A fader boost raises amplitude; a compressor reduces the peaks of amplitude.',
    whyItMatters: 'Dynamics (loud vs. soft) are an amplitude story. Emotional arc in a mix = amplitude changes over time.',
    relatedLessons: ['lang-01'],
  },
  {
    id: 'harmonic',
    name: 'Harmonic',
    definition: 'A frequency that’s a whole-number multiple of the fundamental pitch of a sound. Harmonics are what make a Rhodes sound different from a piano even at the same pitch.',
    example: 'A 220 Hz note has harmonics at 440, 660, 880 Hz and so on.',
    whyItMatters: 'Tape, tube, and transformer saturation add harmonics — that’s the "warmth" you’re chasing.',
    relatedLessons: ['lang-07'],
  },
  {
    id: 'peak',
    name: 'Peak',
    definition: 'The single loudest instant in a sound’s amplitude.',
    example: 'A kick drum’s transient is a peak; the sustained body that follows is the RMS level.',
    whyItMatters: 'Limiters catch peaks. Peak-watching prevents clipping; managing peaks vs RMS is the whole game of mastering.',
    relatedLessons: ['lang-06'],
  },
  {
    id: 'phase',
    name: 'Phase',
    definition: 'The relative timing of two audio signals. When two signals are "out of phase," their waveforms cancel each other.',
    example: 'Two mics on the same guitar cabinet — move one a half-inch and the tone changes completely because phase shifts.',
    whyItMatters: 'Phase issues are subtle. The most common sign: bass feels weak on a layered track — flip the phase and it jumps forward.',
    relatedLessons: ['lang-01'],
  },

  // --- Recording ----------------------------------------------------
  {
    id: 'record',
    name: 'Record',
    definition: 'The act of capturing audio or MIDI into a track. In Logic, engaged by pressing R.',
    example: 'Arm the track, hit R, play; Logic creates a new region with your performance.',
    whyItMatters: 'Recording is the step where intention becomes data. Everything downstream depends on the take.',
    relatedLessons: ['wf-04'],
  },
  {
    id: 'take',
    name: 'Take',
    definition: 'A single recorded pass over a section of a song.',
    example: 'You record three verses back-to-back in Cycle mode — each loop is a separate take.',
    whyItMatters: 'Great performances are almost never one perfect take. Comp multiple takes for the best of each.',
    relatedLessons: ['wf-04', 'wf-07', 'vocal-02'],
  },
  {
    id: 'take-folder',
    name: 'Take Folder',
    definition: 'A Logic region that holds multiple takes stacked on the same track — the artefact created by Cycle recording.',
    example: 'After looped recording, you get one region labelled "Verse 1" containing all the takes as lanes.',
    whyItMatters: 'Take Folders + Quick Swipe Comping are Logic’s killer vocal workflow. Nearly every modern R&B vocal is built this way.',
    relatedLessons: ['wf-07', 'vocal-02'],
  },
  {
    id: 'comping',
    name: 'Comping',
    definition: 'Short for "compositing" — choosing the best sections from multiple takes and assembling them into one continuous performance.',
    example: 'Take 1 has the best first line; Take 3 has the best chorus note; Take 4 nails the bridge. Comp them together.',
    whyItMatters: 'Modern vocal production is inseparable from comping. Learn it before you learn anything else vocal-related.',
    relatedLessons: ['wf-07', 'vocal-02'],
  },
  {
    id: 'quick-swipe-comping',
    name: 'Quick Swipe Comping',
    definition: 'Logic’s interaction for comping: drag across take lanes to pick which take plays at which moment.',
    example: 'Inside a Take Folder, swipe your mouse across the verse — Logic highlights the chosen take for that span.',
    whyItMatters: 'Dramatically faster than cutting + moving regions manually. The difference between "I can comp" and "I dread comping."',
    relatedLessons: ['wf-07', 'vocal-02'],
  },
  {
    id: 'flatten',
    name: 'Flatten',
    definition: 'The action of committing a Take Folder’s comp into a single audio region — no more swiping, just the chosen performance.',
    example: 'Right-click a Take Folder → Flatten. The folder collapses into one region containing only the selected takes.',
    whyItMatters: 'Flatten after comping so downstream edits (tuning, timing) operate on one clean region.',
    relatedLessons: ['wf-07', 'vocal-02'],
  },
  {
    id: 'composite',
    name: 'Composite',
    definition: 'The finished comp — the single assembled performance that resulted from swiping across takes.',
    example: 'After flattening, the composite is your official Verse 1 vocal.',
    whyItMatters: 'When producers ask "send me the comp," they mean the composite — not the Take Folder with all the alternates.',
    relatedLessons: ['wf-07', 'vocal-02'],
  },
  {
    id: 'midi',
    name: 'MIDI',
    definition: 'A data format that records what notes you played and how, but not the sound. MIDI drives a synth or sampler to make the actual audio.',
    example: 'Play a Rhodes patch on a keyboard controller — Logic stores the notes as MIDI, and the patch turns them into audible Rhodes.',
    whyItMatters: 'Endlessly editable. You can change the patch, transpose, quantise, swap notes — long after recording.',
    relatedLessons: ['wf-04'],
  },
  {
    id: 'arm',
    name: 'Arm',
    definition: 'Enabling a track so it will record when you hit R. Shows as a red "R" button glowing on the track.',
    example: 'Click the R button on your vocal track to arm it, then press Record.',
    whyItMatters: 'Forgetting to arm the right track is the most common reason "Logic didn’t record anything."',
    relatedLessons: ['wf-04'],
  },
  {
    id: 'input-monitoring',
    name: 'Input Monitoring',
    definition: 'Hearing the input signal through Logic’s processing even when you’re not recording. Toggled with the "I" button next to the arm button.',
    example: 'Turn on Input Monitoring to hear your vocal with reverb and compression while you warm up, without rolling tape.',
    whyItMatters: 'Singers perform differently when they hear themselves processed. Give them the full mix — it pulls a better take.',
    relatedLessons: ['wf-04', 'vocal-01'],
  },
  {
    id: 'cycle',
    name: 'Cycle',
    definition: 'A playback / recording mode that loops a section between two locators repeatedly.',
    example: 'Set a cycle over the chorus, hit record, and sing four passes back-to-back — Logic stacks them as takes.',
    whyItMatters: 'The core move of modern vocal production. Cycle + comp = the way nearly every vocal is built.',
    relatedLessons: ['wf-07', 'vocal-02'],
  },
  {
    id: 'punch',
    name: 'Punch',
    definition: 'Recording only over a specific range inside an existing region — "punching in" replaces just that section.',
    example: 'The vocalist flubbed one line. Set the punch points around that line, hit record, and they sing only the fix.',
    whyItMatters: 'Surgical. Saves re-tracking a whole verse when only one line is the problem.',
    relatedLessons: ['wf-04'],
  },
  {
    id: 'playhead',
    name: 'Playhead',
    definition: 'The vertical line in the Tracks Area showing your current playback position.',
    example: 'Click anywhere in the timeline to move the playhead; press Return to send it to the beginning.',
    whyItMatters: 'Your constant companion — knowing the playhead’s state is half of navigation.',
    relatedLessons: ['wf-01', 'wf-06'],
  },
  {
    id: 'marker',
    name: 'Marker',
    definition: 'A named point on the timeline. Used to label sections of a song so you can jump instantly.',
    example: 'Add markers for Intro, Verse 1, Pre-Chorus, Chorus, Bridge, Outro. Press the marker shortcut to jump between.',
    whyItMatters: 'Navigating a song by "drag the playhead until it looks right" is brutal. Markers are the answer.',
    relatedLessons: ['wf-06'],
  },
  {
    id: 'arrangement-track',
    name: 'Arrangement Track',
    definition: 'A specialised track where you define song sections as coloured blocks — drag them around to re-order entire verses or choruses.',
    example: 'Decide the bridge should come before the second chorus? Drag the Bridge block in the Arrangement Track — every track moves with it.',
    whyItMatters: 'The single fastest way to try a different song form. Experiments you’d avoid with regions are one-drag trivial here.',
    relatedLessons: ['wf-06'],
  },

  // --- Microphones --------------------------------------------------
  {
    id: 'microphone',
    name: 'Microphone',
    definition: 'A transducer that converts sound pressure into an electrical signal so it can be recorded.',
    example: 'A Shure SM7B on a vocal, an SM57 on a snare, a large-diaphragm condenser on a piano — each converts air into voltage differently.',
    whyItMatters: 'The mic is step one. No amount of plugin magic can fix a bad mic choice or placement.',
    relatedLessons: ['vocal-01'],
  },
  {
    id: 'pop-filter',
    name: 'Pop Filter',
    definition: 'A mesh screen placed between the singer and the microphone to catch plosives.',
    example: 'The thin black disc you see on every vocal booth photo — that’s the pop filter.',
    whyItMatters: 'Cheap, effective, essential. Fixing a popped "P" in post is tedious; a pop filter makes it a non-issue.',
    relatedLessons: ['vocal-01'],
  },
  {
    id: 'plosive',
    name: 'Plosive',
    definition: 'A low-frequency thump caused by a burst of air hitting the mic on consonants like P and B.',
    example: '"Pop" sung too close to the mic creates a loud thud that takes over the waveform.',
    whyItMatters: 'Plosives ruin otherwise great takes. Pop filter + mic placement off-axis solves 95% of them.',
    relatedLessons: ['vocal-01'],
  },
  {
    id: 'sibilance',
    name: 'Sibilance',
    definition: 'The harsh high-frequency energy in "S" and "Sh" sounds — typically 5–10 kHz.',
    example: 'A singer who hisses noticeably on "sail" or "stay" — that’s sibilance.',
    whyItMatters: 'Modern pop mixes process sibilance heavily with de-essers. Every vocal chain needs to address it.',
    relatedLessons: ['vocal-05'],
  },
  {
    id: 'phantom-power',
    name: 'Phantom Power',
    definition: '+48 volts sent through an XLR cable to power a condenser microphone. Toggled with a switch on your audio interface labelled 48V.',
    example: 'Plug in a condenser mic, flip the 48V switch on your interface, and the mic comes to life.',
    whyItMatters: 'Dynamic mics don’t need it; condensers don’t work without it. Forget to turn it on and you’ll think your mic is dead.',
    relatedLessons: ['vocal-01'],
  },
  {
    id: 'condenser-microphone',
    name: 'Condenser Microphone',
    definition: 'A sensitive mic style favoured for vocals and quiet acoustic sources. Needs phantom power.',
    example: 'A Neumann U87, a Warm WA-47, a Rode NT1 — all condensers.',
    whyItMatters: 'The go-to for lead vocals in modern R&B and gospel because of their detail and air.',
    relatedLessons: ['vocal-01'],
  },
  {
    id: 'dynamic-microphone',
    name: 'Dynamic Microphone',
    definition: 'A rugged mic style that doesn’t need phantom power. Less sensitive than condensers, great for loud or untreated rooms.',
    example: 'A Shure SM7B is a dynamic — famously used on Michael Jackson’s Thriller vocals.',
    whyItMatters: 'If your room isn’t acoustically treated, a dynamic rejects more of the bad room sound than a condenser picks up.',
    relatedLessons: ['vocal-01'],
  },

  // --- Processing: EQ -----------------------------------------------
  {
    id: 'eq',
    name: 'EQ',
    definition: 'Equalisation — turning specific frequency bands up or down to shape the tone of a sound.',
    example: 'Boost 5 kHz on a vocal for presence; cut 250 Hz on an acoustic guitar to remove boxiness.',
    whyItMatters: 'EQ is the most-used tool in any mix. Every track has EQ decisions — intentional or not.',
    relatedLessons: ['lang-02'],
  },
  {
    id: 'parametric-eq',
    name: 'Parametric EQ',
    definition: 'An EQ where you choose the frequency, amount, and width (Q) of each band precisely. The standard modern EQ.',
    example: 'Logic’s Channel EQ is parametric — you can boost 3 kHz by 2 dB with a Q of 1.2 and see the exact curve.',
    whyItMatters: 'Surgical and corrective work needs parametric precision. "That vocal is muddy" requires a specific cut at a specific frequency.',
    relatedLessons: ['lang-02'],
  },
  {
    id: 'shelving-eq',
    name: 'Shelving EQ',
    definition: 'An EQ band that boosts or cuts everything above (high shelf) or below (low shelf) a chosen frequency.',
    example: 'Pull a high shelf at 10 kHz down 2 dB to soften a too-bright vocal.',
    whyItMatters: 'Great for broad tonal moves — warmer, brighter, fatter — in a way bell-shaped parametric cuts can’t match.',
    relatedLessons: ['lang-02'],
  },
  {
    id: 'high-pass-filter',
    name: 'High-pass Filter',
    definition: 'An EQ move that removes everything below a chosen frequency, letting only higher frequencies through.',
    example: 'Put a high-pass at 80 Hz on a vocal to kill rumble and plosive energy without affecting the voice itself.',
    whyItMatters: 'Almost every mix track gets a high-pass. Cleans out bass-region mud that doesn’t belong.',
    relatedLessons: ['lang-02'],
  },
  {
    id: 'low-pass-filter',
    name: 'Low-pass Filter',
    definition: 'An EQ move that removes everything above a chosen frequency, letting only lower frequencies through.',
    example: 'Low-pass a synth pad at 8 kHz to tuck it behind the lead vocal.',
    whyItMatters: 'Classic for making a part feel "darker" or "further back" — a common move in modern R&B pads.',
    relatedLessons: ['lang-02'],
  },
  {
    id: 'q-factor',
    name: 'Q Factor',
    definition: 'The width of an EQ band. High Q = narrow, surgical. Low Q = wide, musical.',
    example: 'Boost 300 Hz with Q=1 (wide, warms the whole track) versus Q=8 (narrow, only hits a specific resonance).',
    whyItMatters: 'Corrective cuts want high Q; musical boosts want low Q. Mixing the two up sounds harsh.',
    relatedLessons: ['lang-02'],
  },

  // --- Processing: Compression --------------------------------------
  {
    id: 'compression',
    name: 'Compression',
    definition: 'A process that turns down loud parts of a signal and leaves quiet parts alone, reducing the range between them.',
    example: 'A vocal that sings from whisper to scream gets compressed so every word sits at roughly the same level.',
    whyItMatters: 'Modern records are heavily compressed. Without it, vocals disappear in quiet sections and distort in loud ones.',
    relatedLessons: ['lang-03', 'vocal-04'],
  },
  {
    id: 'threshold',
    name: 'Threshold',
    definition: 'The level a signal must cross before a compressor starts acting on it.',
    example: 'Set the threshold to -18 dB on a vocal — everything above -18 dB gets compressed, below stays untouched.',
    whyItMatters: 'Threshold decides how often the compressor does anything. Too high = no compression; too low = everything compressed, squashed.',
    relatedLessons: ['lang-03', 'vocal-04'],
  },
  {
    id: 'ratio',
    name: 'Ratio',
    definition: 'How aggressively a compressor reduces signal that crosses the threshold. 4:1 means 4 dB over becomes 1 dB over.',
    example: 'A gentle vocal compressor at 2:1; a drum-bus compressor at 4:1; a limiter at 20:1+.',
    whyItMatters: 'Ratio is the compressor’s personality — subtle evening-out versus aggressive shaping.',
    relatedLessons: ['lang-03', 'vocal-04'],
  },
  {
    id: 'attack',
    name: 'Attack',
    definition: 'How quickly a compressor reacts once the signal crosses the threshold. Measured in milliseconds.',
    example: 'Fast attack (1 ms) grabs transients; slow attack (30 ms) lets the punch through and compresses the sustain.',
    whyItMatters: 'Attack shapes punch. Fast attacks flatten dynamics; slow attacks preserve them. Both are right tools — for different jobs.',
    relatedLessons: ['lang-03'],
  },
  {
    id: 'release',
    name: 'Release',
    definition: 'How quickly a compressor stops compressing once the signal drops back below the threshold.',
    example: 'Fast release can pump; slow release leaves the signal compressed until things settle.',
    whyItMatters: 'Release tuning is half of what makes a compressor "feel musical." Match it to the song’s tempo and you get groove.',
    relatedLessons: ['lang-03'],
  },
  {
    id: 'knee',
    name: 'Knee',
    definition: 'How abrupt the compression onset is as the signal crosses the threshold. Soft knee = gradual; hard knee = sudden.',
    example: 'A vocal compressor with a soft knee feels invisible; a drum-bus compressor with a hard knee hits like a punch.',
    whyItMatters: 'Soft knee for vocals and anything "gentle"; hard knee for attitude and grit.',
    relatedLessons: ['lang-03'],
  },
  {
    id: 'makeup-gain',
    name: 'Makeup Gain',
    definition: 'Volume added after compression to restore the loudness you lost when the compressor pushed peaks down.',
    example: 'Compression reduces a vocal by 4 dB at the peaks; add 4 dB of makeup gain to bring the average level back up.',
    whyItMatters: 'Without makeup gain, compressed tracks sound quieter rather than more-controlled — the move feels like a downgrade.',
    relatedLessons: ['lang-03'],
  },
  {
    id: 'gain-reduction',
    name: 'Gain Reduction',
    definition: 'How many dB the compressor is currently cutting. Read off the GR meter on the plugin.',
    example: 'A vocal compressor showing 3–6 dB GR on the loudest words is doing a healthy amount.',
    whyItMatters: 'The GR meter tells you what the compressor is actually doing — more useful than any knob in diagnosing problems.',
    relatedLessons: ['lang-03'],
  },
  {
    id: 'parallel-compression',
    name: 'Parallel Compression',
    definition: 'Blending a heavily-compressed copy of a track underneath the uncompressed original.',
    example: 'Send drums to a bus, crush them with a compressor, blend 30% of the crushed copy back in — drums feel huge without losing their transients.',
    whyItMatters: 'The secret behind "New York" drum tones and weightier lead vocals. You get the body without flattening the performance.',
    relatedLessons: ['vocal-08'],
  },
  {
    id: 'side-chain',
    name: 'Side-chain',
    definition: 'Telling a compressor to react to a different signal than the one it’s processing. Most famously, ducking the bass every time the kick hits.',
    example: 'Set the compressor on your bass track to side-chain from the kick — every kick hit pulls the bass down briefly, then it rebounds.',
    whyItMatters: 'The defining sound of modern pop, house, and a lot of R&B — the "pump" that gives a mix forward motion.',
    relatedLessons: ['lang-08'],
  },

  // --- Processing: Reverb -------------------------------------------
  {
    id: 'reverb',
    name: 'Reverb',
    definition: 'Simulated room sound — the tail of reflections that tells your ear "this happened in a space."',
    example: 'A dry vocal sounds like it’s in your face; add a plate reverb and it sounds like it’s in a studio booth.',
    whyItMatters: 'Reverb glues sounds together and places them in emotional space. Too much = distant and muddy; none = sterile.',
    relatedLessons: ['lang-04', 'vocal-06'],
  },
  {
    id: 'decay',
    name: 'Decay',
    definition: 'How long a reverb tail lasts before it fades out. Measured in seconds.',
    example: 'A 0.8 s decay is a small room; 2.5 s is a hall; 6 s is a cathedral.',
    whyItMatters: 'Decay decides scale. A ballad loves 2+ second plates; a tight funk groove wants 0.6 s rooms.',
    relatedLessons: ['lang-04', 'vocal-06'],
  },
  {
    id: 'pre-delay',
    name: 'Pre-delay',
    definition: 'The gap between a sound and the start of its reverb tail. Measured in milliseconds.',
    example: 'Pre-delay of 30 ms on a vocal reverb keeps the dry word clear; the reverb blooms after the consonant.',
    whyItMatters: 'The single most underrated reverb control. Adds depth without mud.',
    relatedLessons: ['lang-04', 'vocal-06'],
  },
  {
    id: 'wet-dry',
    name: 'Wet/Dry',
    definition: 'The balance between the processed reverb signal (wet) and the original untreated signal (dry).',
    example: 'A Wet/Dry knob at 20% means 20% reverb, 80% direct sound.',
    whyItMatters: 'On sends you go 100% wet (the dry comes from the original track). On inserts you mix wet + dry in one place.',
    relatedLessons: ['lang-04', 'vocal-06'],
  },
  {
    id: 'chromaverb',
    name: 'ChromaVerb',
    definition: 'Logic Pro’s flagship reverb plugin. Offers room, chamber, plate, and creative algorithms in one interface.',
    example: 'Load ChromaVerb on a vocal send, pick Chamber, tune decay to 1.8 s, pre-delay 25 ms — a classic lead-vocal space.',
    whyItMatters: 'High-quality, low-CPU, always installed. No need to spend money to get a pro vocal reverb in Logic.',
    relatedLessons: ['lang-04', 'vocal-06'],
  },
  {
    id: 'space-designer',
    name: 'Space Designer',
    definition: 'Logic Pro’s convolution reverb — plays your signal through impulse responses captured from real rooms, halls, and hardware.',
    example: 'Load a Sinatra-era studio impulse response into Space Designer for a vintage chamber sound.',
    whyItMatters: 'Convolution gives you character no algorithmic reverb can — real spaces have irregularities that algorithms smooth over.',
    relatedLessons: ['lang-04'],
  },
  {
    id: 'plate-reverb',
    name: 'Plate Reverb',
    definition: 'A reverb style originally made by vibrating a large steel plate with the signal and miking its response. Known for its dense, smooth, bright tail.',
    example: 'Every classic soul and Motown vocal sits in a plate — the shimmering wash behind Aretha and Marvin.',
    whyItMatters: 'The go-to vocal reverb for anything vintage or polished. Modern plate plugins emulate the EMT 140 hardware.',
    relatedLessons: ['lang-04', 'vocal-06'],
  },
  {
    id: 'hall-reverb',
    name: 'Hall Reverb',
    definition: 'A reverb style emulating large concert halls — long decay, pronounced early reflections, a sense of grand space.',
    example: 'Gospel choir stacks and orchestral productions live in halls.',
    whyItMatters: 'For ballads and epic moments, a hall makes things feel important. Overused on close-mic’d R&B it just sounds "far away."',
    relatedLessons: ['lang-04', 'vocal-06'],
  },
  {
    id: 'convolution',
    name: 'Convolution',
    definition: 'A technique that applies the acoustic signature of a real space (an impulse response) to your audio.',
    example: 'Convolution reverbs turn your track into "how it would sound inside Abbey Road Studio 2."',
    whyItMatters: 'Where algorithmic reverb approximates, convolution copies. The difference is audible on lead vocals and acoustic sources.',
    relatedLessons: ['lang-04'],
  },
  {
    id: 'send',
    name: 'Send',
    definition: 'Routing a copy of a track’s signal to a separate auxiliary destination, typically for a shared reverb or delay.',
    example: 'Send your lead vocal, BGVs, and snare to one "Verb A" bus — they share the same reverb and feel like the same space.',
    whyItMatters: 'Sends are how you glue a mix. One reverb on five sources uses less CPU and sounds more cohesive than five separate reverbs.',
    relatedLessons: ['lang-04', 'vocal-06'],
  },

  // --- Processing: Delay + Saturation -------------------------------
  {
    id: 'delay',
    name: 'Delay',
    definition: 'An effect that plays back a copy of the signal after a chosen time, creating echoes.',
    example: 'A dotted-eighth delay on a vocal "ooh" creates a rhythmic ping that plays against the main groove.',
    whyItMatters: 'Delay carves space differently from reverb — rhythmic, intentional. Every modern R&B hook has delay on something.',
    relatedLessons: ['lang-05'],
  },
  {
    id: 'feedback',
    name: 'Feedback',
    definition: 'The number of echoes a delay repeats before fading out. Higher feedback = more repeats.',
    example: 'Feedback at 25% = three clear echoes; at 70% = the echo stacks into a washy cloud.',
    whyItMatters: 'Feedback is where delay goes from a subtle nudge to a psychedelic signature.',
    relatedLessons: ['lang-05'],
  },
  {
    id: 'slapback',
    name: 'Slapback',
    definition: 'A short, single delay (typically 80–150 ms) with no feedback — one quick echo that thickens the source.',
    example: 'Elvis’ vocals, rockabilly guitars, some Kirk Franklin adlibs — all lean on slapback.',
    whyItMatters: 'A classic vintage sound. Doubles a vocal without the phase issues of actual doubling.',
    relatedLessons: ['lang-05'],
  },
  {
    id: 'tape-delay',
    name: 'Tape Delay',
    definition: 'A delay emulation of old tape-based units. Characterised by warm saturation, pitch wobble, and high-frequency roll-off on each repeat.',
    example: 'Use a tape delay on a lead vocal hook — the repeats get darker and more analogue as they fade.',
    whyItMatters: 'The sound of decades of soul, dub, and hip-hop. Digital delays can sound sterile; tape delay is instant character.',
    relatedLessons: ['lang-05'],
  },
  {
    id: 'stereo-delay',
    name: 'Stereo Delay',
    definition: 'A delay that outputs different echoes to the left and right speakers.',
    example: 'Left delayed 3/8 note, right delayed 1/4 note — a vocal ad-lib bounces around the room.',
    whyItMatters: 'Creates motion and width without making the mix feel cluttered in the centre.',
    relatedLessons: ['lang-05'],
  },
  {
    id: 'saturation',
    name: 'Saturation',
    definition: 'Gentle distortion that adds harmonic complexity to a signal — the "warmth" engineers chase.',
    example: 'Run a clean bass DI through a tape saturation plugin — the tone thickens and the level feels more solid.',
    whyItMatters: 'Digital recordings can feel sterile. Saturation is the difference between "recorded" and "sounds like a record."',
    relatedLessons: ['lang-07'],
  },
  {
    id: 'distortion',
    name: 'Distortion',
    definition: 'A stronger cousin of saturation — clipping that creates obvious harmonic colour and texture.',
    example: 'A subtly distorted drum bus on a hip-hop record; obvious guitar distortion on a rock track.',
    whyItMatters: 'Distortion used in small amounts on drums and bass is one of the defining sounds of modern rap and R&B.',
    relatedLessons: ['lang-07'],
  },
  {
    id: 'tape-saturation',
    name: 'Tape Saturation',
    definition: 'Saturation that emulates the soft compression and harmonic character of analogue tape.',
    example: 'J Dilla’s drums sit in a halo of tape saturation — softer transients, warmer tone.',
    whyItMatters: 'Every track on a Motown record was on tape. Emulating that softens modern plugins’ edges.',
    relatedLessons: ['lang-07'],
  },
  {
    id: 'tube-saturation',
    name: 'Tube Saturation',
    definition: 'Saturation emulating vacuum-tube amplifiers. Adds even-order harmonics — musical, smooth, pleasing.',
    example: 'Tube saturation on a lead vocal adds "presence" without EQ — the vocal sits forward, feels rounder.',
    whyItMatters: 'Tube character is why vintage gear is prized. Software emulations are now excellent.',
    relatedLessons: ['lang-07'],
  },

  // --- Mixing -------------------------------------------------------
  {
    id: 'gain-staging',
    name: 'Gain Staging',
    definition: 'Managing the volume level of a signal at every stage of the chain so nothing clips, distorts, or falls too quiet.',
    example: 'Recording at -18 dBFS average, keeping inserts from clipping, leaving -6 dB headroom on the master.',
    whyItMatters: 'Boring but fundamental. Bad gain staging is why "my mix sounds muddy" — everything’s overloaded.',
    relatedLessons: ['lang-06'],
  },
  {
    id: 'headroom',
    name: 'Headroom',
    definition: 'The space between the loudest peak in your mix and 0 dBFS (where digital clipping happens).',
    example: 'If your loudest moment peaks at -6 dBFS, you have 6 dB of headroom.',
    whyItMatters: 'Mastering engineers want headroom to work with. A mix clipping into the master is already cooked.',
    relatedLessons: ['lang-06'],
  },
  {
    id: 'clipping',
    name: 'Clipping',
    definition: 'When a signal exceeds the maximum digital level. The waveform gets cut off at the ceiling, producing harsh distortion.',
    example: 'Red lights on your meters mean clipping. Back off.',
    whyItMatters: 'Digital clipping sounds bad — nothing like the pleasant tape saturation you get when analogue gear overloads.',
    relatedLessons: ['lang-06'],
  },
  {
    id: 'clip-gain',
    name: 'Clip Gain',
    definition: 'Volume automation applied directly to a region — the gain handle at the top of an audio clip that you can drag.',
    example: 'One word of a vocal take is too loud; pull its clip gain down 3 dB instead of automating the whole fader.',
    whyItMatters: 'Surgical. Fixes dynamic inconsistencies before the compressor has to, giving the compressor less work to do.',
    relatedLessons: ['lang-06'],
  },
  {
    id: 'master-fader',
    name: 'Master Fader',
    definition: 'The single fader controlling the overall output level of your mix.',
    example: 'The rightmost fader in the Mixer window — when you pull it down, the whole song gets quieter.',
    whyItMatters: 'Never push the master fader hard to compensate for a quiet mix. Fix the mix; leave the master near 0.',
    relatedLessons: ['lang-06'],
  },
  {
    id: 'mix-bus',
    name: 'Mix Bus',
    definition: 'The signal path where all your tracks are summed together — typically the Stereo Out in Logic.',
    example: 'A 2-bus compressor glues the whole mix together; EQ on the mix bus shapes the final tone.',
    whyItMatters: 'Mix-bus processing is the final 5% that makes a mix feel cohesive and commercial.',
    relatedLessons: ['lang-06'],
  },
  {
    id: 'auxiliary-track',
    name: 'Auxiliary Track',
    definition: 'A track that doesn’t record audio itself — it sums signals sent to it for processing (reverb, delay, parallel compression, etc.).',
    example: 'Create an Aux, insert ChromaVerb on it, send your lead vocal there — that Aux is your vocal-reverb bus.',
    whyItMatters: 'The foundation of send-based effects and grouped processing. Indispensable once you have more than five tracks.',
    relatedLessons: ['lang-04', 'vocal-06'],
  },
  {
    id: 'pan',
    name: 'Pan',
    definition: 'The left/right position of a track in the stereo field.',
    example: 'Center the kick and lead vocal. Hard-left the rhythm guitar. Hard-right the shaker. Everything else spread across.',
    whyItMatters: 'Pan is free real estate. Two instruments fighting in mono stop fighting when you pan them apart.',
    relatedLessons: ['lang-06', 'vocal-07'],
  },
  {
    id: 'stereo-field',
    name: 'Stereo Field',
    definition: 'The panoramic space between your left and right speakers.',
    example: 'A mix with a wide stereo field feels big and immersive; a narrow one feels small and intimate.',
    whyItMatters: 'How you place elements in the stereo field shapes perceived scale — ballads want less width, dance tracks want more.',
    relatedLessons: ['lang-06'],
  },
  {
    id: 'automation',
    name: 'Automation',
    definition: 'Recorded movements of any mix parameter over time — faders, pan, plugin knobs.',
    example: 'Ride the vocal fader up 1 dB for the chorus, automating the move so it happens every pass.',
    whyItMatters: 'Static mixes feel lifeless. Automation is the craft of modern mixing — small moves in the right places.',
    relatedLessons: ['lang-06'],
  },

  // --- Vocal-specific -----------------------------------------------
  {
    id: 'de-esser',
    name: 'De-esser',
    definition: 'A specialised compressor that only reduces high-frequency sibilance — the "S" and "Sh" energy that sticks out.',
    example: 'A de-esser triggered at 7 kHz reduces sibilance by 3 dB on the offending consonants only.',
    whyItMatters: 'Without de-essing, modern vocal processing (especially bright EQ + compression) makes every S into an ice-pick.',
    relatedLessons: ['vocal-05'],
  },
  {
    id: 'flex-pitch',
    name: 'Flex Pitch',
    definition: 'Logic Pro’s built-in pitch correction editor. Analyses an audio vocal, lets you nudge individual notes up or down, adjust vibrato, and reshape the performance.',
    example: 'A singer’s third line lands 40 cents flat; Flex Pitch lets you drag that note up to exactly in-tune.',
    whyItMatters: 'Tuning is standard modern practice. Done well, it’s invisible; done heavy-handed, it sounds robotic. Flex Pitch supports both.',
    relatedLessons: ['vocal-03'],
  },
  {
    id: 'pitch-correction',
    name: 'Pitch Correction',
    definition: 'The general category of tools (Flex Pitch, Melodyne, Auto-Tune) that nudge off-pitch performances closer to correct notes.',
    example: 'Tuning a soul ballad subtly for polish; tuning a trap hook heavy-handed for the Auto-Tune effect.',
    whyItMatters: 'Almost every pop / R&B / gospel vocal on a release is pitch-corrected. The question is always "how much."',
    relatedLessons: ['vocal-03'],
  },
  {
    id: 'cents',
    name: 'Cents',
    definition: 'A unit of pitch — 1 semitone = 100 cents. Used for fine pitch adjustments below the note level.',
    example: 'A singer’s "Yeah" lands 20 cents sharp; Flex Pitch pulls it down 20 cents to sit exactly on the note.',
    whyItMatters: 'Modern tuning lives in cents, not semitones. Small cent moves preserve a singer’s character.',
    relatedLessons: ['vocal-03'],
  },
  {
    id: 'semitone',
    name: 'Semitone',
    definition: 'A half-step — the distance from one key on the piano to the next, including black keys.',
    example: 'C to C# is a semitone; E to F is also a semitone.',
    whyItMatters: 'Transposing by one semitone up often makes a performance feel brighter; down often darker and warmer.',
    relatedLessons: ['vocal-03'],
  },
  {
    id: 'formant',
    name: 'Formant',
    definition: 'The harmonic resonances of the vocal tract that make a voice sound like a specific person.',
    example: 'Shift formants up and a deep voice becomes a chipmunk; shift down and a bright voice becomes dark — even at the same pitch.',
    whyItMatters: 'Pitch-correction plugins can shift formants independently. Keep them natural and heavy tuning stays invisible.',
    relatedLessons: ['vocal-03'],
  },
  {
    id: 'new-york-compression',
    name: 'New York Compression',
    definition: 'A slang term for parallel compression applied to vocals or drums — blending a heavily-compressed duplicate under the dry original.',
    example: 'Lead vocal on its own fader; a buried, crushed parallel copy adds weight without flattening dynamics.',
    whyItMatters: 'The trick behind tracks that feel dense and controlled without sounding obviously compressed.',
    relatedLessons: ['vocal-08'],
  },
  {
    id: 'background-vocals',
    name: 'Background Vocals (BGVs)',
    definition: 'The harmony and texture vocals that support the lead — typically stacked, panned wide, and mixed softer than the lead.',
    example: 'Classic Boyz II Men choruses are dense BGV stacks; gospel choir productions are layered BGVs on steroids.',
    whyItMatters: 'BGVs are how a mix feels big. The lead is the soloist; the BGVs are the building.',
    relatedLessons: ['vocal-07'],
  },
  {
    id: 'bgv',
    name: 'BGV',
    definition: 'Abbreviation for Background Vocal — used interchangeably with "BGV stack" or "background vocal track."',
    example: 'Engineer to producer: "Send me the lead, the BGV stack, and the ad-libs stems."',
    whyItMatters: 'Studio shorthand. Learn the abbreviations and your sessions move faster.',
    relatedLessons: ['vocal-07'],
  },
  {
    id: 'stacking',
    name: 'Stacking',
    definition: 'Recording the same vocal line (or harmony) multiple times on separate tracks and layering them.',
    example: 'Stack three unison takes of a chorus vocal, pan them at 10-o’clock, center, and 2-o’clock for a solid "wall."',
    whyItMatters: 'The fundamental BGV technique. Two is sparse, three is solid, five+ is a choir.',
    relatedLessons: ['vocal-07'],
  },
  {
    id: 'double',
    name: 'Double',
    definition: 'A second performance of a part recorded to thicken it — typically panned against the original or layered in unison.',
    example: 'Lead vocal + one unison "double" makes the lead feel fuller without being as dense as full BGV stacks.',
    whyItMatters: 'A lightweight thickening trick. Double the chorus vocal, not the verse, and you get a natural "lift" at the hook.',
    relatedLessons: ['vocal-07'],
  },

  // --- Files / formats / bouncing -----------------------------------
  {
    id: 'wav',
    name: 'WAV',
    definition: 'An uncompressed audio file format — preserves every bit of the original recording.',
    example: 'Bounce your mix as a 24-bit, 44.1 kHz WAV to send to mastering.',
    whyItMatters: 'Mastering, collaboration, archive — always WAV. MP3 is for listening, not working.',
    relatedLessons: ['wf-08'],
  },
  {
    id: 'mp3',
    name: 'MP3',
    definition: 'A compressed audio file format — smaller file size at the cost of some high-frequency detail.',
    example: 'Export a 320 kbps MP3 of a rough mix to share with a collaborator over text.',
    whyItMatters: 'Great for sharing rough mixes, wrong for final delivery. Never master from an MP3.',
    relatedLessons: ['wf-08'],
  },
  {
    id: 'sample-rate',
    name: 'Sample Rate',
    definition: 'How many times per second digital audio samples the analogue signal. Measured in kHz.',
    example: '44.1 kHz is CD-quality; 48 kHz is video-standard; 96 kHz is high-resolution.',
    whyItMatters: 'Match your project to your final format. Mismatches cause subtle quality loss in conversion.',
    relatedLessons: ['wf-08'],
  },
  {
    id: 'bit-depth',
    name: 'Bit Depth',
    definition: 'How many bits represent each audio sample. Higher bit depth = more dynamic range.',
    example: '16-bit is CD-quality; 24-bit is modern studio standard; 32-bit float is "no clipping possible" territory.',
    whyItMatters: 'Record and mix at 24-bit. Export final masters at whatever the platform requires — usually 16-bit for streaming.',
    relatedLessons: ['wf-08'],
  },
  {
    id: 'bounce',
    name: 'Bounce',
    definition: 'Exporting a mix or part of a mix from Logic as a new audio file.',
    example: 'File → Bounce → Project or Section creates a WAV of your song.',
    whyItMatters: 'Bouncing is the step that turns a Logic session into a shareable, listenable file.',
    relatedLessons: ['wf-08'],
  },
  {
    id: 'bounce-in-place',
    name: 'Bounce in Place',
    definition: 'Bouncing a single track (including its plugins) to a new audio file inside the same project.',
    example: 'Bounce a synth patch with its effects to free up CPU — the audio file now replaces the live plugin chain.',
    whyItMatters: 'Performance and permanence. Once a synth sound is locked in, bounce in place and stop worrying about it.',
    relatedLessons: ['wf-08'],
  },
  {
    id: 'stem',
    name: 'Stem',
    definition: 'A bounce of a grouped element (all drums, all BGVs, etc.) that contains processing but is separate from the rest of the mix.',
    example: 'Deliver a drum stem, a bass stem, a vocal stem, and a music-bed stem for remix collaboration.',
    whyItMatters: 'Stems are the standard handoff format for remixing, mastering alternates, and collaboration.',
    relatedLessons: ['wf-08'],
  },
];

export function glossaryById(id: string): GlossaryContent | undefined {
  return GLOSSARY.find(t => t.id === id);
}

/** Alphabetical index for the standalone glossary view. */
export function glossaryAlphabetical(): GlossaryContent[] {
  return [...GLOSSARY].sort((a, b) => a.name.localeCompare(b.name));
}
