// Pre-generated track suggestions grouped by genre / era. Powers the
// "Browse Track Suggestions" curator flow — user picks a pool, reviews
// 15+ suggestions, checks the ones they want, and those land in the
// library. All guided-listening notes are written in a producer's
// voice (what to actually *notice* while listening) and never invent
// specific gear or ratios. Producer credits are historical fact, not
// speculation; if a track's production credit is ambiguous or
// contested it isn't here.

export interface PoolTrack {
  title: string;
  artist: string;
  producer: string;
  genre: string;
  whatToListenFor: string;
  tags: string[];
}

export interface TrackPool {
  id: string;
  label: string;
  subtitle: string;
  tracks: PoolTrack[];
}

// --- 6/8 Church Beat / Gospel Freestyle -----------------------------
const GOSPEL_6_8: PoolTrack[] = [
  {
    title: 'Total Praise',
    artist: 'Richard Smallwood',
    producer: 'Richard Smallwood',
    genre: '6/8 Gospel',
    whatToListenFor: "Listen for the lift of the 6/8 pocket — you can feel each bar swing rather than click. Notice how Smallwood lets the piano carry the song and the choir paint above it. When the key change hits, pay attention to how the arrangement opens up rather than getting louder. Compare how the choir feels during the verse versus the climactic modulation — the same voices, but the room has widened.",
    tags: ['gospel', '6/8', 'choir', 'piano-driven'],
  },
  {
    title: 'Center of My Joy',
    artist: 'Richard Smallwood',
    producer: 'Richard Smallwood',
    genre: '6/8 Gospel',
    whatToListenFor: "The 6/8 lope here is unhurried — notice how the piano sits a hair behind the beat to give the vocal room. Listen for the space between lines; the track breathes more than it pushes. Pay attention to the hush at the start versus the bloom of the choir later — the arrangement earns every moment of fullness.",
    tags: ['gospel', '6/8', 'worship', 'piano-driven'],
  },
  {
    title: 'We Fall Down',
    artist: 'Donnie McClurkin',
    producer: 'Warryn Campbell',
    genre: '6/8 Gospel',
    whatToListenFor: "Pay attention to the restraint. Donnie preaches more than he sings, and the band is holding a cushion under him rather than competing. Listen for the moment the choir enters — it doesn't crash, it answers. Compare how the groove steadies into that 6/8 pulse and how the drums stay conversational, never stomping.",
    tags: ['gospel', '6/8', 'worship', 'vocal-leading'],
  },
  {
    title: 'Open My Heart',
    artist: 'Yolanda Adams',
    producer: 'Jimmy Jam, Terry Lewis',
    genre: '6/8 Gospel',
    whatToListenFor: "Jam & Lewis make a gospel song feel like a Quiet Storm cut. Notice how the drums are programmed but feel human, and how the keys layer in a soft bed that never muddies. Listen for how close Yolanda's voice feels — intimate, conversational. Compare the prayerful verses with how the bridge opens up; the arrangement is doing most of the emotional work.",
    tags: ['gospel', '6/8', 'jam-lewis', 'modern-gospel'],
  },
  {
    title: 'I Love the Lord',
    artist: 'Whitney Houston',
    producer: 'Mervyn Warren',
    genre: '6/8 Gospel',
    whatToListenFor: "From The Preacher's Wife. Listen for how Whitney treats every note like a sentence — phrasing is everything. The choir sits in a wide hall behind her; her lead is closer, drier, in your ear. Notice how the 6/8 is almost hymnal — the swing is there but gentle. Compare her quieter passages to her full belt: the mic never rejects her, she just gets bigger inside the same space.",
    tags: ['gospel', '6/8', 'whitney', 'hymnal'],
  },
  {
    title: 'It Remains to Be Seen',
    artist: 'Commissioned',
    producer: 'Fred Hammond',
    genre: '6/8 Gospel',
    whatToListenFor: "Classic Hammond-era gospel 6/8. Notice how the bass and keys are having a conversation under the vocal — quartet-rooted, jazz-informed. Listen for the way harmony parts swap the lead line between singers. Pay attention to the drum feel: it lopes rather than drives.",
    tags: ['gospel', '6/8', 'fred-hammond', 'quartet'],
  },
  {
    title: 'The Blood Will Never Lose Its Power',
    artist: 'Andraé Crouch',
    producer: 'Andraé Crouch',
    genre: '6/8 Gospel',
    whatToListenFor: "Hear how Crouch builds a worship moment entirely out of repetition and dynamics. The 6/8 carries you; the arrangement barely changes but the weight keeps stacking. Listen for how each chorus pulls more voices in rather than new instruments. Compare the raw first pass with the full climax.",
    tags: ['gospel', '6/8', 'andrae-crouch', 'traditional'],
  },
  {
    title: 'Let the Church Say Amen',
    artist: 'Andraé Crouch feat. Marvin Winans',
    producer: 'Andraé Crouch',
    genre: '6/8 Gospel',
    whatToListenFor: "A textbook 6/8 church shuffle. Listen for how the organ and rhythm section frame Marvin's preaching, never stepping on the vocal. Notice the call-and-response architecture between lead and choir. Pay attention to the way the groove pockets the ad-libs — the drums are gliding, not punching.",
    tags: ['gospel', '6/8', 'call-response', 'organ'],
  },
  {
    title: 'Nobody Greater',
    artist: 'VaShawn Mitchell',
    producer: 'VaShawn Mitchell',
    genre: '6/8 Gospel',
    whatToListenFor: "A modern 6/8 worship anthem. Notice how the build is patient — it doesn't explode, it expands. Listen for when the drums switch from soft to full, and how much more emotional weight the same chords carry once the kick is in. Compare the quiet intro to the final chorus: the arrangement is a slow climb.",
    tags: ['gospel', '6/8', 'modern-worship', 'dynamics'],
  },
  {
    title: 'Holy Spirit',
    artist: 'Francesca Battistelli',
    producer: 'Ian Eskelin',
    genre: '6/8 Worship',
    whatToListenFor: "A CCM take on the 6/8 worship feel. Listen for how clean and forward the vocal sits — pop-polished, but the arrangement around it stays sparse. Notice the piano's rolling triplet feel underneath. Compare the intimate opening to the fuller bridge; the track gains weight without losing warmth.",
    tags: ['worship', '6/8', 'ccm', 'piano-driven'],
  },
  {
    title: 'How He Loves',
    artist: 'David Crowder Band',
    producer: 'David Crowder, Ed Cash',
    genre: '6/8 Worship',
    whatToListenFor: "A loose, spacious 6/8. The arrangement is indie-rock dressed up as worship — pay attention to the crunchy acoustic strum and the way the drums are kept low until very late. Listen for the moment the band arrives in full; you'll feel the song decide to be big only once it has something to say.",
    tags: ['worship', '6/8', 'indie-rock', 'dynamics'],
  },
  {
    title: 'God Is',
    artist: 'James Cleveland & The Southern California Community Choir',
    producer: 'James Cleveland',
    genre: 'Traditional Gospel',
    whatToListenFor: "Live traditional gospel in 6/8 — the room itself is part of the mix. Listen for how the choir, band, and congregation blur together. Notice Cleveland's preaching rhythm; the band shadows his phrasing rather than keeping perfect time. Pay attention to the way the tempo breathes; it's felt, not counted.",
    tags: ['gospel', '6/8', 'traditional', 'live'],
  },
  {
    title: 'The Battle Is the Lord\'s',
    artist: 'Yolanda Adams',
    producer: 'Ben Tankard',
    genre: 'Traditional Gospel',
    whatToListenFor: "A long-form 6/8 worship arc. Pay attention to the verse, pre-chorus, chorus, vamp — each section clearly shifts weight. Listen for how the ad-libs come in late, earning their space. Notice Yolanda's restraint early versus her full-voice declarations at the climax.",
    tags: ['gospel', '6/8', 'yolanda-adams', 'dynamics'],
  },
  {
    title: 'I Won\'t Complain',
    artist: 'Rev. Paul Jones',
    producer: 'Paul Jones',
    genre: '6/8 Gospel',
    whatToListenFor: "Raw, slow 6/8 gospel. Minimal arrangement — Hammond, piano, drums, voice — so every choice is visible. Listen for how the Hammond swells carry harmonic motion between phrases. Pay attention to how the vocal bends notes; much of the emotional content lives in the slides, not the pitches.",
    tags: ['gospel', '6/8', 'hammond-organ', 'traditional'],
  },
  {
    title: 'I Need You Now',
    artist: 'Smokie Norful',
    producer: 'Myron Butler',
    genre: '6/8 Gospel',
    whatToListenFor: "Piano-led 6/8 with modern polish. Notice how the keys are doing most of the lifting — the drums are almost incidental. Listen for the strings sneaking in; they build the chorus without ever becoming the focus. Pay attention to Smokie's phrasing inside the 6/8 — he leans on the top of each bar.",
    tags: ['gospel', '6/8', 'piano-driven', 'modern-gospel'],
  },
];

// --- 90s/00s Gospel Choir (Kirk Franklin / Fred Hammond) ------------
const GOSPEL_CHOIR_90S: PoolTrack[] = [
  {
    title: 'Stomp',
    artist: "Kirk Franklin and God's Property",
    producer: 'Kirk Franklin',
    genre: 'Gospel',
    whatToListenFor: "Listen for how a choir can feel enormous and precise at the same time. Try to count the parts — soprano, alto, tenor, bass — and notice how each part has its own space. Pay attention to the ad-libs over the top: dry and present versus wet and far. Compare the choir sound to Kirk's lead; his voice is closer. When the groove drops in, notice how the drums push without overpowering.",
    tags: ['gospel', 'choir', 'arrangement', 'kirk-franklin'],
  },
  {
    title: 'Why We Sing',
    artist: 'Kirk Franklin and The Family',
    producer: 'Kirk Franklin',
    genre: 'Gospel',
    whatToListenFor: "An early Kirk masterclass. Notice how he lets the choir do the testifying — his role is to frame and call. Listen for the tight stop-and-start arrangement; every silence is intentional. Pay attention to the piano line threading through the choir stack.",
    tags: ['gospel', 'choir', 'kirk-franklin', '90s'],
  },
  {
    title: 'Now Behold the Lamb',
    artist: 'Kirk Franklin and The Family',
    producer: 'Kirk Franklin',
    genre: 'Gospel',
    whatToListenFor: "A hushed, reverent 6/8 that swells into full choir power. Listen for the layered vocal lead between Kirk and the featured vocalist. Pay attention to the slow gathering of parts into the chorus — the track waits until the emotional moment to reveal its full size.",
    tags: ['gospel', 'choir', 'kirk-franklin', 'dynamics'],
  },
  {
    title: 'Melodies from Heaven',
    artist: 'Kirk Franklin and The Family',
    producer: 'Kirk Franklin',
    genre: 'Gospel',
    whatToListenFor: "The happiest arrangement Kirk ever wrote. Listen for the horns and keys dancing around each other, and the choir playing the role of a full rhythm section. Pay attention to how the vamp keeps adding small variations — the bed doesn't change much, but the ad-libs make every pass feel new.",
    tags: ['gospel', 'choir', 'kirk-franklin', 'uptempo'],
  },
  {
    title: 'Revolution',
    artist: 'Kirk Franklin',
    producer: 'Kirk Franklin',
    genre: 'Gospel',
    whatToListenFor: "Gospel meets hip-hop drum programming. Listen for the tight kick/snare that would feel at home on a rap record, and how the choir sits confidently over it. Notice the horn stabs and how they punctuate without cluttering. Compare the solo vocal sections to the full choir hits.",
    tags: ['gospel', 'choir', 'kirk-franklin', 'hip-hop-influenced'],
  },
  {
    title: 'Lean on Me',
    artist: 'Kirk Franklin feat. Mary J. Blige, Bono, R. Kelly, Crystal Lewis',
    producer: 'Kirk Franklin',
    genre: 'Gospel',
    whatToListenFor: "A gospel posse cut. Notice how each feature's voice sits in a distinctly different place in the mix — you can tell Kirk staged them rather than blended them. Listen for the choir filling the space between features. Pay attention to how the arrangement keeps space for a new personality every few bars.",
    tags: ['gospel', 'choir', 'kirk-franklin', 'features'],
  },
  {
    title: 'Hero',
    artist: 'Kirk Franklin',
    producer: 'Kirk Franklin',
    genre: 'Gospel',
    whatToListenFor: "Pay attention to the orchestration — strings, horns, choir, and featured vocals layered thickly without fighting. Listen for the cinematic swell into the chorus. Compare the verse arrangement (sparse, storytelling) to the chorus (wide, anthemic).",
    tags: ['gospel', 'choir', 'cinematic', 'kirk-franklin'],
  },
  {
    title: 'No Weapon',
    artist: 'Fred Hammond',
    producer: 'Fred Hammond',
    genre: 'Gospel',
    whatToListenFor: "Hammond's signature bottom-heavy gospel sound. Listen for the bass — he plays it, and it carries as much melody as the vocal. Notice how the choir is tight and quartet-rooted rather than expansive. Pay attention to the groove pocket; it's R&B with gospel vocabulary.",
    tags: ['gospel', 'choir', 'fred-hammond', 'bass-forward'],
  },
  {
    title: 'Glory to the Lamb',
    artist: 'Fred Hammond',
    producer: 'Fred Hammond',
    genre: 'Gospel',
    whatToListenFor: "Worship in a pocket. Notice how patient the groove is — the track never rushes. Listen for how the keys and bass lock up on every phrase. Pay attention to the choir's role: they aren't a crowd, they're a band member.",
    tags: ['gospel', 'choir', 'fred-hammond', 'worship'],
  },
  {
    title: "We're Blessed",
    artist: 'Fred Hammond & Radical for Christ',
    producer: 'Fred Hammond',
    genre: 'Gospel',
    whatToListenFor: "Funk-flavored gospel. Listen for the syncopated drum pattern and how the bass plays off of it. Notice how the choir trades lines like a horn section. Pay attention to the groove switches between verse and chorus — the feel shifts subtly but completely.",
    tags: ['gospel', 'choir', 'fred-hammond', 'funk'],
  },
  {
    title: 'Jesus Be a Fence',
    artist: 'Fred Hammond',
    producer: 'Fred Hammond',
    genre: 'Gospel',
    whatToListenFor: "Traditional gospel reframed with 90s polish. Listen for the organ swells beneath the choir, and how the bass keeps the song anchored while the harmony moves above. Pay attention to the breakdowns — moments where the track drops to almost nothing before rebuilding.",
    tags: ['gospel', 'choir', 'fred-hammond', 'traditional'],
  },
  {
    title: 'I Smile',
    artist: 'Kirk Franklin',
    producer: 'Kirk Franklin',
    genre: 'Gospel',
    whatToListenFor: "Glossy, uplifting gospel pop. Notice the tight programmed drums and the stacked BGVs that feel closer to R&B than choir. Listen for how Kirk uses the choir as an occasional instrument rather than the main event. Pay attention to the bridge modulation — a classic pop-gospel trick.",
    tags: ['gospel', 'pop-gospel', 'kirk-franklin', 'polished'],
  },
  {
    title: 'Brighter Day',
    artist: 'Kirk Franklin',
    producer: 'Kirk Franklin',
    genre: 'Gospel',
    whatToListenFor: "Radio-ready gospel with a strong hook. Listen for the electronic-leaning drums and synths coexisting with the choir — Kirk's 2000s sound. Notice how the chorus is built more around the hook than the choir stack. Pay attention to the bass drops and how they create space for the vocal to arrive.",
    tags: ['gospel', 'pop-gospel', 'kirk-franklin', '2000s'],
  },
  {
    title: 'I Need You More',
    artist: 'Kirk Franklin & Shirley Caesar',
    producer: 'Kirk Franklin',
    genre: 'Gospel',
    whatToListenFor: "Generations colliding. Notice how Shirley's traditional phrasing and Kirk's modern production find each other. Listen for how the arrangement leaves room for call-and-response between her and the choir. Pay attention to the organ — old-school church, sitting inside a new-school bed.",
    tags: ['gospel', 'choir', 'kirk-franklin', 'traditional-modern'],
  },
  {
    title: 'Love',
    artist: "Kirk Franklin and God's Property",
    producer: 'Kirk Franklin',
    genre: 'Gospel',
    whatToListenFor: "Hear how Kirk builds a slow anthem. Listen for the choir entering in stages — a few voices first, the full group later. Pay attention to the piano being the emotional spine. Compare how the choir sounds at the first chorus versus the outro: more voices, more ad-libs, same bed.",
    tags: ['gospel', 'choir', 'kirk-franklin', 'dynamics'],
  },
];

// --- 90s R&B Ballads (Babyface / Jermaine Dupri era) ----------------
const RNB_BALLADS_90S: PoolTrack[] = [
  {
    title: 'Every Time I Close My Eyes',
    artist: 'Babyface feat. Mariah Carey',
    producer: 'Babyface',
    genre: 'R&B ballad',
    whatToListenFor: "A textbook Babyface vocal production. Listen for how both voices sit in exactly the same space despite being two different stars — equal presence, no ego. Notice the acoustic guitar carrying the harmonic work and the bass gently underlining. Pay attention to the restraint of the arrangement; the song lets the voices breathe.",
    tags: ['90s-rnb', 'babyface', 'ballad', 'duet'],
  },
  {
    title: 'When Can I See You',
    artist: 'Babyface',
    producer: 'Babyface',
    genre: 'R&B ballad',
    whatToListenFor: "Just voice and guitar. Listen for how much Babyface can do with almost nothing — every breath audible, every inflection clear. Pay attention to how he doubles himself in the chorus and how that doubling creates emotional weight without a full arrangement. Compare the verse to the chorus; the only thing that really changes is how many Babyfaces you're hearing.",
    tags: ['90s-rnb', 'babyface', 'ballad', 'minimal'],
  },
  {
    title: 'Always Be My Baby',
    artist: 'Mariah Carey',
    producer: 'Jermaine Dupri, Mariah Carey, Manuel Seal',
    genre: 'R&B ballad',
    whatToListenFor: "Notice how the drums are low-key hip-hop underneath a sweet vocal melody — that's Jermaine Dupri's fingerprint. Listen for the way the BGVs stack a breathy cloud above Mariah's lead. Pay attention to the guitar loop and how it takes the place of a traditional arrangement change — the track rides the same pocket throughout.",
    tags: ['90s-rnb', 'jermaine-dupri', 'mariah-carey', 'midtempo'],
  },
  {
    title: 'End of the Road',
    artist: 'Boyz II Men',
    producer: 'Babyface, L.A. Reid, Daryl Simmons',
    genre: 'R&B ballad',
    whatToListenFor: "The gold standard of 90s R&B ensemble vocals. Pay attention to how the voices blend into one instrument during harmonies, then separate when a solo happens. Notice how the track feels big without feeling loud. Listen for the subtle automation — parts duck and lift so your ear always knows where to focus.",
    tags: ['90s-rnb', 'babyface', 'ballad', 'bgv-stacking'],
  },
  {
    title: "I'll Make Love to You",
    artist: 'Boyz II Men',
    producer: 'Babyface',
    genre: 'R&B ballad',
    whatToListenFor: "Quiet-storm Babyface. Listen for how the lead vocal stays close and dry while everything behind it gets a warm wash of reverb. Pay attention to how the rhythm section almost disappears during verses and how the chorus adds weight mostly through more backgrounds. Notice the key change and how the band meets it without fuss.",
    tags: ['90s-rnb', 'babyface', 'ballad', 'quiet-storm'],
  },
  {
    title: 'Water Runs Dry',
    artist: 'Boyz II Men',
    producer: 'Babyface',
    genre: 'R&B ballad',
    whatToListenFor: "Focus on the background vocals. Start by trying to hear the lead alone, then notice the harmony stack — is it a few voices, or a cloud? When the chorus hits, does the room feel bigger? See if you can tell when a harmony enters and exits; that's arrangement at work.",
    tags: ['90s-rnb', 'babyface', 'ballad', 'bgv-stacking'],
  },
  {
    title: 'Un-Break My Heart',
    artist: 'Toni Braxton',
    producer: 'David Foster',
    genre: 'R&B ballad',
    whatToListenFor: "David Foster's big-pop gospel of sadness. Listen for the string arrangement — how it carries the emotional swell that a choir would carry in gospel. Pay attention to Toni's lower register; the production keeps that thickness present even when the strings are huge. Compare the verses to the last chorus: full orchestral weight at the peak.",
    tags: ['90s-rnb', 'david-foster', 'ballad', 'strings'],
  },
  {
    title: "You're Makin' Me High",
    artist: 'Toni Braxton',
    producer: 'Babyface, Bryce Wilson',
    genre: 'R&B midtempo',
    whatToListenFor: "A seductive midtempo. Listen for the programmed drums with their tight snare and soft hi-hats, and how the bass is felt more than heard. Pay attention to the way Toni is mic'd — very close, very warm. Notice the BGV stack on the chorus; they're stacked but treated as background texture, not lead.",
    tags: ['90s-rnb', 'babyface', 'midtempo', 'toni-braxton'],
  },
  {
    title: 'Breathe Again',
    artist: 'Toni Braxton',
    producer: 'Babyface',
    genre: 'R&B ballad',
    whatToListenFor: "Babyface's writer-producer-arranger side on full display. Listen for the electric piano carrying the chords while acoustic guitar does fills. Pay attention to the moment the drums arrive in the chorus — up to then the song feels almost like a demo; after, it feels cinematic.",
    tags: ['90s-rnb', 'babyface', 'ballad', 'toni-braxton'],
  },
  {
    title: 'My, My, My',
    artist: 'Johnny Gill',
    producer: 'Babyface, L.A. Reid, Daryl Simmons',
    genre: 'R&B ballad',
    whatToListenFor: "Old-school soul energy in a 90s production. Listen for the horns and how they punctuate the ends of Johnny's phrases. Pay attention to the groove — there's a slight swing in the drum programming that keeps it from feeling rigid. Notice how Johnny's voice is left mostly dry, letting the power carry itself.",
    tags: ['90s-rnb', 'babyface', 'soul', 'horns'],
  },
  {
    title: 'Red Light Special',
    artist: 'TLC',
    producer: 'Babyface',
    genre: 'R&B midtempo',
    whatToListenFor: "A slow jam built on groove and space. Listen for the bass and how it's doing most of the harmonic work, while the keys float above. Notice how the three vocals stay distinct yet sisterly. Pay attention to the whisper and ad-lib layers in the background — the arrangement has a lot of secondary voices to discover.",
    tags: ['90s-rnb', 'babyface', 'tlc', 'slow-jam'],
  },
  {
    title: 'Exhale (Shoop Shoop)',
    artist: 'Whitney Houston',
    producer: 'Babyface',
    genre: 'R&B ballad',
    whatToListenFor: "Near-silent production. Listen for how little is happening around Whitney — she's carrying nearly the whole song. Pay attention to the soft 'shoop' BGVs and how they replace a traditional arrangement. Compare the first verse to the final one; the track gains almost no new elements, yet the feeling has moved.",
    tags: ['90s-rnb', 'babyface', 'ballad', 'minimal'],
  },
  {
    title: 'Fallin\'',
    artist: 'Alicia Keys',
    producer: 'Alicia Keys',
    genre: 'R&B ballad',
    whatToListenFor: "Classic soul filtered through 2001 ears. Listen for how much room the piano gets — it's the whole rhythm section early on. Pay attention to the drums; when they arrive, they're gritty and sampled-sounding rather than clean. Notice the gospel influence in Alicia's phrasing and how the BGVs echo that.",
    tags: ['2000s-rnb', 'alicia-keys', 'piano-driven', 'soul'],
  },
  {
    title: 'I Don\'t Wanna',
    artist: 'Mariah Carey',
    producer: 'Walter Afanasieff, Mariah Carey',
    genre: 'R&B ballad',
    whatToListenFor: "Mariah's softer ballad mode. Listen for the church-piano feel and how the drums don't arrive until the chorus, if at all. Pay attention to her whistle register and how the mix keeps it clear without harshness. Notice the BGVs — Mariah stacking herself — and how the layers are tight, no sloppy pitching.",
    tags: ['90s-rnb', 'mariah-carey', 'ballad', 'piano-driven'],
  },
  {
    title: 'Not Gon\' Cry',
    artist: 'Mary J. Blige',
    producer: 'Babyface',
    genre: 'R&B ballad',
    whatToListenFor: "Mary's vocal is left conversational and rough in the best way. Listen for how Babyface leaves breath and emotion in rather than smoothing it out. Notice the string arrangement — sparse early, lush later. Pay attention to the way the drums gallop just slightly, keeping the song moving forward.",
    tags: ['90s-rnb', 'babyface', 'mary-j-blige', 'ballad'],
  },
];

// --- 2000s R&B (Usher era) ------------------------------------------
const RNB_2000S: PoolTrack[] = [
  {
    title: 'U Got It Bad',
    artist: 'Usher',
    producer: 'Jermaine Dupri, Bryan-Michael Cox',
    genre: '2000s R&B',
    whatToListenFor: "Bryan-Michael Cox's signature keys. Listen for that electric piano sound and how it defines the era. Notice the subtle programmed drums — Jermaine Dupri keeps them snap-quiet. Pay attention to Usher's doubled lead, and how the BGV stack supports rather than competes. Compare how the song feels intimate even with a full arrangement.",
    tags: ['2000s-rnb', 'jermaine-dupri', 'usher', 'ballad'],
  },
  {
    title: 'Burn',
    artist: 'Usher',
    producer: 'Jermaine Dupri, Bryan-Michael Cox',
    genre: '2000s R&B',
    whatToListenFor: "A midtempo breakup anthem. Listen for the programmed drums and how the snare is pitched slightly higher than you'd expect. Pay attention to the bridge where everything drops out except voice and keys — that contrast is the song. Notice how tight the BGV blend is when the chorus lifts.",
    tags: ['2000s-rnb', 'jermaine-dupri', 'usher', 'midtempo'],
  },
  {
    title: 'Confessions Part II',
    artist: 'Usher',
    producer: 'Jermaine Dupri, Bryan-Michael Cox',
    genre: '2000s R&B',
    whatToListenFor: "Notice the sparseness — hi-hat, kick, and keys are doing most of the work. Listen for how Usher's phrasing sits on top of the pocket; he's almost rapping. Pay attention to the string stabs in the chorus and how they raise the stakes without cluttering. The arrangement is built around negative space.",
    tags: ['2000s-rnb', 'jermaine-dupri', 'usher', 'midtempo'],
  },
  {
    title: 'So Sick',
    artist: 'Ne-Yo',
    producer: 'Stargate',
    genre: '2000s R&B',
    whatToListenFor: "Stargate's melancholic R&B. Listen for how the piano riff is the hook, not the vocal line. Notice the drum programming — crisp, spacious, pop-R&B bridged. Pay attention to Ne-Yo's layered harmonies; he stacks himself a lot, subtly. Compare the verse (stark) to the chorus (warmer, more voice).",
    tags: ['2000s-rnb', 'stargate', 'ne-yo', 'ballad'],
  },
  {
    title: 'Be Without You',
    artist: 'Mary J. Blige',
    producer: 'Bryan-Michael Cox, Johnta Austin, Jason Perry',
    genre: '2000s R&B',
    whatToListenFor: "Mary's voice is the whole song. Listen for how the beat is a bed, intentionally simple. Pay attention to her adlibs over the chorus — they're the real melody. Notice how the production respects her grit; she's not over-polished.",
    tags: ['2000s-rnb', 'bryan-michael-cox', 'mary-j-blige', 'midtempo'],
  },
  {
    title: 'Foolish',
    artist: 'Ashanti',
    producer: '7 Aurelius, Irv Gotti',
    genre: '2000s R&B',
    whatToListenFor: "A DeBarge sample turned into a hook. Listen for how the sample dictates the mood and Ashanti sings around it. Pay attention to the drum pattern — hip-hop drums under R&B melody, that Murder Inc signature. Notice how BGVs are sparse; the sample is doing the texture work.",
    tags: ['2000s-rnb', 'murder-inc', 'ashanti', 'sample-based'],
  },
  {
    title: 'Dilemma',
    artist: 'Nelly feat. Kelly Rowland',
    producer: 'Bam, Ryan Bowser',
    genre: '2000s R&B',
    whatToListenFor: "A slow-tempo duet. Listen for the Patti LaBelle sample anchoring the groove. Pay attention to the ping-pong between Nelly's raps and Kelly's melodies. Notice how the drums are hip-hop-first, and Kelly's voice is treated almost like an R&B lead while Nelly's is a rap vocal; two worlds in one track.",
    tags: ['2000s-rnb', 'crossover', 'duet', 'sample-based'],
  },
  {
    title: 'Irreplaceable',
    artist: 'Beyoncé',
    producer: 'Stargate',
    genre: '2000s R&B',
    whatToListenFor: "Another Stargate calling card. Listen for the acoustic guitar loop — that's the whole chord progression. Notice the simplicity of the drum programming. Pay attention to Beyoncé's phrasing; she rides the beat closer to rap than to ballad, which is what makes it stick.",
    tags: ['2000s-rnb', 'stargate', 'beyonce', 'midtempo'],
  },
  {
    title: 'Bump, Bump, Bump',
    artist: 'B2K feat. P. Diddy',
    producer: 'R. Kelly',
    genre: '2000s R&B',
    whatToListenFor: "A big-production slow groove. Listen for how the drums have real weight — sub-bass and fat snare. Pay attention to the stacked harmonies behind the lead; it's a four-voice group acting like one instrument. Notice the space the track leaves for ad-libs.",
    tags: ['2000s-rnb', 'b2k', 'slow-jam', 'group-vocal'],
  },
  {
    title: 'U Remind Me',
    artist: 'Usher',
    producer: 'Edmund "Eddie Hustle" Clement, Jermaine Dupri',
    genre: '2000s R&B',
    whatToListenFor: "Early Usher, pre-Confessions polish. Listen for the skippy drum pattern and the keys that punctuate the bars. Pay attention to how Usher phrases across the beat rather than on it. Notice how the BGVs answer his lines instead of doubling them.",
    tags: ['2000s-rnb', 'usher', 'midtempo'],
  },
  {
    title: 'Differences',
    artist: 'Ginuwine',
    producer: 'Troy Oliver',
    genre: '2000s R&B',
    whatToListenFor: "A lush ballad built on warm keys and strings. Listen for how the bass is soft but always present. Pay attention to Ginuwine's sustained notes — the mix gives them ring-out room. Compare the verse's intimacy to the chorus's breadth; the arrangement opens without getting loud.",
    tags: ['2000s-rnb', 'ginuwine', 'ballad'],
  },
  {
    title: 'Nobody Wants to Be Lonely',
    artist: 'Ricky Martin & Christina Aguilera',
    producer: 'Desmond Child, Walter Afanasieff, Gary Burr',
    genre: '2000s Pop R&B',
    whatToListenFor: "A big pop-R&B duet. Listen for the orchestral framing under the vocal — strings, piano, programmed drums together. Pay attention to how the two voices interlock in the chorus. Notice the way the production uses dynamic swells rather than fills to build intensity.",
    tags: ['2000s-rnb', 'duet', 'pop-rnb', 'big-production'],
  },
  {
    title: 'Heartbreaker',
    artist: 'Mariah Carey feat. Jay-Z',
    producer: 'Mariah Carey, DJ Clue',
    genre: '2000s R&B',
    whatToListenFor: "A Stacy Lattisaw sample turned into a glossy late-90s groove. Listen for how the drums are programmed loose and quick. Pay attention to Mariah stacking herself into a one-woman chorus, and how Jay-Z's verse sits inside her sonic world rather than disrupting it.",
    tags: ['2000s-rnb', 'mariah-carey', 'crossover', 'sample-based'],
  },
  {
    title: 'Yeah!',
    artist: 'Usher feat. Lil Jon, Ludacris',
    producer: 'Lil Jon',
    genre: '2000s Crunk R&B',
    whatToListenFor: "R&B meets crunk. Listen for the aggressive synth stabs and how the song is built on repetition and energy rather than harmony. Pay attention to how Usher's vocal cuts through a chaotic beat — close mic'd, doubled, no reverb to speak of. Notice how the song manufactures momentum from silence-into-hit contrast.",
    tags: ['2000s-rnb', 'crunk', 'usher', 'uptempo'],
  },
  {
    title: 'Superstar',
    artist: 'Usher',
    producer: 'Manuel Seal, Usher',
    genre: '2000s R&B',
    whatToListenFor: "A quiet, vulnerable track. Listen for how small the arrangement is — keys, drums, little else. Pay attention to Usher's phrasing; he lets pauses sit. Notice how the chorus adds one or two elements rather than a full orchestral flourish.",
    tags: ['2000s-rnb', 'usher', 'ballad', 'minimal'],
  },
];

// --- Lo-fi / Atmospheric Indie --------------------------------------
const LOFI_INDIE: PoolTrack[] = [
  {
    title: 'Bags',
    artist: 'Clairo',
    producer: 'Rostam Batmanglij',
    genre: 'Bedroom pop',
    whatToListenFor: "Notice the way the whole track feels slightly hazy, as if you're hearing it through soft fabric. Listen for the drums — punchy but not clean, a little crunchy. Pay attention to how Clairo's vocal sits at the same softness as everything else; the mix refuses to make anything loud.",
    tags: ['bedroom-pop', 'indie', 'lofi', 'clairo'],
  },
  {
    title: 'Tailwhip',
    artist: 'Men I Trust',
    producer: 'Men I Trust',
    genre: 'Dream pop',
    whatToListenFor: "An endless groove that barely changes. Listen for how the bass is the hook, not the vocal. Pay attention to how soft everything is — guitars, drums, vocals — a uniform hush. Compare the verse to the chorus; you'll find the difference is atmospheric, not structural.",
    tags: ['dream-pop', 'indie', 'bass-forward', 'men-i-trust'],
  },
  {
    title: 'Slow Dancing in the Dark',
    artist: 'Joji',
    producer: 'Patrick Wimberly, Joji',
    genre: 'Alt R&B',
    whatToListenFor: "Listen for the swelling strings underneath a sparse piano and drum bed. Pay attention to how Joji's voice is doubled and slightly pitched, giving it a lonely, distant quality. Notice the way the bridge suddenly goes full orchestral — the track saves its biggest move for near the end.",
    tags: ['alt-rnb', 'joji', 'melancholy', 'strings'],
  },
  {
    title: 'Tek It',
    artist: 'Cafuné',
    producer: 'Cafuné',
    genre: 'Alt pop',
    whatToListenFor: "A sleepy-sounding uptempo track. Listen for the soft drums underneath the warbly chord pad. Pay attention to how the vocal is nearly whispered but still commands the front of the mix. Notice the layers that sneak in over the track — each one quiet enough that you almost miss them.",
    tags: ['alt-pop', 'indie', 'atmospheric', 'dream-pop'],
  },
  {
    title: 'Chamber of Reflection',
    artist: 'Mac DeMarco',
    producer: 'Mac DeMarco',
    genre: 'Indie',
    whatToListenFor: "Synth-heavy and intentionally unpolished. Listen for the wobbly analog-sounding keys and how they carry most of the harmonic content. Pay attention to the way Mac's voice is layered and slightly out of tune — that's the charm, not a bug. Notice how long the song lets a mood sit.",
    tags: ['indie', 'synth-pop', 'mac-demarco', 'lofi'],
  },
  {
    title: 'Nobody',
    artist: 'Mitski',
    producer: 'Patrick Hyland',
    genre: 'Indie rock',
    whatToListenFor: "An upbeat groove carrying heartbreaking lyrics. Listen for the contrast between the sunny disco-ish drums and Mitski's vocal weight. Pay attention to the sparse arrangement — it stays intentionally thin so the dissonance between mood and meaning lands.",
    tags: ['indie', 'indie-rock', 'mitski', 'upbeat'],
  },
  {
    title: 'Flower Boy',
    artist: 'The Marías',
    producer: 'Josh Conway',
    genre: 'Dream pop',
    whatToListenFor: "Sultry, hazy, slightly bossa-leaning groove. Listen for the bass walking under a soft keys bed. Pay attention to how María's vocal is close but treated — a little warmth, a little distance, at the same time. Notice the guitar fills; they're reserved and never stepping on the vocal.",
    tags: ['dream-pop', 'indie', 'bossa', 'the-marias'],
  },
  {
    title: 'The Less I Know the Better',
    artist: 'Tame Impala',
    producer: 'Kevin Parker',
    genre: 'Psych pop',
    whatToListenFor: "Notice how the drums have that 'room' sound — you can almost hear where they were recorded. Listen for the bassline, which is the melodic hook. Pay attention to how the vocal effects (phaser, doubling) place Kevin's voice inside the track rather than over it.",
    tags: ['psych-pop', 'indie', 'tame-impala', 'bass-forward'],
  },
  {
    title: 'Apocalypse',
    artist: 'Cigarettes After Sex',
    producer: 'Greg Gonzalez',
    genre: 'Dream pop',
    whatToListenFor: "A slow, drifting track where nothing moves quickly. Listen for the guitar's clean, bell-like tone and how it doesn't compete with the vocal. Pay attention to the drums — brushed, distant, holding time without pushing. Notice how the reverb on everything creates one big room.",
    tags: ['dream-pop', 'slowcore', 'atmospheric'],
  },
  {
    title: 'Delicate',
    artist: 'Damien Rice',
    producer: 'Damien Rice',
    genre: 'Folk',
    whatToListenFor: "A quiet folk song with cello and voice at its heart. Listen for how the cello carries emotional weight the voice doesn't name. Pay attention to the dynamics — Damien whispers and then almost breaks. Notice how minimal the mix is; you can count the instruments on one hand.",
    tags: ['folk', 'indie', 'minimal', 'cello'],
  },
  {
    title: 'Sofia',
    artist: 'Clairo',
    producer: 'Rostam Batmanglij',
    genre: 'Bedroom pop',
    whatToListenFor: "A pop-structured song given a lofi sheen. Listen for the drums and how they have that slightly vintage snap. Pay attention to the harmony guitars throughout the choruses. Notice how the solo section pulls back rather than escalating — a counterintuitive move that makes the return of the hook feel bigger.",
    tags: ['bedroom-pop', 'indie', 'lofi', 'clairo'],
  },
  {
    title: 'Redbone',
    artist: 'Childish Gambino',
    producer: 'Donald Glover, Ludwig Göransson',
    genre: 'Psychedelic R&B',
    whatToListenFor: "Hypnotic funk with a sleepy vibe. Listen for how the bass is big and warm, holding the whole track. Pay attention to the way the vocals are pitched high and doubled with themselves an octave down. Notice how patient the groove is — nothing hurries.",
    tags: ['alt-rnb', 'psychedelic', 'childish-gambino', 'atmospheric'],
  },
  {
    title: 'Somebody Else',
    artist: 'The 1975',
    producer: 'Matthew Healy, George Daniel',
    genre: 'Alt pop',
    whatToListenFor: "80s synth-pop reimagined for 2016. Listen for the lush pad sounds and the way they wash behind everything. Pay attention to the drum machine; it's intentionally retro. Notice how the chorus is emotionally huge yet sonically cool — the contrast is the hook.",
    tags: ['alt-pop', 'synth-pop', 'the-1975', '80s-inspired'],
  },
  {
    title: 'Heaven Sent',
    artist: 'Keyshia Cole',
    producer: 'Jack Knight',
    genre: '2000s R&B',
    whatToListenFor: "Soulful midtempo. Listen for the mid-range keys carrying most of the harmony while the drums stay understated. Pay attention to Keyshia's adlibs — gospel-schooled, church-flavored. Notice how the BGVs come in late, adding weight to the climax without changing the core groove.",
    tags: ['2000s-rnb', 'keyshia-cole', 'midtempo', 'soulful'],
  },
  {
    title: 'SANTERIA',
    artist: 'Leon Bridges',
    producer: 'Nate Mercereau',
    genre: 'Soul',
    whatToListenFor: "Modern soul with an old-school tone. Listen for how the guitars are clean and slightly compressed, giving the track a 60s studio vibe. Pay attention to the drums — live-sounding, bright snare, airy hi-hat. Notice the restraint in the arrangement; everything serves the vocal.",
    tags: ['soul', 'indie-soul', 'leon-bridges', 'retro'],
  },
];

// --- Modern Minimal R&B (Frank Ocean, H.E.R., Daniel Caesar) --------
const MODERN_MINIMAL_RNB: PoolTrack[] = [
  {
    title: 'Pink + White',
    artist: 'Frank Ocean',
    producer: "Frank Ocean, Om'Mas Keith, Pharrell Williams",
    genre: 'Modern R&B',
    whatToListenFor: "A reference for space. Notice how much silence lives between the drum hits and how much air sits around the vocal. Listen for how Frank's voice feels in-your-ear versus the backgrounds feeling room-far. The minimalism is doing the work — every element was chosen carefully because there are so few.",
    tags: ['modern-rnb', 'minimalism', 'frank-ocean'],
  },
  {
    title: 'Thinkin Bout You',
    artist: 'Frank Ocean',
    producer: 'Shea Taylor',
    genre: 'Modern R&B',
    whatToListenFor: "Listen for how the drums tap rather than drive. The snare is almost a texture. Pay attention to Frank's falsetto in the chorus — it's doubled with itself, clearly treated, but still feels human. Notice the chord voicings; they're ambiguous in a way that makes the song always feel about to resolve.",
    tags: ['modern-rnb', 'frank-ocean', 'falsetto', 'minimal'],
  },
  {
    title: 'Ivy',
    artist: 'Frank Ocean',
    producer: 'Rostam Batmanglij, Frank Ocean',
    genre: 'Modern R&B',
    whatToListenFor: "Almost a demo. Listen for the clean electric guitar carrying the whole harmonic arrangement. Pay attention to how Frank's vocal is raw, sometimes cracking — no polish applied. Notice how the song builds by sheer accumulation rather than a big arrangement move.",
    tags: ['modern-rnb', 'frank-ocean', 'guitar-driven', 'raw'],
  },
  {
    title: 'Nights',
    artist: 'Frank Ocean',
    producer: "Michael Uzowuru, Om'Mas Keith, Frank Ocean",
    genre: 'Modern R&B',
    whatToListenFor: "A two-part suite. Listen for the beat switch midway and how the whole mood rotates. Pay attention to the vocal manipulation — pitched-down, pitched-up, layered conversations between voices. Notice how neither half of the track loses the overall loose, lo-fi aesthetic.",
    tags: ['modern-rnb', 'frank-ocean', 'beat-switch', 'experimental'],
  },
  {
    title: 'Best Part (feat. H.E.R.)',
    artist: 'Daniel Caesar',
    producer: 'Daniel Caesar, Jordan Evans, Matthew Burnett',
    genre: 'Modern R&B',
    whatToListenFor: "Listen for intimacy. How close does each voice feel? The guitar and vocals are the whole show. Pay attention to how the vocals hand off between Daniel and H.E.R.; where does one stop and the other begin? Listen for the subtle doubling in the background — almost whispered.",
    tags: ['modern-rnb', 'daniel-caesar', 'her', 'duet'],
  },
  {
    title: 'Get You',
    artist: 'Daniel Caesar feat. Kali Uchis',
    producer: 'Matthew Burnett, Jordan Evans, Daniel Caesar',
    genre: 'Modern R&B',
    whatToListenFor: "Gospel chord movement in a bedroom arrangement. Listen for the swelling organ under the verses and how it becomes a full chorus pad later. Pay attention to Kali's vocal — she's mic'd with breath intact, and the lightness of her voice contrasts with Daniel's weightier tone.",
    tags: ['modern-rnb', 'daniel-caesar', 'kali-uchis', 'gospel-influenced'],
  },
  {
    title: 'Focus',
    artist: 'H.E.R.',
    producer: 'Darhyl "DJ" Camper Jr.',
    genre: 'Modern R&B',
    whatToListenFor: "A minimalist late-night groove. Listen for how the bass and kick lock in while the rest of the track floats. Pay attention to H.E.R.'s phrasing — conversational, low in her range, casual. Notice how few ad-libs there are; when they come, they're intentional.",
    tags: ['modern-rnb', 'her', 'minimal', 'late-night'],
  },
  {
    title: 'Every Kind of Way',
    artist: 'H.E.R.',
    producer: 'Darhyl "DJ" Camper Jr.',
    genre: 'Modern R&B',
    whatToListenFor: "A piano-driven ballad with patience. Listen for how the drums barely move. Pay attention to H.E.R.'s doubled harmonies — they're tight but slightly offset, creating a haunted quality. Notice how the chorus is not louder than the verse; it just opens sonically.",
    tags: ['modern-rnb', 'her', 'ballad', 'piano-driven'],
  },
  {
    title: 'Suit and Tie (acoustic)',
    artist: 'Daniel Caesar',
    producer: 'Daniel Caesar',
    genre: 'Modern R&B',
    whatToListenFor: "A reharmonization of a familiar song. Listen for how the stripped-back production reveals the melodic bones. Pay attention to Daniel's vocal control in the dynamic shifts — he whispers, then opens up, without ever pushing.",
    tags: ['modern-rnb', 'daniel-caesar', 'acoustic', 'cover'],
  },
  {
    title: 'Electric Feel',
    artist: 'Daniel Caesar (cover)',
    producer: 'Daniel Caesar',
    genre: 'Modern R&B',
    whatToListenFor: "A slowed-down, melancholic take on an uptempo song. Listen for the chord reharmonization and how much darker the track sits. Pay attention to how minimal the beat is; the groove is implied more than stated. Notice how the ad-libs become the arrangement change.",
    tags: ['modern-rnb', 'daniel-caesar', 'cover', 'reharm'],
  },
  {
    title: 'Moonlight',
    artist: 'Ariana Grande',
    producer: 'Max Martin, Ilya Salmanzadeh',
    genre: 'Modern R&B',
    whatToListenFor: "A doo-wop-tinged ballad. Listen for how the drums feel organic despite being programmed. Pay attention to Ariana's layered harmonies; she's a one-woman BGV choir. Notice the retro-leaning chord progression and how the modern mix makes it sparkle.",
    tags: ['modern-rnb', 'ariana-grande', 'doo-wop', 'ballad'],
  },
  {
    title: 'Call Out My Name',
    artist: 'The Weeknd',
    producer: 'Frank Dukes, The Weeknd, Nicolas Jaar',
    genre: 'Modern R&B',
    whatToListenFor: "A brooding, cinematic ballad. Listen for the synth bass carrying most of the harmonic weight. Pay attention to the way Abel's voice is almost always treated — reverb trails, slap delays, doubled up. Notice the gothic, film-score atmosphere.",
    tags: ['modern-rnb', 'the-weeknd', 'cinematic', 'atmospheric'],
  },
  {
    title: 'Come Through and Chill',
    artist: 'Miguel feat. J. Cole',
    producer: 'Salaam Remi',
    genre: 'Modern R&B',
    whatToListenFor: "A laid-back midtempo. Listen for the soft kick/snare pattern and the way the rest of the track drifts over it. Pay attention to Miguel's high falsetto — close mic'd, breath included. Notice how the arrangement leaves room for J. Cole's verse without disrupting the mood.",
    tags: ['modern-rnb', 'miguel', 'j-cole', 'mellow'],
  },
  {
    title: 'In My Room',
    artist: 'Frank Ocean',
    producer: 'Frank Ocean',
    genre: 'Modern R&B',
    whatToListenFor: "A sketch-like track. Listen for the sparse beat and how the vocal leans into the rhythm like a rap verse. Pay attention to the chord changes — ambient, simple. Notice how the song doesn't resolve; it fades, a deliberate refusal of the traditional arc.",
    tags: ['modern-rnb', 'frank-ocean', 'experimental', 'sketch'],
  },
  {
    title: 'Could\'ve Been',
    artist: "H.E.R. feat. Bryson Tiller",
    producer: "Darhyl 'DJ' Camper Jr.",
    genre: 'Modern R&B',
    whatToListenFor: "A late-night slow jam duet. Listen for the trap-flavored drum pattern underneath a warm, lush keys arrangement. Pay attention to the vocal handoffs between H.E.R. and Bryson — their tones are close enough to feel unified but distinct. Notice how sparse the arrangement stays even at the chorus.",
    tags: ['modern-rnb', 'her', 'bryson-tiller', 'duet'],
  },
];

// --- 80s Pop Ballads ------------------------------------------------
const POP_BALLADS_80S: PoolTrack[] = [
  {
    title: 'Against All Odds (Take a Look at Me Now)',
    artist: 'Phil Collins',
    producer: 'Phil Collins, Arif Mardin',
    genre: '80s Pop ballad',
    whatToListenFor: "Listen for the sparse piano intro and how long it takes for anything else to arrive. Pay attention to Phil's vocal — every crack is intentional, nothing smoothed. Notice how the drums finally land like an emotional release rather than a groove. The key change at the end is one of the most famous in pop for a reason.",
    tags: ['80s-pop', 'ballad', 'phil-collins', 'dramatic'],
  },
  {
    title: 'Time After Time',
    artist: 'Cyndi Lauper',
    producer: 'Rick Chertoff',
    genre: '80s Pop ballad',
    whatToListenFor: "A synth-pop ballad with real emotional restraint. Listen for the delicate drum machine and how it functions more like a pulse than a backbeat. Pay attention to Cyndi's lower register in the verses — not the belting she's famous for. Notice how the arrangement adds one instrument per section, building quietly.",
    tags: ['80s-pop', 'ballad', 'synth-pop', 'cyndi-lauper'],
  },
  {
    title: 'Careless Whisper',
    artist: 'George Michael',
    producer: 'George Michael',
    genre: '80s Pop ballad',
    whatToListenFor: "The sax is the other lead singer. Listen for how it's mixed almost as loud as the vocal. Pay attention to the way George doubles himself in the chorus — still one of the best vocal stack examples of the era. Notice the programmed drums' signature snare — huge, gated, iconic.",
    tags: ['80s-pop', 'ballad', 'george-michael', 'sax'],
  },
  {
    title: 'Every Breath You Take',
    artist: 'The Police',
    producer: 'Hugh Padgham, The Police',
    genre: '80s Pop ballad',
    whatToListenFor: "Listen for the clean, palm-muted guitar riff that defines the song. Pay attention to how few elements there really are — guitar, bass, drums, voice — and how much space each gets. Notice Sting's vocal; it's quiet but forward in the mix, a trick that makes a creepy lyric feel intimate.",
    tags: ['80s-pop', 'the-police', 'minimal', 'iconic-riff'],
  },
  {
    title: 'In Your Eyes',
    artist: 'Peter Gabriel',
    producer: 'Peter Gabriel, Daniel Lanois',
    genre: '80s Pop',
    whatToListenFor: "World music meets big 80s production. Listen for the African percussion threading through the programmed drums. Pay attention to the way Youssou N'Dour's vocal appears in the bridge — a texture as much as a feature. Notice the spaciousness; nothing is fighting for room.",
    tags: ['80s-pop', 'world-music', 'peter-gabriel', 'atmospheric'],
  },
  {
    title: 'Endless Love',
    artist: 'Diana Ross & Lionel Richie',
    producer: 'Lionel Richie, James Anthony Carmichael',
    genre: '80s Pop ballad',
    whatToListenFor: "A classic duet framing. Listen for how the two voices take turns rather than fighting for the lead. Pay attention to the piano-led arrangement; it never gets in the singers' way. Notice how the strings arrive in stages, each one lifting the emotional ceiling without crashing through it.",
    tags: ['80s-pop', 'ballad', 'duet', 'lionel-richie'],
  },
  {
    title: 'Hello',
    artist: 'Lionel Richie',
    producer: 'Lionel Richie, James Anthony Carmichael',
    genre: '80s Pop ballad',
    whatToListenFor: "Soft piano, softer vocal. Listen for how restrained Lionel is through the verses; the chorus is barely louder. Pay attention to the BGVs — stacked but held back. Notice how the drums enter almost hesitantly. The song refuses to be big until it absolutely has to be.",
    tags: ['80s-pop', 'ballad', 'lionel-richie', 'piano-driven'],
  },
  {
    title: 'Saving All My Love for You',
    artist: 'Whitney Houston',
    producer: 'Michael Masser',
    genre: '80s Pop ballad',
    whatToListenFor: "Whitney's breakthrough ballad. Listen for the sax motif threaded through. Pay attention to the way the drums are light-touch — this is song territory, not groove territory. Notice how dry and forward her vocal sits; the reverb tail is short, keeping her in your ear.",
    tags: ['80s-pop', 'ballad', 'whitney-houston', 'jazz-adjacent'],
  },
  {
    title: 'Total Eclipse of the Heart',
    artist: 'Bonnie Tyler',
    producer: 'Jim Steinman',
    genre: '80s Pop ballad',
    whatToListenFor: "Steinman's operatic pop. Listen for the sheer scale — the song is all peaks and valleys, a theatrical arc. Pay attention to the drum hits that arrive like punctuation. Notice how the BGVs stop and start in dramatic unison; they're actors, not a choir.",
    tags: ['80s-pop', 'ballad', 'bonnie-tyler', 'dramatic'],
  },
  {
    title: 'Nothing\'s Gonna Stop Us Now',
    artist: 'Starship',
    producer: 'Narada Michael Walden',
    genre: '80s Pop ballad',
    whatToListenFor: "A huge, radio-ready power ballad. Listen for the layered gated snares and programmed drums giving the track its 80s arena feel. Pay attention to how the male and female leads swap the melody line. Notice the way the synth pads are washing the whole mix — ever-present, never obtrusive.",
    tags: ['80s-pop', 'power-ballad', 'starship', 'gated-drums'],
  },
  {
    title: 'Anything for You',
    artist: 'Gloria Estefan & Miami Sound Machine',
    producer: 'Emilio Estefan Jr., Jorge Casas, Clay Ostwald',
    genre: '80s Pop ballad',
    whatToListenFor: "A tender bilingual ballad. Listen for the acoustic guitar threading through the song — it's the spine. Pay attention to the sax solo and how it takes over lead-vocal duties for a bar. Notice Gloria's vocal; it's close mic'd and emotionally bare.",
    tags: ['80s-pop', 'ballad', 'gloria-estefan', 'latin-pop'],
  },
  {
    title: 'How Deep Is Your Love',
    artist: 'Bee Gees',
    producer: 'Bee Gees, Karl Richardson, Albhy Galuten',
    genre: 'Pop ballad',
    whatToListenFor: "Note the harmony — three brothers singing one sound. Listen for the Rhodes-like keyboard carrying the chord progression. Pay attention to how quiet the drums are; there's a pulse but no weight. Compare this to any modern ballad — you'll hear how much less compression there is.",
    tags: ['pop-ballad', 'bee-gees', 'harmony', 'soft-rock'],
  },
  {
    title: 'Truly',
    artist: 'Lionel Richie',
    producer: 'Lionel Richie, James Anthony Carmichael',
    genre: '80s Pop ballad',
    whatToListenFor: "An almost jazz-informed ballad. Listen for the lush string arrangement and how it takes over the bridge. Pay attention to the Rhodes and how it sets the harmonic tone. Notice the space Lionel leaves at the ends of phrases; nothing is rushed.",
    tags: ['80s-pop', 'ballad', 'lionel-richie', 'strings'],
  },
  {
    title: 'When I Need You',
    artist: 'Leo Sayer',
    producer: 'Richard Perry',
    genre: '70s/80s Pop ballad',
    whatToListenFor: "A string-driven ballad with a soft-rock bed. Listen for the way the strings are the real lead instrument. Pay attention to Leo's breath in the vocal — a very intimate mic presence. Notice the arrangement's restraint; there's no crescendo for its own sake.",
    tags: ['pop-ballad', 'leo-sayer', 'soft-rock', 'strings'],
  },
  {
    title: 'I Want to Know What Love Is',
    artist: 'Foreigner',
    producer: 'Mick Jones, Alex Sadkin',
    genre: '80s Pop ballad',
    whatToListenFor: "A rock ballad that ends as a gospel song. Listen for the slow build — piano, then drums, then guitars, then the Thompson Community Choir in the last chorus. Pay attention to how restrained the lead vocal is until the emotional surge arrives. Notice the choir's arrival: the song changes genre without losing itself.",
    tags: ['80s-pop', 'rock-ballad', 'foreigner', 'choir-climax'],
  },
];

// --- Modern Thoughtful Hip-Hop (J. Cole, Kendrick, Drake) -----------
const THOUGHTFUL_HIP_HOP: PoolTrack[] = [
  {
    title: 'Love Yourz',
    artist: 'J. Cole',
    producer: 'J. Cole',
    genre: 'Hip-hop',
    whatToListenFor: "A sample-driven introspection. Listen for the warm loop that carries the whole song and how the drums are programmed to feel like a warmer version of a boom-bap beat. Pay attention to Cole's flow; he's rapping through the beat rather than over it. Notice how the hook is just a melodic speech, no sung chorus.",
    tags: ['hip-hop', 'j-cole', 'sample-based', 'introspective'],
  },
  {
    title: 'No Role Modelz',
    artist: 'J. Cole',
    producer: 'J. Cole, Phonix Beats',
    genre: 'Hip-hop',
    whatToListenFor: "Pay attention to the chord loop that repeats the whole track — it's catchy on its own, which is why the song works as a singalong. Listen for the drum programming; the kick and clap are crisp and forward. Notice the interludes of speech samples; they replace traditional breakdowns.",
    tags: ['hip-hop', 'j-cole', 'loop-based', 'hook-driven'],
  },
  {
    title: 'Alright',
    artist: 'Kendrick Lamar',
    producer: 'Pharrell Williams, Sounwave',
    genre: 'Hip-hop',
    whatToListenFor: "Jazz-sampled defiance. Listen for the sax lines weaving through the beat — it's jazz DNA in a hip-hop frame. Pay attention to how the drums get chopped and stuttered between bars. Notice Kendrick's cadence shifts constantly; he's a vocalist in the truest sense here, not just a rapper.",
    tags: ['hip-hop', 'kendrick-lamar', 'jazz-influenced', 'pharrell'],
  },
  {
    title: 'King Kunta',
    artist: 'Kendrick Lamar',
    producer: 'Sounwave, Terrace Martin',
    genre: 'Hip-hop',
    whatToListenFor: "A funk-rooted hip-hop track. Listen for the Michael Jackson-referencing bass groove and how it anchors the whole song. Pay attention to the drum tightness — they snap rather than thud. Notice how the BGV stack in the hook is almost gospel in its layering.",
    tags: ['hip-hop', 'kendrick-lamar', 'funk', 'bass-forward'],
  },
  {
    title: 'HUMBLE.',
    artist: 'Kendrick Lamar',
    producer: 'Mike WiLL Made-It',
    genre: 'Hip-hop',
    whatToListenFor: "A minimal, confrontational beat. Listen for how few elements are actually here — a piano loop, a kick, a snare, a hi-hat. Pay attention to the silences between hits; the space is part of the punch. Notice Kendrick's vocal is dry and close, no post-processing softening his bars.",
    tags: ['hip-hop', 'kendrick-lamar', 'minimal', 'trap'],
  },
  {
    title: 'DNA.',
    artist: 'Kendrick Lamar',
    producer: 'Mike WiLL Made-It',
    genre: 'Hip-hop',
    whatToListenFor: "A two-beat suite in one song. Listen for the beat switch and how radically the mood shifts while Kendrick's energy stays constant. Pay attention to the way the first beat sits on a menacing low synth and the second goes hyperactive. Notice how the track resists pop structure entirely.",
    tags: ['hip-hop', 'kendrick-lamar', 'beat-switch', 'aggressive'],
  },
  {
    title: 'Marvin\'s Room',
    artist: 'Drake',
    producer: 'Noah "40" Shebib',
    genre: 'Hip-hop',
    whatToListenFor: "40's signature muffled sonic. Listen for how the drums sound like they're in the next room. Pay attention to the way Drake's voice slips between singing and rapping without marking the difference. Notice how the song is built almost entirely on mood — long stretches with no real change.",
    tags: ['hip-hop', 'drake', 'noah-40-shebib', 'atmospheric'],
  },
  {
    title: 'Take Care',
    artist: 'Drake feat. Rihanna',
    producer: 'Jamie xx, Noah "40" Shebib',
    genre: 'Hip-hop',
    whatToListenFor: "UK-dance sample turned into a moody duet. Listen for the stuttered vocal sample anchoring the groove. Pay attention to how Rihanna's voice sits wider than Drake's — different reverb, different depth. Notice the drums; they're sparse, almost shy.",
    tags: ['hip-hop', 'drake', 'rihanna', 'sample-based'],
  },
  {
    title: 'Hold On, We\'re Going Home',
    artist: 'Drake feat. Majid Jordan',
    producer: 'Nineteen85, Majid Jordan',
    genre: 'Pop R&B',
    whatToListenFor: "A warm, pop-crossover track. Listen for how clean and bright everything is — a departure from Drake's usual hazy production. Pay attention to the Majid Jordan BGVs; they're the real textural spine of the song. Notice the kick-clap-snap pattern that keeps the groove dancey.",
    tags: ['pop-rnb', 'drake', 'crossover', 'nineteen85'],
  },
  {
    title: 'Feel No Ways',
    artist: 'Drake',
    producer: 'Jordan Ullman, Nineteen85',
    genre: 'Pop R&B',
    whatToListenFor: "An 80s synth-pop throwback. Listen for the programmed drums and that classic 80s snare sound. Pay attention to the bass synth; it's the hook as much as the vocal. Notice how Drake stays on beat more strictly than usual — the pop structure demands it.",
    tags: ['pop-rnb', 'drake', '80s-inspired', 'synth-pop'],
  },
  {
    title: 'm.A.A.d city',
    artist: 'Kendrick Lamar feat. MC Eiht',
    producer: 'Sounwave, THC',
    genre: 'Hip-hop',
    whatToListenFor: "A two-beat track with an entirely different second half. Listen for the switch and how the second half's synths carry the emotional weight. Pay attention to Kendrick's flow shifts — he changes voices, almost characters, inside one song. Notice the use of vocal samples from his city as texture.",
    tags: ['hip-hop', 'kendrick-lamar', 'beat-switch', 'west-coast'],
  },
  {
    title: 'Middle Child',
    artist: 'J. Cole',
    producer: 'T-Minus, J. Cole',
    genre: 'Hip-hop',
    whatToListenFor: "A strings-forward beat. Listen for the looped violin line and how it gives the track a cinematic quality. Pay attention to the crisp kick and clap — classic trap but cleaner than usual. Notice Cole's hook is half-sung; that 50/50 sing-rap is a modern hip-hop standard he helps define.",
    tags: ['hip-hop', 'j-cole', 'strings', 't-minus'],
  },
  {
    title: 'Mask Off',
    artist: 'Future',
    producer: 'Metro Boomin',
    genre: 'Trap',
    whatToListenFor: "A flute-led trap beat. Listen for the sample (Carlton Williams' 'Prison Song') and how Metro Boomin lets it breathe. Pay attention to the 808 movement; it's the melodic low end. Notice how minimal the top end is — flute, vocal, hats. The song is mostly low-frequency weight.",
    tags: ['trap', 'metro-boomin', 'future', 'sample-based'],
  },
  {
    title: 'Passionfruit',
    artist: 'Drake',
    producer: 'Nana Rogues',
    genre: 'Pop R&B',
    whatToListenFor: "A breezy dance-influenced R&B track. Listen for the way the chord progression loops without ever feeling repetitive. Pay attention to the rhythmic bass that keeps the energy moving. Notice Drake's voice is mixed slightly back — he's part of the groove, not above it.",
    tags: ['pop-rnb', 'drake', 'dancehall-influenced', 'loop-based'],
  },
  {
    title: 'Money Trees',
    artist: 'Kendrick Lamar feat. Jay Rock',
    producer: 'DJ Dahi',
    genre: 'Hip-hop',
    whatToListenFor: "A reversed sample acting as the hook. Listen for how the beat has that 'pulled backwards' feeling throughout. Pay attention to Kendrick's double-time cadence in the verses. Notice the drum pattern — loose and a little off-grid, which is what gives it character.",
    tags: ['hip-hop', 'kendrick-lamar', 'sample-based', 'dj-dahi'],
  },
];

// --- Classic Dance R&B (Beyoncé-era) --------------------------------
const DANCE_RNB: PoolTrack[] = [
  {
    title: 'Crazy in Love',
    artist: 'Beyoncé feat. Jay-Z',
    producer: 'Rich Harrison, Beyoncé',
    genre: 'Dance R&B',
    whatToListenFor: "Listen for how the horn sample is looped — it's the whole song's energy. Pay attention to the drum programming: claps, layered percussion, hi-hats all layered to feel live. Notice how Beyoncé's vocal is stacked in the hook, and how her ad-libs tumble out at the end of every bar.",
    tags: ['dance-rnb', 'beyonce', 'sample-based', 'horns'],
  },
  {
    title: 'Single Ladies (Put a Ring on It)',
    artist: 'Beyoncé',
    producer: 'Tricky Stewart, The-Dream, Thaddis Harrell, Beyoncé',
    genre: 'Dance R&B',
    whatToListenFor: "Almost no instrumentation. Listen for how much work the vocal stacks are doing — they ARE the arrangement. Pay attention to the handclap pattern carrying the groove. Notice the way the track's energy comes from empty space as much as from the rhythmic hits.",
    tags: ['dance-rnb', 'beyonce', 'the-dream', 'minimal'],
  },
  {
    title: 'Run the World (Girls)',
    artist: 'Beyoncé',
    producer: 'Switch, Diplo, Beyoncé',
    genre: 'Dance R&B',
    whatToListenFor: "Aggressive drum programming built on a Major Lazer track. Listen for the layered percussion that feels tribal and electronic at once. Pay attention to the call-and-response between Beyoncé's lead and the BGV stack. Notice how the arrangement has almost no harmonic content — it's all rhythm and vocal.",
    tags: ['dance-rnb', 'beyonce', 'diplo', 'percussive'],
  },
  {
    title: 'Drunk in Love',
    artist: 'Beyoncé feat. Jay-Z',
    producer: 'Detail, Boots, Beyoncé',
    genre: 'Dance R&B',
    whatToListenFor: "A slow-burning track built around repeated vocal phrases. Listen for the synth stabs and how they replace a traditional chord bed. Pay attention to Beyoncé's delivery; she shifts register constantly within a single bar. Notice how the song doesn't build — it simmers.",
    tags: ['dance-rnb', 'beyonce', 'jay-z', 'minimal'],
  },
  {
    title: 'Partition',
    artist: 'Beyoncé',
    producer: 'Detail, Key Wane, Mike Dean, Beyoncé',
    genre: 'Dance R&B',
    whatToListenFor: "Two beats in one song. Listen for the switch and how the second half's trap drums transform the vibe. Pay attention to the ambient French monologue before the second section — it's an arrangement choice, not a gimmick. Notice the subbass; it's enormous and demands a speaker that can carry it.",
    tags: ['dance-rnb', 'beyonce', 'beat-switch', 'trap-influenced'],
  },
  {
    title: 'Formation',
    artist: 'Beyoncé',
    producer: 'Mike Will Made-It, Pluss',
    genre: 'Dance R&B',
    whatToListenFor: "Aggressive trap drums under a defiant vocal. Listen for the vocal sample chops that punctuate the beat. Pay attention to how the kick and 808 are mixed huge. Notice the arrangement's refusal to build to a traditional chorus — the energy sustains.",
    tags: ['dance-rnb', 'beyonce', 'trap', 'mike-will-made-it'],
  },
  {
    title: 'Say My Name',
    artist: "Destiny's Child",
    producer: 'Rodney Jerkins, LaShawn Daniels, Fred Jerkins III, Beyoncé',
    genre: '2000s R&B',
    whatToListenFor: "Rodney Jerkins' signature skittering drum programming. Listen for how the three voices are panned and placed — distinct spaces for each member. Pay attention to the way the song stops and starts rhythmically. Notice how a skeletal arrangement (mostly keys and drums) feels full because of vocal layering.",
    tags: ['2000s-rnb', 'destinys-child', 'rodney-jerkins', 'group-vocal'],
  },
  {
    title: 'Independent Women Part I',
    artist: "Destiny's Child",
    producer: 'Cory Rooney, Poke & Tone, Beyoncé',
    genre: '2000s R&B',
    whatToListenFor: "An anthemic, horn-forward banger. Listen for the strings and horns layered to create a near-orchestral hook. Pay attention to how the three leads trade bars inside the verses. Notice the dramatic stop-breakdown before the final chorus — a classic pop arrangement trick perfected.",
    tags: ['2000s-rnb', 'destinys-child', 'group-vocal', 'horns'],
  },
  {
    title: 'No, No, No Part 2',
    artist: "Destiny's Child feat. Wyclef Jean",
    producer: 'Wyclef Jean, Jerry Duplessis',
    genre: '90s R&B',
    whatToListenFor: "A slowed-down remix that became the hit. Listen for the guitar loop from the original sample. Pay attention to how the song uses groove rather than build to create tension. Notice the handclaps and how they're the backbone of the rhythm.",
    tags: ['90s-rnb', 'destinys-child', 'wyclef', 'remix'],
  },
  {
    title: 'Lose My Breath',
    artist: "Destiny's Child",
    producer: 'Rodney Jerkins, Beyoncé',
    genre: '2000s R&B',
    whatToListenFor: "Military-drum-roll percussion. Listen for the way the song is all rhythm and vocal — almost no harmonic content. Pay attention to the call-and-response between the three voices. Notice how tightly arranged the vocal stops are; this is precision choreography in audio form.",
    tags: ['2000s-rnb', 'destinys-child', 'rodney-jerkins', 'percussive'],
  },
  {
    title: 'Get Me Bodied',
    artist: 'Beyoncé',
    producer: 'Swizz Beatz, Beyoncé, Solange Knowles, Sean Garrett',
    genre: 'Dance R&B',
    whatToListenFor: "Playful, percussion-driven dance track. Listen for the kick pattern and how every section has a slightly different drum flavor. Pay attention to the vocal ad-libs that drive the energy rather than the instrumentation. Notice the way the song is designed for choreography — you can almost hear the dance.",
    tags: ['dance-rnb', 'beyonce', 'swizz-beatz', 'uptempo'],
  },
  {
    title: 'XO',
    artist: 'Beyoncé',
    producer: 'Terius "The-Dream" Nash, Ryan Tedder, Hit-Boy, Beyoncé',
    genre: 'Pop R&B',
    whatToListenFor: "Arena-sized pop R&B. Listen for the driving 808 and the big, bright synths. Pay attention to how Beyoncé's voice is doubled and stacked to fill the space. Notice the way the bridge drops elements to reset the energy for the final chorus.",
    tags: ['pop-rnb', 'beyonce', 'the-dream', 'anthemic'],
  },
  {
    title: 'Naughty Girl',
    artist: 'Beyoncé',
    producer: 'Scott Storch, Beyoncé, Robert Waller',
    genre: 'Dance R&B',
    whatToListenFor: "Donna Summer-sampled disco R&B. Listen for how the sample is the bed — Beyoncé is singing alongside a classic, not replacing it. Pay attention to the way strings and disco guitar are layered over modern drum programming. Notice the tempo; it's a dance track at a classic-era disco speed.",
    tags: ['dance-rnb', 'beyonce', 'disco', 'sample-based'],
  },
  {
    title: "Check on It",
    artist: 'Beyoncé feat. Bun B, Slim Thug',
    producer: 'Swizz Beatz, Sean Garrett, Beyoncé',
    genre: 'Dance R&B',
    whatToListenFor: "Hip-hop-flavored dance R&B. Listen for the whistle motif and how it becomes the song's identifier. Pay attention to the way Beyoncé's hook is delivered melodically while the features rap in a totally different style. Notice the minimal arrangement; it stays on a groove without ever getting busier.",
    tags: ['dance-rnb', 'beyonce', 'swizz-beatz', 'southern-rap'],
  },
  {
    title: 'Upgrade U',
    artist: 'Beyoncé feat. Jay-Z',
    producer: 'Willy Will, Swizz Beatz, Cameron Wallace, Beyoncé',
    genre: 'Dance R&B',
    whatToListenFor: "A Betty Wright sample driving the entire track. Listen for the way the sample loops and how Beyoncé's melody is built over it. Pay attention to the drum programming — punchy, simple. Notice how the song's structure follows Beyoncé's hook rather than a traditional pop shape.",
    tags: ['dance-rnb', 'beyonce', 'sample-based', 'hip-hop-influenced'],
  },
];

// --- 70s Soul/Funk Grooves ------------------------------------------
const SOUL_FUNK_70S: PoolTrack[] = [
  {
    title: 'Superstition',
    artist: 'Stevie Wonder',
    producer: 'Stevie Wonder',
    genre: '70s Funk',
    whatToListenFor: "The clavinet riff is the whole hook. Listen for how drums, bass, and clav lock into a single animal. Pay attention to Stevie's vocal phrasing — he's behind the beat, then on it, then ahead, constantly. Notice the horns; they're punctuation, not a pad.",
    tags: ['70s-funk', 'stevie-wonder', 'clavinet', 'groove'],
  },
  {
    title: 'Sir Duke',
    artist: 'Stevie Wonder',
    producer: 'Stevie Wonder',
    genre: '70s Funk',
    whatToListenFor: "A horn-led, uptempo tribute track. Listen for the unison horn line and how it takes the melodic lead equally with the vocal. Pay attention to the way the bass walks through changes instead of sitting in pockets. Notice the arrangement — everything feels celebratory, and every element is playing off the horns.",
    tags: ['70s-funk', 'stevie-wonder', 'horns', 'uptempo'],
  },
  {
    title: 'Lovely Day',
    artist: 'Bill Withers',
    producer: 'Bill Withers, Skip Scarborough',
    genre: '70s Soul',
    whatToListenFor: "A groove-driven soul classic. Listen for the strings that wash behind the verses without ever feeling intrusive. Pay attention to Bill's voice — warm, close, front-and-center. Notice the sustained vocal note near the end; it's famous because of how steady and relaxed it stays.",
    tags: ['70s-soul', 'bill-withers', 'strings', 'groove'],
  },
  {
    title: 'Use Me',
    artist: 'Bill Withers',
    producer: 'Bill Withers',
    genre: '70s Funk',
    whatToListenFor: "A funky, repetitive two-chord groove. Listen for the clav riff carrying the energy and how the band locks into it tight. Pay attention to the vocal phrasing — conversational and slightly raspy. Notice the arrangement's refusal to change; the groove is the point.",
    tags: ['70s-funk', 'bill-withers', 'clavinet', 'two-chord'],
  },
  {
    title: 'September',
    artist: 'Earth, Wind & Fire',
    producer: 'Maurice White, Allee Willis',
    genre: '70s Funk',
    whatToListenFor: "Listen for the iconic horn riff and how everything in the arrangement answers it. Pay attention to Philip Bailey's falsetto and how it sits on top of the stack without cutting through harshly. Notice the bass — funky but melodically rich, never just rhythmic.",
    tags: ['70s-funk', 'earth-wind-fire', 'horns', 'falsetto'],
  },
  {
    title: 'Boogie Wonderland',
    artist: 'Earth, Wind & Fire with The Emotions',
    producer: 'Maurice White, Al McKay',
    genre: '70s Disco',
    whatToListenFor: "A disco-funk anthem. Listen for the four-on-the-floor drums and how the horns punctuate every bar. Pay attention to the string arrangement; it's orchestral but in service of the groove, not in front of it. Notice how the two groups trade lead in the chorus.",
    tags: ['70s-disco', 'earth-wind-fire', 'horns', 'strings'],
  },
  {
    title: "Let's Groove",
    artist: 'Earth, Wind & Fire',
    producer: 'Maurice White, Wayne Vaughn',
    genre: '70s Funk',
    whatToListenFor: "Late-era EWF. Listen for the vocoder on the hook — they're using a then-new tool to make the voice futuristic. Pay attention to the way the horn stabs remain classically EWF despite the modernized production. Notice the bass; it's more rhythmic and less melodic than earlier cuts.",
    tags: ['70s-funk', 'earth-wind-fire', 'vocoder', 'disco'],
  },
  {
    title: 'I Want You Back',
    artist: 'The Jackson 5',
    producer: 'The Corporation (Berry Gordy, Freddie Perren, Deke Richards, Fonce Mizell)',
    genre: 'Motown Soul',
    whatToListenFor: "A blueprint for tight pop soul. Listen for the bass line — it's a melodic masterclass. Pay attention to the percussive guitar and how it locks with the drum pattern. Notice young Michael's voice: already commanding, placed right in the front, no reverb to hide behind.",
    tags: ['motown', 'jackson-5', 'the-corporation', 'bass-line'],
  },
  {
    title: 'Flash Light',
    artist: 'Parliament',
    producer: 'George Clinton',
    genre: '70s Funk',
    whatToListenFor: "Minimoog bass carrying the groove where an electric bass would normally be. Listen for how much rhythmic and melodic responsibility the synth has. Pay attention to the choir-like stacked vocals — it's gospel DNA in a funk frame. Notice how sparse the drums are; the groove is mostly bass and voice.",
    tags: ['70s-funk', 'parliament', 'george-clinton', 'synth-bass'],
  },
  {
    title: 'Give Up the Funk (Tear the Roof off the Sucker)',
    artist: 'Parliament',
    producer: 'George Clinton',
    genre: '70s Funk',
    whatToListenFor: "Call-and-response between lead and a crowd of voices. Listen for how many people are singing at once — it sounds like a party. Pay attention to the horn arrangement; they're stab-heavy, punctuating lines. Notice the rhythm section; it's impossibly tight despite how loose the vocals feel.",
    tags: ['70s-funk', 'parliament', 'george-clinton', 'call-response'],
  },
  {
    title: 'Play That Funky Music',
    artist: 'Wild Cherry',
    producer: 'Rob Parissi',
    genre: '70s Funk',
    whatToListenFor: "White-rock-band-goes-funk. Listen for the tight guitar chords on the hook — that's the whole energy. Pay attention to the cowbell and how it's an actual musical element, not just percussion. Notice the bass line and how it pops rather than thuds.",
    tags: ['70s-funk', 'wild-cherry', 'rock-funk', 'guitar-driven'],
  },
  {
    title: 'Brick House',
    artist: 'Commodores',
    producer: 'James Anthony Carmichael, Commodores',
    genre: '70s Funk',
    whatToListenFor: "A textbook funk groove. Listen for how the bassline sits dead center in the mix and carries most of the melodic interest. Pay attention to the horn hits on the chorus. Notice the drums — they're clean and tight, pop-funk rather than grittier James Brown-style funk.",
    tags: ['70s-funk', 'commodores', 'bass-forward', 'horns'],
  },
  {
    title: "Papa Was a Rollin' Stone",
    artist: 'The Temptations',
    producer: 'Norman Whitfield',
    genre: '70s Psych Soul',
    whatToListenFor: "A 12-minute psychedelic soul epic. Listen for the extended instrumental intro and how slowly the song reveals itself. Pay attention to the layered strings, horns, and wah-wah guitar all existing in the same space without fighting. Notice how the vocals arrive almost two minutes in — the arrangement is as much the statement as the lyrics.",
    tags: ['70s-soul', 'temptations', 'norman-whitfield', 'epic'],
  },
  {
    title: "I'll Take You There",
    artist: 'The Staple Singers',
    producer: 'Al Bell',
    genre: '70s Soul',
    whatToListenFor: "Reggae-influenced soul groove. Listen for the one-drop-feel drums and the bass walking through the song. Pay attention to Mavis Staples' lead — deep, conversational, church-rooted. Notice how little harmonic motion the song has; the groove carries everything.",
    tags: ['70s-soul', 'staple-singers', 'reggae-influenced', 'al-bell'],
  },
  {
    title: "Ain't No Mountain High Enough",
    artist: 'Marvin Gaye & Tammi Terrell',
    producer: 'Ashford & Simpson',
    genre: '60s/70s Soul',
    whatToListenFor: "A Motown masterpiece of arrangement. Listen for how the strings and horns are equal citizens in the hook. Pay attention to the way the two leads trade lines like a conversation, never stepping on each other. Notice the drum pattern — driving, tambourine-heavy, a pop-soul gold standard.",
    tags: ['motown', 'marvin-gaye', 'duet', 'ashford-simpson'],
  },
];

// --- Neo-Soul (D'Angelo, Erykah Badu) -------------------------------
const NEO_SOUL: PoolTrack[] = [
  {
    title: 'Untitled (How Does It Feel)',
    artist: "D'Angelo",
    producer: "D'Angelo, Raphael Saadiq",
    genre: 'Neo-soul',
    whatToListenFor: "The neo-soul blueprint. Listen for how the drums pull slightly behind the beat — the whole track has a dragging, sensual feel. Pay attention to the Rhodes and the bass: they share frequency space that would be mud elsewhere. Notice how D'Angelo's vocal feels like it's in the same room as the instruments, not on top of them.",
    tags: ['neo-soul', 'dangelo', 'dilla-feel', 'rhodes'],
  },
  {
    title: 'Brown Sugar',
    artist: "D'Angelo",
    producer: "D'Angelo, Ali Shaheed Muhammad",
    genre: 'Neo-soul',
    whatToListenFor: "A laid-back, jazz-informed groove. Listen for how the drums have that lo-fi, slightly wobbly feel — it's intentional looseness. Pay attention to D'Angelo's falsetto, doubled with his chest voice. Notice the Rhodes and bass moving together, carrying almost the entire harmonic load.",
    tags: ['neo-soul', 'dangelo', 'rhodes', 'jazz-influenced'],
  },
  {
    title: "Lady",
    artist: "D'Angelo",
    producer: "D'Angelo, Raphael Saadiq",
    genre: 'Neo-soul',
    whatToListenFor: "A groove that almost refuses to move. Listen for the way D'Angelo's vocal is layered with himself — two, three, four Ds all at once. Pay attention to the bass locking with the kick drum exclusively. Notice the ad-lib density in the outro; it's a jazz singer's instinct applied to R&B.",
    tags: ['neo-soul', 'dangelo', 'vocal-stacking', 'groove'],
  },
  {
    title: "Cruisin'",
    artist: "D'Angelo",
    producer: "D'Angelo",
    genre: 'Neo-soul',
    whatToListenFor: "A cover that pulls the Smokey Robinson original into a neo-soul world. Listen for how the original's 70s production is replaced by a sparser, hazier bed. Pay attention to the drum programming — sampled, loose, shadows of a live kit. Notice how D'Angelo holds the original melody but treats every note with different color.",
    tags: ['neo-soul', 'dangelo', 'cover', 'smokey-robinson'],
  },
  {
    title: 'On & On',
    artist: 'Erykah Badu',
    producer: 'Erykah Badu, JaBorn "JaBo" Jamal, Bob Power',
    genre: 'Neo-soul',
    whatToListenFor: "Jazz-vocal phrasing over a hip-hop groove. Listen for the upright bass and drum combo giving a Blue Note-era feel. Pay attention to Erykah's syllable placement; she's singing jazz but over a breakbeat. Notice how the Rhodes and flute make the song feel like it's both 1972 and 1997 at once.",
    tags: ['neo-soul', 'erykah-badu', 'jazz-influenced', 'upright-bass'],
  },
  {
    title: 'Bag Lady',
    artist: 'Erykah Badu',
    producer: 'Erykah Badu, Isaac Hayes',
    genre: 'Neo-soul',
    whatToListenFor: "A hypnotic loop built on a chilled Isaac Hayes-style groove. Listen for the slow-burn drum pattern and how the bass rarely changes notes. Pay attention to Erykah's vocal — conversational, not showy. Notice the use of space in the arrangement; long stretches of just groove with a line or two of vocal.",
    tags: ['neo-soul', 'erykah-badu', 'isaac-hayes', 'minimal'],
  },
  {
    title: 'Tyrone',
    artist: 'Erykah Badu',
    producer: 'Norman Hurt',
    genre: 'Neo-soul',
    whatToListenFor: "Live recording energy. Listen for the audience reaction inside the mix — it's a performance, not just a track. Pay attention to Erykah's phrasing; she's acting as much as singing. Notice how sparse the arrangement is — bass, keys, drums — and how much the room tone is part of the sonic identity.",
    tags: ['neo-soul', 'erykah-badu', 'live', 'performance'],
  },
  {
    title: 'Didn\'t Cha Know',
    artist: 'Erykah Badu',
    producer: 'J Dilla',
    genre: 'Neo-soul',
    whatToListenFor: "A pure Dilla production. Listen for the drums' signature wobble — they're programmed to feel human and slightly drunk. Pay attention to the sample and how it loops in a way that never quite resolves. Notice Erykah's vocal floating over the beat rather than riding it strictly.",
    tags: ['neo-soul', 'erykah-badu', 'j-dilla', 'dilla-feel'],
  },
  {
    title: 'Ex-Factor',
    artist: 'Lauryn Hill',
    producer: 'Lauryn Hill, Che Guevara',
    genre: 'Neo-soul',
    whatToListenFor: "A Wu-Tang sample turned into a soulful ballad. Listen for how the groove sits at a heartbeat tempo. Pay attention to Lauryn's vocal — raw, cracked, emotionally unguarded. Notice how the arrangement is almost entirely on one chord pattern, yet never feels static because her delivery keeps evolving.",
    tags: ['neo-soul', 'lauryn-hill', 'sample-based', 'miseducation'],
  },
  {
    title: 'Doo Wop (That Thing)',
    artist: 'Lauryn Hill',
    producer: 'Lauryn Hill',
    genre: 'Hip-hop Soul',
    whatToListenFor: "A song that's half rap, half doo-wop. Listen for how the two sections are mixed differently — the rap section is gritty, the doo-wop is warm and retro. Pay attention to the horn and piano interplay. Notice how Lauryn switches vocal delivery completely between modes, yet the song feels unified.",
    tags: ['neo-soul', 'lauryn-hill', 'hip-hop-soul', 'miseducation'],
  },
  {
    title: 'Nothing Even Matters',
    artist: "Lauryn Hill feat. D'Angelo",
    producer: 'Lauryn Hill',
    genre: 'Neo-soul',
    whatToListenFor: "A duet in the spirit of Marvin and Tammi. Listen for how quiet and private the arrangement feels. Pay attention to the way the two voices shadow each other in the hook. Notice the electric piano's role — it's the orchestra.",
    tags: ['neo-soul', 'lauryn-hill', 'dangelo', 'duet'],
  },
  {
    title: 'A Long Walk',
    artist: 'Jill Scott',
    producer: 'Jill Scott, Vidal Davis, Andre Harris',
    genre: 'Neo-soul',
    whatToListenFor: "A strolling groove. Listen for the laid-back drum pocket and how the rhodes never rushes. Pay attention to Jill's spoken-word phrasing inside a sung melody. Notice the warm, slightly lo-fi treatment that gives the whole track a sun-dappled quality.",
    tags: ['neo-soul', 'jill-scott', 'mellow', 'rhodes'],
  },
  {
    title: 'You Got Me',
    artist: 'The Roots feat. Erykah Badu',
    producer: 'The Roots',
    genre: 'Neo-soul',
    whatToListenFor: "Live hip-hop band meets neo-soul voice. Listen for ?uestlove's drum pocket — it's the heartbeat of the song. Pay attention to how Erykah's chorus is the melodic anchor while Black Thought's rap carries the narrative. Notice the bass; it's walking, melodic, jazz-rooted.",
    tags: ['neo-soul', 'the-roots', 'erykah-badu', 'live-band'],
  },
  {
    title: 'Ascension (Don\'t Ever Wonder)',
    artist: 'Maxwell',
    producer: 'Maxwell, Stuart Matthewman',
    genre: 'Neo-soul',
    whatToListenFor: "Smooth, mid-90s neo-soul. Listen for the slightly retro production; it references 70s Philly soul directly. Pay attention to Maxwell's falsetto placement and the breathy way it's delivered. Notice the horn stabs — pure homage.",
    tags: ['neo-soul', 'maxwell', 'philly-soul', 'falsetto'],
  },
  {
    title: 'Feel Like Makin\' Love',
    artist: 'D\'Angelo',
    producer: "D'Angelo, Raphael Saadiq",
    genre: 'Neo-soul',
    whatToListenFor: "A Roberta Flack cover rebuilt as neo-soul. Listen for how D'Angelo slows the original almost to a crawl. Pay attention to how everything in the track — drums, bass, keys — has been pulled slightly behind the grid. Notice how the vocal is multi-layered but feels like one singer lost in thought.",
    tags: ['neo-soul', 'dangelo', 'cover', 'roberta-flack'],
  },
];

// --- Master list ----------------------------------------------------
export const TRACK_POOLS: TrackPool[] = [
  {
    id: 'gospel-6-8',
    label: '6/8 Church Beat / Gospel Freestyle',
    subtitle: 'Gospel standards with the 6/8 feel — Smallwood, McClurkin, Whitney in the church',
    tracks: GOSPEL_6_8,
  },
  {
    id: 'gospel-choir-90s',
    label: '90s/00s Gospel Choir',
    subtitle: 'Kirk Franklin, Fred Hammond, and the big-choir gospel era',
    tracks: GOSPEL_CHOIR_90S,
  },
  {
    id: 'rnb-ballads-90s',
    label: '90s R&B Ballads',
    subtitle: 'Babyface, Jermaine Dupri, and the gold-standard 90s ballad production',
    tracks: RNB_BALLADS_90S,
  },
  {
    id: 'rnb-2000s',
    label: '2000s R&B',
    subtitle: 'Usher-era slow jams and midtempos — Jermaine Dupri, Bryan-Michael Cox, Stargate',
    tracks: RNB_2000S,
  },
  {
    id: 'lofi-indie',
    label: 'Lo-fi / Atmospheric Indie',
    subtitle: 'Bedroom-pop and dream-leaning indie — Clairo, Men I Trust, Mac DeMarco, Joji',
    tracks: LOFI_INDIE,
  },
  {
    id: 'modern-minimal-rnb',
    label: 'Modern Minimal R&B',
    subtitle: 'Frank Ocean, H.E.R., Daniel Caesar — space, restraint, and warmth',
    tracks: MODERN_MINIMAL_RNB,
  },
  {
    id: '80s-pop-ballads',
    label: '80s Pop Ballads',
    subtitle: 'Gated-drum power ballads and soft-rock classics',
    tracks: POP_BALLADS_80S,
  },
  {
    id: 'thoughtful-hip-hop',
    label: 'Modern Thoughtful Hip-Hop',
    subtitle: 'J. Cole, Kendrick, Drake — introspection and modern production',
    tracks: THOUGHTFUL_HIP_HOP,
  },
  {
    id: 'dance-rnb',
    label: 'Classic Dance R&B',
    subtitle: 'Beyoncé-era up-tempo R&B and dance records',
    tracks: DANCE_RNB,
  },
  {
    id: 'soul-funk-70s',
    label: '70s Soul/Funk Grooves',
    subtitle: 'Stevie, EWF, Parliament, Bill Withers — the groove bible',
    tracks: SOUL_FUNK_70S,
  },
  {
    id: 'neo-soul',
    label: 'Neo-Soul',
    subtitle: "D'Angelo, Erykah, Lauryn, Jill — the post-Soulquarian canon",
    tracks: NEO_SOUL,
  },
];

export function trackPoolById(id: string): TrackPool | undefined {
  return TRACK_POOLS.find(p => p.id === id);
}
